The Hubzilla: include/acl_selectors.php File Reference
acl_selectors.php File Reference
Namespaces
acl_selectors
Functions
group_select ($selname, $selclass, $preselected=false, $size=4)
contact_select ($selname, $selclass, $preselected=false, $size=4, $privmail=false, $celeb=false, $privatenet=false, $tabindex=null)
fixacl (&$item)
populate_acl ($defaults=null, $show_jotnets=true, $emptyACL_description= '', $dialog_description= '', $context_help= '', $readonly=false)
get_post_aclDialogDescription ()
Function Documentation
contact_select ($selname, $selclass, $preselected = false, $size = 4, $privmail = false, $celeb = false, $privatenet = false, $tabindex = null)
fixacl (& $item)
get_post_aclDialogDescription ()
Returns a string that's suitable for passing as the $dialog_description argument to a populate_acl() call for wall posts or network posts.
This string is needed in 3 different files, and our .po translation system currently cannot be used as a string table (because the value is always the key in english) so I've centralized the value here (making this function name the "key") until we have a better way.
Returns
string Description to present to user in modal permissions dialog
Referenced by Zotlabs\Module\Network\get(), Zotlabs\Module\Rpost\get(), and Zotlabs\Module\Channel\get().
group_select ($selname, $selclass, $preselected = false, $size = 4)
Parameters
string $selname
string $selclass
mixed $preselected
number $size
Returns
string
populate_acl ($defaults = null, $show_jotnets = true, $emptyACL_description = '', $dialog_description = '', $context_help = '', $readonly = false)
Builds a modal dialog for editing permissions, using acl_selector.tpl as the template.
Parameters
array $defaults Optional access control list for the initial state of the dialog.
boolean $show_jotnets Whether plugins for federated networks should be included in the permissions dialog
\Zotlabs\Lib\PermissionDescription $emptyACL_description - An optional description for the permission implied by selecting an empty ACL. Preferably an instance of PermissionDescription.
string $dialog_description Optional message to include at the top of the dialog. E.g. "Warning: Post permissions cannot be changed once sent".
string $context_help Allows the dialog to present a help icon. E.g. "acl_dialog_post"
boolean $readonly Not implemented yet. When implemented, the dialog will use acl_readonly.tpl instead, so that permissions may be viewed for posts that can no longer have their permissions changed.
Returns
string html modal dialog built from acl_selector.tpl
Referenced by Zotlabs\Module\Pubstream\get(), Zotlabs\Module\Article_edit\get(), Zotlabs\Module\Card_edit\get(), Zotlabs\Module\Display\get(), Zotlabs\Module\Articles\get(), Zotlabs\Module\Cards\get(), Zotlabs\Module\Editwebpage\get(), Zotlabs\Module\Webpages\get(), Zotlabs\Module\Network\get(), Zotlabs\Module\Rpost\get(), Zotlabs\Module\Hq\get(), Zotlabs\Module\Wiki\get(), Zotlabs\Module\Filestorage\get(), Zotlabs\Module\Channel\get(), Zotlabs\Module\Chat\get(), Zotlabs\Module\Mitem\get(), Zotlabs\Module\Thing\get(), Zotlabs\Module\Events\get(), Zotlabs\Module\Settings\Channel\get(), and Zotlabs\Module\Photos\get().