The Hubzilla: include/api.php File Reference
api.php File Reference
Functions
api_user ()
api_date ($str)
api_register_func ($path, $func, $auth=false)
api_call ()
api_apply_template ($templatename, $type, $data)
api_client_register ($type)
api_oauth_request_token ($type)
api_oauth_access_token ($type)
Variables
$API = array()
$called_api = Null
Function Documentation
api_apply_template ($templatename, $type, $data)
load api $templatename for $type and replace $data array
api_call ()
Referenced by Zotlabs\Module\Api\get().
api_client_register ($type)
api_date ($str)
api_oauth_access_token ($type)
api_oauth_request_token ($type)
api_register_func ($path, $func, $auth = false)
Referenced by Zotlabs\Module\Api\init(), and zot_api_init().
api_user ()
Referenced by api_albums(), api_attach_list(), api_call(), api_channel_stream(), api_export_basic(), api_file_data(), api_file_detail(), api_file_export(), api_file_meta(), api_group(), api_group_members(), api_network_stream(), api_photo_detail(), api_photos(), api_red_xchan(), api_zot_abconfig(), api_zot_abook_xchan(), api_zot_perm_allowed(), Zotlabs\Module\Wall_upload\post(), Zotlabs\Module\Wall_attach\post(), red_item(), and zot_item_update().
Variable Documentation
$API = array()
$called_api = Null