The Hubzilla: include/bbcode.php File Reference
bbcode.php File Reference
BBCode related functions for parsing, etc.
Functions
get_bb_tag_pos ($s, $name, $occurance=1)
bb_tag_preg_replace ($pattern, $replace, $name, $s)
tryoembed ($match)
nakedoembed ($match)
tryzrlaudio ($match)
tryzrlvideo ($match)
bb_spacefy ($st)
bb_unspacefy_and_trim ($st)
bb_extract_images ($body)
bb_replace_images ($body, $images)
bb_parse_crypt ($match)
Parses crypt BBCode.
bb_parse_app ($match)
bb_parse_element ($match)
translate_design_element ($type)
bb_ShareAttributes ($match)
bb_location ($match)
bb_iframe ($match)
Returns an iframe from $match[1].
bb_ShareAttributesSimple ($match)
rpost_callback ($match)
bb_map_coords ($match)
bb_map_location ($match)
bb_opentag ($match)
bb_spoilertag ($match)
bb_definitionList ($match)
bb_definitionList_unescapeBraces ($match)
bb_checklist ($match)
bb_sanitize_style ($input)
Sanitize style properties from BBCode to HTML.
oblanguage_callback ($matches)
oblanguage_necallback ($matches)
bb_observer ($Text)
bb_code ($match)
bb_code_options ($match)
bb_highlight ($match)
bb_fixtable_lf ($match)
parseIdentityAwareHTML ($Text)
bbcode ($Text, $options=[])
Detailed Description
BBCode related functions for parsing, etc.
Function Documentation
bb_checklist ($match)
bb_code ($match)
bb_code_options ($match)
bb_definitionList ($match)
bb_definitionList_unescapeBraces ($match)
bb_extract_images ($body)
Referenced by bbcode().
bb_fixtable_lf ($match)
bb_highlight ($match)
bb_iframe ($match)
Returns an iframe from $match[1].
Parameters
array $match
Returns
string HTML iframe with content of $match[1]
bb_location ($match)
bb_map_coords ($match)
bb_map_location ($match)
bb_observer ($Text)
bb_opentag ($match)
bb_parse_app ($match)
bb_parse_crypt ($match)
Parses crypt BBCode.
Parameters
array $match
Returns
string HTML code
bb_parse_element ($match)
bb_replace_images ($body, $images)
Referenced by bbcode().
bb_sanitize_style ($input)
Sanitize style properties from BBCode to HTML.
Parameters
array $input
Returns
string A HTML span tag with the styles.
bb_ShareAttributes ($match)
bb_ShareAttributesSimple ($match)
bb_spacefy ($st)
bb_spoilertag ($match)
bb_tag_preg_replace ($pattern, $replace, $name, $s)
bb_unspacefy_and_trim ($st)
bbcode ($Text, $options = [])
Referenced by advanced_profile(), atom_entry(), bb_to_markdown(), construct_activity_object(), construct_activity_target(), Zotlabs\Lib\Enotify\format(), format_event_html(), format_event_obj(), format_ical_text(), Zotlabs\Module\Notifications\get(), Zotlabs\Module\Search\get(), Zotlabs\Module\Siteinfo\get(), Zotlabs\Module\Wiki\get(), Zotlabs\Module\Notify\get(), Zotlabs\Module\Cal\get(), Zotlabs\Module\Tagrm\get(), Zotlabs\Module\Directory\get(), Zotlabs\Module\Chatsvc\get(), Zotlabs\Module\Mail\get(), Zotlabs\Module\Register\get(), Zotlabs\Module\Events\get(), get_help_content(), Zotlabs\Module\Ping\init(), menu_render(), Zotlabs\Module\Oep\oep_articles_reply(), Zotlabs\Module\Oep\oep_cards_reply(), Zotlabs\Module\Oep\oep_display_reply(), Zotlabs\Module\Oep\oep_mid_reply(), Zotlabs\Module\Mail\post(), Zotlabs\Module\Wiki\post(), preg_callback_help_include(), prepare_text(), and Zotlabs\Lib\Enotify\submit().
get_bb_tag_pos ($s, $name, $occurance = 1)
Referenced by bb_tag_preg_replace().
nakedoembed ($match)
oblanguage_callback ($matches)
oblanguage_necallback ($matches)
parseIdentityAwareHTML ($Text)
Referenced by get_help_content().
rpost_callback ($match)
translate_design_element ($type)
tryoembed ($match)
tryzrlaudio ($match)
tryzrlvideo ($match)