The Hubzilla: boot.php File Reference
boot.php File Reference
This file defines some global constants and includes the central App class.
Classes
class miniApp
class App
Our main application structure for the life of this page.
Functions
sys_boot ()
startup ()
Reverse the effect of magic_quotes_gpc if it is enabled.
x ($s, $k=null)
Multi-purpose function to check variable state.
system_unavailable ()
Called from db initialisation if db is dead.
clean_urls ()
z_path ()
z_root ()
Returns the baseurl.
absurl ($path)
Return absolute URL for given $path.
os_mkdir ($path, $mode=0777, $recursive=false)
rrmdir ($path)
Recursively delete a directory.
is_ajax ()
Function to check if request was an AJAX (xmlhttprequest) request.
check_config ()
fix_system_urls ($oldurl, $newurl)
login ($register=false, $form_id= 'main-login', $hiddens=false, $login_page=true)
Wrapper for adding a login box.
killme ()
Used to end the current process, after saving session state.
goaway ($s)
Redirect to another URL and terminate this process.
shutdown ()
get_account_id ()
Returns the entity id of locally logged in account or false.
local_channel ()
Returns the entity id (channel_id) of locally logged in channel or false.
remote_channel ()
Returns a xchan_hash (visitor_id) of remote authenticated visitor or false.
notice ($s)
Show an error or alert text on next page load.
info ($s)
Show an information text on next page load.
get_max_import_size ()
Wrapper around config to limit the text length of an incoming message.
proc_run ()
Wrap calls to proc_close(proc_open()) and call hook so plugins can take part in process :)
is_windows ()
Checks if we are running on M$ Windows.
is_site_admin ()
Check if current user has admin role.
is_developer ()
Check if current user has developer role.
load_contact_links ($uid)
build_querystring ($params, $name=null)
Returns querystring as string from a mapped array.
argc ()
argv ($x)
dba_timer ()
get_observer_hash ()
Returns xchan_hash from the observer.
curPageURL ()
Returns the complete URL of the current page, e.g.: http(s)://something.com/network.
get_custom_nav ($navname)
Returns a custom navigation by name???
load_pdl ()
Loads a page definition file for a module.
exec_pdl ()
construct_page ()
build the page.
appdirpath ()
Returns appplication root directory.
head_set_icon ($icon)
Set a pageicon.
head_get_icon ()
Get the pageicon.
get_directory_realm ()
Return the Realm of the directory.
get_directory_primary ()
Return the primary directory server.
get_poller_runtime ()
Return relative date of last completed poller execution.
z_get_upload_dir ()
z_get_temp_dir ()
z_check_cert ()
Check if server certificate is valid.
cert_bad_email ()
Send email to admin if server has an invalid certificate.
check_for_new_perms ()
check_cron_broken ()
Send warnings every 3-5 days if cron is not running.
observer_prohibited ($allow_account=false)
Variables
const PLATFORM_NAME 'hubzilla'
const STD_VERSION '3.0'
const ZOT_REVISION '1.3'
const DB_UPDATE_VERSION 1198
const PROJECT_BASE __DIR__
const EOL '<br>' . "\r\n"
Constant with a HTML line break.
const ATOM_TIME 'Y-m-d\\TH:i:s\\Z'
const TEMPLATE_BUILD_PATH 'store/[data]/smarty3'
const DIRECTORY_MODE_NORMAL 0x0000
const DIRECTORY_MODE_PRIMARY 0x0001
const DIRECTORY_MODE_SECONDARY 0x0002
const DIRECTORY_MODE_STANDALONE 0x0100
const DIRECTORY_REALM 'RED_GLOBAL'
const DIRECTORY_FALLBACK_MASTER 'https://gravizot.de'
$DIRECTORY_FALLBACK_SERVERS
const JPEG_QUALITY 100
const PNG_QUALITY 8
const LANGUAGE_DETECT_MIN_LENGTH 128
const LANGUAGE_DETECT_MIN_CONFIDENCE 0.01
const MAX_IMAGE_LENGTH (!defined('STORAGE_DEFAULT_PERMISSIONS')) -1
const LOGGER_NORMAL 0
const LOGGER_TRACE 1
const LOGGER_DEBUG 2
const LOGGER_DATA 3
const LOGGER_ALL 4
const REGISTER_CLOSED 0
const REGISTER_APPROVE 1
const REGISTER_OPEN 2
const ACCESS_PRIVATE 0
const ACCESS_PAID 1
const ACCESS_FREE 2
const ACCESS_TIERED 3
const UPDATE_SUCCESS 0
const UPDATE_FAILED 1
const CLIENT_MODE_NORMAL 0x0000
const CLIENT_MODE_LOAD 0x0001
const CLIENT_MODE_UPDATE 0x0002
const PAGE_NORMAL 0x0000
const PAGE_HIDDEN 0x0001
const PAGE_AUTOCONNECT 0x0002
const PAGE_APPLICATION 0x0004
const PAGE_ALLOWCODE 0x0008
const PAGE_PREMIUM 0x0010
const PAGE_ADULT 0x0020
const PAGE_CENSORED 0x0040
const PAGE_SYSTEM 0x1000
const PAGE_HUBADMIN 0x2000
const PAGE_REMOVED 0x8000
const PHOTO_NORMAL 0x0000
const PHOTO_PROFILE 0x0001
const PHOTO_XCHAN 0x0002
const PHOTO_THING 0x0004
const PHOTO_COVER 0x0010
const PHOTO_ADULT 0x0008
const PHOTO_FLAG_OS 0x4000
const PHOTO_RES_ORIG 0
const PHOTO_RES_1024 1
const PHOTO_RES_640 2
const PHOTO_RES_320 3
const PHOTO_RES_PROFILE_300 4
const PHOTO_RES_PROFILE_80 5
const PHOTO_RES_PROFILE_48 6
const PHOTO_RES_COVER_1200 7
const PHOTO_RES_COVER_850 8
const PHOTO_RES_COVER_425 9
const MENU_SYSTEM 0x0001
const MENU_BOOKMARK 0x0002
const NETWORK_FRND 'friendica-over-diaspora'
const NETWORK_DFRN 'dfrn'
const NETWORK_ZOT 'zot'
const NETWORK_OSTATUS 'stat'
const NETWORK_GNUSOCIAL 'gnusoc'
const NETWORK_FEED 'rss'
const NETWORK_DIASPORA 'diaspora'
const NETWORK_ACTIVITYPUB 'activitypub'
const NETWORK_MAIL 'mail'
const NETWORK_MAIL2 'mai2'
const NETWORK_FACEBOOK 'face'
const NETWORK_LINKEDIN 'lnkd'
const NETWORK_XMPP 'xmpp'
const NETWORK_MYSPACE 'mysp'
const NETWORK_GPLUS 'goog'
const NETWORK_PHANTOM 'unkn'
const PERMS_R_STREAM 0x00001
const PERMS_R_PROFILE 0x00002
const PERMS_R_PHOTOS 0x00004
const PERMS_R_ABOOK 0x00008
const PERMS_W_STREAM 0x00010
const PERMS_W_WALL 0x00020
const PERMS_W_TAGWALL 0x00040
const PERMS_W_COMMENT 0x00080
const PERMS_W_MAIL 0x00100
const PERMS_W_PHOTOS 0x00200
const PERMS_W_CHAT 0x00400
const PERMS_A_DELEGATE 0x00800
const PERMS_R_STORAGE 0x01000
const PERMS_W_STORAGE 0x02000
const PERMS_R_PAGES 0x04000
const PERMS_W_PAGES 0x08000
const PERMS_A_REPUBLISH 0x10000
const PERMS_W_LIKE 0x20000
const PERMS_PUBLIC 0x0001
const PERMS_NETWORK 0x0002
const PERMS_SITE 0x0004
const PERMS_CONTACTS 0x0008
const PERMS_SPECIFIC 0x0080
const PERMS_AUTHED 0x0100
const PERMS_PENDING 0x0200
const ABOOK_FLAG_BLOCKED 0x0001
const ABOOK_FLAG_IGNORED 0x0002
const ABOOK_FLAG_HIDDEN 0x0004
const ABOOK_FLAG_ARCHIVED 0x0008
const ABOOK_FLAG_PENDING 0x0010
const ABOOK_FLAG_UNCONNECTED 0x0020
const ABOOK_FLAG_SELF 0x0080
const ABOOK_FLAG_FEED 0x0100
const MAIL_DELETED 0x0001
const MAIL_REPLIED 0x0002
const MAIL_ISREPLY 0x0004
const MAIL_SEEN 0x0008
const MAIL_RECALLED 0x0010
const MAIL_OBSCURED 0x0020
const ATTACH_FLAG_DIR 0x0001
const ATTACH_FLAG_OS 0x0002
const MENU_ITEM_ZID 0x0001
const MENU_ITEM_NEWWIN 0x0002
const MENU_ITEM_CHATROOM 0x0004
const SITE_TYPE_ZOT 0
const SITE_TYPE_NOTZOT 1
const SITE_TYPE_UNKNOWN 2
const POLL_SIMPLE_RATING 0x0001
const POLL_TENSCALE 0x0002
const POLL_MULTIPLE_CHOICE 0x0004
const POLL_OVERWRITE 0x8000
const UPDATE_FLAGS_UPDATED 0x0001
const UPDATE_FLAGS_FORCED 0x0002
const UPDATE_FLAGS_DELETED 0x1000
const DROPITEM_NORMAL 0
const DROPITEM_PHASE1 1
const DROPITEM_PHASE2 2
const MAX_LIKERS 10
const ZCURL_TIMEOUT (-1)
const NOTIFY_INTRO 0x0001
const NOTIFY_CONFIRM 0x0002
const NOTIFY_WALL 0x0004
const NOTIFY_COMMENT 0x0008
const NOTIFY_MAIL 0x0010
const NOTIFY_SUGGEST 0x0020
const NOTIFY_PROFILE 0x0040
const NOTIFY_TAGSELF 0x0080
const NOTIFY_TAGSHARE 0x0100
const NOTIFY_POKE 0x0200
const NOTIFY_LIKE 0x0400
const NOTIFY_SYSTEM 0x8000
const VNOTIFY_NETWORK 0x0001
const VNOTIFY_CHANNEL 0x0002
const VNOTIFY_MAIL 0x0004
const VNOTIFY_EVENT 0x0008
const VNOTIFY_EVENTTODAY 0x0010
const VNOTIFY_BIRTHDAY 0x0020
const VNOTIFY_SYSTEM 0x0040
const VNOTIFY_INFO 0x0080
const VNOTIFY_ALERT 0x0100
const VNOTIFY_INTRO 0x0200
const VNOTIFY_REGISTER 0x0400
const VNOTIFY_FILES 0x0800
const VNOTIFY_PUBS 0x1000
const TERM_UNKNOWN 0
const TERM_HASHTAG 1
const TERM_MENTION 2
const TERM_CATEGORY 3
const TERM_PCATEGORY 4
const TERM_FILE 5
const TERM_SAVEDSEARCH 6
const TERM_THING 7
const TERM_BOOKMARK 8
const TERM_HIERARCHY 9
const TERM_COMMUNITYTAG 10
const TERM_FORUM 11
const TERM_OBJ_POST 1
const TERM_OBJ_PHOTO 2
const TERM_OBJ_PROFILE 3
const TERM_OBJ_CHANNEL 4
const TERM_OBJ_OBJECT 5
const TERM_OBJ_THING 6
const TERM_OBJ_APP 7
const PROTOCOL_ZOT 'http://purl.org/zot/protocol'
const NAMESPACE_ZOT 'http://purl.org/zot'
const NAMESPACE_DFRN 'http://purl.org/macgirvin/dfrn/1.0'
const NAMESPACE_THREAD 'http://purl.org/syndication/thread/1.0'
const NAMESPACE_TOMB 'http://purl.org/atompub/tombstones/1.0'
const NAMESPACE_ACTIVITY 'http://activitystrea.ms/spec/1.0/'
const NAMESPACE_ACTIVITY_SCHEMA 'http://activitystrea.ms/schema/1.0/'
const NAMESPACE_MEDIA 'http://purl.org/syndication/atommedia'
const NAMESPACE_SALMON_ME 'http://salmon-protocol.org/ns/magic-env'
const NAMESPACE_OSTATUSSUB 'http://ostatus.org/schema/1.0/subscribe'
const NAMESPACE_GEORSS 'http://www.georss.org/georss'
const NAMESPACE_POCO 'http://portablecontacts.net/spec/1.0'
const NAMESPACE_FEED 'http://schemas.google.com/g/2010#updates-from'
const NAMESPACE_OSTATUS 'http://ostatus.org/schema/1.0'
const NAMESPACE_STATUSNET 'http://status.net/schema/api/1/'
const NAMESPACE_ATOM1 'http://www.w3.org/2005/Atom'
const NAMESPACE_YMEDIA 'http://search.yahoo.com/mrss/'
const ACTIVITYSTREAMS_JSONLD_REV 'https://www.w3.org/ns/activitystreams'
const ZOT_APSCHEMA_REV '/apschema/v1.2'
const ACTIVITY_PUBLIC_INBOX 'https://www.w3.org/ns/activitystreams#Public'
const ACTIVITY_REACT NAMESPACE_ZOT . '/activity/react'
const ACTIVITY_LIKE NAMESPACE_ACTIVITY_SCHEMA . 'like'
const ACTIVITY_DISLIKE NAMESPACE_ZOT . '/activity/dislike'
const ACTIVITY_AGREE NAMESPACE_ZOT . '/activity/agree'
const ACTIVITY_DISAGREE NAMESPACE_ZOT . '/activity/disagree'
const ACTIVITY_ABSTAIN NAMESPACE_ZOT . '/activity/abstain'
const ACTIVITY_ATTEND NAMESPACE_ZOT . '/activity/attendyes'
const ACTIVITY_ATTENDNO NAMESPACE_ZOT . '/activity/attendno'
const ACTIVITY_ATTENDMAYBE NAMESPACE_ZOT . '/activity/attendmaybe'
const ACTIVITY_OBJ_HEART NAMESPACE_ZOT . '/activity/heart'
const ACTIVITY_FRIEND NAMESPACE_ACTIVITY_SCHEMA . 'make-friend'
const ACTIVITY_REQ_FRIEND NAMESPACE_ACTIVITY_SCHEMA . 'request-friend'
const ACTIVITY_UNFRIEND NAMESPACE_ACTIVITY_SCHEMA . 'remove-friend'
const ACTIVITY_FOLLOW NAMESPACE_ACTIVITY_SCHEMA . 'follow'
const ACTIVITY_UNFOLLOW NAMESPACE_ACTIVITY_SCHEMA . 'stop-following'
const ACTIVITY_JOIN NAMESPACE_ACTIVITY_SCHEMA . 'join'
const ACTIVITY_POST NAMESPACE_ACTIVITY_SCHEMA . 'post'
const ACTIVITY_UPDATE NAMESPACE_ACTIVITY_SCHEMA . 'update'
const ACTIVITY_TAG NAMESPACE_ACTIVITY_SCHEMA . 'tag'
const ACTIVITY_SHARE NAMESPACE_ACTIVITY_SCHEMA . 'share'
const ACTIVITY_FAVORITE NAMESPACE_ACTIVITY_SCHEMA . 'favorite'
const ACTIVITY_CREATE NAMESPACE_ACTIVITY_SCHEMA . 'create'
const ACTIVITY_DELETE NAMESPACE_ACTIVITY_SCHEMA . 'delete'
const ACTIVITY_WIN NAMESPACE_ACTIVITY_SCHEMA . 'win'
const ACTIVITY_LOSE NAMESPACE_ACTIVITY_SCHEMA . 'lose'
const ACTIVITY_TIE NAMESPACE_ACTIVITY_SCHEMA . 'tie'
const ACTIVITY_COMPLETE NAMESPACE_ACTIVITY_SCHEMA . 'complete'
const ACTIVITY_POKE NAMESPACE_ZOT . '/activity/poke'
const ACTIVITY_MOOD NAMESPACE_ZOT . '/activity/mood'
const ACTIVITY_OBJ_COMMENT NAMESPACE_ACTIVITY_SCHEMA . 'comment'
const ACTIVITY_OBJ_ACTIVITY NAMESPACE_ACTIVITY_SCHEMA . 'activity'
const ACTIVITY_OBJ_NOTE NAMESPACE_ACTIVITY_SCHEMA . 'note'
const ACTIVITY_OBJ_PERSON NAMESPACE_ACTIVITY_SCHEMA . 'person'
const ACTIVITY_OBJ_PHOTO NAMESPACE_ACTIVITY_SCHEMA . 'photo'
const ACTIVITY_OBJ_P_PHOTO NAMESPACE_ACTIVITY_SCHEMA . 'profile-photo'
const ACTIVITY_OBJ_ALBUM NAMESPACE_ACTIVITY_SCHEMA . 'photo-album'
const ACTIVITY_OBJ_EVENT NAMESPACE_ACTIVITY_SCHEMA . 'event'
const ACTIVITY_OBJ_GROUP NAMESPACE_ACTIVITY_SCHEMA . 'group'
const ACTIVITY_OBJ_GAME NAMESPACE_ACTIVITY_SCHEMA . 'game'
const ACTIVITY_OBJ_WIKI NAMESPACE_ACTIVITY_SCHEMA . 'wiki'
const ACTIVITY_OBJ_TAGTERM NAMESPACE_ZOT . '/activity/tagterm'
const ACTIVITY_OBJ_PROFILE NAMESPACE_ZOT . '/activity/profile'
const ACTIVITY_OBJ_THING NAMESPACE_ZOT . '/activity/thing'
const ACTIVITY_OBJ_LOCATION NAMESPACE_ZOT . '/activity/location'
const ACTIVITY_OBJ_FILE NAMESPACE_ZOT . '/activity/file'
const ACTIVITY_OBJ_CARD NAMESPACE_ZOT . '/activity/card'
const ACCOUNT_OK 0x0000
const ACCOUNT_UNVERIFIED 0x0001
const ACCOUNT_BLOCKED 0x0002
const ACCOUNT_EXPIRED 0x0004
const ACCOUNT_REMOVED 0x0008
const ACCOUNT_PENDING 0x0010
const ACCOUNT_ROLE_SYSTEM 0x0002
const ACCOUNT_ROLE_DEVELOPER 0x0004
const ACCOUNT_ROLE_ADMIN 0x1000
const ITEM_VISIBLE 0x0000
const ITEM_HIDDEN 0x0001
const ITEM_BLOCKED 0x0002
const ITEM_MODERATED 0x0004
const ITEM_SPAM 0x0008
const ITEM_DELETED 0x0010
const ITEM_UNPUBLISHED 0x0020
const ITEM_WEBPAGE 0x0040
const ITEM_DELAYED_PUBLISH 0x0080
const ITEM_BUILDBLOCK 0x0100
const ITEM_PDL 0x0200
const ITEM_BUG 0x0400
const ITEM_PENDING_REMOVE 0x0800
const ITEM_DOC 0x1000
const ITEM_CARD 0x2000
const ITEM_ARTICLE 0x4000
const ITEM_TYPE_POST 0
const ITEM_TYPE_BLOCK 1
const ITEM_TYPE_PDL 2
const ITEM_TYPE_WEBPAGE 3
const ITEM_TYPE_BUG 4
const ITEM_TYPE_DOC 5
const ITEM_TYPE_CARD 6
const ITEM_TYPE_ARTICLE 7
const ITEM_IS_STICKY 1000
const DBTYPE_MYSQL 0
const DBTYPE_POSTGRES 1
Detailed Description
This file defines some global constants and includes the central App class.
Function Documentation
absurl ($path)
Return absolute URL for given $path.
Parameters
string $path
Returns
string
appdirpath ()
Returns appplication root directory.
Returns
string
Referenced by get_capath().
argc ()
Referenced by Zotlabs\Web\SubModule\__construct(), Zotlabs\Widget\Wiki_pages\create_missing_page(), Zotlabs\Module\Achievements\get(), Zotlabs\Module\Manage\get(), Zotlabs\Module\Update\get(), Zotlabs\Module\Dreport\get(), Zotlabs\Module\Regver\get(), Zotlabs\Module\Lockview\get(), Zotlabs\Module\Viewsrc\get(), Zotlabs\Module\Regmod\get(), Zotlabs\Module\Contactgroup\get(), Zotlabs\Module\Apps\get(), Zotlabs\Module\Article_edit\get(), Zotlabs\Module\Moderate\get(), Zotlabs\Module\Card_edit\get(), Zotlabs\Module\Like\get(), Zotlabs\Module\Admin\Dbsync\get(), Zotlabs\Module\Editpost\get(), Zotlabs\Module\Subthread\get(), Zotlabs\Module\Tagger\get(), Zotlabs\Module\Display\get(), Zotlabs\Module\Sharedwithme\get(), Zotlabs\Module\Dirsearch\get(), Zotlabs\Module\Help\get(), Zotlabs\Module\Oexchange\get(), Zotlabs\Module\Block\get(), Zotlabs\Module\Connections\get(), Zotlabs\Module\Articles\get(), Zotlabs\Module\Cards\get(), Zotlabs\Module\Profperm\get(), Zotlabs\Module\Pdledit\get(), Zotlabs\Module\Layouts\get(), Zotlabs\Module\Editblock\get(), Zotlabs\Module\Editlayout\get(), Zotlabs\Module\Editwebpage\get(), Zotlabs\Module\Hq\get(), Zotlabs\Module\Rpost\get(), Zotlabs\Module\Wiki\get(), Zotlabs\Module\Admin\Features\get(), Zotlabs\Module\Pconfig\get(), Zotlabs\Module\Admin\get(), Zotlabs\Module\Settings\Permcats\get(), Zotlabs\Module\Filestorage\get(), Zotlabs\Module\Cal\get(), Zotlabs\Module\Rbmark\get(), Zotlabs\Module\Home\get(), Zotlabs\Module\Admin\Account_edit\get(), Zotlabs\Module\Admin\Profs\get(), Zotlabs\Module\Tagrm\get(), Zotlabs\Module\Admin\Channels\get(), Zotlabs\Module\Group\get(), Zotlabs\Module\Menu\get(), Zotlabs\Module\Admin\Accounts\get(), Zotlabs\Module\Profile\get(), Zotlabs\Module\Sources\get(), Zotlabs\Module\Settings\Oauth\get(), Zotlabs\Module\Settings\Tokens\get(), Zotlabs\Module\Appman\get(), Zotlabs\Module\Chat\get(), Zotlabs\Module\Mitem\get(), Zotlabs\Module\Mail\get(), Zotlabs\Module\Thing\get(), Zotlabs\Module\Events\get(), Zotlabs\Module\Cover_photo\get(), Zotlabs\Module\Profile_photo\get(), Zotlabs\Module\Connedit\get(), Zotlabs\Module\Photos\get(), Zotlabs\Module\Profiles\get(), Zotlabs\Module\Cdav\get(), Zotlabs\Module\Item\get(), get_help_content(), Zotlabs\Module\Uexport\init(), Zotlabs\Module\Well_known\init(), Zotlabs\Module\Xref\init(), Zotlabs\Module\Nojs\init(), Zotlabs\Module\Notes\init(), Zotlabs\Module\Online\init(), Zotlabs\Module\Branchtopic\init(), Zotlabs\Module\Hcard\init(), Zotlabs\Module\Starred\init(), Zotlabs\Module\Notify\init(), Zotlabs\Module\Oembed\init(), Zotlabs\Module\Oexchange\init(), Zotlabs\Module\Viewconnections\init(), Zotlabs\Module\Ratingsearch\init(), Zotlabs\Module\Common\init(), Zotlabs\Module\Ratings\init(), Zotlabs\Module\Register\init(), Zotlabs\Module\Tasks\init(), Zotlabs\Module\Zotfeed\init(), Zotlabs\Module\Profiles\init(), Zotlabs\Module\Mitem\init(), Zotlabs\Module\Page\init(), Zotlabs\Module\Attach\init(), Zotlabs\Module\Editblock\init(), Zotlabs\Module\Editlayout\init(), Zotlabs\Module\Feed\init(), Zotlabs\Module\Share\init(), Zotlabs\Module\Layouts\init(), Zotlabs\Module\Articles\init(), Zotlabs\Module\Editwebpage\init(), Zotlabs\Module\New_channel\init(), Zotlabs\Module\Ofeed\init(), Zotlabs\Module\Webpages\init(), Zotlabs\Module\Blocks\init(), Zotlabs\Module\Photo\init(), Zotlabs\Module\Settings\init(), Zotlabs\Module\Permcat\init(), Zotlabs\Module\Home\init(), Zotlabs\Module\Cards\init(), Zotlabs\Module\Chat\init(), Zotlabs\Module\Connect\init(), Zotlabs\Module\Cal\init(), Zotlabs\Module\Oep\init(), Zotlabs\Module\Profile\init(), Zotlabs\Module\Photos\init(), Zotlabs\Module\Wiki\init(), Zotlabs\Module\Channel\init(), Zotlabs\Module\Ping\init(), Zotlabs\Module\Setup\init(), Zotlabs\Module\Connedit\init(), Zotlabs\Module\Dav\init(), Zotlabs\Module\Snap\init(), Zotlabs\Module\Cloud\init(), load_doc_file(), poco(), Zotlabs\Module\Settings\Oauth\post(), Zotlabs\Module\Group\post(), Zotlabs\Module\Wall_upload\post(), Zotlabs\Module\Admin\Plugins\post(), Zotlabs\Module\Wall_attach\post(), Zotlabs\Module\Menu\post(), Zotlabs\Module\Embedphotos\post(), Zotlabs\Module\Admin\post(), Zotlabs\Module\Settings\post(), Zotlabs\Module\Mitem\post(), Zotlabs\Module\Tasks\post(), Zotlabs\Module\Cover_photo\post(), Zotlabs\Module\Profile_photo\post(), Zotlabs\Module\Photos\post(), Zotlabs\Module\Connedit\post(), Zotlabs\Module\Profiles\post(), Zotlabs\Module\Cdav\post(), Zotlabs\Module\Wiki\post(), Zotlabs\Web\WebServer\run(), Zotlabs\Daemon\Queue\run(), Zotlabs\Widget\Conversations\widget(), Zotlabs\Widget\Cdav\widget(), and Zotlabs\Widget\Wiki_pages\widget().
argv ($x)
Referenced by Zotlabs\Web\SubModule\__construct(), channel_apps(), Zotlabs\Widget\Wiki_pages\create_missing_page(), determine_help_language(), Zotlabs\Module\Achievements\get(), Zotlabs\Module\Update\get(), Zotlabs\Module\Manage\get(), Zotlabs\Module\Dreport\get(), Zotlabs\Module\Regver\get(), Zotlabs\Module\Theme_info\get(), Zotlabs\Module\Viewsrc\get(), Zotlabs\Module\Lockview\get(), Zotlabs\Module\Regmod\get(), Zotlabs\Module\Apps\get(), Zotlabs\Module\Contactgroup\get(), Zotlabs\Module\Card_edit\get(), Zotlabs\Module\Article_edit\get(), Zotlabs\Module\Moderate\get(), Zotlabs\Module\Subthread\get(), Zotlabs\Module\Tagger\get(), Zotlabs\Module\Like\get(), Zotlabs\Module\Admin\Dbsync\get(), Zotlabs\Module\Editpost\get(), Zotlabs\Module\Display\get(), Zotlabs\Module\Sharedwithme\get(), Zotlabs\Module\Dirsearch\get(), Zotlabs\Module\Help\get(), Zotlabs\Module\Oexchange\get(), Zotlabs\Module\Block\get(), Zotlabs\Module\Cards\get(), Zotlabs\Module\Articles\get(), Zotlabs\Module\Connections\get(), Zotlabs\Module\Profperm\get(), Zotlabs\Module\Pdledit\get(), Zotlabs\Module\Layouts\get(), Zotlabs\Module\Editblock\get(), Zotlabs\Module\Editlayout\get(), Zotlabs\Module\Editwebpage\get(), Zotlabs\Module\Webpages\get(), Zotlabs\Module\Blocks\get(), Zotlabs\Module\Hq\get(), Zotlabs\Module\Rpost\get(), Zotlabs\Module\Wiki\get(), Zotlabs\Module\Admin\Features\get(), Zotlabs\Module\Pconfig\get(), Zotlabs\Module\Settings\Permcats\get(), Zotlabs\Module\Filestorage\get(), Zotlabs\Module\Cal\get(), Zotlabs\Module\Rbmark\get(), Zotlabs\Module\Home\get(), Zotlabs\Module\Admin\Account_edit\get(), Zotlabs\Module\Admin\Profs\get(), Zotlabs\Module\Tagrm\get(), Zotlabs\Module\Admin\Channels\get(), Zotlabs\Module\Group\get(), Zotlabs\Module\Menu\get(), Zotlabs\Module\Admin\Accounts\get(), Zotlabs\Module\Profile\get(), Zotlabs\Module\Sources\get(), Zotlabs\Module\Settings\Oauth\get(), Zotlabs\Module\Settings\Tokens\get(), Zotlabs\Module\Appman\get(), Zotlabs\Module\Chat\get(), Zotlabs\Module\Mitem\get(), Zotlabs\Module\Mail\get(), Zotlabs\Module\Thing\get(), Zotlabs\Module\Events\get(), Zotlabs\Module\Cover_photo\get(), Zotlabs\Module\Profile_photo\get(), Zotlabs\Module\Connedit\get(), Zotlabs\Module\Photos\get(), Zotlabs\Module\Profiles\get(), Zotlabs\Module\Cdav\get(), Zotlabs\Module\Item\get(), get_help_content(), get_online_status(), Zotlabs\Module\Siteinfo\init(), Zotlabs\Module\Uexport\init(), Zotlabs\Module\Well_known\init(), Zotlabs\Module\Xref\init(), Zotlabs\Module\Cloud_tiles\init(), Zotlabs\Module\Nojs\init(), Zotlabs\Module\Notes\init(), Zotlabs\Module\Online\init(), Zotlabs\Module\Prate\init(), Zotlabs\Module\Hcard\init(), Zotlabs\Module\Branchtopic\init(), Zotlabs\Module\Starred\init(), Zotlabs\Module\Viewconnections\init(), Zotlabs\Module\Notify\init(), Zotlabs\Module\Oembed\init(), Zotlabs\Module\Oexchange\init(), Zotlabs\Module\Ratingsearch\init(), Zotlabs\Module\Common\init(), Zotlabs\Module\Block\init(), Zotlabs\Module\Ratings\init(), Zotlabs\Module\Register\init(), Zotlabs\Module\Share\init(), Zotlabs\Module\Feed\init(), Zotlabs\Module\Tasks\init(), Zotlabs\Module\Editblock\init(), Zotlabs\Module\Page\init(), Zotlabs\Module\Layouts\init(), Zotlabs\Module\View\init(), Zotlabs\Module\Zotfeed\init(), Zotlabs\Module\Mitem\init(), Zotlabs\Module\Attach\init(), Zotlabs\Module\Profiles\init(), Zotlabs\Module\Editlayout\init(), Zotlabs\Module\Cards\init(), Zotlabs\Module\Permcat\init(), Zotlabs\Module\Articles\init(), Zotlabs\Module\Webpages\init(), Zotlabs\Module\Photo\init(), Zotlabs\Module\Home\init(), Zotlabs\Module\New_channel\init(), Zotlabs\Module\Ofeed\init(), Zotlabs\Module\Cdav\init(), Zotlabs\Module\Blocks\init(), Zotlabs\Module\Editwebpage\init(), Zotlabs\Module\Chat\init(), Zotlabs\Module\Connect\init(), Zotlabs\Module\Cal\init(), Zotlabs\Module\Oep\init(), Zotlabs\Module\Profile\init(), Zotlabs\Module\Photos\init(), Zotlabs\Module\Wiki\init(), Zotlabs\Module\Channel\init(), Zotlabs\Module\Ping\init(), Zotlabs\Module\Setup\init(), Zotlabs\Module\Connedit\init(), Zotlabs\Module\Dav\init(), Zotlabs\Module\Snap\init(), Zotlabs\Module\Cloud\init(), load_doc_file(), poco(), Zotlabs\Module\Settings\Oauth\post(), Zotlabs\Module\Group\post(), Zotlabs\Module\Pconfig\post(), Zotlabs\Module\Wall_upload\post(), Zotlabs\Module\Admin\Plugins\post(), Zotlabs\Module\Admin\Themes\post(), Zotlabs\Module\Wall_attach\post(), Zotlabs\Module\Menu\post(), Zotlabs\Module\Embedphotos\post(), Zotlabs\Module\Mitem\post(), Zotlabs\Module\Tasks\post(), Zotlabs\Module\Cover_photo\post(), Zotlabs\Module\Defperms\post(), Zotlabs\Module\Profile_photo\post(), Zotlabs\Module\Photos\post(), Zotlabs\Module\Connedit\post(), Zotlabs\Module\Profiles\post(), Zotlabs\Module\Cdav\post(), Zotlabs\Module\Wiki\post(), profile_tabs(), Zotlabs\Web\WebServer\run(), Zotlabs\Daemon\Queue\run(), Zotlabs\Widget\Settings_menu\widget(), Zotlabs\Widget\Conversations\widget(), Zotlabs\Widget\Mailmenu\widget(), Zotlabs\Widget\Collections\widget(), Zotlabs\Widget\Cdav\widget(), and Zotlabs\Widget\Wiki_pages\widget().
build_querystring ($params, $name = null)
Returns querystring as string from a mapped array.
Parameters
array $params mapped array with query parameters
string $name of parameter, default null
Returns
string
cert_bad_email ()
Send email to admin if server has an invalid certificate.
If a hub is available over https it must have a publicly valid certificate.
Referenced by z_check_cert().
check_config ()
Primarily involved with database upgrade, but also sets the base url for use in cmdline programs which don't have $_SERVER variables, and synchronising the state of installed plugins.
Synchronise plugins:
App::$config['system']['addon'] contains a comma-separated list of names of plugins/addons which are used on this system. Go through the database list of already installed addons, and if we have an entry, but it isn't in the config list, call the unload procedure and mark it uninstalled in the database (for now we'll remove it). Then go through the config list and if we have a plugin that isn't installed, call the install procedure and add it to the database.
Referenced by Zotlabs\Web\WebServer\run().
check_cron_broken ()
Send warnings every 3-5 days if cron is not running.
Referenced by check_config().
check_for_new_perms ()
Referenced by check_config().
clean_urls ()
Referenced by z_path().
construct_page ()
build the page.
Build the page - now that we have all the components
Hooks:
construct_page General purpose hook to provide content to certain page regions. Called when constructing the Comanche page.
string module
string layout
Referenced by Zotlabs\Module\Cloud\DAVException(), Zotlabs\Module\Cloud\init(), and Zotlabs\Web\WebServer\run().
curPageURL ()
Returns the complete URL of the current page, e.g.: http(s)://something.com/network.
Taken from http://webcheatsheet.com/php/get_current_page_url.php
Returns
string
Referenced by construct_page().
dba_timer ()
Referenced by Zotlabs\Module\Ping\init(), and private_messages_list().
exec_pdl ()
Referenced by construct_page().
fix_system_urls ($oldurl, $newurl)
Referenced by check_config().
get_account_id ()
Returns the entity id of locally logged in account or false.
Returns numeric account_id if authenticated or 0. It is possible to be authenticated and not connected to a channel.
Returns
int|bool account_id or false
Referenced by api_user(), change_channel(), file_activity(), Zotlabs\Module\Manage\get(), Zotlabs\Module\Rpost\get(), Zotlabs\Module\New_channel\get(), Zotlabs\Module\Import\get(), identity_selector(), import_profiles(), Zotlabs\Module\Profiles\init(), Zotlabs\Module\Home\init(), Zotlabs\Module\Mood\init(), nav(), observer_prohibited(), Zotlabs\Module\Removeaccount\post(), Zotlabs\Module\Settings\Account\post(), Zotlabs\Module\Events\post(), Zotlabs\Module\Cover_photo\post(), Zotlabs\Module\Profile_photo\post(), Zotlabs\Module\New_channel\post(), and Zotlabs\Module\Import\post().
get_custom_nav ($navname)
Returns a custom navigation by name???
If no $navname provided load default page['nav']
Todo:
not fully implemented yet
Parameters
string $navname
Returns
mixed
get_directory_primary ()
Return the primary directory server.
Returns
string
Referenced by import_site(), Zotlabs\Daemon\Cron_weekly\run(), and Zotlabs\Daemon\Ratenotif\run().
get_directory_realm ()
Return the Realm of the directory.
Returns
string
Referenced by Zotlabs\Lib\System\compatible_project(), Zotlabs\Module\Admin\Site\get(), import_site(), import_xchan(), Zotlabs\Module\Sitelist\init(), Zotlabs\Module\Regdir\init(), Zotlabs\Module\Dirsearch\list_public_sites(), Zotlabs\Daemon\Cron_weekly\run(), sync_directories(), and zot_site_info().
get_max_import_size ()
Wrapper around config to limit the text length of an incoming message.
Returns
int
Referenced by get_item_elements(), and limit_body_size().
get_observer_hash ()
Returns xchan_hash from the observer.
Returns
string xchan_hash from observer, otherwise empty string if no observer
Referenced by advanced_profile(), api_attach_list(), api_network_stream(), Zotlabs\Lib\Apps\app_store(), Zotlabs\Lib\Apps\app_update(), article_tagadelic(), attach_mkdir(), attach_store(), builtin_activity_puller(), card_tagadelic(), channel_apps(), common_friends_visitor_widget(), contact_block(), Zotlabs\Widget\Wiki_pages\create_missing_page(), dir_sort_links(), dir_tagblock(), Zotlabs\Module\Embedphotos\embedphotos_widget_album(), Zotlabs\Module\Pubstream\get(), Zotlabs\Module\Article_edit\get(), Zotlabs\Module\Card_edit\get(), Zotlabs\Module\Tagger\get(), Zotlabs\Module\Editpost\get(), Zotlabs\Module\Display\get(), Zotlabs\Module\Viewconnections\get(), Zotlabs\Module\Block\get(), Zotlabs\Module\Suggest\get(), Zotlabs\Module\Common\get(), Zotlabs\Module\Editblock\get(), Zotlabs\Module\Editwebpage\get(), Zotlabs\Module\Network\get(), Zotlabs\Module\Hq\get(), Zotlabs\Module\Wiki\get(), Zotlabs\Module\Cal\get(), Zotlabs\Module\Directory\get(), Zotlabs\Module\Bookmarks\get(), Zotlabs\Module\Channel\get(), Zotlabs\Module\Menu\get(), Zotlabs\Module\Chatsvc\get(), Zotlabs\Module\Profile\get(), Zotlabs\Module\Chat\get(), Zotlabs\Module\Mitem\get(), Zotlabs\Module\Thing\get(), Zotlabs\Module\Events\get(), Zotlabs\Module\Photos\get(), Zotlabs\Module\Item\get(), Zotlabs\Lib\ThreadItem\get_comment_box(), Zotlabs\Render\Comanche\get_condition_var(), get_public_feed(), import_webpage_element(), Zotlabs\Module\Toggle_safesearch\init(), Zotlabs\Module\Magic\init(), Zotlabs\Module\Attach\init(), Zotlabs\Module\Zotfeed\init(), Zotlabs\Module\Photo\init(), Zotlabs\Module\Chatsvc\init(), Zotlabs\Module\Impel\init(), Zotlabs\Module\Directory\init(), Zotlabs\Module\Thing\init(), Zotlabs\Module\Ping\init(), Zotlabs\Module\Acl\init(), Zotlabs\Module\Cloud\init(), item_permissions_sql(), Zotlabs\Render\Comanche\menu(), menu_render(), new_contact(), Zotlabs\Module\Oep\oep_album_reply(), Zotlabs\Module\Oep\oep_articles_reply(), Zotlabs\Module\Oep\oep_cards_reply(), Zotlabs\Module\Oep\oep_display_reply(), Zotlabs\Module\Oep\oep_mid_reply(), Zotlabs\Module\Oep\oep_photo_reply(), Zotlabs\Module\Oep\oep_phototop_reply(), Zotlabs\Module\Oep\oep_profile_reply(), permissions_sql(), Zotlabs\Module\File_upload\post(), Zotlabs\Module\Events\post(), Zotlabs\Module\Mail\post(), Zotlabs\Module\Menu\post(), Zotlabs\Module\Chatsvc\post(), Zotlabs\Module\Mitem\post(), Zotlabs\Module\Cover_photo\post(), Zotlabs\Module\Profile_photo\post(), Zotlabs\Module\Photos\post(), Zotlabs\Module\Wiki\post(), prepare_body(), profile_sidebar(), red_item(), Zotlabs\Lib\NativeWikiPage\render_page_history(), send_message(), stream_perms_xchans(), tagadelic(), thread_action_menu(), Zotlabs\Widget\Wiki_page_history\widget(), Zotlabs\Widget\Zcard\widget(), Zotlabs\Widget\Tagcloud_wall\widget(), Zotlabs\Widget\Wiki_list\widget(), Zotlabs\Widget\Bookmarkedchats\widget(), Zotlabs\Widget\Catcloud_wall\widget(), Zotlabs\Widget\Suggestedchats\widget(), Zotlabs\Widget\Archive\widget(), Zotlabs\Widget\Common_friends\widget(), Zotlabs\Widget\Portfolio\widget(), Zotlabs\Widget\Photo_albums\widget(), Zotlabs\Widget\Album\widget(), Zotlabs\Widget\Categories\widget(), Zotlabs\Widget\Item\widget(), Zotlabs\Widget\Suggestions\widget(), Zotlabs\Widget\Wiki_pages\widget(), and z_readdir().
get_poller_runtime ()
Return relative date of last completed poller execution.
Returns
string relative date of last completed poller execution
goaway ($s)
Redirect to another URL and terminate this process.
Referenced by Zotlabs\Zot\Auth\__construct(), account_remove(), authenticate_success(), channel_remove(), check_form_security_token_redirectOnErr(), drop_item(), Zotlabs\Zot\Auth\Finalise(), Zotlabs\Module\Login\get(), Zotlabs\Module\Manage\get(), Zotlabs\Module\Dreport\get(), Zotlabs\Module\Filerm\get(), Zotlabs\Module\Chanview\get(), Zotlabs\Module\Moderate\get(), Zotlabs\Module\Admin\Dbsync\get(), Zotlabs\Module\Editpost\get(), Zotlabs\Module\Display\get(), Zotlabs\Module\Search\get(), Zotlabs\Module\Sharedwithme\get(), Zotlabs\Module\Pdledit\get(), Zotlabs\Module\Api\get(), Zotlabs\Module\Network\get(), Zotlabs\Module\Rpost\get(), Zotlabs\Module\Hq\get(), Zotlabs\Module\Wiki\get(), Zotlabs\Module\Admin\Themes\get(), Zotlabs\Module\Removeaccount\get(), Zotlabs\Module\Filestorage\get(), Zotlabs\Module\Removeme\get(), Zotlabs\Module\Rbmark\get(), Zotlabs\Module\Home\get(), Zotlabs\Module\Admin\Profs\get(), Zotlabs\Module\Admin\Channels\get(), Zotlabs\Module\Tagrm\get(), Zotlabs\Module\Lostpass\get(), Zotlabs\Module\Directory\get(), Zotlabs\Module\Changeaddr\get(), Zotlabs\Module\Channel\get(), Zotlabs\Module\Group\get(), Zotlabs\Module\Menu\get(), Zotlabs\Module\Chatsvc\get(), Zotlabs\Module\Admin\Accounts\get(), Zotlabs\Module\Sources\get(), Zotlabs\Module\Settings\Oauth\get(), Zotlabs\Module\Locs\get(), Zotlabs\Module\Appman\get(), Zotlabs\Module\Chat\get(), Zotlabs\Module\Mitem\get(), Zotlabs\Module\Mail\get(), Zotlabs\Module\Events\get(), Zotlabs\Module\Admin\Plugins\get(), Zotlabs\Module\Profile_photo\get(), Zotlabs\Module\Connedit\get(), Zotlabs\Module\Photos\get(), get_help_content(), Zotlabs\Module\Import\import_account(), Zotlabs\Module\Logout\init(), Zotlabs\Module\Cloud_tiles\init(), Zotlabs\Module\Nojs\init(), Zotlabs\Module\Rmagic\init(), Zotlabs\Module\Toggle_mobile\init(), Zotlabs\Module\Toggle_safesearch\init(), Zotlabs\Module\Xref\init(), Zotlabs\Module\Notify\init(), Zotlabs\Module\Randprof\init(), Zotlabs\Module\Magic\init(), Zotlabs\Module\Wfinger\init(), Zotlabs\Module\Profiles\init(), Zotlabs\Module\Follow\init(), Zotlabs\Module\Home\init(), Zotlabs\Module\Directory\init(), Zotlabs\Module\Mood\init(), Zotlabs\Module\Network\init(), Zotlabs\Module\Wiki\init(), Zotlabs\Module\Cloud\init(), new_contact(), Zotlabs\Module\Pdledit\post(), Zotlabs\Module\Settings\Account\post(), Zotlabs\Module\Sources\post(), Zotlabs\Module\Changeaddr\post(), Zotlabs\Module\Lostpass\post(), Zotlabs\Module\Admin\Security\post(), Zotlabs\Module\Admin\Profs\post(), Zotlabs\Module\Tagrm\post(), Zotlabs\Module\Settings\Oauth\post(), Zotlabs\Module\Admin\Account_edit\post(), Zotlabs\Module\Group\post(), Zotlabs\Module\Filestorage\post(), Zotlabs\Module\Admin\Features\post(), Zotlabs\Module\Pconfig\post(), Zotlabs\Module\Settings\Channel\post(), Zotlabs\Module\File_upload\post(), Zotlabs\Module\Appman\post(), Zotlabs\Module\Admin\Site\post(), Zotlabs\Module\Settings\Display\post(), Zotlabs\Module\Events\post(), Zotlabs\Module\Mail\post(), Zotlabs\Module\Admin\Plugins\post(), Zotlabs\Module\Admin\Logs\post(), Zotlabs\Module\Admin\Channels\post(), Zotlabs\Module\Admin\Themes\post(), Zotlabs\Module\Admin\Accounts\post(), Zotlabs\Module\Menu\post(), Zotlabs\Module\Rmagic\post(), Zotlabs\Module\Admin\post(), Zotlabs\Module\Rbmark\post(), Zotlabs\Module\Item\post(), Zotlabs\Module\Connect\post(), Zotlabs\Module\Settings\post(), Zotlabs\Module\Mitem\post(), Zotlabs\Module\Register\post(), Zotlabs\Module\Cover_photo\post(), Zotlabs\Module\Defperms\post(), Zotlabs\Module\Chat\post(), Zotlabs\Module\Profile_photo\post(), Zotlabs\Module\Photos\post(), Zotlabs\Module\Connedit\post(), Zotlabs\Module\New_channel\post(), Zotlabs\Module\Wiki\post(), Zotlabs\Web\Session\return_check(), and zid_init().
head_get_icon ()
Get the pageicon.
Returns
string absolut path to pageicon
head_set_icon ($icon)
Set a pageicon.
Parameters
string $icon
Referenced by Zotlabs\Module\Message\get(), Zotlabs\Module\Settings\get(), Zotlabs\Module\Mail\get(), Zotlabs\Module\Block\init(), Zotlabs\Module\Page\init(), Zotlabs\Module\Connections\init(), Zotlabs\Module\Network\init(), Zotlabs\Module\Cal\init(), Zotlabs\Module\Photos\init(), Zotlabs\Module\Defperms\init(), Zotlabs\Module\Connedit\init(), and profile_sidebar().
info ($s)
Show an information text on next page load.
Contents of $s are displayed prominently on the page the next time a page is loaded. Usually used for information.
For error and alerts use notice().
Parameters
string $s Text to display
Referenced by account_allow(), Zotlabs\Lib\NativeWiki\delete_wiki(), Zotlabs\Module\Regmod\get(), Zotlabs\Module\Admin\Dbsync\get(), Zotlabs\Module\Oexchange\get(), Zotlabs\Module\Viewconnections\get(), Zotlabs\Module\Suggest\get(), Zotlabs\Module\Network\get(), Zotlabs\Module\Admin\Themes\get(), Zotlabs\Module\Filestorage\get(), Zotlabs\Module\Tagrm\get(), Zotlabs\Module\Lostpass\get(), Zotlabs\Module\Directory\get(), Zotlabs\Module\Group\get(), Zotlabs\Module\Sources\get(), Zotlabs\Module\Locs\get(), Zotlabs\Module\Mitem\get(), Zotlabs\Module\Mail\get(), Zotlabs\Module\Events\get(), Zotlabs\Module\Admin\Plugins\get(), Zotlabs\Module\Connedit\get(), Zotlabs\Module\Bookmarks\init(), Zotlabs\Module\Profiles\init(), Zotlabs\Module\Follow\init(), Zotlabs\Module\Impel\init(), Zotlabs\Module\Thing\init(), owt_init(), Zotlabs\Module\Pdledit\post(), Zotlabs\Module\Settings\Account\post(), Zotlabs\Module\Sources\post(), Zotlabs\Module\Settings\Featured\post(), Zotlabs\Module\Lostpass\post(), Zotlabs\Module\Admin\Account_edit\post(), Zotlabs\Module\Tagrm\post(), Zotlabs\Module\Settings\Permcats\post(), Zotlabs\Module\Settings\Tokens\post(), Zotlabs\Module\Group\post(), Zotlabs\Module\Appman\post(), Zotlabs\Module\Settings\Channel\post(), Zotlabs\Module\Admin\Site\post(), Zotlabs\Module\Events\post(), Zotlabs\Module\Import_items\post(), Zotlabs\Module\Admin\Logs\post(), Zotlabs\Module\Admin\Themes\post(), Zotlabs\Module\Item\post(), Zotlabs\Module\Register\post(), Zotlabs\Module\Profile_photo\post(), Zotlabs\Module\Connedit\post(), Zotlabs\Module\Profiles\post(), Zotlabs\Module\Webpages\post(), Zotlabs\Lib\NativeWiki\update_wiki(), Zotlabs\Zot\Auth\Verify(), and Zotlabs\Widget\Conversations\widget().
is_ajax ()
Function to check if request was an AJAX (xmlhttprequest) request.
Returns
boolean
Referenced by Zotlabs\Module\Viewsrc\get(), Zotlabs\Module\Admin\get(), Zotlabs\Module\Admin\Themes\post(), and Zotlabs\Module\Photos\post().
is_developer ()
Check if current user has developer role.
Check if the current user has ACCOUNT_ROLE_DEVELOPER.
Returns
bool true if user is a developer
Referenced by change_channel(), and Zotlabs\Module\Achievements\get().
is_site_admin ()
Check if current user has admin role.
Check if the current user has ACCOUNT_ROLE_ADMIN.
Returns
bool true if user is an admin
Referenced by Zotlabs\Storage\GitRepo\__construct(), Zotlabs\Lib\Apps\app_render(), change_channel(), check_account_admin(), design_tools(), drop_item(), findpeople_widget(), Zotlabs\Module\Regmod\get(), Zotlabs\Module\Probe\get(), Zotlabs\Module\Fhublocs\get(), Zotlabs\Module\Editblock\get(), Zotlabs\Module\Editlayout\get(), Zotlabs\Module\Layouts\get(), Zotlabs\Module\Editwebpage\get(), Zotlabs\Module\Webpages\get(), Zotlabs\Module\Blocks\get(), Zotlabs\Module\Admin\get(), Zotlabs\Module\Menu\get(), Zotlabs\Module\Invite\get(), Zotlabs\Module\Mitem\get(), Zotlabs\Module\Item\get(), import_channel(), Zotlabs\Module\Mitem\init(), Zotlabs\Module\Editblock\init(), Zotlabs\Module\Editlayout\init(), Zotlabs\Module\Layouts\init(), Zotlabs\Module\Menu\init(), Zotlabs\Module\Webpages\init(), Zotlabs\Module\Editwebpage\init(), Zotlabs\Module\Blocks\init(), Zotlabs\Module\Thing\init(), Zotlabs\Module\Ping\init(), nav(), Zotlabs\Lib\Apps\parse_app_description(), Zotlabs\Module\Invite\post(), Zotlabs\Module\Menu\post(), Zotlabs\Module\Admin\post(), Zotlabs\Module\Item\post(), Zotlabs\Module\Mitem\post(), Zotlabs\Module\Register\post(), website_portation_tools(), Zotlabs\Widget\Notifications\widget(), and Zotlabs\Widget\Admin\widget().
is_windows ()
Checks if we are running on M$ Windows.
Returns
bool true if we run on M$ Windows
It's possible you might be able to run on WAMP or XAMPP, and this has been accomplished, but is not officially supported. Good luck.
Referenced by Zotlabs\Module\Setup\check_php(), and proc_run().
killme ()
Used to end the current process, after saving session state.
Referenced by Zotlabs\Render\SmartyTemplate\__construct(), Zotlabs\Web\Router\__construct(), api_file_data(), api_file_detail(), api_file_export(), api_file_meta(), api_login(), api_oauth_access_token(), api_oauth_request_token(), api_photo_detail(), api_zot_version(), check_form_security_token_ForbiddenOnErr(), Zotlabs\Module\Cloud\DAVException(), Zotlabs\Module\Regver\get(), Zotlabs\Module\Update\get(), Zotlabs\Module\Filerm\get(), Zotlabs\Module\Regmod\get(), Zotlabs\Module\Theme_info\get(), Zotlabs\Module\Viewsrc\get(), Zotlabs\Module\Lockview\get(), Zotlabs\Module\Contactgroup\get(), Zotlabs\Module\Token\get(), Zotlabs\Module\Authorize\get(), Zotlabs\Module\Linkinfo\get(), Zotlabs\Module\Subthread\get(), Zotlabs\Module\Tagger\get(), Zotlabs\Module\Filer\get(), Zotlabs\Module\Like\get(), Zotlabs\Module\Display\get(), Zotlabs\Module\Fbrowser\get(), Zotlabs\Module\Help\get(), Zotlabs\Module\Viewconnections\get(), Zotlabs\Module\Connections\get(), Zotlabs\Module\Layouts\get(), Zotlabs\Module\Api\get(), Zotlabs\Module\Network\get(), Zotlabs\Module\Wiki\get(), Zotlabs\Module\Admin\get(), Zotlabs\Module\Filestorage\get(), Zotlabs\Module\Cal\get(), Zotlabs\Module\Home\get(), Zotlabs\Module\Directory\get(), Zotlabs\Module\Profile\get(), Zotlabs\Module\Mail\get(), Zotlabs\Module\Events\get(), Zotlabs\Module\Photos\get(), goaway(), http_status_exit(), Zotlabs\Module\Prate\init(), Zotlabs\Module\Pretheme\init(), Zotlabs\Module\Sitelist\init(), Zotlabs\Module\Sslify\init(), Zotlabs\Module\Uexport\init(), Zotlabs\Module\Well_known\init(), Zotlabs\Module\Zfinger\init(), Zotlabs\Module\Hostxrd\init(), Zotlabs\Module\Bookmarks\init(), Zotlabs\Module\Search_ac\init(), Zotlabs\Module\Starred\init(), Zotlabs\Module\Oembed\init(), Zotlabs\Module\Oexchange\init(), Zotlabs\Module\Wfinger\init(), Zotlabs\Module\Xrd\init(), Zotlabs\Module\Profiles\init(), Zotlabs\Module\Share\init(), Zotlabs\Module\View\init(), Zotlabs\Module\Feed\init(), Zotlabs\Module\Attach\init(), Zotlabs\Module\Photo\init(), Zotlabs\Module\Ofeed\init(), Zotlabs\Module\Cdav\init(), Zotlabs\Module\Oep\init(), Zotlabs\Module\Ping\init(), Zotlabs\Module\Acl\init(), Zotlabs\Module\Setup\init(), Zotlabs\Module\Dav\init(), Zotlabs\Module\Snap\init(), Zotlabs\Module\Cloud\init(), json_return_and_die(), ZotOAuth1\loginUser(), poco(), Zotlabs\Module\File_upload\post(), Zotlabs\Module\Events\post(), Zotlabs\Module\Wall_upload\post(), Zotlabs\Module\Mail\post(), Zotlabs\Module\Wall_attach\post(), Zotlabs\Module\Getfile\post(), Zotlabs\Module\Item\post(), Zotlabs\Module\Photos\post(), Zotlabs\Module\Setup\post(), Zotlabs\Module\Cdav\post(), Zotlabs\Module\Webpages\post(), App\register_template_engine(), retry_basic_auth(), Zotlabs\Web\WebServer\run(), Zotlabs\Daemon\Poller\run(), Zotlabs\Daemon\Cron\run(), Zotlabs\Daemon\CurlAuth\run(), system_unavailable(), and App\template_engine().
load_contact_links ($uid)
Referenced by api_call(), conversation(), Zotlabs\Module\Ratings\init(), and thread_author_menu().
load_pdl ()
Loads a page definition file for a module.
If there is no parsed Comanche template already load a module's pdl file and parse it with Comanche.
Hooks:
load_pdl Called when we load a PDL file or description.
string module
string layout
Referenced by Zotlabs\Web\Router\Dispatch().
local_channel ()
Returns the entity id (channel_id) of locally logged in channel or false.
Returns authenticated numeric channel_id if authenticated and connected to a channel or 0. Sometimes referred to as $uid in the code.
Before 2.1 this function was called local_user().
Since
2.1
Returns
int|bool channel_id or false
Referenced by Zotlabs\Lib\ThreadStream\__construct(), Zotlabs\Lib\ThreadStream\add_thread(), api_photo_detail(), api_user(), Zotlabs\Lib\Apps\app_render(), app_tagadelic(), best_link_url(), App\build_pagehead(), build_sync_packet(), change_channel(), channel_apps(), channel_remove(), check_form_security_token(), common_friends_visitor_widget(), Zotlabs\Module\Connedit\connedit_clone(), construct_page(), contact_block(), contact_select(), conversation(), Zotlabs\Widget\Wiki_pages\create_missing_page(), Zotlabs\Module\Defperms\defperms_clone(), drop_item(), drop_items(), file_activity(), fileas_widget(), findpeople_widget(), Zotlabs\Theme\RedbasicConfig\form(), Zotlabs\Module\Dreport\get(), Zotlabs\Module\Filerm\get(), Zotlabs\Module\Login\get(), Zotlabs\Module\Manage\get(), Zotlabs\Module\Pubsites\get(), Zotlabs\Module\Viewsrc\get(), Zotlabs\Module\Lockview\get(), Zotlabs\Module\Notifications\get(), Zotlabs\Module\Chanview\get(), Zotlabs\Module\React\get(), Zotlabs\Module\Regmod\get(), Zotlabs\Module\Service_limits\get(), Zotlabs\Module\Zping\get(), Zotlabs\Module\Apps\get(), Zotlabs\Module\Contactgroup\get(), Zotlabs\Module\Pubstream\get(), Zotlabs\Module\Moderate\get(), Zotlabs\Module\Article_edit\get(), Zotlabs\Module\Card_edit\get(), Zotlabs\Module\Editpost\get(), Zotlabs\Module\Filer\get(), Zotlabs\Module\Like\get(), Zotlabs\Module\Message\get(), Zotlabs\Module\Subthread\get(), Zotlabs\Module\Tagger\get(), Zotlabs\Module\Display\get(), Zotlabs\Module\Apporder\get(), Zotlabs\Module\Search\get(), Zotlabs\Module\Sharedwithme\get(), Zotlabs\Module\Fbrowser\get(), Zotlabs\Module\Oexchange\get(), Zotlabs\Module\Viewconnections\get(), Zotlabs\Module\Articles\get(), Zotlabs\Module\Cards\get(), Zotlabs\Module\Connections\get(), Zotlabs\Module\Suggest\get(), Zotlabs\Module\Profperm\get(), Zotlabs\Module\Pdledit\get(), Zotlabs\Module\Editblock\get(), Zotlabs\Module\Editlayout\get(), Zotlabs\Module\Layouts\get(), Zotlabs\Module\Editwebpage\get(), Zotlabs\Module\Webpages\get(), Zotlabs\Module\Settings\Features\get(), Zotlabs\Module\Api\get(), Zotlabs\Module\Blocks\get(), Zotlabs\Module\Network\get(), Zotlabs\Module\Hq\get(), Zotlabs\Theme\RedbasicConfig\get(), Zotlabs\Module\Rpost\get(), Zotlabs\Module\Settings\Featured\get(), Zotlabs\Module\Wiki\get(), Zotlabs\Module\Notify\get(), Zotlabs\Module\Pconfig\get(), Zotlabs\Module\Settings\Permcats\get(), Zotlabs\Module\Removeaccount\get(), Zotlabs\Module\Filestorage\get(), Zotlabs\Module\Removeme\get(), Zotlabs\Module\Cal\get(), Zotlabs\Module\Rbmark\get(), Zotlabs\Module\Settings\get(), Zotlabs\Module\Tagrm\get(), Zotlabs\Module\Directory\get(), Zotlabs\Module\Follow\get(), Zotlabs\Module\Bookmarks\get(), Zotlabs\Module\Changeaddr\get(), Zotlabs\Module\Channel\get(), Zotlabs\Module\Group\get(), Zotlabs\Module\Menu\get(), Zotlabs\Module\Profile\get(), Zotlabs\Module\Sources\get(), Zotlabs\Module\Settings\Oauth\get(), Zotlabs\Module\Connect\get(), Zotlabs\Module\Settings\Tokens\get(), Zotlabs\Module\Locs\get(), Zotlabs\Module\Appman\get(), Zotlabs\Module\Chat\get(), Zotlabs\Module\Invite\get(), Zotlabs\Module\Tasks\get(), Zotlabs\Module\Mitem\get(), Zotlabs\Module\Settings\Display\get(), Zotlabs\Module\Rate\get(), Zotlabs\Module\Mood\get(), Zotlabs\Module\Import_items\get(), Zotlabs\Module\Mail\get(), Zotlabs\Module\Poke\get(), Zotlabs\Module\Defperms\get(), Zotlabs\Module\Thing\get(), Zotlabs\Module\Events\get(), Zotlabs\Module\Cover_photo\get(), Zotlabs\Module\Profile_photo\get(), Zotlabs\Module\Settings\Channel\get(), Zotlabs\Module\Connedit\get(), Zotlabs\Module\Photos\get(), Zotlabs\Module\Profiles\get(), Zotlabs\Module\Cdav\get(), Zotlabs\Module\Item\get(), Zotlabs\Render\Comanche\get_channel_id(), Zotlabs\Lib\ThreadItem\get_comment_box(), Zotlabs\Render\Comanche\get_condition_var(), get_form_security_token(), Zotlabs\Lib\NativeWiki\get_permissions(), Zotlabs\Lib\ThreadItem\get_template_data(), get_theme_uid(), group_get_members(), group_get_members_xchan(), group_select(), group_side(), handle_tag(), identity_selector(), Zotlabs\Lib\Apps\import_system_apps(), import_webpage_element(), Zotlabs\Module\Uexport\init(), Zotlabs\Module\Hcard\init(), Zotlabs\Module\Notes\init(), Zotlabs\Module\Bookmarks\init(), Zotlabs\Module\Branchtopic\init(), Zotlabs\Module\Prate\init(), Zotlabs\Module\Rmagic\init(), Zotlabs\Module\Cloud_tiles\init(), Zotlabs\Module\Starred\init(), Zotlabs\Module\Notify\init(), Zotlabs\Module\Rate\init(), Zotlabs\Module\Search_ac\init(), Zotlabs\Module\Magic\init(), Zotlabs\Module\Ratings\init(), Zotlabs\Module\Profperm\init(), Zotlabs\Module\Follow\init(), Zotlabs\Module\Mitem\init(), Zotlabs\Module\Profiles\init(), Zotlabs\Module\Share\init(), Zotlabs\Module\Suggest\init(), Zotlabs\Module\Permcat\init(), Zotlabs\Module\Home\init(), Zotlabs\Module\Impel\init(), Zotlabs\Module\Cdav\init(), Zotlabs\Module\Settings\init(), Zotlabs\Module\Connections\init(), Zotlabs\Module\Directory\init(), Zotlabs\Module\Mood\init(), Zotlabs\Module\Chat\init(), Zotlabs\Module\Hq\init(), Zotlabs\Module\Network\init(), Zotlabs\Module\Profile\init(), Zotlabs\Module\Thing\init(), Zotlabs\Module\Wiki\init(), Zotlabs\Module\Defperms\init(), Zotlabs\Module\Channel\init(), Zotlabs\Module\Ping\init(), Zotlabs\Module\Acl\init(), Zotlabs\Module\Poke\init(), Zotlabs\Module\Connedit\init(), Zotlabs\Module\Cover_photo\init(), Zotlabs\Module\Snap\init(), Zotlabs\Module\Cloud\init(), Zotlabs\Module\Profile_photo\init(), is_public_profile(), item_permissions_sql(), items_fetch(), login(), menu_add_item(), menu_edit_item(), menu_render(), mimetype_select(), nav(), observer_prohibited(), oembed_action(), oembed_fetch_url(), Zotlabs\Lib\Apps\parse_app_description(), Zotlabs\Module\Pconfig\pconfig_form(), permissions_sql(), populate_acl(), Zotlabs\Module\Sources\post(), Zotlabs\Module\Pdledit\post(), Zotlabs\Module\Changeaddr\post(), Zotlabs\Module\Removeaccount\post(), Zotlabs\Module\Removeme\post(), Zotlabs\Module\Settings\Features\post(), Zotlabs\Module\Locs\post(), Zotlabs\Module\Settings\Featured\post(), Zotlabs\Module\Tagrm\post(), Zotlabs\Module\Settings\Permcats\post(), Zotlabs\Module\Settings\Oauth\post(), Zotlabs\Module\Settings\Tokens\post(), Zotlabs\Module\Filestorage\post(), Zotlabs\Module\Group\post(), Zotlabs\Module\Pconfig\post(), Zotlabs\Module\Appman\post(), Zotlabs\Module\File_upload\post(), Zotlabs\Module\Settings\Channel\post(), Zotlabs\Module\Admin\Site\post(), Zotlabs\Module\Settings\Display\post(), Zotlabs\Module\Events\post(), Zotlabs\Module\Import_items\post(), Zotlabs\Module\Invite\post(), Zotlabs\Module\Mail\post(), Zotlabs\Module\Menu\post(), Zotlabs\Module\Hq\post(), Zotlabs\Module\Api\post(), Zotlabs\Module\Prate\post(), Zotlabs\Module\Item\post(), Zotlabs\Module\Connect\post(), Zotlabs\Module\Settings\post(), Zotlabs\Module\Tasks\post(), Zotlabs\Module\Mitem\post(), Zotlabs\Module\Cover_photo\post(), Zotlabs\Module\Defperms\post(), Zotlabs\Module\Chat\post(), Zotlabs\Module\Rate\post(), Zotlabs\Module\Profile_photo\post(), Zotlabs\Module\Photos\post(), Zotlabs\Module\Connedit\post(), Zotlabs\Theme\RedbasicConfig\post(), Zotlabs\Module\Profiles\post(), Zotlabs\Module\Cdav\post(), Zotlabs\Module\Wiki\post(), prepare_body(), private_messages_list(), profile_activity(), profile_edit_menu(), profile_load(), profile_photo_set_profile_perms(), profile_sidebar(), Zotlabs\Web\WebServer\run(), scopes_sql(), search(), searchbox(), send_message(), service_class_fetch(), Zotlabs\Lib\ThreadStream\set_mode(), smilies(), stream_perms_api_uids(), stream_perms_xchans(), tasks_fetch(), thread_action_menu(), thread_author_menu(), vcard_from_xchan(), Zotlabs\Zot\Auth\Verify(), Zotlabs\Widget\Hq_controls\widget(), Zotlabs\Widget\Design_tools\widget(), Zotlabs\Widget\Affinity\widget(), Zotlabs\Widget\Rating\widget(), Zotlabs\Widget\Forums\widget(), Zotlabs\Widget\Appcloud\widget(), Zotlabs\Widget\Savedsearch\widget(), Zotlabs\Widget\Mailmenu\widget(), Zotlabs\Widget\Eventstools\widget(), Zotlabs\Widget\Notifications\widget(), Zotlabs\Widget\Activity\widget(), Zotlabs\Widget\Settings_menu\widget(), Zotlabs\Widget\Conversations\widget(), Zotlabs\Widget\Appcategories\widget(), Zotlabs\Widget\Notes\widget(), Zotlabs\Widget\Website_portation_tools\widget(), Zotlabs\Widget\Follow\widget(), Zotlabs\Widget\Cdav\widget(), Zotlabs\Widget\Filer\widget(), Zotlabs\Widget\Tasklist\widget(), Zotlabs\Widget\Suggestions\widget(), Zotlabs\Widget\Wiki_pages\widget(), Zotlabs\Web\SessionHandler\write(), zat_init(), zid_init(), zidify_callback(), and zidify_img_callback().
login ($register = false, $form_id = 'main-login', $hiddens = false, $login_page = true)
Wrapper for adding a login box.
If $register == true provide a registration link. This will most always depend on the value of App::$config['system']['register_policy']. Returns the complete html for inserting into the page
Parameters
boolean $register (optional) default false
string $form_id (optional) default main-login
boolean $hiddens (optional) default false
boolean $login_page (optional) default true
Returns
string Parsed HTML code.
Hooks:
login_hook Called when generating the login form.
string with parsed HTML
Referenced by Zotlabs\Module\Login\get(), Zotlabs\Module\Regmod\get(), Zotlabs\Module\Pubstream\get(), Zotlabs\Module\Message\get(), Zotlabs\Module\Oexchange\get(), Zotlabs\Module\Cards\get(), Zotlabs\Module\Connections\get(), Zotlabs\Module\Articles\get(), Zotlabs\Module\Api\get(), Zotlabs\Module\Network\get(), Zotlabs\Module\Rpost\get(), Zotlabs\Module\Notify\get(), Zotlabs\Module\Wiki\get(), Zotlabs\Module\Pconfig\get(), Zotlabs\Module\Admin\get(), Zotlabs\Module\Rbmark\get(), Zotlabs\Module\Home\get(), Zotlabs\Module\Settings\get(), Zotlabs\Module\Follow\get(), Zotlabs\Module\Channel\get(), Zotlabs\Module\Profile\get(), Zotlabs\Module\Import_items\get(), Zotlabs\Module\Mail\get(), Zotlabs\Module\Defperms\get(), Zotlabs\Module\Connedit\get(), and nav().
notice ($s)
Show an error or alert text on next page load.
Contents of $s are displayed prominently on the page the next time a page is loaded. Usually used for errors or alerts.
For informational text use info().
Parameters
string $s Text to display
Referenced by account_deny(), account_remove(), check_form_security_token_redirectOnErr(), Zotlabs\Module\Cloud\DAVException(), drop_item(), Zotlabs\Lib\Chatroom\enter(), Zotlabs\Module\Achievements\get(), Zotlabs\Module\Manage\get(), Zotlabs\Module\Dreport\get(), Zotlabs\Module\Chanview\get(), Zotlabs\Module\Viewsrc\get(), Zotlabs\Module\Xchan\get(), Zotlabs\Module\Notifications\get(), Zotlabs\Module\Regmod\get(), Zotlabs\Module\Service_limits\get(), Zotlabs\Module\Moderate\get(), Zotlabs\Module\Article_edit\get(), Zotlabs\Module\Card_edit\get(), Zotlabs\Module\Subthread\get(), Zotlabs\Module\Tagger\get(), Zotlabs\Module\Like\get(), Zotlabs\Module\Message\get(), Zotlabs\Module\Editpost\get(), Zotlabs\Module\Display\get(), Zotlabs\Module\Search\get(), Zotlabs\Module\Sharedwithme\get(), Zotlabs\Module\Oexchange\get(), Zotlabs\Module\Viewconnections\get(), Zotlabs\Module\Block\get(), Zotlabs\Module\Cards\get(), Zotlabs\Module\Connections\get(), Zotlabs\Module\Articles\get(), Zotlabs\Module\Suggest\get(), Zotlabs\Module\Profperm\get(), Zotlabs\Module\Pdledit\get(), Zotlabs\Module\Layouts\get(), Zotlabs\Module\Common\get(), Zotlabs\Module\Editblock\get(), Zotlabs\Module\Editlayout\get(), Zotlabs\Module\Editwebpage\get(), Zotlabs\Module\Webpages\get(), Zotlabs\Module\Api\get(), Zotlabs\Module\Blocks\get(), Zotlabs\Module\Network\get(), Zotlabs\Module\Wiki\get(), Zotlabs\Module\Admin\Themes\get(), Zotlabs\Module\Pconfig\get(), Zotlabs\Module\Admin\get(), Zotlabs\Module\Filestorage\get(), Zotlabs\Module\Cal\get(), Zotlabs\Module\Admin\Account_edit\get(), Zotlabs\Module\Settings\get(), Zotlabs\Module\Admin\Profs\get(), Zotlabs\Module\Admin\Channels\get(), Zotlabs\Module\Lostpass\get(), Zotlabs\Module\Directory\get(), Zotlabs\Module\Bookmarks\get(), Zotlabs\Module\Channel\get(), Zotlabs\Module\Group\get(), Zotlabs\Module\Menu\get(), Zotlabs\Module\Profile\get(), Zotlabs\Module\Admin\Accounts\get(), Zotlabs\Module\Sources\get(), Zotlabs\Module\Settings\Oauth\get(), Zotlabs\Module\Ratings\get(), Zotlabs\Module\Locs\get(), Zotlabs\Module\Appman\get(), Zotlabs\Module\Chat\get(), Zotlabs\Module\Invite\get(), Zotlabs\Module\Mitem\get(), Zotlabs\Module\New_channel\get(), Zotlabs\Module\Rate\get(), Zotlabs\Module\Mood\get(), Zotlabs\Module\Import_items\get(), Zotlabs\Module\Mail\get(), Zotlabs\Module\Poke\get(), Zotlabs\Module\Defperms\get(), Zotlabs\Module\Register\get(), Zotlabs\Module\Thing\get(), Zotlabs\Module\Events\get(), Zotlabs\Module\Admin\Plugins\get(), Zotlabs\Module\Cover_photo\get(), Zotlabs\Module\Profile_photo\get(), Zotlabs\Module\Connedit\get(), Zotlabs\Module\Import\get(), Zotlabs\Module\Photos\get(), Zotlabs\Module\Profiles\get(), Zotlabs\Module\Item\get(), group_add(), Zotlabs\Module\Import\import_account(), import_channel(), Zotlabs\Module\Hcard\init(), Zotlabs\Module\Magic\init(), Zotlabs\Module\Common\init(), Zotlabs\Module\Ratings\init(), Zotlabs\Module\Follow\init(), Zotlabs\Module\Mitem\init(), Zotlabs\Module\Attach\init(), Zotlabs\Module\Profiles\init(), Zotlabs\Module\Page\init(), Zotlabs\Module\Impel\init(), Zotlabs\Module\Chat\init(), Zotlabs\Module\Connect\init(), Zotlabs\Module\Network\init(), Zotlabs\Module\Profile\init(), Zotlabs\Module\Thing\init(), Zotlabs\Module\Wiki\init(), Zotlabs\Module\Channel\init(), Zotlabs\Module\Settings\Account\post(), Zotlabs\Module\Removeme\post(), Zotlabs\Module\Changeaddr\post(), Zotlabs\Module\Sources\post(), Zotlabs\Module\Removeaccount\post(), Zotlabs\Module\Locs\post(), Zotlabs\Module\Lostpass\post(), Zotlabs\Module\Settings\Oauth\post(), Zotlabs\Module\Settings\Tokens\post(), Zotlabs\Module\Filestorage\post(), Zotlabs\Module\Group\post(), Zotlabs\Module\Pconfig\post(), Zotlabs\Module\Appman\post(), Zotlabs\Module\Settings\Channel\post(), Zotlabs\Module\Import_items\post(), Zotlabs\Module\Events\post(), Zotlabs\Module\Wall_upload\post(), Zotlabs\Module\Invite\post(), Zotlabs\Module\Mail\post(), Zotlabs\Module\Admin\Channels\post(), Zotlabs\Module\Admin\Accounts\post(), Zotlabs\Module\Wall_attach\post(), Zotlabs\Module\Menu\post(), Zotlabs\Module\Api\post(), Zotlabs\Module\Rmagic\post(), Zotlabs\Module\Getfile\post(), Zotlabs\Module\Item\post(), Zotlabs\Module\Connect\post(), Zotlabs\Module\Mitem\post(), Zotlabs\Module\Cover_photo\post(), Zotlabs\Module\Register\post(), Zotlabs\Module\Defperms\post(), Zotlabs\Module\Profile_photo\post(), Zotlabs\Module\Photos\post(), Zotlabs\Module\Connedit\post(), Zotlabs\Module\New_channel\post(), Zotlabs\Module\Profiles\post(), Zotlabs\Module\Cdav\post(), Zotlabs\Module\Webpages\post(), Zotlabs\Module\Wiki\post(), profile_load(), and Zotlabs\Zot\Auth\Verify().
observer_prohibited ($allow_account = false)
Parameters
boolean $allow_account (optional) default false
Returns
boolean
Referenced by Zotlabs\Module\Pubstream\get(), Zotlabs\Module\Display\get(), Zotlabs\Module\Viewconnections\get(), Zotlabs\Module\Articles\get(), Zotlabs\Module\Cards\get(), Zotlabs\Module\Wiki\get(), Zotlabs\Module\Cal\get(), Zotlabs\Module\Directory\get(), Zotlabs\Module\Channel\get(), Zotlabs\Module\Profile\get(), Zotlabs\Module\Ratings\get(), Zotlabs\Module\Photos\get(), get_online_status(), Zotlabs\Module\Viewconnections\init(), Zotlabs\Module\Ratings\init(), Zotlabs\Module\Feed\init(), Zotlabs\Module\Zotfeed\init(), Zotlabs\Module\Ofeed\init(), Zotlabs\Module\Cal\init(), Zotlabs\Module\Photos\init(), Zotlabs\Module\Acl\navbar_complete(), poco(), Zotlabs\Widget\Fullprofile\widget(), Zotlabs\Widget\Shortprofile\widget(), and Zotlabs\Widget\Profile\widget().
os_mkdir ($path, $mode = 0777, $recursive = false)
Referenced by Zotlabs\Render\SmartyTemplate\__construct(), attach_mkdir(), attach_mkdirp(), change_channel(), Zotlabs\Module\Setup\check_store(), Zotlabs\Module\Dav\init(), Zotlabs\Module\Snap\init(), Zotlabs\Module\Cloud\init(), jsonld_document_loader(), save_chunk(), sync_files(), update_r1091(), and update_r1116().
proc_run ()
Wrap calls to proc_close(proc_open()) and call hook so plugins can take part in process :)
args: $cmd program to run next args are passed as $cmd command line
e.g.:
proc_run("ls", "-la", "/tmp");
$cmd and string args are surrounded with ""
Hooks:
proc_run Called when invoking PHP sub processes.
array args
boolean run_cmd
Referenced by Zotlabs\Daemon\Master\Summon().
remote_channel ()
Returns a xchan_hash (visitor_id) of remote authenticated visitor or false.
Returns authenticated string hash of Red global identifier (xchan_hash), if authenticated via remote auth, or an empty string.
Before 2.1 this function was called remote_user().
Since
2.1
Returns
string|bool visitor_id or false
Referenced by Zotlabs\Lib\Apps\app_render(), drop_items(), Zotlabs\Module\Login\get(), Zotlabs\Module\Search\get(), Zotlabs\Module\Oexchange\get(), Zotlabs\Module\Rpost\get(), Zotlabs\Module\Directory\get(), Zotlabs\Module\Profile\get(), Zotlabs\Module\Item\get(), Zotlabs\Module\Share\init(), Zotlabs\Module\Home\init(), nav(), observer_prohibited(), Zotlabs\Module\Item\post(), Zotlabs\Module\Photos\post(), profile_sidebar(), Zotlabs\Zot\Auth\Verify(), Zotlabs\Widget\Rating\widget(), Zotlabs\Web\SessionHandler\write(), zat_init(), and zid_init().
rrmdir ($path)
Recursively delete a directory.
Parameters
string $path
Returns
boolean
Referenced by channel_remove(), Zotlabs\Module\Wiki\get(), Zotlabs\Module\Admin\Plugins\post(), and Zotlabs\Module\Webpages\post().
shutdown ()
startup ()
Reverse the effect of magic_quotes_gpc if it is enabled.
Please disable magic_quotes_gpc so we don't have to do this. See http://php.net/manual/en/security.magicquotes.disabling.php
Referenced by App\init().
sys_boot ()
Hooks:
init_1
Referenced by cli_startup(), and Zotlabs\Web\WebServer\run().
system_unavailable ()
Called from db initialisation if db is dead.
include/system_unavailable.php will handle everything further.
Referenced by sys_boot().
x ($s, $k = null)
Multi-purpose function to check variable state.
Usage: x($var) or $x($array, 'key')
returns false if variable/key is not set if variable is set, returns 1 if has 'non-zero' value, otherwise returns 0. e.g. x('') or x(0) returns 0;
Parameters
string | array $s variable to check
string $k key inside the array to check
Returns
bool|int
Referenced by Zotlabs\Render\SmartyInterface\__construct(), Zotlabs\Web\Router\__construct(), account_service_class_allows(), account_service_class_fetch(), api_user(), Zotlabs\Lib\Apps\app_store(), Zotlabs\Lib\Apps\app_update(), attach_store(), authenticate_success(), best_link_url(), bookmark_add(), App\build_pagehead(), channel_apps(), check_form_security_token(), construct_page(), consume_feed(), conversation(), create_account(), create_identity(), Zotlabs\Render\Theme\current(), Zotlabs\Lib\XConfig\Delete(), detect_language(), discover_by_url(), Zotlabs\Web\Router\Dispatch(), encode_rel_links(), event_addtocal(), feed_get_reshare(), feed_meta(), Zotlabs\Module\Filerm\get(), Zotlabs\Module\Xchan\get(), Zotlabs\Module\Token\get(), Zotlabs\Module\Webfinger\get(), Zotlabs\Module\Authorize\get(), Zotlabs\Module\Probe\get(), Zotlabs\Module\Pubstream\get(), Zotlabs\Module\Linkinfo\get(), Zotlabs\Module\Search\get(), Zotlabs\Module\Display\get(), Zotlabs\Module\Dirsearch\get(), Zotlabs\Module\Oexchange\get(), Zotlabs\Module\Connections\get(), Zotlabs\Module\Api\get(), Zotlabs\Module\Network\get(), Zotlabs\Module\Rpost\get(), Zotlabs\Module\Hq\get(), Zotlabs\Module\Admin\Themes\get(), Zotlabs\Module\Cal\get(), Zotlabs\Module\Rbmark\get(), Zotlabs\Module\Home\get(), Zotlabs\Module\Lostpass\get(), Zotlabs\Module\Directory\get(), Zotlabs\Module\Channel\get(), Zotlabs\Module\Chatsvc\get(), Zotlabs\Module\New_channel\get(), Zotlabs\Module\Settings\Display\get(), Zotlabs\Module\Mood\get(), Zotlabs\Module\Mail\get(), Zotlabs\Module\Poke\get(), Zotlabs\Module\Admin\Site\get(), Zotlabs\Module\Setup\get(), Zotlabs\Module\Register\get(), Zotlabs\Module\Events\get(), Zotlabs\Module\Admin\Plugins\get(), Zotlabs\Module\Cover_photo\get(), Zotlabs\Module\Profile_photo\get(), Zotlabs\Module\Connedit\get(), Zotlabs\Module\Photos\get(), get_atom_elements(), get_browser_language(), get_dirpath_by_cloudpath(), get_item_elements(), get_my_address(), get_my_url(), get_plink(), get_public_feed(), get_responses(), Zotlabs\Lib\ThreadItem\get_template_data(), get_timezones(), group_add(), group_rmv(), group_side(), Zotlabs\Module\Import\import_account(), import_xchan(), info(), Zotlabs\Module\Search\init(), Zotlabs\Module\Search_ac\init(), Zotlabs\Module\Wfinger\init(), Zotlabs\Module\Magic\init(), Zotlabs\Module\Suggest\init(), Zotlabs\Module\Feed\init(), Zotlabs\Module\Ofeed\init(), Zotlabs\Module\Directory\init(), Zotlabs\Module\Mood\init(), Zotlabs\Module\Ping\init(), Zotlabs\Module\Acl\init(), Zotlabs\Module\Poke\init(), Zotlabs\Module\Setup\init(), Zotlabs\Module\Snap\init(), App\init(), item_store(), item_store_update(), lang_selector(), load_contact_links(), mail_store(), nav(), Zotlabs\Module\Acl\navbar_complete(), Zotlabs\Web\Session\new_cookie(), notice(), photo_upload(), poco(), poco_load(), Zotlabs\Module\Changeaddr\post(), Zotlabs\Module\Removeaccount\post(), Zotlabs\Module\Settings\Account\post(), Zotlabs\Module\Removeme\post(), Zotlabs\Module\Settings\Features\post(), Zotlabs\Module\Admin\Security\post(), Zotlabs\Module\Tagrm\post(), Zotlabs\Module\Settings\Oauth\post(), Zotlabs\Module\Filestorage\post(), Zotlabs\Module\Settings\Channel\post(), Zotlabs\Module\Admin\Site\post(), Zotlabs\Module\Settings\Display\post(), Zotlabs\Module\Wall_upload\post(), Zotlabs\Module\Events\post(), Zotlabs\Module\Import_items\post(), Zotlabs\Module\Invite\post(), Zotlabs\Module\Mail\post(), Zotlabs\Module\Admin\Channels\post(), Zotlabs\Module\Admin\Logs\post(), Zotlabs\Module\Admin\Accounts\post(), Zotlabs\Module\Embedphotos\post(), Zotlabs\Module\Rbmark\post(), Zotlabs\Module\Item\post(), Zotlabs\Module\Register\post(), Zotlabs\Module\Photos\post(), Zotlabs\Module\Profiles\post(), Zotlabs\Module\Webpages\post(), post_activity_item(), proc_run(), profile_sidebar(), App\register_template_engine(), Zotlabs\Web\WebServer\run(), scrape_feed(), script_path(), service_class_allows(), service_class_fetch(), App\set_baseurl(), t(), App\template_engine(), tt(), Zotlabs\Render\Theme\url(), validate_channelname(), Zotlabs\Widget\Savedsearch\widget(), Zotlabs\Widget\Appcategories\widget(), Zotlabs\Widget\Affinity\widget(), Zotlabs\Widget\Sitesearch\widget(), Zotlabs\Widget\Filer\widget(), Zotlabs\Widget\Categories\widget(), Zotlabs\Widget\Tagcloud\widget(), z_fetch_url(), z_post_url(), zot_item_update(), and zotinfo().
z_check_cert ()
Check if server certificate is valid.
Notify admin if not.
Referenced by Zotlabs\Daemon\Cron_weekly\run().
z_get_temp_dir ()
z_get_upload_dir ()
z_path ()
Referenced by absurl().
z_root ()
Returns the baseurl.
See Also
App::get_baseurl()
Returns
string
Referenced by Zotlabs\Web\CheckJS\__construct(), Zotlabs\Lib\DB_Upgrade\__construct(), Zotlabs\Zot\Auth\__construct(), account_allow(), account_remove(), advanced_profile(), allowed_public_recips(), alt_pager(), anon_identity_init(), Zotlabs\Lib\Apps\app_feature(), Zotlabs\Lib\Apps\app_render(), Zotlabs\Lib\Apps\app_store(), Zotlabs\Lib\Apps\app_update(), atoken_xchan(), attach_export_data(), attach_store(), authenticate_success(), bb_parse_crypt(), Zotlabs\Lib\NativeWikiPage\bbcode(), bbcode(), best_link_url(), build_sync_packet(), cert_bad_email(), change_channel_keys(), chanlink_cid(), chanlink_hash(), chanlink_url(), channel_apps(), channel_change_address(), channel_export_items(), channel_remove(), check_config(), check_cron_broken(), check_form_security_token_redirectOnErr(), Zotlabs\Module\Setup\check_htaccess(), check_location_move(), check_zotinfo(), common_friends_visitor_widget(), construct_page(), consume_feed(), conversation(), create_identity(), Zotlabs\Lib\NativeWiki\create_wiki(), Zotlabs\Render\Comanche\css(), deliverable_singleton(), delivery_report_is_storable(), dir_tagadelic(), discover_by_url(), drop_item(), Zotlabs\Module\Embedphotos\embedphotos_widget_album(), event_store_item(), feed_get_reshare(), feed_salmonlinks(), Zotlabs\Module\Fbrowser\files1(), Zotlabs\Module\Fbrowser\files2(), find_upstream_directory(), fix_attached_photo_permissions(), fix_private_photos(), Zotlabs\Theme\RedbasicConfig\form(), format_categories(), format_filer(), Zotlabs\Module\Pubsites\get(), Zotlabs\Module\Dreport\get(), Zotlabs\Module\Filerm\get(), Zotlabs\Module\Login\get(), Zotlabs\Module\Manage\get(), Zotlabs\Module\React\get(), Zotlabs\Module\Notifications\get(), Zotlabs\Module\Pubstream\get(), Zotlabs\Module\Moderate\get(), Zotlabs\Module\Subthread\get(), Zotlabs\Module\Tagger\get(), Zotlabs\Module\Admin\Dbsync\get(), Zotlabs\Module\Editpost\get(), Zotlabs\Module\Fhublocs\get(), Zotlabs\Module\Like\get(), Zotlabs\Module\Search\get(), Zotlabs\Module\Display\get(), Zotlabs\Module\Sharedwithme\get(), Zotlabs\Module\Fbrowser\get(), Zotlabs\Module\Oexchange\get(), Zotlabs\Module\Articles\get(), Zotlabs\Module\Cards\get(), Zotlabs\Module\Connections\get(), Zotlabs\Module\Suggest\get(), Zotlabs\Module\Pdledit\get(), Zotlabs\Module\Layouts\get(), Zotlabs\Module\Webpages\get(), Zotlabs\Module\Blocks\get(), Zotlabs\Module\Network\get(), Zotlabs\Module\Rpost\get(), Zotlabs\Module\Hq\get(), Zotlabs\Module\Notify\get(), Zotlabs\Module\Wiki\get(), Zotlabs\Module\Admin\Logs\get(), Zotlabs\Module\Admin\Themes\get(), Zotlabs\Module\Settings\Permcats\get(), Zotlabs\Module\Removeaccount\get(), Zotlabs\Module\Filestorage\get(), Zotlabs\Module\Removeme\get(), Zotlabs\Module\Cal\get(), Zotlabs\Module\Uexport\get(), Zotlabs\Module\Rbmark\get(), Zotlabs\Module\Home\get(), Zotlabs\Module\Admin\Profs\get(), Zotlabs\Module\Tagrm\get(), Zotlabs\Module\Admin\Channels\get(), Zotlabs\Module\Lostpass\get(), Zotlabs\Module\Directory\get(), Zotlabs\Module\Changeaddr\get(), Zotlabs\Module\Channel\get(), Zotlabs\Module\Group\get(), Zotlabs\Module\Menu\get(), Zotlabs\Module\Chatsvc\get(), Zotlabs\Module\Profile\get(), Zotlabs\Module\Admin\Accounts\get(), Zotlabs\Module\Sources\get(), Zotlabs\Module\Settings\Oauth\get(), Zotlabs\Module\Settings\Tokens\get(), Zotlabs\Module\Appman\get(), Zotlabs\Module\Locs\get(), Zotlabs\Module\Chat\get(), Zotlabs\Module\Invite\get(), Zotlabs\Module\Mitem\get(), Zotlabs\Module\Settings\Display\get(), Zotlabs\Module\Mail\get(), Zotlabs\Module\Admin\Site\get(), Zotlabs\Module\Setup\get(), Zotlabs\Module\Register\get(), Zotlabs\Module\Events\get(), Zotlabs\Module\Admin\Plugins\get(), Zotlabs\Module\Cover_photo\get(), Zotlabs\Module\Profile_photo\get(), Zotlabs\Module\Settings\Channel\get(), Zotlabs\Module\Connedit\get(), Zotlabs\Module\Photos\get(), Zotlabs\Module\Profiles\get(), get_cloud_url(), get_cover_photo(), get_directory_primary(), Zotlabs\Lib\System\get_notify_icon(), get_post_aclDialogDescription(), Zotlabs\Lib\System\get_site_icon(), get_site_info(), Zotlabs\Lib\ThreadItem\get_template_data(), get_theme_screenshot(), get_things(), get_zcard(), get_zcard_embed(), handle_tag(), App\head_get_icon(), head_get_icon(), identity_basic_export(), identity_export_year(), Zotlabs\Module\Import\import_account(), import_hublocs(), import_items(), import_menus(), import_objs(), import_profiles(), import_xchan(), import_xchan_photo(), Zotlabs\Module\Toggle_safesearch\init(), Zotlabs\Module\Hostxrd\init(), Zotlabs\Module\Toggle_mobile\init(), Zotlabs\Module\Xref\init(), Zotlabs\Module\Cloud_tiles\init(), Zotlabs\Module\Rmagic\init(), Zotlabs\Module\Hcard\init(), Zotlabs\Module\Logout\init(), Zotlabs\Module\Nojs\init(), Zotlabs\Module\Oexchange\init(), Zotlabs\Module\Randprof\init(), Zotlabs\Module\Search_ac\init(), Zotlabs\Module\Notify\init(), Zotlabs\Module\Xrd\init(), Zotlabs\Module\Wfinger\init(), Zotlabs\Module\Magic\init(), Zotlabs\Module\Profiles\init(), Zotlabs\Module\Follow\init(), Zotlabs\Module\Home\init(), Zotlabs\Module\Impel\init(), Zotlabs\Module\Directory\init(), Zotlabs\Module\Mood\init(), Zotlabs\Module\Profile\init(), Zotlabs\Module\Thing\init(), Zotlabs\Module\Wiki\init(), Zotlabs\Module\Regdir\init(), Zotlabs\Module\Channel\init(), Zotlabs\Module\Ping\init(), Zotlabs\Module\Acl\init(), Zotlabs\Module\Cloud\init(), item_store(), Zotlabs\Render\Comanche\js(), list_smilies(), login(), magiclink_url(), mail_prepare_binary(), menu_element(), nav(), Zotlabs\Module\Acl\navbar_complete(), new_contact(), oembed_format_object(), oembed_iframe(), Zotlabs\Module\Oep\oep_album_reply(), Zotlabs\Module\Oep\oep_photo_reply(), Zotlabs\Module\Oep\oep_phototop_reply(), paginate(), Zotlabs\Lib\Apps\parse_app_description(), parseIdentityAwareHTML(), photo_upload(), photos_album_widget(), photos_albums_list(), photos_create_item(), photos_list_photos(), populate_acl(), Zotlabs\Module\Pdledit\post(), Zotlabs\Module\Sources\post(), Zotlabs\Module\Changeaddr\post(), Zotlabs\Module\Settings\Account\post(), Zotlabs\Module\Admin\Security\post(), Zotlabs\Module\Admin\Profs\post(), Zotlabs\Module\Locs\post(), Zotlabs\Module\Lostpass\post(), Zotlabs\Module\Admin\Account_edit\post(), Zotlabs\Module\Tagrm\post(), Zotlabs\Module\Settings\Oauth\post(), Zotlabs\Module\Admin\Features\post(), Zotlabs\Module\Group\post(), Zotlabs\Module\Pconfig\post(), Zotlabs\Module\Appman\post(), Zotlabs\Module\Settings\Channel\post(), Zotlabs\Module\File_upload\post(), Zotlabs\Module\Admin\Site\post(), Zotlabs\Module\Settings\Display\post(), Zotlabs\Module\Events\post(), Zotlabs\Module\Mail\post(), Zotlabs\Module\Admin\Plugins\post(), Zotlabs\Module\Admin\Channels\post(), Zotlabs\Module\Admin\Logs\post(), Zotlabs\Module\Admin\Themes\post(), Zotlabs\Module\Admin\Accounts\post(), Zotlabs\Module\Menu\post(), Zotlabs\Module\Rmagic\post(), Zotlabs\Module\Admin\post(), Zotlabs\Module\Item\post(), Zotlabs\Module\Rbmark\post(), Zotlabs\Module\Settings\post(), Zotlabs\Module\Connect\post(), Zotlabs\Module\Mitem\post(), Zotlabs\Module\Cover_photo\post(), Zotlabs\Module\Register\post(), Zotlabs\Module\Defperms\post(), Zotlabs\Module\Chat\post(), Zotlabs\Module\Profile_photo\post(), Zotlabs\Module\Photos\post(), Zotlabs\Module\Connedit\post(), Zotlabs\Module\Setup\post(), Zotlabs\Module\New_channel\post(), Zotlabs\Module\Wiki\post(), post_activity_item(), preg_heart(), prepare_binary(), process_channel_sync_delivery(), process_delivery(), process_mail_delivery(), profile_activity(), profile_edit_menu(), profile_sidebar(), public_recips(), queue_deliver(), reflect_article_callback(), reflect_comment_store(), reflect_photo_callback(), remove_obsolete_hublocs(), Zotlabs\Render\SmartyTemplate\replace_macros(), Zotlabs\Web\Session\return_check(), Zotlabs\Web\WebServer\run(), Zotlabs\Daemon\Cron_weekly\run(), Zotlabs\Daemon\Checksites\run(), Zotlabs\Daemon\Deliver\run(), Zotlabs\Daemon\Ratenotif\run(), Zotlabs\Daemon\Onepoll\run(), Zotlabs\Daemon\Externals\run(), Zotlabs\Lib\LDSignatures\salmon_sign(), scale_external_images(), script_path(), search(), searchbox(), Zotlabs\Module\Cover_photo\send_cover_photo_activity(), send_message(), send_profile_photo_activity(), send_reg_approval_email(), send_register_success_email(), send_status_notifications(), Zotlabs\Lib\LDSignatures\sign(), sslify(), start_delivery_chain(), store_doc_file(), Zotlabs\Lib\Enotify\submit(), sync_directories(), sync_menus(), sync_objs(), theme_attachments(), thread_author_menu(), update_suggestions(), vcard_from_xchan(), verify_email_address(), Zotlabs\Module\Setup\what_next(), Zotlabs\Widget\Mailmenu\widget(), Zotlabs\Widget\Savedsearch\widget(), Zotlabs\Widget\Admin\widget(), Zotlabs\Widget\Chatroom_list\widget(), Zotlabs\Widget\Appcloud\widget(), Zotlabs\Widget\Settings_menu\widget(), Zotlabs\Widget\Appcategories\widget(), Zotlabs\Widget\Archive\widget(), Zotlabs\Widget\Album\widget(), Zotlabs\Widget\Dirtags\widget(), Zotlabs\Widget\Portfolio\widget(), Zotlabs\Widget\Filer\widget(), Zotlabs\Widget\Suggestions\widget(), xchan_store(), z_check_cert(), z_fetch_url(), z_path(), z_post_url(), zid_init(), zot_build_packet(), zot_encode_locations(), zot_fetch(), zot_new_uid(), zot_refresh(), zot_reply_ping(), zot_site_info(), and zotinfo().
Variable Documentation
$DIRECTORY_FALLBACK_SERVERS
Initial value:
= array(
    'https://hubzilla.zottel.net',
    'https://my.federated.social',
    'https://gravizot.de'
)
Referenced by find_upstream_directory().
const ABOOK_FLAG_ARCHIVED 0x0008
Referenced by abook_toggle_flag(), and Zotlabs\Module\Connedit\get().
const ABOOK_FLAG_BLOCKED 0x0001
Referenced by abook_toggle_flag(), and Zotlabs\Module\Connedit\get().
const ABOOK_FLAG_FEED 0x0100
Referenced by abook_toggle_flag().
const ABOOK_FLAG_HIDDEN 0x0004
Referenced by abook_toggle_flag(), and Zotlabs\Module\Connedit\get().
const ABOOK_FLAG_IGNORED 0x0002
Referenced by abook_toggle_flag(), and Zotlabs\Module\Connedit\get().
const ABOOK_FLAG_PENDING 0x0010
Referenced by abook_toggle_flag(), and Zotlabs\Module\Connedit\get().
const ABOOK_FLAG_SELF 0x0080
Referenced by abook_toggle_flag(), and update_r1130().
const ABOOK_FLAG_UNCONNECTED 0x0020
Referenced by abook_toggle_flag(), and update_r1102().
const ACCESS_FREE 2
Referenced by Zotlabs\Module\Admin\Site\get(), import_site(), Zotlabs\Module\Dirsearch\list_public_sites(), and zot_site_info().
const ACCESS_PAID 1
Referenced by Zotlabs\Module\Admin\Site\get(), import_site(), Zotlabs\Module\Dirsearch\list_public_sites(), and zot_site_info().
const ACCESS_PRIVATE 0
site access policy
Referenced by Zotlabs\Module\Admin\Site\get(), import_site(), and zot_site_info().
const ACCESS_TIERED 3
Referenced by Zotlabs\Module\Admin\Site\get(), import_site(), Zotlabs\Module\Dirsearch\list_public_sites(), and zot_site_info().
const ACCOUNT_BLOCKED 0x0002
Referenced by account_allow(), account_approve(), account_verify_password(), Zotlabs\Module\Admin\admin_page_summary(), Zotlabs\Module\Admin\Accounts\get(), Zotlabs\Module\Admin\Accounts\post(), and Zotlabs\Module\Register\post().
const ACCOUNT_EXPIRED 0x0004
Referenced by account_verify_password(), and downgrade_accounts().
const ACCOUNT_OK 0x0000
Account Flags
Referenced by account_verify_password(), create_account(), Zotlabs\Module\Register\post(), Zotlabs\Daemon\Poller\run(), and Zotlabs\Daemon\Onepoll\run().
const ACCOUNT_PENDING 0x0010
Referenced by account_allow(), account_approve(), account_verify_password(), Zotlabs\Module\Admin\Accounts\get(), Zotlabs\Module\Ping\init(), and Zotlabs\Module\Register\post().
const ACCOUNT_REMOVED 0x0008
Referenced by account_verify_password().
const ACCOUNT_ROLE_ADMIN 0x1000
Referenced by account_remove(), create_account(), is_site_admin(), and send_reg_approval_email().
const ACCOUNT_ROLE_DEVELOPER 0x0004
Referenced by is_developer().
const ACCOUNT_ROLE_SYSTEM 0x0002
Account roles
const ACCOUNT_UNVERIFIED 0x0001
Referenced by account_approve(), account_verify_password(), Zotlabs\Module\Lostpass\get(), Zotlabs\Module\Register\post(), Zotlabs\Daemon\Poller\run(), and Zotlabs\Daemon\Onepoll\run().
const ACTIVITY_ABSTAIN NAMESPACE_ZOT . '/activity/abstain'
Referenced by builtin_activity_puller(), Zotlabs\Module\Like\get(), and visible_activity().
const ACTIVITY_AGREE NAMESPACE_ZOT . '/activity/agree'
Referenced by builtin_activity_puller(), Zotlabs\Module\Like\get(), and visible_activity().
const ACTIVITY_ATTEND NAMESPACE_ZOT . '/activity/attendyes'
Referenced by builtin_activity_puller(), Zotlabs\Module\Like\get(), and visible_activity().
const ACTIVITY_ATTENDMAYBE NAMESPACE_ZOT . '/activity/attendmaybe'
Referenced by builtin_activity_puller(), Zotlabs\Module\Like\get(), and visible_activity().
const ACTIVITY_ATTENDNO NAMESPACE_ZOT . '/activity/attendno'
Referenced by builtin_activity_puller(), Zotlabs\Module\Like\get(), and visible_activity().
const ACTIVITY_COMPLETE NAMESPACE_ACTIVITY_SCHEMA . 'complete'
const ACTIVITY_CREATE NAMESPACE_ACTIVITY_SCHEMA . 'create'
Referenced by Zotlabs\Lib\NativeWiki\create_wiki().
const ACTIVITY_DELETE NAMESPACE_ACTIVITY_SCHEMA . 'delete'
Referenced by consume_feed().
const ACTIVITY_DISAGREE NAMESPACE_ZOT . '/activity/disagree'
Referenced by builtin_activity_puller(), Zotlabs\Module\Like\get(), and visible_activity().
const ACTIVITY_DISLIKE NAMESPACE_ZOT . '/activity/dislike'
Referenced by Zotlabs\Lib\ThreadItem\add_child(), Zotlabs\Lib\ThreadStream\add_thread(), builtin_activity_puller(), conversation(), Zotlabs\Lib\Enotify\format(), Zotlabs\Module\Like\get(), Zotlabs\Module\Display\get(), Zotlabs\Module\Network\get(), Zotlabs\Module\Hq\get(), Zotlabs\Module\Channel\get(), localize_item(), and visible_activity().
const ACTIVITY_FAVORITE NAMESPACE_ACTIVITY_SCHEMA . 'favorite'
Referenced by get_atom_elements().
const ACTIVITY_FOLLOW NAMESPACE_ACTIVITY_SCHEMA . 'follow'
Referenced by Zotlabs\Module\Subthread\get().
const ACTIVITY_FRIEND NAMESPACE_ACTIVITY_SCHEMA . 'make-friend'
Referenced by localize_item(), and Zotlabs\Module\Connedit\post().
const ACTIVITY_JOIN NAMESPACE_ACTIVITY_SCHEMA . 'join'
const ACTIVITY_LIKE NAMESPACE_ACTIVITY_SCHEMA . 'like'
Referenced by Zotlabs\Lib\ThreadItem\add_child(), Zotlabs\Lib\ThreadStream\add_thread(), advanced_profile(), builtin_activity_puller(), consume_feed(), conversation(), Zotlabs\Lib\Enotify\format(), Zotlabs\Module\Like\get(), Zotlabs\Module\Display\get(), Zotlabs\Module\Network\get(), Zotlabs\Module\Hq\get(), Zotlabs\Module\Channel\get(), get_atom_elements(), localize_item(), Zotlabs\Lib\Enotify\submit(), and visible_activity().
const ACTIVITY_LOSE NAMESPACE_ACTIVITY_SCHEMA . 'lose'
const ACTIVITY_MOOD NAMESPACE_ZOT . '/activity/mood'
Referenced by Zotlabs\Module\Mood\init(), and localize_item().
const ACTIVITY_OBJ_ACTIVITY NAMESPACE_ACTIVITY_SCHEMA . 'activity'
Referenced by get_atom_elements().
const ACTIVITY_OBJ_ALBUM NAMESPACE_ACTIVITY_SCHEMA . 'photo-album'
Referenced by photo_upload().
const ACTIVITY_OBJ_CARD NAMESPACE_ZOT . '/activity/card'
const ACTIVITY_OBJ_COMMENT NAMESPACE_ACTIVITY_SCHEMA . 'comment'
Referenced by Zotlabs\Module\Like\get(), get_atom_elements(), is_edit_activity(), item_create_edit_activity(), item_store(), Zotlabs\Module\Item\post(), and post_activity_item().
const ACTIVITY_OBJ_EVENT NAMESPACE_ACTIVITY_SCHEMA . 'event'
Referenced by atom_entry(), event_addtocal(), event_store_item(), Zotlabs\Module\Tagger\get(), Zotlabs\Module\Like\get(), Zotlabs\Lib\ThreadItem\get_template_data(), localize_item(), and prepare_body().
const ACTIVITY_OBJ_FILE NAMESPACE_ZOT . '/activity/file'
Referenced by apply_updates(), file_activity(), Zotlabs\Module\Sharedwithme\get(), get_file_activity_object(), Zotlabs\Module\Ping\init(), is_item_normal(), item_normal(), item_normal_search(), item_normal_update(), and Zotlabs\Daemon\Notifier\run().
const ACTIVITY_OBJ_GAME NAMESPACE_ACTIVITY_SCHEMA . 'game'
const ACTIVITY_OBJ_GROUP NAMESPACE_ACTIVITY_SCHEMA . 'group'
const ACTIVITY_OBJ_HEART NAMESPACE_ZOT . '/activity/heart'
const ACTIVITY_OBJ_LOCATION NAMESPACE_ZOT . '/activity/location'
const ACTIVITY_OBJ_NOTE NAMESPACE_ACTIVITY_SCHEMA . 'note'
Referenced by Zotlabs\Module\Like\get(), Zotlabs\Module\Subthread\get(), Zotlabs\Module\Tagger\get(), get_atom_elements(), is_edit_activity(), item_create_edit_activity(), item_store(), localize_item(), Zotlabs\Module\Item\post(), post_activity_item(), and send_status_notifications().
const ACTIVITY_OBJ_P_PHOTO NAMESPACE_ACTIVITY_SCHEMA . 'profile-photo'
const ACTIVITY_OBJ_PERSON NAMESPACE_ACTIVITY_SCHEMA . 'person'
Referenced by get_atom_elements(), Zotlabs\Module\Poke\init(), localize_item(), Zotlabs\Module\Connedit\post(), and tag_deliver().
const ACTIVITY_OBJ_PHOTO NAMESPACE_ACTIVITY_SCHEMA . 'photo'
Referenced by create_export_photo_body(), Zotlabs\Module\Like\get(), Zotlabs\Module\Subthread\get(), Zotlabs\Module\Tagger\get(), Zotlabs\Module\Rpost\get(), Zotlabs\Module\Share\init(), localize_item(), photo_upload(), prepare_body(), Zotlabs\Module\Cover_photo\send_cover_photo_activity(), send_profile_photo_activity(), and send_status_notifications().
const ACTIVITY_OBJ_PROFILE NAMESPACE_ZOT . '/activity/profile'
Referenced by advanced_profile(), Zotlabs\Module\Like\get(), and profile_activity().
const ACTIVITY_OBJ_TAGTERM NAMESPACE_ZOT . '/activity/tagterm'
Referenced by Zotlabs\Module\Tagger\get(), remove_community_tag(), and tag_deliver().
const ACTIVITY_OBJ_THING NAMESPACE_ZOT . '/activity/thing'
Referenced by Zotlabs\Module\Like\get(), get_things(), Zotlabs\Module\Thing\init(), and localize_item().
const ACTIVITY_OBJ_WIKI NAMESPACE_ACTIVITY_SCHEMA . 'wiki'
Referenced by Zotlabs\Lib\NativeWiki\create_wiki().
const ACTIVITY_POKE NAMESPACE_ZOT . '/activity/poke'
Referenced by Zotlabs\Module\Poke\init(), localize_item(), and tag_deliver().
const ACTIVITY_POST NAMESPACE_ACTIVITY_SCHEMA . 'post'
Referenced by apply_updates(), atom_entry(), builtin_activity_puller(), construct_verb(), create_export_photo_body(), event_store_item(), file_activity(), Zotlabs\Module\Sharedwithme\get(), Zotlabs\Module\Ping\init(), item_post_type(), item_store(), mail_store(), photo_upload(), Zotlabs\Module\Item\post(), post_activity_item(), prepare_body(), refimport_content(), reflect_comment_store(), and send_status_notifications().
const ACTIVITY_PUBLIC_INBOX 'https://www.w3.org/ns/activitystreams#Public'
activity stream defines
const ACTIVITY_REACT NAMESPACE_ZOT . '/activity/react'
Referenced by Zotlabs\Module\React\get().
const ACTIVITY_REQ_FRIEND NAMESPACE_ACTIVITY_SCHEMA . 'request-friend'
const ACTIVITY_SHARE NAMESPACE_ACTIVITY_SCHEMA . 'share'
Referenced by get_atom_elements().
const ACTIVITY_TAG NAMESPACE_ACTIVITY_SCHEMA . 'tag'
Referenced by Zotlabs\Module\Tagger\get(), remove_community_tag(), and tag_deliver().
const ACTIVITY_TIE NAMESPACE_ACTIVITY_SCHEMA . 'tie'
const ACTIVITY_UNFOLLOW NAMESPACE_ACTIVITY_SCHEMA . 'stop-following'
Referenced by Zotlabs\Module\Subthread\get(), get_atom_elements(), and send_status_notifications().
const ACTIVITY_UNFRIEND NAMESPACE_ACTIVITY_SCHEMA . 'remove-friend'
const ACTIVITY_UPDATE NAMESPACE_ACTIVITY_SCHEMA . 'update'
Referenced by apply_updates(), categories_widget(), file_activity(), is_edit_activity(), item_create_edit_activity(), profile_activity(), Zotlabs\Module\Cover_photo\send_cover_photo_activity(), send_profile_photo_activity(), and term_item_parent_query().
const ACTIVITY_WIN NAMESPACE_ACTIVITY_SCHEMA . 'win'
const ACTIVITYSTREAMS_JSONLD_REV 'https://www.w3.org/ns/activitystreams'
Referenced by Zotlabs\Lib\LDSignatures\sign().
const ATOM_TIME 'Y-m-d\\TH:i:s\\Z'
Referenced by atom_entry(), btlogger(), dlogger(), format_event_html(), format_event_obj(), Zotlabs\Module\Display\get(), get_feed_for(), and logger().
const ATTACH_FLAG_DIR 0x0001
const ATTACH_FLAG_OS 0x0002
const CLIENT_MODE_LOAD 0x0001
Referenced by items_fetch().
const CLIENT_MODE_NORMAL 0x0000
Referenced by get_feed_for(), and items_fetch().
const CLIENT_MODE_UPDATE 0x0002
Referenced by items_fetch().
const DB_UPDATE_VERSION 1198
Referenced by check_config(), Zotlabs\Lib\System\get_update_version(), identity_basic_export(), Zotlabs\Module\Import\import_account(), and Zotlabs\Module\Import_items\post().
const DBTYPE_MYSQL 0
const DBTYPE_POSTGRES 1
Referenced by DBA\dba_factory(), Zotlabs\Module\Search\get(), update_r1131(), update_r1132(), update_r1133(), update_r1134(), update_r1139(), update_r1141(), update_r1145(), update_r1149(), update_r1150(), update_r1152(), update_r1161(), update_r1162(), update_r1163(), update_r1164(), update_r1165(), update_r1167(), update_r1168(), update_r1169(), update_r1172(), update_r1173(), update_r1174(), update_r1175(), update_r1177(), update_r1179(), update_r1183(), update_r1187(), update_r1189(), update_r1191(), update_r1192(), update_r1193(), update_r1195(), and update_r1196().
const DIRECTORY_FALLBACK_MASTER 'https://gravizot.de'
Referenced by get_directory_primary(), and sync_directories().
const DIRECTORY_MODE_NORMAL 0x0000
Referenced by find_upstream_directory(), Zotlabs\Module\Dirsearch\get(), Zotlabs\Module\Admin\Site\get(), import_site(), import_xchan(), Zotlabs\Module\Ratingsearch\init(), Zotlabs\Module\Regdir\init(), mark_orphan_hubsxchans(), remove_all_xchan_resources(), Zotlabs\Daemon\Directory\run(), sync_directories(), update_modtime(), update_suggestions(), and zot_site_info().
const DIRECTORY_MODE_PRIMARY 0x0001
Referenced by Zotlabs\Module\Pubsites\get(), Zotlabs\Module\Directory\get(), Zotlabs\Module\Admin\Site\get(), get_directory_primary(), import_site(), Zotlabs\Module\Acl\navbar_complete(), Zotlabs\Daemon\Cron_weekly\run(), Zotlabs\Daemon\Poller\run(), Zotlabs\Daemon\Cron_daily\run(), sync_directories(), update_suggestions(), and zot_site_info().
const DIRECTORY_MODE_SECONDARY 0x0002
Referenced by Zotlabs\Module\Admin\Site\get(), import_site(), Zotlabs\Daemon\Cron_daily\run(), Zotlabs\Daemon\Cron_weekly\run(), Zotlabs\Daemon\Poller\run(), sync_directories(), and zot_site_info().
const DIRECTORY_MODE_STANDALONE 0x0100
Referenced by dir_tagadelic(), find_upstream_directory(), Zotlabs\Module\Pubsites\get(), Zotlabs\Module\Dirsearch\get(), Zotlabs\Module\Directory\get(), Zotlabs\Module\Register\get(), get_directory_primary(), import_site(), import_xchan(), Zotlabs\Module\Regdir\init(), Zotlabs\Module\Acl\navbar_complete(), Zotlabs\Daemon\Externals\run(), sync_directories(), update_suggestions(), and zot_site_info().
const DIRECTORY_REALM 'RED_GLOBAL'
Referenced by Zotlabs\Lib\System\compatible_project(), get_directory_realm(), Zotlabs\Module\Sitelist\init(), Zotlabs\Module\Regdir\init(), Zotlabs\Module\Dirsearch\list_public_sites(), sync_directories(), and update_r1122().
const DROPITEM_NORMAL 0
Referenced by attach_drop_photo(), delete_item_lowlevel(), Zotlabs\Lib\NativeWiki\delete_wiki(), and drop_item().
const DROPITEM_PHASE1 1
Referenced by attach_drop_photo(), delete_imported_item(), delete_item_lowlevel(), drop_item(), Zotlabs\Module\Like\get(), and Zotlabs\Module\Item\get().
const DROPITEM_PHASE2 2
Referenced by delete_item_lowlevel(), drop_item(), and Zotlabs\Daemon\Expire\run().
const EOL '<br>' . "\r\n"
Constant with a HTML line break.
Contains a HTML line break (br) element and a real carriage return with line feed for the source. This can be used in HTML and JavaScript where needed a line break.
Referenced by account_allow(), account_deny(), account_remove(), check_account_email(), check_account_invite(), check_form_security_std_err_msg(), Zotlabs\Module\Setup\check_htaccess(), Zotlabs\Module\Setup\check_keys(), Zotlabs\Module\Setup\check_php(), Zotlabs\Module\Setup\check_smarty3(), Zotlabs\Module\Setup\check_store(), Zotlabs\Module\Cloud\DAVException(), Zotlabs\Zot\Auth\Debug(), drop_item(), Zotlabs\Lib\Chatroom\enter(), format_like(), Zotlabs\Module\Achievements\get(), Zotlabs\Module\Manage\get(), Zotlabs\Module\Dreport\get(), Zotlabs\Module\Pubsites\get(), Zotlabs\Module\Regmod\get(), Zotlabs\Module\Service_limits\get(), Zotlabs\Module\Viewsrc\get(), Zotlabs\Module\Xchan\get(), Zotlabs\Module\Chanview\get(), Zotlabs\Module\Notifications\get(), Zotlabs\Module\Card_edit\get(), Zotlabs\Module\Moderate\get(), Zotlabs\Module\Article_edit\get(), Zotlabs\Module\Fhublocs\get(), Zotlabs\Module\Subthread\get(), Zotlabs\Module\Tagger\get(), Zotlabs\Module\Like\get(), Zotlabs\Module\Admin\Dbsync\get(), Zotlabs\Module\Message\get(), Zotlabs\Module\Editpost\get(), Zotlabs\Module\Search\get(), Zotlabs\Module\Display\get(), Zotlabs\Module\Sharedwithme\get(), Zotlabs\Module\Oexchange\get(), Zotlabs\Module\Viewconnections\get(), Zotlabs\Module\Block\get(), Zotlabs\Module\Cards\get(), Zotlabs\Module\Connections\get(), Zotlabs\Module\Articles\get(), Zotlabs\Module\Suggest\get(), Zotlabs\Module\Profperm\get(), Zotlabs\Module\Pdledit\get(), Zotlabs\Module\Layouts\get(), Zotlabs\Module\Common\get(), Zotlabs\Module\Editblock\get(), Zotlabs\Module\Editlayout\get(), Zotlabs\Module\Editwebpage\get(), Zotlabs\Module\Blocks\get(), Zotlabs\Module\Webpages\get(), Zotlabs\Module\Api\get(), Zotlabs\Module\Network\get(), Zotlabs\Module\Wiki\get(), Zotlabs\Module\Pconfig\get(), Zotlabs\Module\Filestorage\get(), Zotlabs\Module\Cal\get(), Zotlabs\Module\Admin\Account_edit\get(), Zotlabs\Module\Settings\get(), Zotlabs\Module\Admin\Profs\get(), Zotlabs\Module\Tagrm\get(), Zotlabs\Module\Admin\Channels\get(), Zotlabs\Module\Lostpass\get(), Zotlabs\Module\Directory\get(), Zotlabs\Module\Bookmarks\get(), Zotlabs\Module\Channel\get(), Zotlabs\Module\Group\get(), Zotlabs\Module\Menu\get(), Zotlabs\Module\Admin\Accounts\get(), Zotlabs\Module\Profile\get(), Zotlabs\Module\Sources\get(), Zotlabs\Module\Ratings\get(), Zotlabs\Module\Locs\get(), Zotlabs\Module\Appman\get(), Zotlabs\Module\Chat\get(), Zotlabs\Module\Invite\get(), Zotlabs\Module\Mitem\get(), Zotlabs\Module\New_channel\get(), Zotlabs\Module\Rate\get(), Zotlabs\Module\Mood\get(), Zotlabs\Module\Import_items\get(), Zotlabs\Module\Mail\get(), Zotlabs\Module\Poke\get(), Zotlabs\Module\Setup\get(), Zotlabs\Module\Defperms\get(), Zotlabs\Module\Register\get(), Zotlabs\Module\Thing\get(), Zotlabs\Module\Events\get(), Zotlabs\Module\Cover_photo\get(), Zotlabs\Module\Profile_photo\get(), Zotlabs\Module\Connedit\get(), Zotlabs\Module\Import\get(), Zotlabs\Module\Photos\get(), Zotlabs\Module\Profiles\get(), Zotlabs\Module\Item\get(), group_add(), Zotlabs\Module\Import\import_account(), import_channel(), Zotlabs\Module\Bookmarks\init(), Zotlabs\Module\Hcard\init(), Zotlabs\Module\Magic\init(), Zotlabs\Module\Common\init(), Zotlabs\Module\Ratings\init(), Zotlabs\Module\Attach\init(), Zotlabs\Module\Follow\init(), Zotlabs\Module\Mitem\init(), Zotlabs\Module\Page\init(), Zotlabs\Module\Profiles\init(), Zotlabs\Module\Chat\init(), Zotlabs\Module\Network\init(), Zotlabs\Module\Connect\init(), Zotlabs\Module\Profile\init(), Zotlabs\Module\Thing\init(), Zotlabs\Module\Wiki\init(), Zotlabs\Module\Channel\init(), Zotlabs\Module\Setup\load_database(), Zotlabs\Module\Pconfig\pconfig_form(), Zotlabs\Module\Removeaccount\post(), Zotlabs\Module\Pdledit\post(), Zotlabs\Module\Removeme\post(), Zotlabs\Module\Changeaddr\post(), Zotlabs\Module\Settings\Account\post(), Zotlabs\Module\Sources\post(), Zotlabs\Module\Lostpass\post(), Zotlabs\Module\Settings\Featured\post(), Zotlabs\Module\Locs\post(), Zotlabs\Module\Tagrm\post(), Zotlabs\Module\Settings\Oauth\post(), Zotlabs\Module\Admin\Account_edit\post(), Zotlabs\Module\Settings\Tokens\post(), Zotlabs\Module\Settings\Permcats\post(), Zotlabs\Module\Pconfig\post(), Zotlabs\Module\Group\post(), Zotlabs\Module\Filestorage\post(), Zotlabs\Module\Settings\Channel\post(), Zotlabs\Module\Appman\post(), Zotlabs\Module\Admin\Site\post(), Zotlabs\Module\Events\post(), Zotlabs\Module\Wall_upload\post(), Zotlabs\Module\Import_items\post(), Zotlabs\Module\Invite\post(), Zotlabs\Module\Mail\post(), Zotlabs\Module\Wall_attach\post(), Zotlabs\Module\Menu\post(), Zotlabs\Module\Api\post(), Zotlabs\Module\Rmagic\post(), Zotlabs\Module\Getfile\post(), Zotlabs\Module\Item\post(), Zotlabs\Module\Mitem\post(), Zotlabs\Module\Cover_photo\post(), Zotlabs\Module\Register\post(), Zotlabs\Module\Defperms\post(), Zotlabs\Module\Profile_photo\post(), Zotlabs\Module\Photos\post(), Zotlabs\Module\Connedit\post(), Zotlabs\Module\New_channel\post(), Zotlabs\Module\Profiles\post(), Zotlabs\Module\Cdav\post(), Zotlabs\Module\Webpages\post(), Zotlabs\Module\Wiki\post(), profile_load(), refimport_content(), sync_locations(), Zotlabs\Zot\Auth\Verify(), Zotlabs\Widget\Conversations\widget(), zot_reply_auth_check(), and zot_reply_message_request().
const ITEM_ARTICLE 0x4000
const ITEM_BLOCKED 0x0002
const ITEM_BUG 0x0400
const ITEM_BUILDBLOCK 0x0100
const ITEM_CARD 0x2000
const ITEM_DELAYED_PUBLISH 0x0080
const ITEM_DELETED 0x0010
const ITEM_DOC 0x1000
const ITEM_HIDDEN 0x0001
const ITEM_IS_STICKY 1000
const ITEM_MODERATED 0x0004
Referenced by Zotlabs\Module\Moderate\get(), Zotlabs\Module\Display\get(), Zotlabs\Module\Hq\get(), Zotlabs\Module\Item\post(), and Zotlabs\Lib\Enotify\submit().
const ITEM_PDL 0x0200
const ITEM_PENDING_REMOVE 0x0800
const ITEM_SPAM 0x0008
const ITEM_TYPE_ARTICLE 7
Referenced by conversation(), Zotlabs\Module\Article_edit\get(), Zotlabs\Module\Articles\get(), Zotlabs\Lib\ThreadItem\get_template_data(), Zotlabs\Module\Oep\oep_articles_reply(), Zotlabs\Module\Item\post(), and webpage_to_namespace().
const ITEM_TYPE_BLOCK 1
Referenced by Zotlabs\Module\Block\get(), Zotlabs\Module\Editblock\get(), Zotlabs\Module\Blocks\get(), get_item_elements(), get_webpage_elements(), identity_basic_export(), import_webpage_element(), Zotlabs\Module\Impel\init(), webpage_to_namespace(), and Zotlabs\Widget\Random_block\widget().
const ITEM_TYPE_BUG 4
Referenced by get_item_elements().
const ITEM_TYPE_CARD 6
Referenced by conversation(), Zotlabs\Module\Card_edit\get(), Zotlabs\Module\Cards\get(), Zotlabs\Lib\ThreadItem\get_template_data(), Zotlabs\Module\Oep\oep_cards_reply(), Zotlabs\Module\Item\post(), and webpage_to_namespace().
const ITEM_TYPE_DOC 5
Referenced by get_item_elements(), search_doc_files(), store_doc_file(), and webpage_to_namespace().
const ITEM_TYPE_PDL 2
Referenced by Zotlabs\Module\Editlayout\get(), Zotlabs\Module\Layouts\get(), Zotlabs\Module\Page\get(), get_item_elements(), get_webpage_elements(), identity_basic_export(), import_webpage_element(), Zotlabs\Module\Page\init(), Zotlabs\Module\Impel\init(), item_store(), layout_select(), and webpage_to_namespace().
const ITEM_TYPE_POST 0
Referenced by channel_export_items(), identity_export_year(), item_create_edit_activity(), Zotlabs\Module\Item\post(), and Zotlabs\Daemon\Notifier\run().
const ITEM_TYPE_WEBPAGE 3
Referenced by channel_apps(), Zotlabs\Module\Display\get(), Zotlabs\Module\Editwebpage\get(), Zotlabs\Module\Webpages\get(), get_item_elements(), get_webpage_elements(), identity_basic_export(), import_webpage_element(), Zotlabs\Module\Page\init(), Zotlabs\Module\Impel\init(), Zotlabs\Module\Item\item_check_service_class(), items_fetch(), Zotlabs\Module\Item\post(), Zotlabs\Module\Webpages\post(), webpage_to_namespace(), Zotlabs\Widget\Item\widget(), and Zotlabs\Widget\Tagcloud\widget().
const ITEM_UNPUBLISHED 0x0020
const ITEM_VISIBLE 0x0000
Item visibility
const ITEM_WEBPAGE 0x0040
const JPEG_QUALITY 100
Image storage quality. Lower numbers save space at cost of image detail. For ease of upgrade, please do not change here. Change jpeg quality with App::$config['system']['jpeg_quality'] = n; in .htconfig.php, where n is netween 1 and 100, and with very poor results below about 50
Referenced by photo_gd\imageString(), and photo_imagick\load().
const LANGUAGE_DETECT_MIN_CONFIDENCE 0.01
Referenced by detect_language().
const LANGUAGE_DETECT_MIN_LENGTH 128
Language detection parameters
Referenced by detect_language().
const LOGGER_ALL 4
Referenced by Zotlabs\Module\Admin\Logs\get(), logger(), and Zotlabs\Daemon\Master\Release().
const LOGGER_DATA 3
Referenced by allowed_public_recips(), api_oauth_request_token(), attach_store(), build_sync_packet(), check_form_security_token_ForbiddenOnErr(), check_form_security_token_redirectOnErr(), consume_feed(), convert_salmon_key(), delete_item_lowlevel(), detect_language(), Zotlabs\Module\Dirsearch\dir_parse_query(), discover_by_url(), discover_by_webbie(), encode_item(), fetch_xrd_links(), fix_private_photos(), Zotlabs\Module\Admin\Logs\get(), Zotlabs\Module\Directory\get(), get_atom_elements(), import_xchan(), Zotlabs\Module\Search_ac\init(), Zotlabs\Module\Magic\init(), Zotlabs\Module\Wall_attach\init(), Zotlabs\Module\Impel\init(), Zotlabs\Module\Ping\init(), item_store(), item_store_update(), mail_store(), mini_group_select(), new_contact(), oembed_process(), old_webfinger(), parse_xml_string(), poco_load(), Zotlabs\Module\Events\post(), Zotlabs\Module\Mail\post(), Zotlabs\Module\Photos\post(), public_recips(), queue_deliver(), Zotlabs\Daemon\Deliver\run(), Zotlabs\Daemon\Onepoll\run(), Zotlabs\Zot\Finger\run(), Zotlabs\Daemon\Notifier\run(), photo_driver\save(), set_linkified_perms(), sync_directories(), tag_deliver(), tgroup_check(), update_directory_entry(), xml2array(), z_fetch_url(), z_post_url(), zot_build_packet(), zot_fetch(), zot_import(), zot_process_response(), zot_refresh(), zot_register_hub(), and zot_reply_pickup().
const LOGGER_DEBUG 2
Referenced by Zotlabs\Web\Router\__construct(), Zotlabs\Lib\ThreadItem\add_child(), Zotlabs\Lib\ThreadStream\add_thread(), api_call(), api_login(), bookmark_add(), build_sync_packet(), channel_remove(), consume_feed(), contact_remove(), conversation(), delete_imported_item(), discover_by_webbie(), do_delivery(), feed_conversation_fetch(), fetch_lrdd_template(), fetch_xrd_links(), fix_private_photos(), Zotlabs\Lib\PermissionDescription\fromGlobalPermission(), Zotlabs\Lib\PermissionDescription\fromStandalonePermission(), Zotlabs\Module\Linkinfo\get(), Zotlabs\Module\Like\get(), Zotlabs\Module\Admin\Logs\get(), Zotlabs\Module\Admin\get(), Zotlabs\Module\Directory\get(), Zotlabs\Module\Group\get(), Zotlabs\Lib\ThreadStream\get_template_data(), guess_image_type(), hubloc_change_primary(), import_author_rss(), import_author_unknown(), import_author_zot(), import_channel_photo(), import_directory_profile(), import_xchan(), import_xchan_photo(), Zotlabs\Module\Hcard\init(), Zotlabs\Module\Hostxrd\init(), Zotlabs\Module\Notes\init(), Zotlabs\Module\Magic\init(), Zotlabs\Module\Wall_attach\init(), Zotlabs\Module\Wfinger\init(), Zotlabs\Module\Xrd\init(), Zotlabs\Module\Zotfeed\init(), Zotlabs\Module\Mood\init(), Zotlabs\Module\Oep\init(), Zotlabs\Module\Poke\init(), item_store(), item_store_update(), limit_body_size(), load_plugin(), local_dir_update(), ZotOAuth1\loginUser(), ZotOAuth1DataStore\lookup_consumer(), ZotOAuth1DataStore\lookup_token(), mail_store(), ZotOAuth1DataStore\new_access_token(), new_contact(), ZotOAuth1DataStore\new_request_token(), oembed_action(), oembed_fetch_url(), photo_upload(), poco(), poco_load(), Zotlabs\Module\Admin\post(), Zotlabs\Module\Getfile\post(), Zotlabs\Module\Item\post(), Zotlabs\Module\Photos\post(), proc_run(), process_delivery(), process_feed_tombstones(), process_location_delivery(), process_profile_delivery(), process_salmon_feed(), profile_load(), queue_deliver(), queue_set_delivered(), Zotlabs\Lib\ThreadItem\remove_child(), remove_obsolete_hublocs(), remove_queue_by_posturl(), remove_queue_item(), rsa_verify(), Zotlabs\Daemon\Expire\run(), Zotlabs\Daemon\Deliver\run(), Zotlabs\Daemon\Ratenotif\run(), Zotlabs\Daemon\Onepoll\run(), Zotlabs\Daemon\Externals\run(), Zotlabs\Daemon\Directory\run(), Zotlabs\Zot\Finger\run(), Zotlabs\Daemon\Notifier\run(), scale_external_images(), scrape_feed(), Zotlabs\Lib\Enotify\send(), Zotlabs\Lib\ThreadStream\set_mode(), stream_perms_api_uids(), stream_perms_xchans(), Zotlabs\Lib\Enotify\submit(), sync_files(), sync_locations(), tag_deliver(), unload_plugin(), update_queue_item(), Zotlabs\Web\HTTPSig\verify(), z_fetch_url(), z_mail(), z_post_url(), zot_feed(), zot_gethub(), zot_process_response(), zot_register_hub(), zot_reply_auth_check(), zot_reply_message_request(), zot_reply_pickup(), and zot_reply_ping().
const LOGGER_NORMAL 0
log levels
Referenced by check_plugin_versions(), copy_folder_to_cloudfiles(), Zotlabs\Module\Wiki\get(), Zotlabs\Module\Admin\Logs\get(), Zotlabs\Web\Session\init(), markdown_to_bb(), Zotlabs\Module\Webpages\post(), dba_mysqli\q(), dba_pdo\q(), rsa_verify(), Zotlabs\Zot\Finger\run(), Zotlabs\Daemon\Notifier\run(), Zotlabs\Lib\PConfig\Set(), sync_files(), xmlify(), and zot_refresh().
const LOGGER_TRACE 1
Referenced by Zotlabs\Module\Admin\Logs\get().
const MAIL_DELETED 0x0001
const MAIL_ISREPLY 0x0004
const MAIL_OBSCURED 0x0020
const MAIL_RECALLED 0x0010
const MAIL_REPLIED 0x0002
const MAIL_SEEN 0x0008
const MAX_IMAGE_LENGTH(!defined('STORAGE_DEFAULT_PERMISSIONS')) -1
Default permissions for file-based storage (webDAV, etc.) These files will be owned by the webserver who will need write access to the "storage" folder. Ideally you should make this 700, however some hosted platforms may not let you change ownership of this directory so we're defaulting to both owner-write and group-write privilege. This should work for most cases without modification. Over-ride this in your .htconfig.php if you need something either more or less restrictive.
An alternate way of limiting picture upload sizes. Specify the maximum pixel length that pictures are allowed to be (for non-square pictures, it will apply to the longest side). Pictures longer than this length will be resized to be this length (on the longest side, the other side will be scaled appropriately). Modify this value using
App::$config['system']['max_image_length'] = n;
in .htconfig.php
If you don't want to set a maximum length, set to -1. The default value is defined by 'MAX_IMAGE_LENGTH' below.
Referenced by Zotlabs\Module\Cover_photo\cover_photo_crop_ui_head(), photo_upload(), and Zotlabs\Module\Profile_photo\profile_photo_crop_ui_head().
const MAX_LIKERS 10
Maximum number of "people who like (or don't like) this" that we will list by name
Referenced by get_responses(), and Zotlabs\Lib\ThreadItem\get_template_data().
const MENU_BOOKMARK 0x0002
Referenced by bookmark_add(), channel_apps(), Zotlabs\Module\Rbmark\get(), Zotlabs\Module\Bookmarks\get(), Zotlabs\Module\Menu\get(), import_menus(), Zotlabs\Module\Impel\init(), menu_element(), Zotlabs\Module\Menu\post(), and sync_menus().
const MENU_ITEM_CHATROOM 0x0004
Referenced by bookmark_add(), import_menus(), Zotlabs\Module\Impel\init(), menu_element(), poco(), and sync_menus().
const MENU_ITEM_NEWWIN 0x0002
Referenced by Zotlabs\Module\Mitem\get(), import_menus(), Zotlabs\Module\Impel\init(), menu_element(), menu_render(), Zotlabs\Module\Mitem\post(), and sync_menus().
const MENU_ITEM_ZID 0x0001
Referenced by bookmark_add(), Zotlabs\Module\Mitem\get(), import_menus(), Zotlabs\Module\Impel\init(), menu_element(), menu_render(), Zotlabs\Module\Mitem\post(), and sync_menus().
const MENU_SYSTEM 0x0001
Menu types
Referenced by bookmark_add(), channel_apps(), Zotlabs\Module\Bookmarks\get(), Zotlabs\Module\Menu\get(), import_menus(), Zotlabs\Module\Impel\init(), menu_element(), Zotlabs\Module\Menu\post(), and sync_menus().
const NAMESPACE_ACTIVITY 'http://activitystrea.ms/spec/1.0/'
Referenced by feed_get_reshare(), and get_atom_elements().
const NAMESPACE_ACTIVITY_SCHEMA 'http://activitystrea.ms/schema/1.0/'
const NAMESPACE_ATOM1 'http://www.w3.org/2005/Atom'
const NAMESPACE_DFRN 'http://purl.org/macgirvin/dfrn/1.0'
Referenced by get_atom_elements().
const NAMESPACE_FEED 'http://schemas.google.com/g/2010#updates-from'
const NAMESPACE_GEORSS 'http://www.georss.org/georss'
Referenced by get_atom_elements().
const NAMESPACE_MEDIA 'http://purl.org/syndication/atommedia'
Referenced by encode_rel_links().
const NAMESPACE_OSTATUS 'http://ostatus.org/schema/1.0'
Referenced by get_atom_elements().
const NAMESPACE_OSTATUSSUB 'http://ostatus.org/schema/1.0/subscribe'
const NAMESPACE_POCO 'http://portablecontacts.net/spec/1.0'
Referenced by feed_meta(), and get_atom_elements().
const NAMESPACE_SALMON_ME 'http://salmon-protocol.org/ns/magic-env'
const NAMESPACE_STATUSNET 'http://status.net/schema/api/1/'
Referenced by get_atom_elements().
const NAMESPACE_THREAD 'http://purl.org/syndication/thread/1.0'
Referenced by consume_feed(), and process_salmon_feed().
const NAMESPACE_TOMB 'http://purl.org/atompub/tombstones/1.0'
Referenced by process_feed_tombstones().
const NAMESPACE_YMEDIA 'http://search.yahoo.com/mrss/'
Referenced by get_atom_elements().
const NAMESPACE_ZOT 'http://purl.org/zot'
Referenced by atom_entry(), and get_atom_elements().
const NETWORK_ACTIVITYPUB 'activitypub'
Referenced by network_to_name().
const NETWORK_DFRN 'dfrn'
Referenced by best_link_url(), and network_to_name().
const NETWORK_DIASPORA 'diaspora'
Referenced by network_to_name().
const NETWORK_FACEBOOK 'face'
Referenced by network_to_name().
const NETWORK_FEED 'rss'
Referenced by network_to_name().
const NETWORK_FRND 'friendica-over-diaspora'
Network and protocol family types
Referenced by network_to_name().
const NETWORK_GNUSOCIAL 'gnusoc'
Referenced by network_to_name().
const NETWORK_GPLUS 'goog'
const NETWORK_LINKEDIN 'lnkd'
Referenced by network_to_name().
const NETWORK_MAIL 'mail'
Referenced by network_to_name().
const NETWORK_MAIL2 'mai2'
const NETWORK_MYSPACE 'mysp'
Referenced by network_to_name().
const NETWORK_OSTATUS 'stat'
Referenced by network_to_name().
const NETWORK_PHANTOM 'unkn'
const NETWORK_XMPP 'xmpp'
Referenced by network_to_name().
const NETWORK_ZOT 'zot'
Referenced by network_to_name().
const NOTIFY_COMMENT 0x0008
Referenced by Zotlabs\Module\Settings\Channel\get(), Zotlabs\Module\Item\post(), send_status_notifications(), and Zotlabs\Lib\Enotify\submit().
const NOTIFY_CONFIRM 0x0002
Referenced by Zotlabs\Module\Settings\Channel\get(), and Zotlabs\Lib\Enotify\submit().
const NOTIFY_INTRO 0x0001
email notification options
Referenced by Zotlabs\Module\Settings\Channel\get(), Zotlabs\Lib\Enotify\submit(), and zot_refresh().
const NOTIFY_LIKE 0x0400
Referenced by Zotlabs\Module\Settings\Channel\get(), and Zotlabs\Lib\Enotify\submit().
const NOTIFY_MAIL 0x0010
Referenced by Zotlabs\Module\Settings\Channel\get(), mail_store(), and Zotlabs\Lib\Enotify\submit().
const NOTIFY_POKE 0x0200
Referenced by Zotlabs\Module\Settings\Channel\get(), Zotlabs\Lib\Enotify\submit(), and tag_deliver().
const NOTIFY_PROFILE 0x0040
const NOTIFY_SUGGEST 0x0020
Referenced by Zotlabs\Module\Settings\Channel\get(), and Zotlabs\Lib\Enotify\submit().
const NOTIFY_SYSTEM 0x8000
Referenced by Zotlabs\Lib\Enotify\submit().
const NOTIFY_TAGSELF 0x0080
Referenced by Zotlabs\Module\Settings\Channel\get(), Zotlabs\Lib\Enotify\submit(), and tag_deliver().
const NOTIFY_TAGSHARE 0x0100
Referenced by Zotlabs\Lib\Enotify\submit().
const NOTIFY_WALL 0x0004
Referenced by Zotlabs\Module\Settings\Channel\get(), Zotlabs\Module\Item\post(), and Zotlabs\Lib\Enotify\submit().
const PAGE_ADULT 0x0020
Referenced by Zotlabs\Module\Settings\Channel\get(), Zotlabs\Module\Settings\Channel\post(), stream_perms_api_uids(), stream_perms_xchans(), and zotinfo().
const PAGE_ALLOWCODE 0x0008
Referenced by channel_codeallowed(), Zotlabs\Module\Admin\Channels\get(), import_channel(), Zotlabs\Module\Impel\init(), Zotlabs\Module\Admin\Channels\post(), and Zotlabs\Module\Item\post().
const PAGE_APPLICATION 0x0004
const PAGE_AUTOCONNECT 0x0002
const PAGE_CENSORED 0x0040
Referenced by Zotlabs\Module\Admin\Channels\get(), Zotlabs\Module\Admin\Channels\post(), stream_perms_api_uids(), stream_perms_xchans(), and zotinfo().
const PAGE_HIDDEN 0x0001
Referenced by zotinfo().
const PAGE_HUBADMIN 0x2000
Referenced by get_site_info().
const PAGE_NORMAL 0x0000
Channel pageflags
Referenced by create_identity().
const PAGE_PREMIUM 0x0010
Referenced by Zotlabs\Module\Connect\get(), Zotlabs\Module\Connect\post(), profile_sidebar(), and zotinfo().
const PAGE_REMOVED 0x8000
Referenced by channel_remove().
const PAGE_SYSTEM 0x1000
const PERMS_A_DELEGATE 0x00800
Referenced by perms_int_to_array(), and translate_abook_perms_outbound().
const PERMS_A_REPUBLISH 0x10000
Referenced by perms_int_to_array(), and translate_abook_perms_outbound().
const PERMS_AUTHED 0x0100
Referenced by Zotlabs\Module\Settings\Channel\get(), get_all_perms(), Zotlabs\Lib\PermissionDescription\get_permission_description(), Zotlabs\Lib\PermissionDescription\get_permission_icon(), map_scope(), and perm_is_allowed().
const PERMS_CONTACTS 0x0008
Referenced by Zotlabs\Module\Settings\Channel\get(), get_all_perms(), Zotlabs\Lib\PermissionDescription\get_permission_description(), Zotlabs\Lib\PermissionDescription\get_permission_icon(), map_scope(), and perm_is_allowed().
const PERMS_NETWORK 0x0002
Referenced by Zotlabs\Module\Display\get(), Zotlabs\Module\Search\get(), Zotlabs\Module\Settings\Channel\get(), get_all_perms(), Zotlabs\Lib\PermissionDescription\get_permission_description(), Zotlabs\Lib\PermissionDescription\get_permission_icon(), map_scope(), perm_is_allowed(), site_default_perms(), stream_perms_api_uids(), and stream_perms_xchans().
const PERMS_PENDING 0x0200
Referenced by Zotlabs\Module\Settings\Channel\get(), get_all_perms(), Zotlabs\Lib\PermissionDescription\get_permission_description(), Zotlabs\Lib\PermissionDescription\get_permission_icon(), map_scope(), perm_is_allowed(), and zot_refresh().
const PERMS_PUBLIC 0x0001
Referenced by Zotlabs\Access\Permissions\BlockedAnonPerms(), conversation(), Zotlabs\Module\Pubstream\get(), Zotlabs\Module\Search\get(), Zotlabs\Module\Display\get(), Zotlabs\Module\Settings\Channel\get(), get_all_perms(), Zotlabs\Lib\PermissionDescription\get_permission_description(), Zotlabs\Lib\PermissionDescription\get_permission_icon(), is_public_profile(), map_scope(), Zotlabs\Access\PermissionRoles\new_custom_perms(), perm_is_allowed(), site_default_perms(), Zotlabs\Access\PermissionLimits\Std_Limits(), stream_perms_api_uids(), and stream_perms_xchans().
const PERMS_R_ABOOK 0x00008
Referenced by Zotlabs\Lib\PermissionDescription\get_permission_origin_description(), perms_int_to_array(), translate_abook_perms_outbound(), and update_r1130().
const PERMS_R_PAGES 0x04000
Referenced by Zotlabs\Lib\PermissionDescription\get_permission_origin_description(), perms_int_to_array(), translate_abook_perms_outbound(), and update_r1130().
const PERMS_R_PHOTOS 0x00004
Referenced by update_r1130().
const PERMS_R_PROFILE 0x00002
Referenced by Zotlabs\Lib\PermissionDescription\get_permission_origin_description(), perms_int_to_array(), translate_abook_perms_outbound(), and update_r1130().
const PERMS_R_STORAGE 0x01000
Referenced by Zotlabs\Lib\PermissionDescription\get_permission_origin_description(), perms_int_to_array(), translate_abook_perms_outbound(), and update_r1130().
const PERMS_R_STREAM 0x00001
Permissions
Referenced by Zotlabs\Lib\PermissionDescription\get_permission_origin_description(), perms_int_to_array(), translate_abook_perms_outbound(), and update_r1130().
const PERMS_SITE 0x0004
Referenced by Zotlabs\Module\Settings\Channel\get(), get_all_perms(), Zotlabs\Lib\PermissionDescription\get_permission_description(), Zotlabs\Lib\PermissionDescription\get_permission_icon(), map_scope(), perm_is_allowed(), stream_perms_api_uids(), and stream_perms_xchans().
const PERMS_SPECIFIC 0x0080
Referenced by Zotlabs\Module\Settings\Permcats\get(), Zotlabs\Module\Settings\Tokens\get(), Zotlabs\Module\Defperms\get(), Zotlabs\Module\Settings\Channel\get(), Zotlabs\Module\Connedit\get(), get_all_perms(), Zotlabs\Lib\PermissionDescription\get_permission_description(), Zotlabs\Lib\PermissionDescription\get_permission_icon(), Zotlabs\Access\PermissionRoles\new_custom_perms(), perm_is_allowed(), Zotlabs\Module\Defperms\post(), Zotlabs\Access\PermissionRoles\role_perms(), site_default_perms(), and Zotlabs\Access\PermissionLimits\Std_Limits().
const PERMS_W_CHAT 0x00400
Referenced by perms_int_to_array(), translate_abook_perms_outbound(), and update_r1130().
const PERMS_W_COMMENT 0x00080
Referenced by perms_int_to_array(), translate_abook_perms_outbound(), and update_r1130().
const PERMS_W_LIKE 0x20000
Referenced by perms_int_to_array(), translate_abook_perms_outbound(), and update_r1130().
const PERMS_W_MAIL 0x00100
Referenced by perms_int_to_array(), translate_abook_perms_outbound(), and update_r1130().
const PERMS_W_PAGES 0x08000
Referenced by perms_int_to_array(), and translate_abook_perms_outbound().
const PERMS_W_PHOTOS 0x00200
const PERMS_W_STORAGE 0x02000
Referenced by perms_int_to_array(), and translate_abook_perms_outbound().
const PERMS_W_STREAM 0x00010
Referenced by perms_int_to_array(), translate_abook_perms_outbound(), and update_r1130().
const PERMS_W_TAGWALL 0x00040
Referenced by Zotlabs\Module\Import\import_account(), perms_int_to_array(), and translate_abook_perms_outbound().
const PERMS_W_WALL 0x00020
Referenced by perms_int_to_array(), translate_abook_perms_outbound(), and update_r1130().
const PHOTO_ADULT 0x0008
const PHOTO_COVER 0x0010
Referenced by get_cover_photo(), get_zcard(), get_zcard_embed(), Zotlabs\Module\Photo\init(), Zotlabs\Module\Cover_photo\post(), and sync_files().
const PHOTO_FLAG_OS 0x4000
const PHOTO_NORMAL 0x0000
Photo usage types
Referenced by Zotlabs\Module\Embedphotos\embedphotos_widget_album(), Zotlabs\Module\Profile_photo\get(), Zotlabs\Module\Photos\get(), import_xchan(), photo_upload(), photos_list_photos(), Zotlabs\Module\Cover_photo\post(), Zotlabs\Module\Profile_photo\post(), sync_files(), Zotlabs\Widget\Album\widget(), and Zotlabs\Widget\Portfolio\widget().
const PHOTO_PROFILE 0x0001
Referenced by Zotlabs\Module\Embedphotos\embedphotos_widget_album(), Zotlabs\Module\Profile_photo\get(), Zotlabs\Module\Photos\get(), identity_basic_export(), import_channel_photo(), import_xchan(), Zotlabs\Module\Photo\init(), photos_list_photos(), Zotlabs\Module\Profile_photo\post(), profile_photo_set_profile_perms(), sync_files(), Zotlabs\Widget\Portfolio\widget(), and Zotlabs\Widget\Album\widget().
const PHOTO_RES_1024 1
const PHOTO_RES_320 3
const PHOTO_RES_640 2
Referenced by Zotlabs\Module\Profile_photo\get(), and Zotlabs\Module\Profile_photo\post().
const PHOTO_RES_COVER_1200 7
Referenced by get_zcard(), get_zcard_embed(), and Zotlabs\Module\Photo\init().
const PHOTO_RES_COVER_425 9
Referenced by get_zcard(), and get_zcard_embed().
const PHOTO_RES_COVER_850 8
Referenced by get_zcard(), and get_zcard_embed().
const PHOTO_RES_ORIG 0
const PHOTO_RES_PROFILE_300 4
Referenced by Zotlabs\Module\Profile_photo\post().
const PHOTO_RES_PROFILE_48 6
Referenced by Zotlabs\Module\Profile_photo\post().
const PHOTO_RES_PROFILE_80 5
Referenced by Zotlabs\Module\Profile_photo\get(), and Zotlabs\Module\Profile_photo\post().
const PHOTO_THING 0x0004
Referenced by delete_thing_photo(), and import_xchan_photo().
const PHOTO_XCHAN 0x0002
Referenced by import_xchan_photo().
const PLATFORM_NAME 'hubzilla'
This is an open source decentralised communications platform combined with a decentralised identity/authentication framework wrapped in an extensible content management system, providing website designers the ability to embed fully decentralised communications and social tools into many traditional website designs (blogs, forums, small business websites, charitable organisations, etc.). Also provided is DNS mobility and internet scale privacy/access control.
This allows any individual website to participate in a matrix of linked sites and people and media sharing which is far greater than the reach of an individual site.
If you are reading the source code and come across a function or code block which is not documented, but you have a good idea what it does, please add some descriptive comments and push it to the main project. Even if your description isn't perfect, it gives us a base which we can build on and correct - so that eventually everything is fully documented.
Referenced by Zotlabs\Lib\System\get_platform_name(), and identity_basic_export().
const PNG_QUALITY 8
App::$config['system']['png_quality'] from 0 (uncompressed) to 9
Referenced by photo_gd\imageString(), and photo_imagick\load().
const POLL_MULTIPLE_CHOICE 0x0004
const POLL_OVERWRITE 0x8000
const POLL_SIMPLE_RATING 0x0001
Poll/Survey types
const POLL_TENSCALE 0x0002
const PROJECT_BASE __DIR__
Referenced by photo_upload(), Zotlabs\Thumbs\Video\Thumb(), and Zotlabs\Thumbs\Pdf\Thumb().
const PROTOCOL_ZOT 'http://purl.org/zot/protocol'
various namespaces we may need to parse
Referenced by discover_by_webbie().
const REGISTER_APPROVE 1
Referenced by Zotlabs\Module\Admin\Site\get(), Zotlabs\Module\Register\get(), import_site(), Zotlabs\Module\Ping\init(), Zotlabs\Module\Dirsearch\list_public_sites(), nav(), Zotlabs\Module\Register\post(), and zot_site_info().
const REGISTER_CLOSED 0
registration policies
Referenced by Zotlabs\Module\Login\get(), Zotlabs\Module\Regmod\get(), Zotlabs\Module\Home\get(), Zotlabs\Module\Admin\Site\get(), Zotlabs\Module\Register\get(), import_site(), Zotlabs\Module\Register\post(), and zot_site_info().
const REGISTER_OPEN 2
Referenced by account_verify_password(), Zotlabs\Module\Admin\Site\get(), import_site(), Zotlabs\Module\Sitelist\init(), Zotlabs\Module\Dirsearch\list_public_sites(), nav(), Zotlabs\Module\Register\post(), and zot_site_info().
const SITE_TYPE_NOTZOT 1
Referenced by queue_deliver().
const SITE_TYPE_UNKNOWN 2
Referenced by queue_deliver().
const SITE_TYPE_ZOT 0
Referenced by import_site(), Zotlabs\Module\Sitelist\init(), Zotlabs\Module\Ratingsearch\init(), Zotlabs\Module\Rate\init(), Zotlabs\Module\Regdir\init(), Zotlabs\Module\Dirsearch\list_public_sites(), prune_hub_reinstalls(), Zotlabs\Daemon\Checksites\run(), Zotlabs\Daemon\Externals\run(), and sync_directories().
const STD_VERSION '3.0'
Referenced by Zotlabs\Module\Admin\admin_page_summary(), check_plugin_versions(), format_css_if_exists(), format_js_if_exists(), Zotlabs\Lib\System\get_std_version(), and identity_basic_export().
const TEMPLATE_BUILD_PATH 'store/[data]/smarty3'
Referenced by Zotlabs\Render\SmartyTemplate\__construct(), Zotlabs\Module\Setup\check_smarty3(), and Zotlabs\Module\Setup\check_store().
const TERM_BOOKMARK 8
Referenced by decode_tags(), encode_item_terms(), get_atom_elements(), Zotlabs\Lib\ThreadItem\get_template_data(), handle_tag(), and Zotlabs\Module\Bookmarks\init().
const TERM_CATEGORY 3
Referenced by Zotlabs\Lib\Apps\app_feature(), Zotlabs\Lib\Apps\app_store(), Zotlabs\Lib\Apps\app_update(), articlecategories_widget(), atom_entry(), cardcategories_widget(), categories_widget(), decode_tags(), encode_item_terms(), file_tag_file_query(), format_categories(), Zotlabs\Module\Filerm\get(), Zotlabs\Module\Article_edit\get(), Zotlabs\Module\Card_edit\get(), Zotlabs\Module\Editpost\get(), Zotlabs\Module\Articles\get(), Zotlabs\Module\Cards\get(), Zotlabs\Module\Network\get(), Zotlabs\Module\Channel\get(), Zotlabs\Module\Events\get(), get_atom_elements(), items_fetch(), Zotlabs\Module\Events\post(), Zotlabs\Module\Item\post(), refimport_content(), start_delivery_chain(), and Zotlabs\Widget\Tagcloud\widget().
const TERM_COMMUNITYTAG 10
Referenced by atom_entry(), check_item_source(), decode_tags(), encode_item_terms(), format_hashtags(), format_term_for_display(), Zotlabs\Module\Tagger\get(), Zotlabs\Module\Search\get(), Zotlabs\Module\Network\get(), Zotlabs\Module\Channel\get(), Zotlabs\Module\Search_ac\init(), item_getfeedtags(), items_fetch(), Zotlabs\Module\Item\post(), post_is_importable(), remove_community_tag(), and tag_deliver().
const TERM_FILE 5
Referenced by decode_tags(), encode_item_terms(), file_tag_file_query(), fileas_widget(), format_filer(), Zotlabs\Module\Filerm\get(), Zotlabs\Module\Filer\get(), Zotlabs\Module\Network\get(), item_expire(), items_fetch(), Zotlabs\Module\Item\post(), and Zotlabs\Widget\Filer\widget().
const TERM_FORUM 11
Referenced by decode_tags(), encode_item_terms(), format_term_for_display(), handle_tag(), tag_deliver(), and tgroup_check().
const TERM_HASHTAG 1
Referenced by atom_entry(), check_item_source(), decode_tags(), encode_item_terms(), format_hashtags(), format_term_for_display(), Zotlabs\Module\Search\get(), Zotlabs\Module\Network\get(), Zotlabs\Module\Channel\get(), get_atom_elements(), handle_tag(), Zotlabs\Module\Search_ac\init(), item_getfeedtags(), items_fetch(), post_is_importable(), and remove_community_tag().
const TERM_HIERARCHY 9
const TERM_MENTION 2
Referenced by atom_entry(), decode_tags(), encode_item_terms(), fetch_post_tags(), format_mentions(), format_term_for_display(), get_atom_elements(), get_mentions(), handle_tag(), item_getfeedtags(), tag_deliver(), and tgroup_check().
const TERM_OBJ_APP 7
Referenced by Zotlabs\Lib\Apps\app_destroy(), Zotlabs\Lib\Apps\app_feature(), Zotlabs\Lib\Apps\app_install(), Zotlabs\Lib\Apps\app_list(), Zotlabs\Lib\Apps\app_store(), app_tagadelic(), Zotlabs\Lib\Apps\app_update(), Zotlabs\Module\Appman\get(), identity_basic_export(), import_apps(), Zotlabs\Lib\Apps\import_system_apps(), sync_apps(), and Zotlabs\Widget\Appcategories\widget().
const TERM_OBJ_CHANNEL 4
const TERM_OBJ_OBJECT 5
const TERM_OBJ_PHOTO 2
const TERM_OBJ_POST 1
Referenced by article_tagadelic(), articlecategories_widget(), card_tagadelic(), cardcategories_widget(), categories_widget(), delete_item_lowlevel(), event_store_item(), fetch_post_tags(), Zotlabs\Module\Filer\get(), Zotlabs\Module\Tagger\get(), Zotlabs\Module\Search\get(), get_atom_elements(), item_store(), item_store_update(), Zotlabs\Module\Events\post(), Zotlabs\Module\Item\post(), Zotlabs\Module\Photos\post(), refimport_content(), remove_community_tag(), start_delivery_chain(), tag_deliver(), and tagadelic().
const TERM_OBJ_PROFILE 3
const TERM_OBJ_THING 6
Referenced by Zotlabs\Module\Like\get(), Zotlabs\Module\Thing\get(), get_things(), and Zotlabs\Module\Thing\init().
const TERM_PCATEGORY 4
Referenced by decode_tags(), and encode_item_terms().
const TERM_SAVEDSEARCH 6
Referenced by identity_basic_export(), and Zotlabs\Widget\Savedsearch\widget().
const TERM_THING 7
Referenced by decode_tags(), and identity_basic_export().
const TERM_UNKNOWN 0
Tag/term types
Referenced by atom_entry(), decode_tags(), encode_item_terms(), handle_tag(), and Zotlabs\Module\Item\post().
const UPDATE_FAILED 1
Referenced by Zotlabs\Module\Admin\Dbsync\get(), update_r1000(), update_r1001(), update_r1002(), update_r1003(), update_r1004(), update_r1006(), update_r1007(), update_r1008(), update_r1009(), update_r1010(), update_r1011(), update_r1012(), update_r1013(), update_r1014(), update_r1015(), update_r1016(), update_r1017(), update_r1018(), update_r1019(), update_r1020(), update_r1021(), update_r1022(), update_r1023(), update_r1024(), update_r1025(), update_r1026(), update_r1027(), update_r1028(), update_r1029(), update_r1030(), update_r1031(), update_r1032(), update_r1033(), update_r1034(), update_r1035(), update_r1036(), update_r1037(), update_r1038(), update_r1039(), update_r1040(), update_r1041(), update_r1042(), update_r1043(), update_r1044(), update_r1045(), update_r1046(), update_r1047(), update_r1048(), update_r1049(), update_r1050(), update_r1051(), update_r1052(), update_r1053(), update_r1054(), update_r1055(), update_r1056(), update_r1057(), update_r1058(), update_r1059(), update_r1060(), update_r1061(), update_r1062(), update_r1063(), update_r1064(), update_r1065(), update_r1066(), update_r1067(), update_r1068(), update_r1069(), update_r1070(), update_r1071(), update_r1072(), update_r1073(), update_r1074(), update_r1075(), update_r1076(), update_r1077(), update_r1078(), update_r1079(), update_r1080(), update_r1081(), update_r1082(), update_r1083(), update_r1084(), update_r1085(), update_r1086(), update_r1087(), update_r1088(), update_r1089(), update_r1090(), update_r1092(), update_r1093(), update_r1094(), update_r1095(), update_r1096(), update_r1098(), update_r1099(), update_r1100(), update_r1104(), update_r1105(), update_r1106(), update_r1107(), update_r1108(), update_r1109(), update_r1111(), update_r1112(), update_r1113(), update_r1114(), update_r1117(), update_r1118(), update_r1119(), update_r1120(), update_r1121(), update_r1122(), update_r1123(), update_r1124(), update_r1125(), update_r1126(), update_r1127(), update_r1128(), update_r1129(), update_r1131(), update_r1132(), update_r1133(), update_r1134(), update_r1135(), update_r1136(), update_r1137(), update_r1138(), update_r1139(), update_r1140(), update_r1141(), update_r1142(), update_r1143(), update_r1145(), update_r1146(), update_r1147(), update_r1148(), update_r1149(), update_r1150(), update_r1152(), update_r1153(), update_r1154(), update_r1155(), update_r1156(), update_r1157(), update_r1160(), update_r1161(), update_r1162(), update_r1163(), update_r1164(), update_r1165(), update_r1166(), update_r1167(), update_r1168(), update_r1169(), update_r1170(), update_r1171(), update_r1172(), update_r1173(), update_r1174(), update_r1175(), update_r1177(), update_r1178(), update_r1179(), update_r1180(), update_r1182(), update_r1183(), update_r1184(), update_r1185(), update_r1186(), update_r1187(), update_r1188(), update_r1189(), update_r1190(), update_r1191(), update_r1192(), update_r1193(), update_r1195(), and update_r1196().
const UPDATE_FLAGS_DELETED 0x1000
Referenced by Zotlabs\Module\Dirsearch\get(), sync_directories(), and update_directory_entry().
const UPDATE_FLAGS_FORCED 0x0002
Referenced by Zotlabs\Module\Dirsearch\get(), import_xchan(), local_dir_update(), sync_directories(), and zot_refresh().
const UPDATE_FLAGS_UPDATED 0x0001
Referenced by import_xchan(), local_dir_update(), process_location_delivery(), process_profile_delivery(), Zotlabs\Daemon\Poller\run(), Zotlabs\Daemon\Onedirsync\run(), update_modtime(), and zot_refresh().
const UPDATE_SUCCESS 0
DB update return values
Referenced by Zotlabs\Module\Admin\Dbsync\get(), update_r1000(), update_r1001(), update_r1002(), update_r1003(), update_r1004(), update_r1005(), update_r1006(), update_r1007(), update_r1008(), update_r1009(), update_r1010(), update_r1011(), update_r1012(), update_r1013(), update_r1014(), update_r1015(), update_r1016(), update_r1017(), update_r1018(), update_r1019(), update_r1020(), update_r1021(), update_r1022(), update_r1023(), update_r1024(), update_r1025(), update_r1026(), update_r1027(), update_r1028(), update_r1029(), update_r1030(), update_r1031(), update_r1032(), update_r1033(), update_r1034(), update_r1035(), update_r1036(), update_r1037(), update_r1038(), update_r1039(), update_r1040(), update_r1041(), update_r1042(), update_r1043(), update_r1044(), update_r1045(), update_r1046(), update_r1047(), update_r1048(), update_r1049(), update_r1050(), update_r1051(), update_r1052(), update_r1053(), update_r1054(), update_r1055(), update_r1056(), update_r1057(), update_r1058(), update_r1059(), update_r1060(), update_r1061(), update_r1062(), update_r1063(), update_r1064(), update_r1065(), update_r1066(), update_r1067(), update_r1068(), update_r1069(), update_r1070(), update_r1071(), update_r1072(), update_r1073(), update_r1074(), update_r1075(), update_r1076(), update_r1077(), update_r1078(), update_r1079(), update_r1080(), update_r1081(), update_r1082(), update_r1083(), update_r1084(), update_r1085(), update_r1086(), update_r1087(), update_r1088(), update_r1089(), update_r1090(), update_r1091(), update_r1092(), update_r1093(), update_r1094(), update_r1095(), update_r1096(), update_r1097(), update_r1098(), update_r1099(), update_r1100(), update_r1101(), update_r1102(), update_r1103(), update_r1104(), update_r1105(), update_r1106(), update_r1107(), update_r1108(), update_r1109(), update_r1110(), update_r1111(), update_r1112(), update_r1113(), update_r1114(), update_r1115(), update_r1116(), update_r1117(), update_r1118(), update_r1119(), update_r1120(), update_r1121(), update_r1122(), update_r1123(), update_r1124(), update_r1125(), update_r1126(), update_r1127(), update_r1128(), update_r1129(), update_r1130(), update_r1131(), update_r1132(), update_r1133(), update_r1134(), update_r1135(), update_r1136(), update_r1137(), update_r1138(), update_r1139(), update_r1140(), update_r1141(), update_r1142(), update_r1143(), update_r1144(), update_r1145(), update_r1146(), update_r1147(), update_r1148(), update_r1149(), update_r1150(), update_r1151(), update_r1152(), update_r1153(), update_r1154(), update_r1155(), update_r1156(), update_r1157(), update_r1158(), update_r1159(), update_r1160(), update_r1161(), update_r1162(), update_r1163(), update_r1164(), update_r1165(), update_r1166(), update_r1167(), update_r1168(), update_r1169(), update_r1170(), update_r1171(), update_r1172(), update_r1173(), update_r1174(), update_r1175(), update_r1176(), update_r1177(), update_r1178(), update_r1179(), update_r1180(), update_r1181(), update_r1182(), update_r1183(), update_r1184(), update_r1185(), update_r1186(), update_r1187(), update_r1188(), update_r1189(), update_r1190(), update_r1191(), update_r1192(), update_r1193(), update_r1194(), update_r1195(), update_r1196(), and update_r1197().
const VNOTIFY_ALERT 0x0100
Referenced by Zotlabs\Module\Settings\Channel\get(), and Zotlabs\Module\Ping\init().
const VNOTIFY_BIRTHDAY 0x0020
Referenced by Zotlabs\Module\Settings\Channel\get(), and Zotlabs\Module\Ping\init().
const VNOTIFY_CHANNEL 0x0002
Referenced by Zotlabs\Module\Settings\Channel\get(), and Zotlabs\Module\Ping\init().
const VNOTIFY_EVENT 0x0008
Referenced by Zotlabs\Module\Settings\Channel\get(), and Zotlabs\Module\Ping\init().
const VNOTIFY_EVENTTODAY 0x0010
Referenced by Zotlabs\Module\Settings\Channel\get(), and Zotlabs\Module\Ping\init().
const VNOTIFY_FILES 0x0800
Referenced by Zotlabs\Module\Settings\Channel\get(), and Zotlabs\Module\Ping\init().
const VNOTIFY_INFO 0x0080
Referenced by Zotlabs\Module\Settings\Channel\get(), and Zotlabs\Module\Ping\init().
const VNOTIFY_INTRO 0x0200
Referenced by Zotlabs\Module\Settings\Channel\get(), and Zotlabs\Module\Ping\init().
const VNOTIFY_MAIL 0x0004
Referenced by Zotlabs\Module\Settings\Channel\get(), and Zotlabs\Module\Ping\init().
const VNOTIFY_NETWORK 0x0001
visual notification options
Referenced by Zotlabs\Module\Settings\Channel\get(), and Zotlabs\Module\Ping\init().
const VNOTIFY_PUBS 0x1000
Referenced by Zotlabs\Module\Settings\Channel\get(), and Zotlabs\Module\Ping\init().
const VNOTIFY_REGISTER 0x0400
Referenced by Zotlabs\Module\Settings\Channel\get(), and Zotlabs\Module\Ping\init().
const VNOTIFY_SYSTEM 0x0040
Referenced by Zotlabs\Module\Settings\Channel\get(), and Zotlabs\Module\Ping\init().
const ZCURL_TIMEOUT (-1)
Communication timeout
const ZOT_APSCHEMA_REV '/apschema/v1.2'
const ZOT_REVISION '1.3'
Referenced by Zotlabs\Lib\System\get_zot_revision(), and Zotlabs\Module\Magic\init().