The Hubzilla: Zotlabs\Access\PermissionRoles Class Reference
Zotlabs\Access\PermissionRoles Class Reference
PermissionRoles class.
Static Public Member Functions
static version ()
PermissionRoles version.
static role_perms ($role)
static new_custom_perms ($uid, $perm, $abooks)
static roles ()
Array with translated role names and grouping.
Detailed Description
PermissionRoles class.
See Also
Permissions
Member Function Documentation
static Zotlabs\Access\PermissionRoles::new_custom_perms ($uid, $perm, $abooks) static
Referenced by check_for_new_perms().
static Zotlabs\Access\PermissionRoles::role_perms ($role) static
Hooks:
get_role_perms
array
Referenced by Zotlabs\Lib\Permcat\__construct(), check_for_new_perms(), Zotlabs\Access\Permissions\connect_perms(), create_identity(), and Zotlabs\Module\Settings\Channel\post().
static Zotlabs\Access\PermissionRoles::roles () static
Array with translated role names and grouping.
Return an associative array with grouped role names that can be used to create select groups like in field_select_grouped.tpl.
Returns
array
Referenced by Zotlabs\Module\New_channel\get(), Zotlabs\Module\Register\get(), and Zotlabs\Module\Settings\Channel\get().
static Zotlabs\Access\PermissionRoles::version () static
PermissionRoles version.
This must match the version in Permissions.php before permission updates can run.
Returns
number
The documentation for this class was generated from the following file:
Zotlabs/Access/PermissionRoles.php