The Hubzilla: Zotlabs\Storage\GitRepo Class Reference
Zotlabs\Storage\GitRepo Class Reference
Public Member Functions
__construct ($channel= 'sys', $url=null, $clone=false, $name=null, $path=null)
initRepo ()
pull ()
getRepoPath ()
setRepoPath ($directory)
setIdentity ($user_name, $user_email)
cloneRepo ()
probeRepo ()
commit ($msg, $options=array())
Static Public Member Functions
static isValidGitRepoURL ($url)
static getRepoNameFromURL ($url)
Public Attributes
$url = null
$name = null
$git = null
Private Attributes
$path = null
$channel = null
$repoBasePath = null
Detailed Description
Wrapper class for PHPGit class for git repositories managed by Hubzilla
Author
Andrew Manning andre.nosp@m.wman.nosp@m.ning@.nosp@m.grid.nosp@m..reti.nosp@m.cu.l.nosp@m.i
Constructor & Destructor Documentation
Zotlabs\Storage\GitRepo::__construct ($channel = 'sys', $url = null, $clone = false, $name = null, $path = null)
Member Function Documentation
Zotlabs\Storage\GitRepo::cloneRepo ()
Referenced by Zotlabs\Storage\GitRepo\__construct().
Zotlabs\Storage\GitRepo::commit ($msg, $options = array())
static Zotlabs\Storage\GitRepo::getRepoNameFromURL ($url) static
Referenced by Zotlabs\Storage\GitRepo\__construct(), and Zotlabs\Module\Admin\Plugins\post().
Zotlabs\Storage\GitRepo::getRepoPath ()
Zotlabs\Storage\GitRepo::initRepo ()
static Zotlabs\Storage\GitRepo::isValidGitRepoURL ($url) static
Referenced by Zotlabs\Storage\GitRepo\__construct(), and Zotlabs\Storage\GitRepo\cloneRepo().
Zotlabs\Storage\GitRepo::probeRepo ()
Zotlabs\Storage\GitRepo::pull ()
Zotlabs\Storage\GitRepo::setIdentity ($user_name, $user_email)
Zotlabs\Storage\GitRepo::setRepoPath ($directory)
Member Data Documentation
Zotlabs\Storage\GitRepo::$channel = null private
Referenced by Zotlabs\Storage\GitRepo\__construct().
Zotlabs\Storage\GitRepo::$git = null
Referenced by Zotlabs\Storage\GitRepo\probeRepo().
Zotlabs\Storage\GitRepo::$name = null
Referenced by Zotlabs\Storage\GitRepo\__construct().
Zotlabs\Storage\GitRepo::$path = null private
Referenced by Zotlabs\Storage\GitRepo\__construct(), and Zotlabs\Storage\GitRepo\getRepoPath().
Zotlabs\Storage\GitRepo::$repoBasePath = null private
Zotlabs\Storage\GitRepo::$url = null
Referenced by Zotlabs\Storage\GitRepo\__construct(), Zotlabs\Storage\GitRepo\getRepoNameFromURL(), and Zotlabs\Storage\GitRepo\isValidGitRepoURL().
The documentation for this class was generated from the following file:
Zotlabs/Storage/GitRepo.php