The Hubzilla: App Class Reference
App Class Reference
Our main application structure for the life of this page.
Static Public Member Functions
static init ()
static get_baseurl ($ssl=false)
static set_baseurl ($url)
static get_scheme ()
static get_hostname ()
static set_hostname ($h)
static set_path ($p)
static get_path ()
static get_channel_links ()
static set_account ($acct)
static get_account ()
static set_channel ($channel)
static get_channel ()
static set_observer ($xchan)
static get_observer ()
static set_perms ($perms)
static get_perms ()
static set_oauth_key ($consumer_id)
static get_oauth_key ()
static get_apps ()
static set_apps ($arr)
static set_groups ($g)
static get_groups ()
static set_pager_total ($n)
static set_pager_itemspage ($n)
static build_pagehead ()
static register_template_engine ($class, $name= '')
Register template engine class.
static template_engine ($name= '')
Return template engine instance.
static get_template_engine ()
Returns the active template engine.
static set_template_engine ($engine= 'smarty3')
static get_template_ldelim ($engine= 'smarty3')
static get_template_rdelim ($engine= 'smarty3')
static head_set_icon ($icon)
static head_get_icon ()
Static Public Attributes
static $install = false
static $account = null
static $channel = null
static $observer = null
static $profile_uid = 0
static $poi = null
static $layout = array()
static $pdl = null
static $config = array()
static $session = null
static $groups
static $language
static $langsave
static $rtl = false
static $plugins_admin
static $module_loaded = false
static $query_string
static $page
static $profile
static $user
static $cid
static $contact
static $contacts
static $content
static $data = array()
static $error = false
static $emojitab = false
static $cmd
static $argv
static $argc
static $module
static $pager
static $strings
static $stringsave
static $hooks
static $timezone
static $interactive = true
static $plugins
static $identities
static $css_sources = array()
static $js_sources = array()
static $linkrel = array()
static $theme_info = array()
static $is_sys = false
static $nav_sel
static $is_mobile = false
static $is_tablet = false
static $comanche
static $channel_links
static $category
static $sourcename = ''
static $videowidth = 425
static $videoheight = 350
static $force_max_items = 0
static $theme_thread_allow = true
static $template_engines = array()
An array of registered template engines ('name'=>'class name')
static $template_engine_instance = array()
An array of instanced template engines ('name'=>'instance')
Static Private Attributes
static $oauth_key = null
static $perms = null
static $widgets = array()
static $apps = array()
static $theme
An array for all theme-controllable parameters.
static $ldelim
static $rdelim
static $scheme
static $hostname
static $path
static $baseurl
static $meta
Detailed Description
Our main application structure for the life of this page.
class: App
Primarily deals with the URL that got us here and tries to make some sense of it, and stores our page contents and config storage and anything else that might need to be passed around before we spit the page out.
Member Function Documentation
static App::build_pagehead () static
Hooks:
build_pagehead Called when creating the HTML page header.
string header - Return the HTML header which should be added
Referenced by construct_page().
static App::get_account () static
Referenced by Zotlabs\Module\Manage\get(), Zotlabs\Module\Service_limits\get(), Zotlabs\Module\New_channel\get(), get_account_techlevel(), Zotlabs\Module\Removeaccount\post(), Zotlabs\Module\Removeme\post(), Zotlabs\Module\Settings\Account\post(), Zotlabs\Module\Changeaddr\post(), Zotlabs\Module\Invite\post(), and Zotlabs\Module\New_channel\post().
static App::get_apps () static
static App::get_baseurl ($ssl = false) static
Referenced by z_root().
static App::get_channel () static
Referenced by api_albums(), api_call(), api_network_stream(), api_photos(), api_user(), bb_observer(), bbcode(), channel_apps(), Zotlabs\Module\Connedit\connedit_clone(), conversation(), Zotlabs\Module\Defperms\defperms_clone(), design_tools(), Zotlabs\Module\Embedphotos\embedphotos_album_list(), Zotlabs\Module\Dreport\get(), Zotlabs\Module\React\get(), Zotlabs\Module\Zping\get(), Zotlabs\Module\Probe\get(), Zotlabs\Module\Pubstream\get(), Zotlabs\Module\Like\get(), Zotlabs\Module\Message\get(), Zotlabs\Module\Subthread\get(), Zotlabs\Module\Tagger\get(), Zotlabs\Module\Editpost\get(), Zotlabs\Module\Display\get(), Zotlabs\Module\Sharedwithme\get(), Zotlabs\Module\Editlayout\get(), Zotlabs\Module\Layouts\get(), Zotlabs\Module\Editblock\get(), Zotlabs\Module\Editwebpage\get(), Zotlabs\Module\Blocks\get(), Zotlabs\Module\Webpages\get(), Zotlabs\Module\Network\get(), Zotlabs\Module\Hq\get(), Zotlabs\Module\Rpost\get(), Zotlabs\Module\Settings\Permcats\get(), Zotlabs\Module\Filestorage\get(), Zotlabs\Module\Rbmark\get(), Zotlabs\Module\Settings\get(), Zotlabs\Module\Changeaddr\get(), Zotlabs\Module\Bookmarks\get(), Zotlabs\Module\Channel\get(), Zotlabs\Module\Menu\get(), Zotlabs\Module\Settings\Tokens\get(), Zotlabs\Module\Locs\get(), Zotlabs\Module\Appman\get(), Zotlabs\Module\Chat\get(), Zotlabs\Module\Invite\get(), Zotlabs\Module\Mitem\get(), Zotlabs\Module\Rate\get(), Zotlabs\Module\Mail\get(), Zotlabs\Module\Defperms\get(), Zotlabs\Module\Thing\get(), Zotlabs\Module\Events\get(), Zotlabs\Module\Cover_photo\get(), Zotlabs\Module\Profile_photo\get(), Zotlabs\Module\Settings\Channel\get(), Zotlabs\Module\Connedit\get(), Zotlabs\Module\Photos\get(), Zotlabs\Module\Profiles\get(), Zotlabs\Module\Cdav\get(), handle_tag(), Zotlabs\Module\Import\import_account(), Zotlabs\Module\Hcard\init(), Zotlabs\Module\Bookmarks\init(), Zotlabs\Module\Uexport\init(), Zotlabs\Module\Prate\init(), Zotlabs\Module\Branchtopic\init(), Zotlabs\Module\Rate\init(), Zotlabs\Module\Magic\init(), Zotlabs\Module\Profiles\init(), Zotlabs\Module\Follow\init(), Zotlabs\Module\Profperm\init(), Zotlabs\Module\Home\init(), Zotlabs\Module\Impel\init(), Zotlabs\Module\Connections\init(), Zotlabs\Module\Cdav\init(), Zotlabs\Module\Chat\init(), Zotlabs\Module\Mood\init(), Zotlabs\Module\Network\init(), Zotlabs\Module\Profile\init(), Zotlabs\Module\Thing\init(), Zotlabs\Module\Wiki\init(), Zotlabs\Module\Defperms\init(), Zotlabs\Module\Channel\init(), Zotlabs\Module\Ping\init(), Zotlabs\Module\Poke\init(), Zotlabs\Module\Connedit\init(), Zotlabs\Module\Cover_photo\init(), Zotlabs\Module\Snap\init(), Zotlabs\Module\Cloud\init(), Zotlabs\Module\Profile_photo\init(), is_public_profile(), menu_add_item(), menu_edit_item(), nav(), Zotlabs\Lib\Apps\parse_app_description(), populate_acl(), Zotlabs\Module\Changeaddr\post(), Zotlabs\Module\Sources\post(), Zotlabs\Module\Locs\post(), Zotlabs\Module\Settings\Permcats\post(), Zotlabs\Module\Settings\Tokens\post(), Zotlabs\Module\Filestorage\post(), Zotlabs\Module\Settings\Channel\post(), Zotlabs\Module\Import_items\post(), Zotlabs\Module\Events\post(), Zotlabs\Module\Mail\post(), Zotlabs\Module\Embedphotos\post(), Zotlabs\Module\Prate\post(), Zotlabs\Module\Item\post(), Zotlabs\Module\Rbmark\post(), Zotlabs\Module\Tasks\post(), Zotlabs\Module\Cover_photo\post(), Zotlabs\Module\Defperms\post(), Zotlabs\Module\Chat\post(), Zotlabs\Module\Rate\post(), Zotlabs\Module\Profile_photo\post(), Zotlabs\Module\Connedit\post(), Zotlabs\Module\Profiles\post(), Zotlabs\Module\Cdav\post(), Zotlabs\Module\Webpages\post(), post_activity_item(), profile_activity(), red_item(), scan_webpage_elements(), send_message(), thread_author_menu(), website_portation_tools(), Zotlabs\Widget\Rating\widget(), Zotlabs\Widget\Notifications\widget(), Zotlabs\Widget\Settings_menu\widget(), and Zotlabs\Widget\Cdav\widget().
static App::get_channel_links () static
Referenced by Zotlabs\Web\WebServer\run().
static App::get_groups () static
static App::get_hostname () static
Referenced by allowed_public_recips(), Zotlabs\Lib\Apps\app_store(), atoken_xchan(), build_sync_packet(), can_comment_on_post(), cert_bad_email(), channel_change_address(), channel_reddress(), check_cron_broken(), check_zotinfo(), comment_local_origin(), create_identity(), event_store_event(), Zotlabs\Module\Fhublocs\get(), Zotlabs\Module\Dirsearch\get(), Zotlabs\Module\Rpost\get(), Zotlabs\Module\Directory\get(), Zotlabs\Module\New_channel\get(), Zotlabs\Module\Admin\Site\get(), Zotlabs\Module\Settings\Channel\get(), Zotlabs\Lib\PermissionDescription\get_permission_description(), Zotlabs\Module\Import\import_account(), import_directory_profile(), import_xchan(), Zotlabs\Module\Hostxrd\init(), Zotlabs\Module\Zfinger\init(), Zotlabs\Module\Magic\init(), Zotlabs\Module\Wfinger\init(), item_message_id(), local_dir_update(), map_scope(), nav(), owt_init(), Zotlabs\Module\Admin\Site\post(), process_location_delivery(), Zotlabs\Web\WebServer\run(), Zotlabs\Daemon\Onepoll\run(), Zotlabs\Daemon\CurlAuth\run(), Zotlabs\Zot\Finger\run(), scopes_sql(), send_message(), Zotlabs\Lib\Enotify\submit(), sync_files(), and z_mail().
static App::get_oauth_key () static
Referenced by get_all_perms(), and perm_is_allowed().
static App::get_observer () static
Referenced by api_albums(), api_photos(), Zotlabs\Lib\Apps\app_render(), attach_recursive_perms(), bb_observer(), Zotlabs\Lib\NativeWikiPage\bbcode(), bbcode(), conversation(), drop_item(), Zotlabs\Module\Embedphotos\embedphotos_album_list(), file_activity(), Zotlabs\Module\Achievements\get(), Zotlabs\Module\Chanview\get(), Zotlabs\Module\Article_edit\get(), Zotlabs\Module\Card_edit\get(), Zotlabs\Module\Like\get(), Zotlabs\Module\Subthread\get(), Zotlabs\Module\Search\get(), Zotlabs\Module\Oexchange\get(), Zotlabs\Module\Articles\get(), Zotlabs\Module\Cards\get(), Zotlabs\Module\Editblock\get(), Zotlabs\Module\Editlayout\get(), Zotlabs\Module\Layouts\get(), Zotlabs\Module\Editwebpage\get(), Zotlabs\Module\Blocks\get(), Zotlabs\Module\Webpages\get(), Zotlabs\Module\Rpost\get(), Zotlabs\Module\Filestorage\get(), Zotlabs\Module\Channel\get(), Zotlabs\Module\Connect\get(), Zotlabs\Module\Chat\get(), Zotlabs\Module\Invite\get(), Zotlabs\Module\Mitem\get(), Zotlabs\Module\Photos\get(), Zotlabs\Render\Comanche\get_condition_var(), get_observer_hash(), Zotlabs\Module\Zotfeed\init(), Zotlabs\Module\Page\init(), Zotlabs\Module\Share\init(), Zotlabs\Module\Photo\init(), Zotlabs\Module\Mood\init(), Zotlabs\Module\Cal\init(), Zotlabs\Module\Photos\init(), item_redir_and_replace_images(), nav(), Zotlabs\Lib\Apps\parse_app_description(), parseIdentityAwareHTML(), poco(), Zotlabs\Module\Wall_upload\post(), Zotlabs\Module\Wall_attach\post(), Zotlabs\Module\Item\post(), Zotlabs\Module\Connect\post(), post_activity_item(), profile_load(), profile_sidebar(), Zotlabs\Lib\ThreadStream\set_mode(), Zotlabs\Widget\Vcard\widget(), Zotlabs\Widget\Rating\widget(), Zotlabs\Widget\Photo_rand\widget(), and Zotlabs\Widget\Photo_albums\widget().
static App::get_path () static
Referenced by Zotlabs\Module\Settings\Channel\get(), and Zotlabs\Module\Setup\post().
static App::get_perms () static
static App::get_scheme () static
Referenced by construct_page().
static App::get_template_engine () static
Returns the active template engine.
Returns
string
Referenced by Zotlabs\Module\Fbrowser\files2().
static App::get_template_ldelim ($engine = 'smarty3') static
Referenced by Zotlabs\Render\SmartyInterface\__construct().
static App::get_template_rdelim ($engine = 'smarty3') static
Referenced by Zotlabs\Render\SmartyInterface\__construct().
static App::head_get_icon () static
Referenced by build_pagehead().
static App::head_set_icon ($icon) static
Referenced by sys_boot().
static App::init () static
App constructor.
Todo:
validate if this is still the desired behavior
Referenced by sys_boot().
static App::register_template_engine ($class, $name = '') static
Register template engine class.
If $name is "", is used class static property $class::$name.
Parameters
string $class
string $name
static App::set_account ($acct) static
static App::set_apps ($arr) static
static App::set_baseurl ($url) static
Referenced by check_config(), and cli_startup().
static App::set_channel ($channel) static
Referenced by change_channel().
static App::set_groups ($g) static
Referenced by owt_init(), and Zotlabs\Zot\Auth\Verify().
static App::set_hostname ($h) static
static App::set_oauth_key ($consumer_id) static
Referenced by api_login(), and ZotOAuth1DataStore\lookup_consumer().
static App::set_observer ($xchan) static
Referenced by atoken_login(), change_channel(), owt_init(), and Zotlabs\Zot\Auth\Verify().
static App::set_pager_itemspage ($n) static
Referenced by Zotlabs\Module\Pubstream\get(), Zotlabs\Module\Search\get(), Zotlabs\Module\Network\get(), Zotlabs\Module\Admin\Channels\get(), Zotlabs\Module\Channel\get(), Zotlabs\Module\Admin\Accounts\get(), Zotlabs\Module\Photos\get(), Zotlabs\Module\Dirsearch\init(), Zotlabs\Module\Directory\init(), items_fetch(), and search_doc_files().
static App::set_pager_total ($n) static
Referenced by Zotlabs\Module\Viewconnections\get(), Zotlabs\Module\Connections\get(), Zotlabs\Module\Admin\Channels\get(), and Zotlabs\Module\Admin\Accounts\get().
static App::set_path ($p) static
static App::set_perms ($perms) static
Referenced by change_channel().
static App::set_template_engine ($engine = 'smarty3') static
static App::template_engine ($name = '') static
Return template engine instance.
If $name is not defined, return engine defined by theme, or default.
Parameters
string $name Template engine name
Returns
object Template Engine instance
Referenced by get_intltext_template(), get_markup_template(), and replace_macros().
Member Data Documentation
App::$account = null static
Referenced by authenticate_success(), channel_remove(), Zotlabs\Module\Settings\Account\get(), get_account_id(), is_developer(), is_site_admin(), Zotlabs\Module\Settings\Account\post(), and service_class_fetch().
App::$apps = array() static private
App::$argc static
Referenced by api_call(), argc(), Zotlabs\Module\Filerm\get(), Zotlabs\Module\Update\get(), Zotlabs\Module\Filer\get(), Zotlabs\Module\Fbrowser\get(), Zotlabs\Module\Connections\get(), Zotlabs\Module\Admin\Themes\get(), Zotlabs\Module\Admin\Plugins\get(), Zotlabs\Module\Well_known\init(), Zotlabs\Module\Settings\init(), and Zotlabs\Module\Mail\post().
App::$argv static
Referenced by api_call(), argv(), Zotlabs\Module\Smilies\get(), Zotlabs\Module\Filerm\get(), Zotlabs\Module\Update\get(), Zotlabs\Module\Manage\get(), Zotlabs\Module\Filer\get(), Zotlabs\Module\Fbrowser\get(), Zotlabs\Module\Connections\get(), Zotlabs\Module\Admin\Themes\get(), Zotlabs\Module\Events\get(), Zotlabs\Module\Admin\Plugins\get(), Zotlabs\Module\Profiles\get(), Zotlabs\Module\Well_known\init(), Zotlabs\Module\Profperm\init(), Zotlabs\Module\Profiles\init(), Zotlabs\Module\Settings\init(), load_context_help(), Zotlabs\Module\Mail\post(), Zotlabs\Module\Photos\post(), Zotlabs\Module\Profiles\post(), and Zotlabs\Widget\Categories\widget().
App::$baseurl static private
App::$category static
App::$channel = null static
Referenced by channel_apps(), check_form_security_token(), Zotlabs\Theme\RedbasicConfig\form(), Zotlabs\Lib\PermissionDescription\fromGlobalPermission(), Zotlabs\Module\Settings\Display\get(), Zotlabs\Module\Cover_photo\get(), Zotlabs\Module\Profile_photo\get(), get_form_security_token(), Zotlabs\Module\Settings\Display\post(), Zotlabs\Web\WebServer\run(), set_channel(), Zotlabs\Zot\Auth\Verify(), and Zotlabs\Widget\Follow\widget().
App::$channel_links static
Referenced by Zotlabs\Web\WebServer\run().
App::$cid static
App::$cmd static
Referenced by api_call(), conversation(), Zotlabs\Module\Regver\get(), Zotlabs\Module\Regmod\get(), Zotlabs\Module\Display\get(), Zotlabs\Module\Connections\get(), Zotlabs\Module\Suggest\get(), Zotlabs\Module\Api\get(), Zotlabs\Module\Cal\get(), Zotlabs\Module\Group\get(), Zotlabs\Module\Events\get(), Zotlabs\Module\Photos\get(), Zotlabs\Module\Well_known\init(), load_context_help(), nav(), Zotlabs\Widget\Archive\widget(), Zotlabs\Widget\Filer\widget(), and zid_init().
App::$comanche static
Referenced by construct_page(), exec_pdl(), Zotlabs\Module\Page\init(), and load_pdl().
App::$config = array() static
Referenced by Zotlabs\Render\SmartyTemplate\__construct(), Zotlabs\Lib\DB_Upgrade\__construct(), Zotlabs\Render\SmartyInterface\__construct(), build_sync_packet(), cert_bad_email(), check_cron_broken(), construct_page(), miniApp\convert(), Zotlabs\Render\Theme\current(), Zotlabs\Lib\Config\Delete(), Zotlabs\Lib\XConfig\Delete(), Zotlabs\Lib\PConfig\Delete(), Zotlabs\Module\Login\get(), Zotlabs\Module\Regmod\get(), Zotlabs\Access\PermissionLimits\Get(), Zotlabs\Module\Pconfig\get(), Zotlabs\Module\Home\get(), Zotlabs\Module\Lostpass\get(), Zotlabs\Lib\XConfig\Get(), Zotlabs\Lib\PConfig\Get(), Zotlabs\Lib\Config\Get(), get_best_language(), Zotlabs\Lib\System\get_notify_icon(), Zotlabs\Lib\System\get_platform_name(), Zotlabs\Lib\System\get_project_link(), Zotlabs\Lib\System\get_project_srclink(), Zotlabs\Lib\System\get_project_version(), Zotlabs\Lib\System\get_site_icon(), get_site_info(), Zotlabs\Lib\System\get_site_name(), Zotlabs\Lib\System\get_update_version(), Zotlabs\Module\Ping\init(), Zotlabs\Lib\Config\Load(), Zotlabs\Lib\PConfig\Load(), Zotlabs\Lib\XConfig\Load(), Zotlabs\Module\Settings\Channel\post(), proc_run(), script_path(), Zotlabs\Lib\Config\Set(), Zotlabs\Lib\XConfig\Set(), Zotlabs\Lib\PConfig\Set(), sys_boot(), and z_dns_check().
App::$contact static
App::$contacts static
Referenced by best_link_url(), Zotlabs\Module\Ratings\init(), load_contact_links(), and thread_author_menu().
App::$content static
App::$css_sources = array() static
Referenced by head_add_css(), head_get_css(), and head_remove_css().
App::$data = array() static
Referenced by conversation(), Zotlabs\Module\Cover_photo\cover_photo_crop_ui_head(), dir_tagblock(), Zotlabs\Module\Embedphotos\embedphotos_widget_album(), Zotlabs\Module\Pubstream\get(), Zotlabs\Module\Search\get(), Zotlabs\Module\Directory\get(), Zotlabs\Module\Chatsvc\get(), Zotlabs\Module\Ratings\get(), Zotlabs\Module\Connect\get(), Zotlabs\Module\Mitem\get(), Zotlabs\Module\Rate\get(), Zotlabs\Module\Setup\get(), Zotlabs\Module\Page\get(), Zotlabs\Module\Cover_photo\get(), Zotlabs\Module\Profile_photo\get(), Zotlabs\Module\Photos\get(), head_get_icon(), head_set_icon(), Zotlabs\Module\Search\init(), Zotlabs\Module\Rate\init(), Zotlabs\Module\Ratings\init(), Zotlabs\Module\Mitem\init(), Zotlabs\Module\Page\init(), Zotlabs\Module\Chatsvc\init(), Zotlabs\Module\Cal\init(), Zotlabs\Module\Connect\init(), Zotlabs\Module\Photos\init(), Zotlabs\Module\Setup\manual_config(), photos_album_widget(), photos_albums_list(), Zotlabs\Module\Chatsvc\post(), Zotlabs\Module\Connect\post(), Zotlabs\Module\Mitem\post(), Zotlabs\Module\Rate\post(), Zotlabs\Module\Photos\post(), Zotlabs\Module\Setup\post(), Zotlabs\Module\Profile_photo\profile_photo_crop_ui_head(), and Zotlabs\Widget\Menu_preview\widget().
App::$emojitab = false static
App::$error = false static
Referenced by Zotlabs\Web\Router\__construct(), Zotlabs\Web\Router\Dispatch(), Zotlabs\Module\Viewsrc\get(), Zotlabs\Module\Display\get(), Zotlabs\Module\Cards\get(), Zotlabs\Module\Articles\get(), Zotlabs\Module\Editblock\get(), Zotlabs\Module\Editlayout\get(), Zotlabs\Module\Layouts\get(), Zotlabs\Module\Editwebpage\get(), Zotlabs\Module\Webpages\get(), Zotlabs\Module\Blocks\get(), Zotlabs\Module\Filestorage\get(), Zotlabs\Module\Hcard\init(), Zotlabs\Module\Common\init(), Zotlabs\Module\Profiles\init(), Zotlabs\Module\Connect\init(), Zotlabs\Module\Profile\init(), and profile_load().
App::$force_max_items = 0 static
App::$groups static
App::$hooks static
Referenced by call_hooks(), Zotlabs\Extend\Hook\insert(), insert_hook(), and load_hooks().
App::$hostname static private
App::$identities static
App::$install = false static
Referenced by Zotlabs\Module\Ping\init(), Zotlabs\Web\WebServer\run(), and sys_boot().
App::$interactive = true static
Referenced by info(), and notice().
App::$is_mobile = false static
Referenced by construct_page(), Zotlabs\Render\Theme\current(), Zotlabs\Module\Connections\get(), and Zotlabs\Module\Connedit\get().
App::$is_sys = false static
Referenced by channel_apps(), design_tools(), Zotlabs\Module\Editblock\get(), Zotlabs\Module\Editlayout\get(), Zotlabs\Module\Layouts\get(), Zotlabs\Module\Editwebpage\get(), Zotlabs\Module\Webpages\get(), Zotlabs\Module\Blocks\get(), Zotlabs\Module\Menu\get(), Zotlabs\Module\Mitem\get(), Zotlabs\Module\Menu\init(), Zotlabs\Module\Editblock\init(), Zotlabs\Module\Editlayout\init(), Zotlabs\Module\Mitem\init(), Zotlabs\Module\Layouts\init(), Zotlabs\Module\Blocks\init(), Zotlabs\Module\Webpages\init(), Zotlabs\Module\Editwebpage\init(), mimetype_select(), Zotlabs\Module\Menu\post(), Zotlabs\Module\Mitem\post(), website_portation_tools(), Zotlabs\Widget\Design_tools\widget(), Zotlabs\Widget\Website_portation_tools\widget(), and z_input_filter().
App::$is_tablet = false static
Referenced by construct_page(), Zotlabs\Render\Theme\current(), Zotlabs\Module\Connections\get(), and Zotlabs\Module\Connedit\get().
App::$js_sources = array() static
Referenced by head_add_js(), head_get_js(), and head_remove_js().
App::$langsave static
Referenced by pop_lang(), and push_lang().
App::$language static
Referenced by determine_help_language(), Zotlabs\Module\Wiki\get(), Zotlabs\Module\Cal\get(), Zotlabs\Module\Events\get(), Zotlabs\Render\SmartyTemplate\get_intltext_template(), ical_wrapper(), Zotlabs\Module\Page\init(), lang_selector(), load_context_help(), oblanguage_callback(), oblanguage_necallback(), pop_lang(), push_lang(), Zotlabs\Web\WebServer\run(), search_doc_files(), Zotlabs\Lib\Enotify\submit(), and tt().
App::$layout = array() static
Referenced by construct_page(), Zotlabs\Render\Theme\current(), load_pdl(), Zotlabs\Render\Comanche\parse_pass0(), Zotlabs\Render\Comanche\parse_pass1(), and Zotlabs\Render\Theme\url().
App::$ldelim static private
Initial value:
= array(
        'internal' => '',
        'smarty3' => '{{'
    )
App::$linkrel = array() static
Referenced by head_add_link(), and head_get_links().
App::$meta static private
App::$module static
Referenced by Zotlabs\Web\Router\__construct(), authenticate_success(), construct_page(), contact_select(), Zotlabs\Web\Router\Dispatch(), dlogger(), get_feed_for(), group_select(), load_pdl(), logger(), nav(), Zotlabs\Web\WebServer\run(), Zotlabs\Widget\Cover_photo\widget(), and Zotlabs\Widget\Notifications\widget().
App::$module_loaded = false static
Referenced by Zotlabs\Web\Router\__construct(), and Zotlabs\Web\Router\Dispatch().
App::$nav_sel static
Referenced by nav(), and nav_set_selected().
App::$oauth_key = null static private
App::$observer = null static
Referenced by check_form_security_token(), check_form_security_token_ForbiddenOnErr(), check_form_security_token_redirectOnErr(), and get_form_security_token().
App::$page static
Referenced by Zotlabs\Web\CheckJS\__construct(), Zotlabs\Web\Router\__construct(), Zotlabs\Render\Comanche\block(), construct_page(), Zotlabs\Module\Cover_photo\cover_photo_crop_ui_head(), Zotlabs\Web\Router\Dispatch(), findpeople_widget(), Zotlabs\Module\Pubstream\get(), Zotlabs\Module\Display\get(), Zotlabs\Module\Search\get(), Zotlabs\Module\Api\get(), Zotlabs\Module\Network\get(), Zotlabs\Module\Hq\get(), Zotlabs\Module\Cal\get(), Zotlabs\Module\Home\get(), Zotlabs\Module\Channel\get(), Zotlabs\Module\Mail\get(), Zotlabs\Module\Page\get(), Zotlabs\Module\Events\get(), Zotlabs\Module\Photos\get(), Zotlabs\Module\Profiles\get(), get_custom_nav(), get_help_content(), Zotlabs\Module\Page\init(), Zotlabs\Module\Cal\init(), Zotlabs\Module\Photos\init(), nav(), Zotlabs\Render\Comanche\parse_pass0(), profile_load(), Zotlabs\Module\Profile_photo\profile_photo_crop_ui_head(), Zotlabs\Render\Comanche\replace_region(), and Zotlabs\Web\WebServer\run().
App::$pager static
Referenced by alt_pager(), conversation(), Zotlabs\Module\Pubstream\get(), Zotlabs\Module\Search\get(), Zotlabs\Module\Display\get(), Zotlabs\Module\Viewconnections\get(), Zotlabs\Module\Connections\get(), Zotlabs\Module\Network\get(), Zotlabs\Module\Hq\get(), Zotlabs\Module\Admin\Channels\get(), Zotlabs\Module\Directory\get(), Zotlabs\Module\Channel\get(), Zotlabs\Module\Admin\Accounts\get(), Zotlabs\Module\Photos\get(), items_fetch(), paginate(), search_doc_files(), and Zotlabs\Widget\Conversations\widget().
App::$path static private
Referenced by init().
App::$pdl = null static
Referenced by exec_pdl(), Zotlabs\Module\Page\init(), and load_pdl().
App::$perms = null static private
Referenced by set_perms().
App::$plugins static
Referenced by Zotlabs\Web\Router\__construct(), Zotlabs\Module\Admin\admin_page_summary(), check_config(), check_plugin_versions(), Zotlabs\Module\Admin\Plugins\get(), and zot_site_info().
App::$plugins_admin static
Referenced by Zotlabs\Widget\Admin\widget().
App::$poi = null static
Referenced by Zotlabs\Module\Connedit\connedit_clone(), Zotlabs\Module\Defperms\defperms_clone(), Zotlabs\Module\Chanview\get(), Zotlabs\Module\Rate\get(), Zotlabs\Module\Mail\get(), Zotlabs\Module\Defperms\get(), Zotlabs\Module\Connedit\get(), Zotlabs\Module\Rate\init(), Zotlabs\Module\Ratings\init(), Zotlabs\Module\Defperms\init(), Zotlabs\Module\Connedit\init(), Zotlabs\Module\Defperms\post(), Zotlabs\Module\Connedit\post(), vcard_from_xchan(), Zotlabs\Widget\Rating\widget(), Zotlabs\Widget\Pubsites\widget(), and Zotlabs\Widget\Collections\widget().
App::$profile static
Referenced by advanced_profile(), articlecategories_widget(), cardcategories_widget(), categories_widget(), channel_apps(), construct_page(), contact_block(), conversation(), Zotlabs\Widget\Wiki_pages\create_missing_page(), Zotlabs\Module\Embedphotos\embedphotos_widget_album(), Zotlabs\Module\Search\get(), Zotlabs\Module\Viewconnections\get(), Zotlabs\Module\Block\get(), Zotlabs\Module\Cards\get(), Zotlabs\Module\Articles\get(), Zotlabs\Module\Common\get(), Zotlabs\Module\Editblock\get(), Zotlabs\Module\Editlayout\get(), Zotlabs\Module\Layouts\get(), Zotlabs\Module\Editwebpage\get(), Zotlabs\Module\Blocks\get(), Zotlabs\Module\Webpages\get(), Zotlabs\Module\Wiki\get(), Zotlabs\Module\Cal\get(), Zotlabs\Module\Channel\get(), Zotlabs\Module\Profile\get(), Zotlabs\Module\Chat\get(), Zotlabs\Module\Photos\get(), Zotlabs\Render\Comanche\get_channel_id(), Zotlabs\Module\Hcard\init(), Zotlabs\Module\Block\init(), Zotlabs\Module\Page\init(), Zotlabs\Module\Profile\init(), menu_render(), nav(), Zotlabs\Module\Photos\post(), profile_load(), Zotlabs\Lib\ThreadStream\set_mode(), vcard_from_xchan(), Zotlabs\Widget\Tagcloud_wall\widget(), Zotlabs\Widget\Bookmarkedchats\widget(), Zotlabs\Widget\Fullprofile\widget(), Zotlabs\Widget\Chatroom_list\widget(), Zotlabs\Widget\Design_tools\widget(), Zotlabs\Widget\Catcloud_wall\widget(), Zotlabs\Widget\Shortprofile\widget(), Zotlabs\Widget\Suggestedchats\widget(), Zotlabs\Widget\Profile\widget(), Zotlabs\Widget\Website_portation_tools\widget(), Zotlabs\Widget\Portfolio\widget(), Zotlabs\Widget\Album\widget(), Zotlabs\Widget\Categories\widget(), Zotlabs\Widget\Common_friends\widget(), Zotlabs\Widget\Photo_albums\widget(), and Zotlabs\Widget\Wiki_pages\widget().
App::$profile_uid = 0 static
Referenced by construct_page(), Zotlabs\Render\Theme\current(), Zotlabs\Module\Embedphotos\embedphotos_widget_album(), Zotlabs\Module\Cards\get(), Zotlabs\Module\Articles\get(), Zotlabs\Module\Webpages\get(), Zotlabs\Module\Wiki\get(), Zotlabs\Module\Channel\get(), Zotlabs\Module\Settings\init(), Zotlabs\Module\Hq\init(), Zotlabs\Module\Network\init(), linkify_tags(), nav(), profile_load(), Zotlabs\Lib\NativeWikiPage\render_page_history(), Zotlabs\Render\Theme\url(), vcard_from_xchan(), Zotlabs\Widget\Random_block\widget(), Zotlabs\Widget\Wiki_page_history\widget(), Zotlabs\Widget\Zcard\widget(), Zotlabs\Widget\Cover_photo\widget(), Zotlabs\Widget\Wiki_list\widget(), Zotlabs\Widget\Archive\widget(), Zotlabs\Widget\Photo_rand\widget(), Zotlabs\Widget\Item\widget(), Zotlabs\Widget\Album\widget(), Zotlabs\Widget\Portfolio\widget(), and Zotlabs\Widget\Tagcloud\widget().
App::$query_string static
Referenced by Zotlabs\Web\CheckJS\__construct(), alt_pager(), api_call(), clean_query_string(), conversation(), Zotlabs\Module\Apps\get(), Zotlabs\Module\Like\get(), Zotlabs\Module\Display\get(), Zotlabs\Module\Viewconnections\get(), Zotlabs\Module\Connections\get(), Zotlabs\Module\Cards\get(), Zotlabs\Module\Articles\get(), Zotlabs\Module\Layouts\get(), Zotlabs\Module\Blocks\get(), Zotlabs\Module\Webpages\get(), Zotlabs\Module\Network\get(), Zotlabs\Module\Channel\get(), Zotlabs\Module\Profile\get(), Zotlabs\Module\Photos\get(), http_status(), Zotlabs\Module\Rmagic\init(), Zotlabs\Module\Photo\init(), Zotlabs\Module\Cloud\init(), login(), owt_init(), paginate(), Zotlabs\Module\Rmagic\post(), Zotlabs\Module\Connect\post(), profile_load(), Zotlabs\Web\WebServer\run(), Zotlabs\Widget\Savedsearch\widget(), Zotlabs\Widget\Sitesearch\widget(), Zotlabs\Widget\Categories\widget(), and zid_init().
App::$rdelim static private
Initial value:
= array(
        'internal' => '',
        'smarty3' => '}}'
    )
App::$rtl = false static
App::$scheme static private
Referenced by get_baseurl().
App::$session = null static
Referenced by account_remove(), channel_remove(), Zotlabs\Module\Logout\init(), Zotlabs\Web\WebServer\run(), Zotlabs\Daemon\CurlAuth\run(), and sys_boot().
App::$sourcename = '' static
Referenced by Zotlabs\Lib\ThreadItem\get_comment_box().
App::$strings static
Referenced by load_translation_table(), pop_lang(), push_lang(), t(), and tt().
App::$stringsave static
Referenced by pop_lang(), and push_lang().
App::$template_engine_instance = array() static
An array of instanced template engines ('name'=>'instance')
App::$template_engines = array() static
An array of registered template engines ('name'=>'class name')
App::$theme static private
Initial value:
= array(
        'sourcename' => '',
        'videowidth' => 425,
        'videoheight' => 350,
        'force_max_items' => 0,
        'thread_allow' => true,
        'stylesheet' => '',
        'template_engine' => 'smarty3',
    )
An array for all theme-controllable parameters.
Mostly unimplemented yet. Only options 'template_engine' and beyond are used.
App::$theme_info = array() static
Referenced by Zotlabs\Render\SmartyInterface\__construct(), Zotlabs\Web\Router\Dispatch(), Zotlabs\Module\Theme_info\get_theme_config_file(), Zotlabs\Module\Settings\Display\get_theme_config_file(), and theme_include().
App::$theme_thread_allow = true static
App::$timezone static
Referenced by create_identity(), and sys_boot().
App::$user static
Referenced by api_login(), conversation(), and dob().
App::$videoheight = 350 static
App::$videowidth = 425 static
Referenced by oembed_fetch_url(), and tryzrlvideo().
App::$widgets = array() static private
The documentation for this class was generated from the following file:
boot.php