The Hubzilla: Zotlabs\Render\SimpleTemplate Class Reference
Zotlabs\Render\SimpleTemplate Class Reference
Public Member Functions
replace_macros ($s, $r)
get_markup_template ($file, $root='')
Public Attributes
$r
$search
$replace
$stack = array()
$nodes = array()
$done = false
$d = false
$lang = null
$debug =false
Static Public Attributes
static $name ="internal"
Private Member Functions
_preg_error ()
_push_stack ()
_pop_stack ()
_get_var ($name, $retNoKey=false)
_replcb_if ($args)
_replcb_for ($args)
_replcb_inc ($args)
_replcb_debug ($args)
_replcb_node ($m)
_replcb ($m)
_build_nodes ($s)
var_replace ($s)
replace ($s, $r)
Member Function Documentation
Zotlabs\Render\SimpleTemplate::_build_nodes ($s) private
Referenced by Zotlabs\Render\SimpleTemplate\replace_macros().
Zotlabs\Render\SimpleTemplate::_get_var ($name, $retNoKey = false) private
Referenced by Zotlabs\Render\SimpleTemplate\_replcb_debug(), Zotlabs\Render\SimpleTemplate\_replcb_for(), Zotlabs\Render\SimpleTemplate\_replcb_if(), Zotlabs\Render\SimpleTemplate\_replcb_inc(), and Zotlabs\Render\SimpleTemplate\var_replace().
Zotlabs\Render\SimpleTemplate::_pop_stack () private
Referenced by Zotlabs\Render\SimpleTemplate\_replcb_for(), and Zotlabs\Render\SimpleTemplate\_replcb_inc().
Zotlabs\Render\SimpleTemplate::_preg_error () private
Referenced by Zotlabs\Render\SimpleTemplate\_build_nodes(), and Zotlabs\Render\SimpleTemplate\replace_macros().
Zotlabs\Render\SimpleTemplate::_push_stack () private
Referenced by Zotlabs\Render\SimpleTemplate\_replcb_for(), and Zotlabs\Render\SimpleTemplate\_replcb_inc().
Zotlabs\Render\SimpleTemplate::_replcb ($m) private
Zotlabs\Render\SimpleTemplate::_replcb_debug ($args) private
DEBUG node
{{ debug $var [$var [$var [...]]] }}{{ enddebug }}
replace node with
var_dump($var, $var, ...);
Zotlabs\Render\SimpleTemplate::_replcb_for ($args) private
FOR node
{{ for <$var> as $name }}...{{ endfor }}
{{ for <$var> as $key=>$name }}...{{ endfor }}
Zotlabs\Render\SimpleTemplate::_replcb_if ($args) private
IF node
{{ if <$var> }}...[{{ else }} ...] {{ endif }}
{{ if <$var>==<val|$var> }}...[{{ else }} ...]{{ endif }}
{{ if <$var>!=<val|$var> }}...[{{ else }} ...]{{ endif }}
Zotlabs\Render\SimpleTemplate::_replcb_inc ($args) private
INC node
{{ inc <templatefile> [with $var1=$var2] }}{{ endinc }}
Zotlabs\Render\SimpleTemplate::_replcb_node ($m) private
Zotlabs\Render\SimpleTemplate::get_markup_template ($file, $root = '')
Implements Zotlabs\Render\TemplateEngine.
Referenced by Zotlabs\Render\SimpleTemplate\_replcb_inc().
Zotlabs\Render\SimpleTemplate::replace ($s, $r) private
Referenced by Zotlabs\Render\SimpleTemplate\_replcb_for(), and Zotlabs\Render\SimpleTemplate\_replcb_inc().
Zotlabs\Render\SimpleTemplate::replace_macros ($s, $r)
Implements Zotlabs\Render\TemplateEngine.
Referenced by Zotlabs\Render\SimpleTemplate\replace().
Zotlabs\Render\SimpleTemplate::var_replace ($s) private
regexp: $ literal $ ([)? optional open square bracket ([a-zA-Z0-9-_]+.?)+ var name, followed by optional dot, repeated at least 1 time (?(1)]) if there was opened square bracket (subgrup 1), match close bracket
Referenced by Zotlabs\Render\SimpleTemplate\replace_macros().
Member Data Documentation
Zotlabs\Render\SimpleTemplate::$d = false
Zotlabs\Render\SimpleTemplate::$debug =false
Zotlabs\Render\SimpleTemplate::$done = false
Zotlabs\Render\SimpleTemplate::$lang = null
Zotlabs\Render\SimpleTemplate::$name ="internal" static
Referenced by Zotlabs\Render\SimpleTemplate\_get_var().
Zotlabs\Render\SimpleTemplate::$nodes = array()
Zotlabs\Render\SimpleTemplate::$r
Referenced by Zotlabs\Render\SimpleTemplate\_get_var(), Zotlabs\Render\SimpleTemplate\_replcb_for(), Zotlabs\Render\SimpleTemplate\_replcb_inc(), Zotlabs\Render\SimpleTemplate\replace(), and Zotlabs\Render\SimpleTemplate\replace_macros().
Zotlabs\Render\SimpleTemplate::$replace
Zotlabs\Render\SimpleTemplate::$search
Zotlabs\Render\SimpleTemplate::$stack = array()
The documentation for this class was generated from the following file:
Zotlabs/Render/SimpleTemplate.php