The Hubzilla: Zotlabs\Lib\Chatroom Class Reference
Zotlabs\Lib\Chatroom Class Reference
A class with chatroom related static methods.
Public Member Functions
leave ($observer_xchan, $room_id, $client)
Static Public Member Functions
static create ($channel, $arr)
Creates a chatroom.
static destroy ($channel, $arr)
static enter ($observer_xchan, $room_id, $status, $client)
static roomlist ($uid)
static list_count ($uid)
static message ($uid, $room_id, $xchan, $text)
Create a chat message via API.
Detailed Description
A class with chatroom related static methods.
Member Function Documentation
static Zotlabs\Lib\Chatroom::create ($channel, $arr) static
Creates a chatroom.
Parameters
array $channel
array $arr
Returns
array An associative array containing:
boolean success - A boolean success status
string message - (optional) A string
Referenced by Zotlabs\Module\Chat\post().
static Zotlabs\Lib\Chatroom::destroy ($channel, $arr) static
Referenced by Zotlabs\Module\Chat\post().
static Zotlabs\Lib\Chatroom::enter ($observer_xchan, $room_id, $status, $client) static
Referenced by Zotlabs\Module\Chat\get().
Zotlabs\Lib\Chatroom::leave ($observer_xchan, $room_id, $client)
Referenced by Zotlabs\Module\Chat\get().
static Zotlabs\Lib\Chatroom::list_count ($uid) static
Referenced by channel_apps().
static Zotlabs\Lib\Chatroom::message ($uid, $room_id, $xchan, $text) static
Create a chat message via API.
It is the caller's responsibility to enter the room.
Parameters
int $uid
int $room_id
string $xchan
string $text
Returns
array
Hooks:
chat_message Called to create a chat message.
int chat_room
string chat_xchan
string chat_text
static Zotlabs\Lib\Chatroom::roomlist ($uid) static
Referenced by Zotlabs\Module\Chat\get(), and Zotlabs\Widget\Chatroom_list\widget().
The documentation for this class was generated from the following file:
Zotlabs/Lib/Chatroom.php