The Hubzilla: Zotlabs\Lib\ActivityStreams Class Reference
Zotlabs\Lib\ActivityStreams Class Reference
ActivityStreams class.
Public Member Functions
__construct ($string)
Constructor for ActivityStreams.
is_valid ()
Return if instantiated ActivityStream is valid.
set_recips ($arr)
collect_recips ($base= '', $namespace= '')
Collects all recipients.
expand ($arr, $base= '', $namespace= '')
get_namespace ($base, $namespace)
get_property_obj ($property, $base= '', $namespace= '')
fetch_property ($url)
Fetches a property from an URL.
get_compound_property ($property, $base= '', $namespace= '')
is_url ($url)
Check if string starts with http.
get_primary_type ($base= '', $namespace= '')
Gets the type property.
debug ()
Public Attributes
$data
$valid = false
$id = ''
$type = ''
$actor = null
$obj = null
$tgt = null
$origin = null
$owner = null
$signer = null
$ldsig = null
$sigok = false
$recips = null
$raw_recips = null
Detailed Description
ActivityStreams class.
Parses an ActivityStream JSON string.
Constructor & Destructor Documentation
Zotlabs\Lib\ActivityStreams::__construct ($string)
Constructor for ActivityStreams.
Takes a JSON string as parameter, decodes it and sets up this object.
Parameters
string $string
Member Function Documentation
Zotlabs\Lib\ActivityStreams::collect_recips ($base = '', $namespace = '')
Collects all recipients.
Parameters
string $base
string $namespace (optional) default empty
Returns
array
Referenced by Zotlabs\Lib\ActivityStreams\__construct().
Zotlabs\Lib\ActivityStreams::debug ()
Zotlabs\Lib\ActivityStreams::expand ($arr, $base = '', $namespace = '')
Fixme:
de-duplicate
Zotlabs\Lib\ActivityStreams::fetch_property ($url)
Fetches a property from an URL.
Parameters
string $url
Returns
NULL|mixed
Referenced by Zotlabs\Lib\ActivityStreams\get_compound_property().
Zotlabs\Lib\ActivityStreams::get_compound_property ($property, $base = '', $namespace = '')
Parameters
string $property
array $base
string $namespace (optional) default empty
Returns
NULL|mixed
Referenced by Zotlabs\Lib\ActivityStreams\__construct(), Zotlabs\Lib\ActivityStreams\collect_recips(), and Zotlabs\Lib\ActivityStreams\expand().
Zotlabs\Lib\ActivityStreams::get_namespace ($base, $namespace)
Parameters
array $base
string $namespace if not set return empty string
Returns
string|NULL
Referenced by Zotlabs\Lib\ActivityStreams\get_property_obj().
Zotlabs\Lib\ActivityStreams::get_primary_type ($base = '', $namespace = '')
Gets the type property.
Parameters
array $base
string $namespace (optional) default empty
Returns
NULL|mixed
Referenced by Zotlabs\Lib\ActivityStreams\__construct().
Zotlabs\Lib\ActivityStreams::get_property_obj ($property, $base = '', $namespace = '')
Parameters
string $property
array $base (optional)
string $namespace (optional) default empty
Returns
NULL|mixed
Referenced by Zotlabs\Lib\ActivityStreams\__construct(), Zotlabs\Lib\ActivityStreams\get_compound_property(), and Zotlabs\Lib\ActivityStreams\get_primary_type().
Zotlabs\Lib\ActivityStreams::is_url ($url)
Check if string starts with http.
Parameters
string $url
Returns
boolean
Referenced by Zotlabs\Lib\ActivityStreams\get_compound_property().
Zotlabs\Lib\ActivityStreams::is_valid ()
Return if instantiated ActivityStream is valid.
Returns
boolean Return true if the JSON string could be decoded.
Referenced by Zotlabs\Lib\ActivityStreams\__construct().
Zotlabs\Lib\ActivityStreams::set_recips ($arr)
Member Data Documentation
Zotlabs\Lib\ActivityStreams::$actor = null
Zotlabs\Lib\ActivityStreams::$data
Referenced by Zotlabs\Lib\ActivityStreams\__construct(), and Zotlabs\Lib\ActivityStreams\get_primary_type().
Zotlabs\Lib\ActivityStreams::$id = ''
Zotlabs\Lib\ActivityStreams::$ldsig = null
Zotlabs\Lib\ActivityStreams::$obj = null
Zotlabs\Lib\ActivityStreams::$origin = null
Zotlabs\Lib\ActivityStreams::$owner = null
Zotlabs\Lib\ActivityStreams::$raw_recips = null
Zotlabs\Lib\ActivityStreams::$recips = null
Zotlabs\Lib\ActivityStreams::$signer = null
Zotlabs\Lib\ActivityStreams::$sigok = false
Zotlabs\Lib\ActivityStreams::$tgt = null
Zotlabs\Lib\ActivityStreams::$type = ''
Zotlabs\Lib\ActivityStreams::$valid = false
Referenced by Zotlabs\Lib\ActivityStreams\is_valid().
The documentation for this class was generated from the following file:
Zotlabs/Lib/ActivityStreams.php