The Hubzilla: Zotlabs\Lib\ThreadItem Class Reference
Zotlabs\Lib\ThreadItem Class Reference
Public Member Functions
__construct ($data)
get_template_data ($conv_responses, $thread_level=1)
get_id ()
get_display_mode ()
set_display_mode ($mode)
is_threaded ()
set_reload ($val)
get_reload ()
set_commentable ($val)
is_commentable ()
add_child ($item)
get_child ($id)
get_children ()
remove_child ($item)
set_conversation ($conv)
get_conversation ()
get_data ()
get_data_value ($name)
get_template ()
set_template ($t)
Public Attributes
$data = array()
Protected Member Functions
set_parent ($item)
remove_parent ()
get_parent ()
check_wall_to_wall ()
Private Member Functions
is_toplevel ()
count_descendants ()
count_unseen_descendants ()
get_comment_box_template ()
get_comment_box ($indent)
get_redirect_url ()
is_wall_to_wall ()
get_owner_url ()
get_owner_photo ()
get_owner_name ()
is_visiting ()
Private Attributes
$template = 'conv_item.tpl'
$comment_box_template = 'comment_item.tpl'
$commentable = false
$reactions = ['1f60a','1f44f','1f37e','1f48b','1f61e','2665','1f606','1f62e','1f634','1f61c','1f607','1f608']
$toplevel = false
$children = array()
$parent = null
$conversation = null
$redirect_url = null
$owner_url = ''
$owner_photo = ''
$owner_name = ''
$wall_to_wall = false
$threaded = false
$visiting = false
$channel = null
$display_mode = 'normal'
$reload = ''
Detailed Description
A thread item
Constructor & Destructor Documentation
Zotlabs\Lib\ThreadItem::__construct ($data)
Member Function Documentation
Zotlabs\Lib\ThreadItem::add_child ($item)
Add a child item
Referenced by Zotlabs\Lib\ThreadItem\__construct().
Zotlabs\Lib\ThreadItem::check_wall_to_wall () protected
Check if we are a wall to wall item and set the relevant properties
Referenced by Zotlabs\Lib\ThreadItem\get_template_data().
Zotlabs\Lib\ThreadItem::count_descendants () private
Count the total of our descendants
Referenced by Zotlabs\Lib\ThreadItem\get_template_data().
Zotlabs\Lib\ThreadItem::count_unseen_descendants () private
Referenced by Zotlabs\Lib\ThreadItem\get_template_data().
Zotlabs\Lib\ThreadItem::get_child ($id)
Get a child by its ID
Referenced by Zotlabs\Lib\ThreadItem\add_child().
Zotlabs\Lib\ThreadItem::get_children ()
Get all our children
Referenced by Zotlabs\Lib\ThreadItem\count_descendants(), Zotlabs\Lib\ThreadItem\count_unseen_descendants(), Zotlabs\Lib\ThreadItem\get_child(), Zotlabs\Lib\ThreadItem\get_template_data(), Zotlabs\Lib\ThreadItem\remove_child(), Zotlabs\Lib\ThreadItem\set_commentable(), and Zotlabs\Lib\ThreadItem\set_conversation().
Zotlabs\Lib\ThreadItem::get_comment_box ($indent) private
Get the comment box
Returns: _ The comment box string (empty if no comment box) _ false on failure
Referenced by Zotlabs\Lib\ThreadItem\get_template_data().
Zotlabs\Lib\ThreadItem::get_comment_box_template () private
Get the template for the comment box
Referenced by Zotlabs\Lib\ThreadItem\get_comment_box().
Zotlabs\Lib\ThreadItem::get_conversation ()
get conversation
Referenced by Zotlabs\Lib\ThreadItem\check_wall_to_wall(), Zotlabs\Lib\ThreadItem\get_comment_box(), and Zotlabs\Lib\ThreadItem\get_template_data().
Zotlabs\Lib\ThreadItem::get_data ()
Get raw data
We shouldn't need this
Referenced by Zotlabs\Lib\ThreadItem\get_template_data().
Zotlabs\Lib\ThreadItem::get_data_value ($name)
Get a data value
Returns: _ value on success _ false on failure
Referenced by Zotlabs\Lib\ThreadItem\__construct(), Zotlabs\Lib\ThreadItem\check_wall_to_wall(), Zotlabs\Lib\ThreadItem\get_id(), and Zotlabs\Lib\ThreadItem\get_template_data().
Zotlabs\Lib\ThreadItem::get_display_mode ()
Referenced by Zotlabs\Lib\ThreadItem\get_template_data().
Zotlabs\Lib\ThreadItem::get_id ()
Referenced by Zotlabs\Lib\ThreadItem\__construct(), Zotlabs\Lib\ThreadItem\get_comment_box(), and Zotlabs\Lib\ThreadItem\get_template_data().
Zotlabs\Lib\ThreadItem::get_owner_name () private
Referenced by Zotlabs\Lib\ThreadItem\get_template_data().
Zotlabs\Lib\ThreadItem::get_owner_photo () private
Referenced by Zotlabs\Lib\ThreadItem\get_template_data().
Zotlabs\Lib\ThreadItem::get_owner_url () private
Referenced by Zotlabs\Lib\ThreadItem\get_template_data().
Zotlabs\Lib\ThreadItem::get_parent () protected
Get parent item
Referenced by Zotlabs\Lib\ThreadItem\set_parent().
Zotlabs\Lib\ThreadItem::get_redirect_url () private
Zotlabs\Lib\ThreadItem::get_reload ()
Zotlabs\Lib\ThreadItem::get_template ()
Get template
Referenced by Zotlabs\Lib\ThreadItem\get_template_data().
Zotlabs\Lib\ThreadItem::get_template_data ($conv_responses, $thread_level = 1)
Get data in a form usable by a conversation template
Returns: _ The data requested on success _ false on failure
Zotlabs\Lib\ThreadItem::is_commentable ()
Referenced by Zotlabs\Lib\ThreadItem\get_comment_box(), and Zotlabs\Lib\ThreadItem\get_template_data().
Zotlabs\Lib\ThreadItem::is_threaded ()
Referenced by Zotlabs\Lib\ThreadItem\get_comment_box(), and Zotlabs\Lib\ThreadItem\get_template_data().
Zotlabs\Lib\ThreadItem::is_toplevel () private
Check if this is a toplevel post
Referenced by Zotlabs\Lib\ThreadItem\check_wall_to_wall(), Zotlabs\Lib\ThreadItem\get_comment_box(), and Zotlabs\Lib\ThreadItem\get_template_data().
Zotlabs\Lib\ThreadItem::is_visiting () private
Zotlabs\Lib\ThreadItem::is_wall_to_wall () private
Zotlabs\Lib\ThreadItem::remove_child ($item)
Remove a child
Zotlabs\Lib\ThreadItem::remove_parent () protected
Remove our parent
Zotlabs\Lib\ThreadItem::set_commentable ($val)
Zotlabs\Lib\ThreadItem::set_conversation ($conv)
set conversation
Referenced by Zotlabs\Lib\ThreadItem\set_parent().
Zotlabs\Lib\ThreadItem::set_display_mode ($mode)
Zotlabs\Lib\ThreadItem::set_parent ($item) protected
Set our parent
Zotlabs\Lib\ThreadItem::set_reload ($val)
Zotlabs\Lib\ThreadItem::set_template ($t)
Member Data Documentation
Zotlabs\Lib\ThreadItem::$channel = null private
Zotlabs\Lib\ThreadItem::$children = array() private
Referenced by Zotlabs\Lib\ThreadItem\count_descendants(), Zotlabs\Lib\ThreadItem\count_unseen_descendants(), Zotlabs\Lib\ThreadItem\get_children(), and Zotlabs\Lib\ThreadItem\get_template_data().
Zotlabs\Lib\ThreadItem::$comment_box_template = 'comment_item.tpl' private
Referenced by Zotlabs\Lib\ThreadItem\get_comment_box_template().
Zotlabs\Lib\ThreadItem::$commentable = false private
Referenced by Zotlabs\Lib\ThreadItem\is_commentable().
Zotlabs\Lib\ThreadItem::$conversation = null private
Referenced by Zotlabs\Lib\ThreadItem\get_conversation().
Zotlabs\Lib\ThreadItem::$data = array()
Referenced by Zotlabs\Lib\ThreadItem\__construct(), and Zotlabs\Lib\ThreadItem\get_data().
Zotlabs\Lib\ThreadItem::$display_mode = 'normal' private
Referenced by Zotlabs\Lib\ThreadItem\get_display_mode().
Zotlabs\Lib\ThreadItem::$owner_name = '' private
Referenced by Zotlabs\Lib\ThreadItem\get_owner_name().
Zotlabs\Lib\ThreadItem::$owner_photo = '' private
Referenced by Zotlabs\Lib\ThreadItem\get_owner_photo().
Zotlabs\Lib\ThreadItem::$owner_url = '' private
Referenced by Zotlabs\Lib\ThreadItem\get_owner_url().
Zotlabs\Lib\ThreadItem::$parent = null private
Referenced by Zotlabs\Lib\ThreadItem\get_parent(), and Zotlabs\Lib\ThreadItem\set_parent().
Zotlabs\Lib\ThreadItem::$reactions = ['1f60a','1f44f','1f37e','1f48b','1f61e','2665','1f606','1f62e','1f634','1f61c','1f607','1f608'] private
Referenced by Zotlabs\Lib\ThreadItem\get_template_data().
Zotlabs\Lib\ThreadItem::$redirect_url = null private
Referenced by Zotlabs\Lib\ThreadItem\get_redirect_url().
Zotlabs\Lib\ThreadItem::$reload = '' private
Referenced by Zotlabs\Lib\ThreadItem\get_reload().
Zotlabs\Lib\ThreadItem::$template = 'conv_item.tpl' private
Referenced by Zotlabs\Lib\ThreadItem\get_comment_box(), and Zotlabs\Lib\ThreadItem\get_template().
Zotlabs\Lib\ThreadItem::$threaded = false private
Referenced by Zotlabs\Lib\ThreadItem\is_threaded().
Zotlabs\Lib\ThreadItem::$toplevel = false private
Referenced by Zotlabs\Lib\ThreadItem\is_toplevel().
Zotlabs\Lib\ThreadItem::$visiting = false private
Referenced by Zotlabs\Lib\ThreadItem\is_visiting().
Zotlabs\Lib\ThreadItem::$wall_to_wall = false private
Referenced by Zotlabs\Lib\ThreadItem\is_wall_to_wall().
The documentation for this class was generated from the following file:
Zotlabs/Lib/ThreadItem.php