The Hubzilla: Zotlabs\Module\Cover_photo Class Reference
Zotlabs\Module\Cover_photo Class Reference
Public Member Functions
init ()
post ()
Evaluate posted values.
send_cover_photo_activity ($channel, $photo, $profile)
get ()
Generate content of profile-photo view.
cover_photo_crop_ui_head (&$a, $ph, $hash, $smallest)
Public Member Functions inherited from Zotlabs\Web\Controller
init ()
post ()
get ()
Member Function Documentation
Zotlabs\Module\Cover_photo::cover_photo_crop_ui_head (& $a, $ph, $hash, $smallest)
Referenced by Zotlabs\Module\Cover_photo\get(), and Zotlabs\Module\Cover_photo\post().
Zotlabs\Module\Cover_photo::get ()
Generate content of profile-photo view.
Returns
string
Fixme:
yuk
Zotlabs\Module\Cover_photo::init ()
Zotlabs\Module\Cover_photo::post ()
Evaluate posted values.
Returns
void
Zotlabs\Module\Cover_photo::send_cover_photo_activity ($channel, $photo, $profile)
Referenced by Zotlabs\Module\Cover_photo\post().
The documentation for this class was generated from the following file:
Zotlabs/Module/Cover_photo.php