The Hubzilla: Zotlabs\Lib\Apps Class Reference
Zotlabs\Lib\Apps Class Reference
Static Public Member Functions
static get_system_apps ($translate=true)
static import_system_apps ()
static check_install_system_app ($app)
static app_name_compare ($a, $b)
static parse_app_description ($f, $translate=true)
static translate_system_apps (&$arr)
static app_render ($papp, $mode= 'view')
static app_install ($uid, $app)
static app_destroy ($uid, $app)
static app_undestroy ($uid, $app)
static app_feature ($uid, $app, $term)
static app_installed ($uid, $app)
static app_list ($uid, $deleted=false, $cats=[])
static app_order ($uid, $apps)
static find_app_in_array ($name, $arr)
static moveup ($uid, $guid)
static movedown ($uid, $guid)
static app_decode ($s)
static app_store ($arr)
static app_update ($arr)
static app_encode ($app, $embed=false)
static papp_encode ($papp)
Static Public Attributes
static $installed_system_apps = null
Detailed Description
Apps
Member Function Documentation
static Zotlabs\Lib\Apps::app_decode ($s) static
Referenced by Zotlabs\Module\Appman\post().
static Zotlabs\Lib\Apps::app_destroy ($uid, $app) static
Referenced by Zotlabs\Module\Appman\post().
static Zotlabs\Lib\Apps::app_encode ($app, $embed = false) static
Referenced by Zotlabs\Module\Apps\get(), Zotlabs\Module\Apporder\get(), and nav().
static Zotlabs\Lib\Apps::app_feature ($uid, $app, $term) static
Referenced by Zotlabs\Module\Appman\post().
static Zotlabs\Lib\Apps::app_install ($uid, $app) static
Referenced by Zotlabs\Module\Appman\post().
static Zotlabs\Lib\Apps::app_installed ($uid, $app) static
static Zotlabs\Lib\Apps::app_list ($uid, $deleted = false, $cats = []) static
Referenced by Zotlabs\Module\Apps\get(), Zotlabs\Module\Apporder\get(), and nav().
static Zotlabs\Lib\Apps::app_name_compare ($a, $b) static
static Zotlabs\Lib\Apps::app_order ($uid, $apps) static
Referenced by Zotlabs\Module\Apporder\get(), and nav().
static Zotlabs\Lib\Apps::app_render ($papp, $mode = 'view') static
modes: view: normal mode for viewing an app via bbcode from a conversation or page provides install/update button if you're logged in locally list: normal mode for viewing an app on the app page no buttons are shown edit: viewing the app page in editing mode provides a delete button nav: render apps for app-bin
Referenced by Zotlabs\Module\Apps\get(), Zotlabs\Module\Apporder\get(), and nav().
static Zotlabs\Lib\Apps::app_store ($arr) static
static Zotlabs\Lib\Apps::app_undestroy ($uid, $app) static
static Zotlabs\Lib\Apps::app_update ($arr) static
static Zotlabs\Lib\Apps::check_install_system_app ($app) static
Install the system app if no system apps have been installed, or if a new system app is discovered, or if the version of a system app changes.
static Zotlabs\Lib\Apps::find_app_in_array ($name, $arr) static
static Zotlabs\Lib\Apps::get_system_apps ($translate = true) static
Referenced by Zotlabs\Module\Apps\get(), and nav().
static Zotlabs\Lib\Apps::import_system_apps () static
Referenced by Zotlabs\Module\Apps\get(), and nav().
static Zotlabs\Lib\Apps::movedown ($uid, $guid) static
Referenced by Zotlabs\Module\Appman\get().
static Zotlabs\Lib\Apps::moveup ($uid, $guid) static
Referenced by Zotlabs\Module\Appman\get().
static Zotlabs\Lib\Apps::papp_encode ($papp) static
static Zotlabs\Lib\Apps::parse_app_description ($f, $translate = true) static
static Zotlabs\Lib\Apps::translate_system_apps (& $arr) static
Referenced by Zotlabs\Module\Apps\get(), Zotlabs\Module\Apporder\get(), nav(), and nav_set_selected().
Member Data Documentation
Zotlabs\Lib\Apps::$installed_system_apps = null static
The documentation for this class was generated from the following file:
Zotlabs/Lib/Apps.php