The Hubzilla: Zotlabs\Web\HTTPSig Class Reference
Zotlabs\Web\HTTPSig Class Reference
Public Member Functions
get_activitypub_key ($id)
Static Public Member Functions
static generate_digest ($body, $set=true)
static verify ($data, $key= '')
static create_sig ($request, $head, $prvkey, $keyid= 'Key', $send_headers=false, $auth=false, $alg= 'sha256', $crypt_key=null, $crypt_algo= 'aes256ctr')
static sign ($request, $head, $prvkey, $alg= 'sha256')
static parse_sigheader ($header)
static decrypt_sigheader ($header, $prvkey=null)
Detailed Description
Implements HTTP Signatures per draft-cavage-http-signatures-07
Member Function Documentation
static Zotlabs\Web\HTTPSig::create_sig ($request, $head, $prvkey, $keyid = 'Key', $send_headers = false, $auth = false, $alg = 'sha256', $crypt_key = null, $crypt_algo = 'aes256ctr') static
Referenced by Zotlabs\Module\Zfinger\init(), Zotlabs\Module\Magic\init(), Zotlabs\Zot\Finger\run(), and sync_files().
static Zotlabs\Web\HTTPSig::decrypt_sigheader ($header, $prvkey = null) static
static Zotlabs\Web\HTTPSig::generate_digest ($body, $set = true) static
Referenced by Zotlabs\Module\Zfinger\init().
Zotlabs\Web\HTTPSig::get_activitypub_key ($id)
static Zotlabs\Web\HTTPSig::parse_sigheader ($header) static
Referenced by api_login(), Zotlabs\Module\Cdav\init(), Zotlabs\Module\Owa\init(), Zotlabs\Module\Dav\init(), and Zotlabs\Module\Getfile\post().
static Zotlabs\Web\HTTPSig::sign ($request, $head, $prvkey, $alg = 'sha256') static
static Zotlabs\Web\HTTPSig::verify ($data, $key = '') static
Referenced by api_login(), Zotlabs\Module\Cdav\init(), Zotlabs\Module\Owa\init(), Zotlabs\Module\Dav\init(), Zotlabs\Module\Getfile\post(), and Zotlabs\Zot\Finger\run().
The documentation for this class was generated from the following file:
Zotlabs/Web/HTTPSig.php