The Hubzilla: Zotlabs\Zot\Finger Class Reference
Zotlabs\Zot\Finger Class Reference
Finger.
Static Public Member Functions
static run ($webbie, $channel=null, $autofallback=true)
Look up information about channel.
Static Private Attributes
static $token
Detailed Description
Finger.
Member Function Documentation
static Zotlabs\Zot\Finger::run ($webbie, $channel = null, $autofallback = true) static
Look up information about channel.
Parameters
string $webbie does not have to be host qualified e.g. 'foo' is treated as 'foo@thishub'
array $channel (optional), if supplied permissions will be enumerated specifically for $channel
boolean $autofallback fallback/failover to http if https connection cannot be established. Default is true.
Returns
zotinfo array (with 'success' => true) or array('success' => false);
Referenced by check_upstream_directory(), Zotlabs\Module\Chanview\get(), Zotlabs\Module\Probe\get(), Zotlabs\Zot\Auth\GetHublocs(), Zotlabs\Module\Magic\init(), Zotlabs\Module\Regdir\init(), new_contact(), owt_init(), poco_load(), Zotlabs\Module\Mail\post(), and Zotlabs\Daemon\Gprobe\run().
Member Data Documentation
Zotlabs\Zot\Finger::$token static private
The documentation for this class was generated from the following file:
Zotlabs/Zot/Finger.php