The Hubzilla: Zotlabs\Zot\Auth Class Reference
Zotlabs\Zot\Auth Class Reference
Public Member Functions
__construct ($req)
GetHublocs ($address)
Verify ($channel, $hubloc)
Debug ($msg)
Finalise ()
Protected Attributes
$test
$test_results
$debug_msg
$address
$desturl
$sec
$version
$delegate
$success
$delegate_success
$remote
$remote_service_class
$remote_level
$remote_hub
$dnt
Constructor & Destructor Documentation
Zotlabs\Zot\Auth::__construct ($req)
Fixme:
we really want to save the return_url in the session before we visit rmagic. This does however prevent a recursion if you visit rmagic directly, as it would otherwise send you back here again. But z_root() probably isn't where you really want to go.
Member Function Documentation
Zotlabs\Zot\Auth::Debug ($msg)
Referenced by Zotlabs\Zot\Auth\__construct(), Zotlabs\Zot\Auth\GetHublocs(), and Zotlabs\Zot\Auth\Verify().
Zotlabs\Zot\Auth::Finalise ()
Referenced by Zotlabs\Zot\Auth\__construct(), Zotlabs\Zot\Auth\GetHublocs(), and Zotlabs\Zot\Auth\Verify().
Zotlabs\Zot\Auth::GetHublocs ($address)
Referenced by Zotlabs\Zot\Auth\__construct().
Zotlabs\Zot\Auth::Verify ($channel, $hubloc)
Referenced by Zotlabs\Zot\Auth\__construct().
Member Data Documentation
Zotlabs\Zot\Auth::$address protected
Referenced by Zotlabs\Zot\Auth\GetHublocs(), and Zotlabs\Zot\Auth\Verify().
Zotlabs\Zot\Auth::$debug_msg protected
Referenced by Zotlabs\Zot\Auth\Finalise().
Zotlabs\Zot\Auth::$delegate protected
Zotlabs\Zot\Auth::$delegate_success protected
Zotlabs\Zot\Auth::$desturl protected
Zotlabs\Zot\Auth::$dnt protected
Referenced by Zotlabs\Zot\Auth\Verify().
Zotlabs\Zot\Auth::$remote protected
Zotlabs\Zot\Auth::$remote_hub protected
Referenced by Zotlabs\Zot\Auth\Verify().
Zotlabs\Zot\Auth::$remote_level protected
Referenced by Zotlabs\Zot\Auth\Verify().
Zotlabs\Zot\Auth::$remote_service_class protected
Referenced by Zotlabs\Zot\Auth\Verify().
Zotlabs\Zot\Auth::$sec protected
Referenced by Zotlabs\Zot\Auth\Verify().
Zotlabs\Zot\Auth::$success protected
Zotlabs\Zot\Auth::$test protected
Zotlabs\Zot\Auth::$test_results protected
Zotlabs\Zot\Auth::$version protected
The documentation for this class was generated from the following file:
Zotlabs/Zot/Auth.php