The Hubzilla: Zotlabs\Lib\System Class Reference
Zotlabs\Lib\System Class Reference
Static Public Member Functions
static get_platform_name ()
static get_site_name ()
static get_project_version ()
static get_update_version ()
static get_notify_icon ()
static get_site_icon ()
static get_project_link ()
static get_project_srclink ()
static get_server_role ()
static get_zot_revision ()
static get_std_version ()
static compatible_project ($p)
Member Function Documentation
static Zotlabs\Lib\System::compatible_project ($p) static
static Zotlabs\Lib\System::get_notify_icon () static
Referenced by Zotlabs\Lib\Enotify\submit().
static Zotlabs\Lib\System::get_platform_name () static
Referenced by Zotlabs\Lib\DB_Upgrade\__construct(), dba_driver\get_install_script(), get_site_info(), ical_wrapper(), and zot_site_info().
static Zotlabs\Lib\System::get_project_link () static
static Zotlabs\Lib\System::get_project_srclink () static
static Zotlabs\Lib\System::get_project_version () static
Referenced by api_zot_version(), get_site_info(), and zot_site_info().
static Zotlabs\Lib\System::get_server_role () static
Referenced by check_plugin_versions(), get_site_info(), identity_basic_export(), Zotlabs\Render\SmartyTemplate\replace_macros(), and zot_site_info().
static Zotlabs\Lib\System::get_site_icon () static
static Zotlabs\Lib\System::get_site_name () static
Referenced by Zotlabs\Module\Admin\Site\post(), Zotlabs\Lib\Enotify\submit(), and z_mail().
static Zotlabs\Lib\System::get_std_version () static
Referenced by get_site_info().
static Zotlabs\Lib\System::get_update_version () static
static Zotlabs\Lib\System::get_zot_revision () static
Referenced by zot_build_packet(), and zot_site_info().
The documentation for this class was generated from the following file:
Zotlabs/Lib/System.php