The Hubzilla: Zotlabs\Lib\MarkdownSoap Class Reference
Zotlabs\Lib\MarkdownSoap Class Reference
Public Member Functions
__construct ($s)
clean ()
extract_code ($s)
encode_code ($matches)
decode_code ($matches)
putback_code ($s)
purify ($s)
protect_autolinks ($s)
unprotect_autolinks ($s)
escape ($s)
Static Public Member Functions
static unescape ($s)
Private Attributes
$token
$str
Detailed Description
MarkdownSoap Purify Markdown for storage $x = new MarkdownSoap($string_to_be_cleansed); $text = $x->clean();
What this does:
extracts code blocks and privately escapes them from processing
Run html purifier on the content
put back the code blocks
run htmlspecialchars on the entire content for safe storage
At render time: $markdown = ::unescape($text); $html = ::DefaultTransform($markdown);
Constructor & Destructor Documentation
Zotlabs\Lib\MarkdownSoap::__construct ($s)
Member Function Documentation
Zotlabs\Lib\MarkdownSoap::clean ()
Zotlabs\Lib\MarkdownSoap::decode_code ($matches)
Zotlabs\Lib\MarkdownSoap::encode_code ($matches)
Zotlabs\Lib\MarkdownSoap::escape ($s)
Referenced by Zotlabs\Lib\MarkdownSoap\clean().
Zotlabs\Lib\MarkdownSoap::extract_code ($s)
Referenced by Zotlabs\Lib\MarkdownSoap\clean().
Zotlabs\Lib\MarkdownSoap::protect_autolinks ($s)
Referenced by Zotlabs\Lib\MarkdownSoap\purify().
Zotlabs\Lib\MarkdownSoap::purify ($s)
Referenced by Zotlabs\Lib\MarkdownSoap\clean().
Zotlabs\Lib\MarkdownSoap::putback_code ($s)
Referenced by Zotlabs\Lib\MarkdownSoap\clean().
static Zotlabs\Lib\MarkdownSoap::unescape ($s) static
Referenced by Zotlabs\Module\Editblock\get(), Zotlabs\Module\Editwebpage\get(), Zotlabs\Module\Wiki\get(), get_item_elements(), Zotlabs\Module\Wiki\post(), and prepare_text().
Zotlabs\Lib\MarkdownSoap::unprotect_autolinks ($s)
Referenced by Zotlabs\Lib\MarkdownSoap\purify().
Member Data Documentation
Zotlabs\Lib\MarkdownSoap::$str private
Zotlabs\Lib\MarkdownSoap::$token private
The documentation for this class was generated from the following file:
Zotlabs/Lib/MarkdownSoap.php