The Hubzilla: Zotlabs\Lib\IConfig Class Reference
Zotlabs\Lib\IConfig Class Reference
Static Public Member Functions
static Load (&$item)
static Get (&$item, $family, $key, $default=false)
static Set (&$item, $family, $key, $value, $sharing=false)
static Delete (&$item, $family, $key)
Member Function Documentation
static Zotlabs\Lib\IConfig::Delete (& $item, $family, $key) static
Referenced by del_iconfig().
static Zotlabs\Lib\IConfig::Get (& $item, $family, $key, $default = false) static
Referenced by get_iconfig().
static Zotlabs\Lib\IConfig::Load (& $item) static
Referenced by load_iconfig().
static Zotlabs\Lib\IConfig::Set (& $item, $family, $key, $value, $sharing = false) static
IConfig::Set(&$item, $family, $key, $value, $sharing = false);
$item - item array or item id. If passed an array the iconfig meta information is added to the item structure (which will need to be saved with item_store eventually). If passed an id, the DB is updated, but may not be federated and/or cloned. $family - namespace of meta variable $key - key of meta variable $value - value of meta variable $sharing - boolean (default false); if true the meta information is propagated with the item to other sites/channels, mostly useful when $item is an array and has not yet been stored/delivered. If the meta information is added after delivery and you wish it to be shared, it may be necessary to alter the item edited timestamp and invoke the delivery process on the updated item. The edited timestamp needs to be altered in order to trigger an item_store_update() at the receiving end.
Referenced by Zotlabs\Module\Impel\init(), Zotlabs\Module\Item\post(), set_iconfig(), store_doc_file(), update_r1176(), and update_remote_id().
The documentation for this class was generated from the following file:
Zotlabs/Lib/IConfig.php