The Hubzilla: Zotlabs\Lib\NativeWiki Class Reference
Zotlabs\Lib\NativeWiki Class Reference
Public Member Functions
create_wiki ($channel, $observer_hash, $wiki, $acl)
update_wiki ($channel_id, $observer_hash, $arr, $acl)
delete_wiki ($channel_id, $observer_hash, $resource_id)
Static Public Member Functions
static listwikis ($channel, $observer_hash)
static sync_a_wiki_item ($uid, $id, $resource_id)
static get_wiki ($channel_id, $observer_hash, $resource_id)
static exists_by_name ($uid, $urlName)
static get_permissions ($resource_id, $owner_id, $observer_hash)
Member Function Documentation
Zotlabs\Lib\NativeWiki::create_wiki ($channel, $observer_hash, $wiki, $acl)
Referenced by Zotlabs\Module\Wiki\post().
Zotlabs\Lib\NativeWiki::delete_wiki ($channel_id, $observer_hash, $resource_id)
Referenced by Zotlabs\Module\Wiki\post().
static Zotlabs\Lib\NativeWiki::exists_by_name ($uid, $urlName) static
Referenced by Zotlabs\Widget\Wiki_pages\create_missing_page(), Zotlabs\Module\Wiki\get(), Zotlabs\Module\Wiki\post(), and Zotlabs\Widget\Wiki_pages\widget().
static Zotlabs\Lib\NativeWiki::get_permissions ($resource_id, $owner_id, $observer_hash) static
Referenced by Zotlabs\Module\Wiki\get(), and Zotlabs\Module\Wiki\post().
static Zotlabs\Lib\NativeWiki::get_wiki ($channel_id, $observer_hash, $resource_id) static
Referenced by Zotlabs\Lib\NativeWikiPage\commit(), Zotlabs\Lib\NativeWikiPage\compare_page(), Zotlabs\Lib\NativeWikiPage\create_page(), Zotlabs\Lib\NativeWikiPage\delete_page(), Zotlabs\Module\Wiki\get(), Zotlabs\Lib\NativeWikiPage\get_page_content(), Zotlabs\Lib\NativeWikiPage\load_page(), Zotlabs\Lib\NativeWikiPage\load_page_history(), Zotlabs\Lib\NativeWikiPage\page_history(), Zotlabs\Lib\NativeWikiPage\page_list(), Zotlabs\Module\Wiki\post(), Zotlabs\Lib\NativeWikiPage\rename_page(), Zotlabs\Lib\NativeWikiPage\revert_page(), and Zotlabs\Lib\NativeWikiPage\save_page().
static Zotlabs\Lib\NativeWiki::listwikis ($channel, $observer_hash) static
Referenced by Zotlabs\Module\Wiki\get(), and Zotlabs\Widget\Wiki_list\widget().
static Zotlabs\Lib\NativeWiki::sync_a_wiki_item ($uid, $id, $resource_id) static
Referenced by Zotlabs\Module\Wiki\post().
Zotlabs\Lib\NativeWiki::update_wiki ($channel_id, $observer_hash, $arr, $acl)
Referenced by Zotlabs\Module\Wiki\post().
The documentation for this class was generated from the following file:
Zotlabs/Lib/NativeWiki.php