The Hubzilla: Zotlabs\Lib\Permcat Class Reference
Zotlabs\Lib\Permcat Class Reference
Public Member Functions
__construct ($channel_id)
listing ()
fetch ($name)
load_permcats ($uid)
Static Public Member Functions
static find_permcat ($arr, $name)
static update ($channel_id, $name, $permarr)
static delete ($channel_id, $name)
Private Attributes
$permcats = []
Constructor & Destructor Documentation
Zotlabs\Lib\Permcat::__construct ($channel_id)
Member Function Documentation
static Zotlabs\Lib\Permcat::delete ($channel_id, $name) static
Referenced by Zotlabs\Module\Settings\Permcats\get().
Zotlabs\Lib\Permcat::fetch ($name)
static Zotlabs\Lib\Permcat::find_permcat ($arr, $name) static
Referenced by Zotlabs\Module\Settings\Permcats\get().
Zotlabs\Lib\Permcat::listing ()
Zotlabs\Lib\Permcat::load_permcats ($uid)
Referenced by Zotlabs\Lib\Permcat\__construct().
static Zotlabs\Lib\Permcat::update ($channel_id, $name, $permarr) static
Referenced by Zotlabs\Module\Settings\Permcats\post().
Member Data Documentation
Zotlabs\Lib\Permcat::$permcats = [] private
Referenced by Zotlabs\Lib\Permcat\listing(), and Zotlabs\Lib\Permcat\load_permcats().
The documentation for this class was generated from the following file:
Zotlabs/Lib/Permcat.php