The Hubzilla: Zotlabs\Lib\NativeWikiPage Class Reference
Zotlabs\Lib\NativeWikiPage Class Reference
Static Public Member Functions
static page_list ($channel_id, $observer_hash, $resource_id)
static create_page ($channel_id, $observer_hash, $name, $resource_id, $mimetype= 'text/bbcode')
static rename_page ($arr)
static get_page_content ($arr)
static page_history ($arr)
static load_page ($arr)
static load_page_history ($arr)
static save_page ($arr)
static delete_page ($arr)
static revert_page ($arr)
static compare_page ($arr)
static commit ($arr)
static convert_links ($s, $wikiURL)
static render_page_history ($arr)
static generate_toc ($s)
static bbcode ($s)
static get_file_ext ($arr)
static toc ($content)
Member Function Documentation
static Zotlabs\Lib\NativeWikiPage::bbcode ($s) static
Converts a select set of bbcode tags. Much of the code is copied from include/bbcode.php
Parameters
string $s
Returns
string
Referenced by Zotlabs\Module\Wiki\post().
static Zotlabs\Lib\NativeWikiPage::commit ($arr) static
Referenced by Zotlabs\Module\Wiki\post().
static Zotlabs\Lib\NativeWikiPage::compare_page ($arr) static
Referenced by Zotlabs\Module\Wiki\post().
static Zotlabs\Lib\NativeWikiPage::convert_links ($s, $wikiURL) static
Referenced by Zotlabs\Module\Wiki\get(), and Zotlabs\Module\Wiki\post().
static Zotlabs\Lib\NativeWikiPage::create_page ($channel_id, $observer_hash, $name, $resource_id, $mimetype = 'text/bbcode') static
Referenced by Zotlabs\Module\Wiki\post().
static Zotlabs\Lib\NativeWikiPage::delete_page ($arr) static
Referenced by Zotlabs\Module\Wiki\post().
static Zotlabs\Lib\NativeWikiPage::generate_toc ($s) static
Replace the instances of the string [toc] with a list element that will be populated by a table of contents by the JavaScript library
Parameters
string $s
Returns
string
Referenced by Zotlabs\Module\Wiki\get(), and Zotlabs\Module\Wiki\post().
static Zotlabs\Lib\NativeWikiPage::get_file_ext ($arr) static
Referenced by Zotlabs\Module\Wiki\get().
static Zotlabs\Lib\NativeWikiPage::get_page_content ($arr) static
Referenced by Zotlabs\Module\Wiki\get().
static Zotlabs\Lib\NativeWikiPage::load_page ($arr) static
static Zotlabs\Lib\NativeWikiPage::load_page_history ($arr) static
static Zotlabs\Lib\NativeWikiPage::page_history ($arr) static
Referenced by Zotlabs\Widget\Wiki_page_history\widget().
static Zotlabs\Lib\NativeWikiPage::page_list ($channel_id, $observer_hash, $resource_id) static
Referenced by Zotlabs\Widget\Wiki_pages\widget().
static Zotlabs\Lib\NativeWikiPage::rename_page ($arr) static
Referenced by Zotlabs\Module\Wiki\post().
static Zotlabs\Lib\NativeWikiPage::render_page_history ($arr) static
Referenced by Zotlabs\Module\Wiki\post().
static Zotlabs\Lib\NativeWikiPage::revert_page ($arr) static
Referenced by Zotlabs\Module\Wiki\post().
static Zotlabs\Lib\NativeWikiPage::save_page ($arr) static
Referenced by Zotlabs\Module\Wiki\post().
static Zotlabs\Lib\NativeWikiPage::toc ($content) static
The documentation for this class was generated from the following file:
Zotlabs/Lib/NativeWikiPage.php