The Hubzilla: Zotlabs\Access\PermissionLimits Class Reference
Zotlabs\Access\PermissionLimits Class Reference
Static Public Member Functions
static Std_Limits ()
static Set ($channel_id, $perm, $perm_limit)
static Get ($channel_id, $perm= '')
Member Function Documentation
static Zotlabs\Access\PermissionLimits::Get ($channel_id, $perm = '') static
Referenced by encode_item(), Zotlabs\Lib\PermissionDescription\fromGlobalPermission(), Zotlabs\Module\Settings\Permcats\get(), Zotlabs\Module\Settings\Tokens\get(), Zotlabs\Module\Defperms\get(), Zotlabs\Module\Settings\Channel\get(), Zotlabs\Module\Connedit\get(), get_all_perms(), is_public_profile(), perm_is_allowed(), Zotlabs\Module\Item\post(), and Zotlabs\Module\Defperms\post().
static Zotlabs\Access\PermissionLimits::Set ($channel_id, $perm, $perm_limit) static
Referenced by check_for_new_perms(), create_identity(), Zotlabs\Access\PermissionRoles\new_custom_perms(), and Zotlabs\Module\Settings\Channel\post().
static Zotlabs\Access\PermissionLimits::Std_Limits () static
Referenced by Zotlabs\Access\PermissionRoles\role_perms().
The documentation for this class was generated from the following file:
Zotlabs/Access/PermissionLimits.php