The Hubzilla: Zotlabs\Module\Setup Class Reference
Zotlabs\Module\Setup Class Reference
Initialisation for the setup module.
Public Member Functions
init ()
post ()
Handle the actions of the different setup steps.
get ()
Get output for the setup page.
check_add (&$checks, $title, $status, $required, $help= '')
Add a check result to the array for output.
check_php (&$phpath, &$checks)
Checks the PHP environment.
check_phpconfig (&$checks)
Some PHP configuration checks.
check_keys (&$checks)
Check if the openssl implementation can generate keys.
check_funcs (&$checks)
Check for some PHP functions and modules.
check_htconfig (&$checks)
Check for .htconfig requirements.
check_smarty3 (&$checks)
Checks for our templating engine Smarty3 requirements.
check_store (&$checks)
Check for store directory.
check_htaccess (&$checks)
Check URL rewrite und SSL certificate.
manual_config (&$a)
load_database_rem ($v, $i)
load_database ($db)
what_next ()
Public Member Functions inherited from Zotlabs\Web\Controller
init ()
post ()
get ()
Static Private Member Functions
static check_passed ($v, $c)
Static Private Attributes
static $install_wizard_pass = 1
Detailed Description
Initialisation for the setup module.
Member Function Documentation
Zotlabs\Module\Setup::check_add (& $checks, $title, $status, $required, $help = '')
Add a check result to the array for output.
Parameters
[in,out] array &$checks array passed to template
string $title a title for the check
boolean $status
boolean $required
string $help optional help string
Referenced by Zotlabs\Module\Setup\check_funcs(), Zotlabs\Module\Setup\check_htaccess(), Zotlabs\Module\Setup\check_htconfig(), Zotlabs\Module\Setup\check_keys(), Zotlabs\Module\Setup\check_php(), Zotlabs\Module\Setup\check_phpconfig(), Zotlabs\Module\Setup\check_smarty3(), and Zotlabs\Module\Setup\check_store().
Zotlabs\Module\Setup::check_funcs (& $checks)
Check for some PHP functions and modules.
Parameters
[in,out] array &$checks
Referenced by Zotlabs\Module\Setup\get().
Zotlabs\Module\Setup::check_htaccess (& $checks)
Check URL rewrite und SSL certificate.
Parameters
[out] array &$checks
Referenced by Zotlabs\Module\Setup\get().
Zotlabs\Module\Setup::check_htconfig (& $checks)
Check for .htconfig requirements.
Parameters
[out] array &$checks
Referenced by Zotlabs\Module\Setup\get().
Zotlabs\Module\Setup::check_keys (& $checks)
Check if the openssl implementation can generate keys.
Parameters
[out] array $checks
Referenced by Zotlabs\Module\Setup\get().
static Zotlabs\Module\Setup::check_passed ($v, $c) static private
Parameters
unknown $v
array $c
Returns
array
Zotlabs\Module\Setup::check_php (& $phpath, & $checks)
Checks the PHP environment.
Parameters
[in,out] string &$phpath
[out] array &$checks
Referenced by Zotlabs\Module\Setup\get().
Zotlabs\Module\Setup::check_phpconfig (& $checks)
Some PHP configuration checks.
Todo:
Change how we display such informational text. Add more description how to change them.
Parameters
[out] array &$checks
Referenced by Zotlabs\Module\Setup\get().
Zotlabs\Module\Setup::check_smarty3 (& $checks)
Checks for our templating engine Smarty3 requirements.
Parameters
[out] array &$checks
Referenced by Zotlabs\Module\Setup\get().
Zotlabs\Module\Setup::check_store (& $checks)
Check for store directory.
Parameters
[out] array &$checks
Referenced by Zotlabs\Module\Setup\get().
Zotlabs\Module\Setup::get ()
Get output for the setup page.
Depending on the state we are currently in it returns different content.
Returns
string parsed HTML output
Zotlabs\Module\Setup::init ()
See Also
\Zotlabs\Web\Controller::init()
Zotlabs\Module\Setup::load_database ($db)
Referenced by Zotlabs\Module\Setup\post().
Zotlabs\Module\Setup::load_database_rem ($v, $i)
Zotlabs\Module\Setup::manual_config (& $a)
Parameters
App &$a
Returns
string with paresed HTML
Referenced by Zotlabs\Module\Setup\get().
Zotlabs\Module\Setup::post ()
Handle the actions of the different setup steps.
Zotlabs\Module\Setup::what_next ()
Returns
string with parsed HTML
Referenced by Zotlabs\Module\Setup\get().
Member Data Documentation
Zotlabs\Module\Setup::$install_wizard_pass = 1 static private
The documentation for this class was generated from the following file:
Zotlabs/Module/Setup.php