The Hubzilla: Zotlabs\Daemon\Master Class Reference
Zotlabs\Daemon\Master Class Reference
Static Public Member Functions
static Summon ($arr)
static Release ($argc, $argv)
Member Function Documentation
static Zotlabs\Daemon\Master::Release ($argc, $argv) static
static Zotlabs\Daemon\Master::Summon ($arr) static
Referenced by attach_store(), build_sync_packet(), change_channel_keys(), channel_change_address(), channel_remove(), check_cron_broken(), consume_feed(), create_identity(), Zotlabs\Lib\NativeWiki\create_wiki(), do_delivery(), drop_item(), drop_items(), fix_system_urls(), Zotlabs\Module\Dreport\get(), Zotlabs\Module\React\get(), Zotlabs\Module\Moderate\get(), Zotlabs\Module\Like\get(), Zotlabs\Module\Admin\Channels\get(), Zotlabs\Module\Locs\get(), Zotlabs\Module\Mail\get(), Zotlabs\Module\Profile_photo\get(), Zotlabs\Module\Connedit\get(), Zotlabs\Module\Import\import_account(), import_items(), import_mail(), Zotlabs\Module\Follow\init(), Zotlabs\Module\Mood\init(), item_create_edit_activity(), new_contact(), photo_upload(), poller_run(), Zotlabs\Module\Locs\post(), Zotlabs\Module\Settings\Channel\post(), Zotlabs\Module\Events\post(), Zotlabs\Module\Admin\Channels\post(), Zotlabs\Module\Prate\post(), Zotlabs\Module\Item\post(), Zotlabs\Module\Connect\post(), Zotlabs\Module\Rate\post(), Zotlabs\Module\Profile_photo\post(), Zotlabs\Module\Connedit\post(), Zotlabs\Module\Profiles\post(), post_activity_item(), proc_run(), process_delivery(), profile_activity(), remove_obsolete_hublocs(), Zotlabs\Daemon\Poller\run(), Zotlabs\Daemon\Cron_daily\run(), Zotlabs\Daemon\Cron\run(), Zotlabs\Daemon\Cron_weekly\run(), Zotlabs\Daemon\Ratenotif\run(), Zotlabs\Daemon\Directory\run(), Zotlabs\Daemon\Notifier\run(), send_message(), Zotlabs\Lib\SuperCurl\set(), start_delivery_chain(), sync_files(), tag_deliver(), zid_init(), zot_refresh(), and zot_reply_message_request().
The documentation for this class was generated from the following file:
Zotlabs/Daemon/Master.php