The Hubzilla: include/connections.php File Reference
connections.php File Reference
Functions
abook_store_lowlevel ($arr)
rconnect_url ($channel_id, $xchan)
abook_connections ($channel_id, $sql_conditions= '')
abook_self ($channel_id)
vcard_from_xchan ($xchan, $observer=null, $mode= '')
abook_toggle_flag ($abook, $flag)
mark_orphan_hubsxchans ()
remove_all_xchan_resources ($xchan, $channel_id=0)
contact_remove ($channel_id, $abook_id)
random_profile ()
update_vcard ($arr, $vcard=null)
get_vcard_array ($vc, $id)
vcard_translate_type ($type)
vcard_query (&$r)
Function Documentation
abook_connections ($channel_id, $sql_conditions = '')
abook_self ($channel_id)
Referenced by Zotlabs\Module\Photos\post().
abook_store_lowlevel ($arr)
Referenced by create_identity(), Zotlabs\Module\Import\import_account(), new_contact(), process_channel_sync_delivery(), and zot_refresh().
abook_toggle_flag ($abook, $flag)
Referenced by Zotlabs\Module\Connedit\get().
contact_remove ($channel_id, $abook_id)
Referenced by Zotlabs\Module\Connedit\get(), process_channel_sync_delivery(), and zot_reply_purge().
get_vcard_array ($vc, $id)
Referenced by Zotlabs\Module\Connedit\get(), Zotlabs\Module\Profiles\get(), and vcard_query().
mark_orphan_hubsxchans ()
mark any hubs "offline" that haven't been heard from in more than 30 days Allow them to redeem themselves if they come back later. Then go through all those that are newly marked and see if any other hubs are attached to the controlling xchan that are still alive. If not, they're dead (although they could come back some day).
Referenced by Zotlabs\Daemon\Cron_weekly\run().
random_profile ()
Referenced by Zotlabs\Module\Randprof\init().
rconnect_url ($channel_id, $xchan)
Referenced by profile_sidebar().
remove_all_xchan_resources ($xchan, $channel_id = 0)
Referenced by zot_reply_purge().
update_vcard ($arr, $vcard = null)
Referenced by Zotlabs\Module\Connedit\post(), and Zotlabs\Module\Profiles\post().
vcard_from_xchan ($xchan, $observer = null, $mode = '')
Referenced by Zotlabs\Widget\Vcard\widget().
vcard_query (& $r)
Referenced by Zotlabs\Module\Connections\get().
vcard_translate_type ($type)
Referenced by get_vcard_array().