The Hubzilla: include/conversation.php File Reference
conversation.php File Reference
Functions
item_extract_images ($body)
item_redir_and_replace_images ($body, $images, $cid)
localize_item (&$item)
count_descendants ($item)
Count the total of comments on this item and its desendants.
visible_activity ($item)
Check if the activity of the item is visible.
is_edit_activity ($item)
Check if a given activity is an edit activity.
conversation ($items, $mode, $update, $page_mode= 'traditional', $prepared_item= '')
"Render" a conversation or list of items for HTML display.
best_link_url ($item)
thread_action_menu ($item, $mode= '')
author_is_pmable ($xchan, $abook)
thread_author_menu ($item, $mode= '')
builtin_activity_puller ($item, &$conv_responses)
Checks item to see if it is one of the builtin activities (like/dislike, event attendance, consensus items, etc.)
format_like ($cnt, $arr, $type, $id)
Format the like/dislike text for a profile item.
status_editor ($a, $x, $popup=false)
get_item_children ($arr, $parent)
sort_item_children ($items)
add_children_to_list ($children, &$arr)
conv_sort ($arr, $order)
sort_thr_created ($a, $b)
sort_thr_created_rev ($a, $b)
sort_thr_commented ($a, $b)
sort_thr_updated ($a, $b)
find_thread_parent_index ($arr, $x)
format_location ($item)
render_location_default ($item)
prepare_page ($item)
network_tabs ()
profile_tabs ($a, $is_owner=false, $nickname=null)
get_responses ($conv_responses, $response_verbs, $ob, $item)
get_response_button_text ($v, $count)
Function Documentation
add_children_to_list ($children, & $arr)
author_is_pmable ($xchan, $abook)
Referenced by thread_author_menu().
best_link_url ($item)
Referenced by conversation().
builtin_activity_puller ($item, & $conv_responses)
Checks item to see if it is one of the builtin activities (like/dislike, event attendance, consensus items, etc.)
Increments the count of each matching activity and adds a link to the author as needed.
Parameters
array $item
array &$conv_responses (already created with builtin activity structure)
Referenced by conversation().
conv_sort ($arr, $order)
Referenced by Zotlabs\Module\Pubstream\get(), Zotlabs\Module\Display\get(), Zotlabs\Module\Cards\get(), Zotlabs\Module\Articles\get(), Zotlabs\Module\Network\get(), Zotlabs\Module\Hq\get(), Zotlabs\Module\Channel\get(), items_fetch(), and zot_feed().
conversation ($items, $mode, $update, $page_mode = 'traditional', $prepared_item = '')
"Render" a conversation or list of items for HTML display.
There are two major forms of display:
Sequential or unthreaded ("New Item View" or search results)
conversation view
The $mode parameter decides between the various renderings and also figures out how to determine page owner and other contextual items that are based on unique features of the calling module.
Parameters
array $items
string $mode
boolean $update
string $page_mode default traditional
string $prepared_item
Returns
string
Referenced by Zotlabs\Module\Pubstream\get(), Zotlabs\Module\Moderate\get(), Zotlabs\Module\Display\get(), Zotlabs\Module\Search\get(), Zotlabs\Module\Cards\get(), Zotlabs\Module\Articles\get(), Zotlabs\Module\Network\get(), Zotlabs\Module\Hq\get(), Zotlabs\Module\Channel\get(), Zotlabs\Module\Item\post(), Zotlabs\Lib\ThreadItem\remove_parent(), and Zotlabs\Lib\ThreadItem\set_conversation().
count_descendants ($item)
Count the total of comments on this item and its desendants.
Parameters
array $item an assoziative item-array which provides:
array children
Returns
number
find_thread_parent_index ($arr, $x)
format_like ($cnt, $arr, $type, $id)
Format the like/dislike text for a profile item.
Parameters
int $cnt number of people who like/dislike the item
array $arr array of pre-linked names of likers/dislikers
string $type one of 'like, 'dislike'
int $id item id
Returns
string formatted text
Referenced by Zotlabs\Lib\ThreadItem\get_template_data().
format_location ($item)
Referenced by conversation(), and Zotlabs\Lib\ThreadItem\get_template_data().
get_item_children ($arr, $parent)
get_response_button_text ($v, $count)
Referenced by get_responses().
get_responses ($conv_responses, $response_verbs, $ob, $item)
Referenced by Zotlabs\Lib\ThreadItem\get_template_data().
is_edit_activity ($item)
Check if a given activity is an edit activity.
Parameters
array $item
Returns
boolean
Referenced by visible_activity().
item_extract_images ($body)
item_redir_and_replace_images ($body, $images, $cid)
localize_item (& $item)
Render actions localized
Fixme:
for obscured private posts, until then leave untranslated
Referenced by conversation(), Zotlabs\Lib\Enotify\format(), Zotlabs\Lib\ThreadItem\get_template_data(), and Zotlabs\Lib\Enotify\submit().
network_tabs ()
Referenced by Zotlabs\Module\Network\get().
prepare_page ($item)
Referenced by Zotlabs\Module\Block\get(), Zotlabs\Module\Page\get(), and Zotlabs\Widget\Item\widget().
profile_tabs ($a, $is_owner = false, $nickname = null)
Parameters
App $a
boolean $is_owner default false
string $nickname default null
Returns
void|string
render_location_default ($item)
sort_item_children ($items)
sort_thr_commented ($a, $b)
sort_thr_created ($a, $b)
sort_thr_created_rev ($a, $b)
sort_thr_updated ($a, $b)
status_editor ($a, $x, $popup = false)
This is our general purpose content editor. It was once nicknamed "jot" and you may see references to "jot" littered throughout the code. They are referring to the content editor or components thereof.
Referenced by Zotlabs\Module\Pubstream\get(), Zotlabs\Module\Card_edit\get(), Zotlabs\Module\Article_edit\get(), Zotlabs\Module\Editpost\get(), Zotlabs\Module\Display\get(), Zotlabs\Module\Articles\get(), Zotlabs\Module\Cards\get(), Zotlabs\Module\Editblock\get(), Zotlabs\Module\Editlayout\get(), Zotlabs\Module\Layouts\get(), Zotlabs\Module\Editwebpage\get(), Zotlabs\Module\Webpages\get(), Zotlabs\Module\Blocks\get(), Zotlabs\Module\Network\get(), Zotlabs\Module\Hq\get(), Zotlabs\Module\Rpost\get(), and Zotlabs\Module\Channel\get().
thread_action_menu ($item, $mode = '')
Referenced by conversation(), and Zotlabs\Lib\ThreadItem\get_template_data().
thread_author_menu ($item, $mode = '')
Referenced by conversation(), and Zotlabs\Lib\ThreadItem\get_template_data().
visible_activity ($item)
Check if the activity of the item is visible.
likes (etc.) can apply to other things besides posts. Check if they are post children, in which case we handle them specially. Activities which are unrecognised as having special meaning and hidden will be treated as posts or comments and visible in the stream.
Parameters
array $item
Returns
boolean
Referenced by Zotlabs\Lib\ThreadItem\__construct(), conversation(), count_descendants(), Zotlabs\Lib\ThreadItem\count_unseen_descendants(), and Zotlabs\Lib\Enotify\submit().