The Hubzilla: include/crypto.php File Reference
crypto.php File Reference
Functions
rsa_sign ($data, $key, $alg= 'sha256')
rsa_verify ($data, $sig, $key, $alg= 'sha256')
pkcs5_pad ($text, $blocksize)
pkcs5_unpad ($text)
AES256CBC_encrypt ($data, $key, $iv)
AES256CBC_decrypt ($data, $key, $iv)
AES128CBC_encrypt ($data, $key, $iv)
AES128CBC_decrypt ($data, $key, $iv)
AES256CTR_encrypt ($data, $key, $iv)
AES256CTR_decrypt ($data, $key, $iv)
CAMELLIA256CFB_encrypt ($data, $key, $iv)
CAMELLIA256CFB_decrypt ($data, $key, $iv)
CAST5CBC_encrypt ($data, $key, $iv)
CAST5CBC_decrypt ($data, $key, $iv)
CAST5CFB_encrypt ($data, $key, $iv)
CAST5CFB_decrypt ($data, $key, $iv)
crypto_encapsulate ($data, $pubkey, $alg='aes256cbc')
other_encapsulate ($data, $pubkey, $alg)
crypto_methods ()
signing_methods ()
aes_encapsulate ($data, $pubkey)
crypto_unencapsulate ($data, $prvkey)
other_unencapsulate ($data, $prvkey, $alg)
aes_unencapsulate ($data, $prvkey)
new_keypair ($bits)
pkcs1to8 ($oldkey, $len)
pkcs8to1 ($oldkey, $len)
DerToPem ($Der, $Private=false)
DerToRsa ($Der)
pkcs8_encode ($Modulus, $PublicExponent)
pkcs1_encode ($Modulus, $PublicExponent)
metopem ($m, $e)
pubrsatome ($key, &$m, &$e)
rsatopem ($key)
pemtorsa ($key)
pemtome ($key, &$m, &$e)
metorsa ($m, $e)
salmon_key ($pubkey)
convert_salmon_key ($key)
z_obscure ($s)
z_unobscure ($s)
Function Documentation
AES128CBC_decrypt ($data, $key, $iv)
AES128CBC_encrypt ($data, $key, $iv)
AES256CBC_decrypt ($data, $key, $iv)
Referenced by aes_unencapsulate().
AES256CBC_encrypt ($data, $key, $iv)
Referenced by aes_encapsulate().
AES256CTR_decrypt ($data, $key, $iv)
AES256CTR_encrypt ($data, $key, $iv)
aes_encapsulate ($data, $pubkey)
Referenced by crypto_encapsulate().
aes_unencapsulate ($data, $prvkey)
Referenced by crypto_unencapsulate().
CAMELLIA256CFB_decrypt ($data, $key, $iv)
CAMELLIA256CFB_encrypt ($data, $key, $iv)
CAST5CBC_decrypt ($data, $key, $iv)
CAST5CBC_encrypt ($data, $key, $iv)
CAST5CFB_decrypt ($data, $key, $iv)
CAST5CFB_encrypt ($data, $key, $iv)
convert_salmon_key ($key)
crypto_encapsulate ($data, $pubkey, $alg = 'aes256cbc')
Referenced by Zotlabs\Web\HTTPSig\create_sig(), z_obscure(), zot_build_packet(), zot_fetch(), zot_reply_pickup(), and zotinfo().
crypto_methods ()
Referenced by zot_best_algorithm(), zot_build_packet(), and zot_site_info().
crypto_unencapsulate ($data, $prvkey)
Referenced by Zotlabs\Zot\Receiver\__construct(), Zotlabs\Web\HTTPSig\decrypt_sigheader(), Zotlabs\Module\Probe\get(), new_contact(), Zotlabs\Module\Mail\post(), z_unobscure(), zot_import(), zot_process_response(), and zot_refresh().
DerToPem ($Der, $Private = false)
Referenced by metopem().
DerToRsa ($Der)
Referenced by metorsa().
metopem ($m, $e)
Referenced by convert_salmon_key(), and rsatopem().
metorsa ($m, $e)
Referenced by pemtorsa().
new_keypair ($bits)
Referenced by change_channel_keys(), create_account(), create_identity(), and create_sys_channel().
other_encapsulate ($data, $pubkey, $alg)
Referenced by crypto_encapsulate().
other_unencapsulate ($data, $prvkey, $alg)
Referenced by crypto_unencapsulate().
pemtome ($key, & $m, & $e)
Referenced by pemtorsa(), and salmon_key().
pemtorsa ($key)
pkcs1_encode ($Modulus, $PublicExponent)
Referenced by metorsa().
pkcs1to8 ($oldkey, $len)
pkcs5_pad ($text, $blocksize)
pkcs5_unpad ($text)
pkcs8_encode ($Modulus, $PublicExponent)
Referenced by metopem().
pkcs8to1 ($oldkey, $len)
pubrsatome ($key, & $m, & $e)
Referenced by rsatopem().
rsa_sign ($data, $key, $alg = 'sha256')
Referenced by change_channel_keys(), check_zotinfo(), create_identity(), fix_system_urls(), Zotlabs\Module\Fhublocs\get(), Zotlabs\Module\Import\import_account(), item_sign(), item_url_replace(), Zotlabs\Module\Prate\post(), Zotlabs\Module\Rate\post(), Zotlabs\Module\Connedit\post(), process_channel_sync_delivery(), Zotlabs\Lib\LDSignatures\salmon_sign(), Zotlabs\Lib\JSalmon\sign(), Zotlabs\Lib\LDSignatures\sign(), Zotlabs\Web\HTTPSig\sign(), sync_files(), zot_build_packet(), zot_fetch(), zot_reply_auth_check(), zot_reply_ping(), zot_site_info(), and zotinfo().
rsa_verify ($data, $sig, $key, $alg = 'sha256')
Referenced by check_zotinfo(), get_item_elements(), import_site(), import_xchan(), Zotlabs\Module\Getfile\post(), process_channel_sync_delivery(), process_rating_delivery(), Zotlabs\Zot\Finger\run(), sync_directories(), sync_locations(), Zotlabs\Lib\LDSignatures\verify(), Zotlabs\Web\HTTPSig\verify(), Zotlabs\Zot\Auth\Verify(), xchan_store(), zot_refresh(), zot_register_hub(), zot_rekey_request(), zot_reply_auth_check(), zot_reply_pickup(), and zotinfo().
rsatopem ($key)
salmon_key ($pubkey)
Referenced by Zotlabs\Module\Wfinger\init(), and Zotlabs\Module\Xrd\init().
signing_methods ()
Referenced by zot_build_packet(), and zot_site_info().
z_obscure ($s)
Referenced by Zotlabs\Module\Pconfig\post().
z_unobscure ($s)
Referenced by Zotlabs\Module\Pconfig\pconfig_form().