The Hubzilla: include/dba/dba_driver.php File Reference
dba_driver.php File Reference
some database related functions and abstract driver class.
Classes
class DBA
class dba_driver
abstract database driver class.
Functions
printable ($s)
dbg ($state)
set database driver debugging state.
dbesc ($str)
Escape strings being passed to DB queries.
dbescbin ($str)
dbunescbin ($str)
dbescdate ($date)
db_quoteinterval ($txt)
dbesc_identifier ($str)
db_utcnow ()
db_optimizetable ($table)
db_concat ($fld, $sep)
q ($sql)
Execute a SQL query with printf style args.
dbq ($sql)
Raw DB query, no arguments.
dbesc_array_cb (&$item, $key)
dbesc_array (&$arr)
db_getfunc ($f)
db_load_file ($f)
db_logger ($s, $level=LOGGER_NORMAL, $syslog=LOG_INFO)
Detailed Description
some database related functions and abstract driver class.
This file contains the abstract database driver class dba_driver and some functions for working with databases.
Function Documentation
db_concat ($fld, $sep)
Referenced by Zotlabs\Module\Admin\Accounts\get().
db_getfunc ($f)
Referenced by common_friends(), contact_block(), downgrade_accounts(), Zotlabs\Module\Search\get(), Zotlabs\Module\Sitelist\init(), item_permissions_sql(), Zotlabs\Module\Dirsearch\list_public_sites(), permissions_sql(), Zotlabs\Module\Admin\Channels\post(), Zotlabs\Module\Connect\post(), public_permissions_sql(), random_profile(), Zotlabs\Daemon\Poller\run(), Zotlabs\Daemon\Externals\run(), search_doc_files(), stream_perms_api_uids(), and Zotlabs\Widget\Random_block\widget().
db_load_file ($f)
db_logger ($s, $level = LOGGER_NORMAL, $syslog = LOG_INFO)
Referenced by dba_postgres\q(), dba_mysqli\q(), and dba_pdo\q().
db_optimizetable ($table)
db_quoteinterval ($txt)
Referenced by Zotlabs\Lib\Chatroom\enter(), Zotlabs\Module\Register\get(), identity_basic_export(), Zotlabs\Module\Ping\init(), item_expire(), mark_orphan_hubsxchans(), poco_load(), Zotlabs\Module\Item\post(), Zotlabs\Module\Register\post(), Zotlabs\Zot\Verify\purge(), random_profile(), Zotlabs\Daemon\Poller\run(), Zotlabs\Daemon\Cron\run(), Zotlabs\Daemon\Cron_daily\run(), Zotlabs\Daemon\Cron_weekly\run(), Zotlabs\Daemon\Expire\run(), Zotlabs\Daemon\Queue\run(), Zotlabs\Daemon\Checksites\run(), Zotlabs\Daemon\Onepoll\run(), update_birthdays(), update_channels_active_halfyear_stat(), update_channels_active_monthly_stat(), and update_suggestions().
db_utcnow ()
Referenced by Zotlabs\Module\Admin\admin_page_summary(), Zotlabs\Lib\Chatroom\enter(), Zotlabs\Module\Register\get(), identity_basic_export(), Zotlabs\Module\Ping\init(), item_expire(), mark_orphan_hubsxchans(), poco_load(), Zotlabs\Module\Item\post(), Zotlabs\Module\Register\post(), Zotlabs\Zot\Verify\purge(), random_profile(), Zotlabs\Daemon\Cron\run(), Zotlabs\Daemon\Cron_daily\run(), Zotlabs\Daemon\Poller\run(), Zotlabs\Daemon\Cron_weekly\run(), Zotlabs\Daemon\Expire\run(), Zotlabs\Daemon\Queue\run(), Zotlabs\Daemon\Checksites\run(), Zotlabs\Daemon\Onepoll\run(), update_birthdays(), update_channels_active_halfyear_stat(), update_channels_active_monthly_stat(), and update_suggestions().
dbesc ($str)
Escape strings being passed to DB queries.
Always escape strings being used in DB queries. This function returns the escaped string. Integer DB parameters should all be proven integers by wrapping with intval().
Parameters
string $str A string to pass to a DB query
Returns
Return an escaped string of the value to pass to a DB query.
Referenced by Zotlabs\Lib\DB_Upgrade\__construct(), Zotlabs\Lib\Permcat\__construct(), abook_toggle_flag(), account_allow(), account_approve(), account_deny(), account_verify_password(), add_source_route(), Zotlabs\Module\Admin\admin_page_summary(), advanced_profile(), allowed_public_recips(), anon_identity_init(), api_client_register(), api_file_data(), api_file_detail(), api_file_meta(), api_group_members(), api_login(), api_perm_is_allowed(), api_photo_detail(), api_user(), Zotlabs\Lib\Apps\app_destroy(), Zotlabs\Lib\Apps\app_feature(), Zotlabs\Lib\Apps\app_install(), Zotlabs\Lib\Apps\app_installed(), Zotlabs\Lib\Apps\app_list(), Zotlabs\Lib\Apps\app_store(), Zotlabs\Lib\Apps\app_undestroy(), Zotlabs\Lib\Apps\app_update(), apply_updates(), article_tagadelic(), articlecategories_widget(), atoken_abook(), atoken_create_xchan(), atoken_delete(), attach_by_hash(), attach_by_hash_nodata(), attach_can_view_folder(), attach_change_permissions(), attach_count_files(), attach_delete(), attach_drop_photo(), attach_export_data(), attach_list_files(), attach_mkdir(), attach_move(), attach_recursive_perms(), attach_store(), attach_syspaths(), attach_upgrade(), authenticate_success(), Zotlabs\Render\Comanche\block(), bookmark_add(), build_sync_packet(), call_hooks(), card_tagadelic(), cardcategories_widget(), categories_widget(), cdav_principal(), change_channel(), change_channel_keys(), channel_apps(), channel_change_address(), channel_export_items(), channel_remove(), channelx_by_hash(), channelx_by_n(), channelx_by_nick(), check_account_email(), check_account_invite(), check_item_source(), check_location_move(), check_webbie(), check_zotinfo(), Zotlabs\Lib\Cache\clear(), common_friends(), Zotlabs\Access\Permissions\connect_perms(), consume_feed(), contact_remove(), copy_of_pubitem(), count_common_friends(), Zotlabs\Zot\Verify\create(), Zotlabs\Lib\Chatroom\create(), create_account(), create_conversation(), create_identity(), Zotlabs\Lib\NativeWiki\create_wiki(), Zotlabs\Lib\AbConfig\Delete(), Zotlabs\Lib\Config\Delete(), Zotlabs\Lib\IConfig\Delete(), Zotlabs\Lib\XConfig\Delete(), Zotlabs\Lib\PConfig\Delete(), delete_imported_item(), delete_item_lowlevel(), Zotlabs\Lib\NativeWikiPage\delete_page(), delete_thing_photo(), deliverable_singleton(), delivery_report_is_storable(), Zotlabs\Lib\Chatroom\destroy(), Zotlabs\Web\SessionHandler\destroy(), Zotlabs\Module\Dirsearch\dir_flag_build(), Zotlabs\Module\Dirsearch\dir_query_build(), dir_tagadelic(), discover_by_url(), downgrade_accounts(), Zotlabs\Module\Embedphotos\embedphotos_widget_album(), Zotlabs\Lib\Chatroom\enter(), event_addtocal(), event_store_event(), event_store_item(), Zotlabs\Lib\NativeWiki\exists_by_name(), expand_groups(), fetch_post_tags(), file_activity(), file_tag_file_query(), find_filename_by_hash(), find_folder_hash_by_attach_hash(), find_folder_hash_by_path(), find_upstream_directory(), fix_attached_photo_permissions(), fix_private_photos(), fix_system_urls(), Zotlabs\Web\SessionHandler\gc(), Zotlabs\Module\Achievements\get(), Zotlabs\Module\Dreport\get(), Zotlabs\Module\Filerm\get(), Zotlabs\Module\Manage\get(), Zotlabs\Module\Chanview\get(), Zotlabs\Module\Lockview\get(), Zotlabs\Module\Xchan\get(), Zotlabs\Module\Contactgroup\get(), Zotlabs\Lib\Cache\get(), Zotlabs\Module\Pubstream\get(), Zotlabs\Module\Editpost\get(), Zotlabs\Module\Fhublocs\get(), Zotlabs\Module\Like\get(), Zotlabs\Module\Subthread\get(), Zotlabs\Lib\IConfig\Get(), Zotlabs\Module\Display\get(), Zotlabs\Module\Search\get(), Zotlabs\Module\Sharedwithme\get(), Zotlabs\Module\Dirsearch\get(), Zotlabs\Module\Fbrowser\get(), Zotlabs\Lib\AbConfig\Get(), Zotlabs\Module\Block\get(), Zotlabs\Module\Articles\get(), Zotlabs\Module\Cards\get(), Zotlabs\Module\Connections\get(), Zotlabs\Module\Profperm\get(), Zotlabs\Module\Pdledit\get(), Zotlabs\Module\Editblock\get(), Zotlabs\Module\Editlayout\get(), Zotlabs\Module\Layouts\get(), Zotlabs\Module\Editwebpage\get(), Zotlabs\Module\Blocks\get(), Zotlabs\Module\Webpages\get(), Zotlabs\Module\Network\get(), Zotlabs\Module\Hq\get(), Zotlabs\Module\Rpost\get(), Zotlabs\Module\Wiki\get(), Zotlabs\Module\Filestorage\get(), Zotlabs\Module\Cal\get(), Zotlabs\Module\Admin\Channels\get(), Zotlabs\Module\Lostpass\get(), Zotlabs\Module\Channel\get(), Zotlabs\Module\Group\get(), Zotlabs\Module\Chatsvc\get(), Zotlabs\Module\Admin\Accounts\get(), Zotlabs\Module\Sources\get(), Zotlabs\Module\Settings\Oauth\get(), Zotlabs\Module\Settings\Tokens\get(), Zotlabs\Module\Appman\get(), Zotlabs\Module\Locs\get(), Zotlabs\Module\Invite\get(), Zotlabs\Module\Rate\get(), Zotlabs\Module\Mail\get(), Zotlabs\Module\Admin\Site\get(), Zotlabs\Module\Thing\get(), Zotlabs\Module\Events\get(), Zotlabs\Module\Admin\Plugins\get(), Zotlabs\Module\Cover_photo\get(), Zotlabs\Module\Profile_photo\get(), Zotlabs\Module\Connedit\get(), Zotlabs\Module\Photos\get(), Zotlabs\Module\Profiles\get(), Zotlabs\Web\HTTPSig\get_activitypub_key(), get_all_api_perms(), get_all_perms(), get_cloudpath(), get_feed_for(), get_file_activity_object(), Zotlabs\Lib\Config\get_from_storage(), get_item_elements(), Zotlabs\Zot\Verify\get_meta(), get_online_status(), Zotlabs\Lib\NativeWiki\get_permissions(), get_things(), Zotlabs\Lib\NativeWiki\get_wiki(), Zotlabs\Zot\Auth\GetHublocs(), group_add(), group_add_member(), group_byname(), group_rec_byhash(), group_rmv(), group_rmv_member(), groups_containing(), handle_feed(), handle_tag(), hubloc_change_primary(), hubloc_mark_as_down(), identity_basic_export(), identity_export_year(), ids_to_querystr(), Zotlabs\Module\Import\import_account(), import_apps(), import_author_rss(), import_author_unknown(), import_author_zot(), import_channel(), import_conv(), import_directory_keywords(), import_directory_profile(), import_item_ids(), import_items(), import_likes(), import_mail(), import_site(), import_webpage_element(), import_xchan(), import_xchan_photo(), Zotlabs\Module\Hcard\init(), Zotlabs\Module\Bookmarks\init(), Zotlabs\Module\Branchtopic\init(), Zotlabs\Module\Prate\init(), Zotlabs\Module\Rmagic\init(), Zotlabs\Module\Sitelist\init(), Zotlabs\Module\Ratingsearch\init(), Zotlabs\Module\Notify\init(), Zotlabs\Module\Rate\init(), Zotlabs\Module\Search_ac\init(), Zotlabs\Module\Wfinger\init(), Zotlabs\Module\Magic\init(), Zotlabs\Module\Xrd\init(), Zotlabs\Module\Profiles\init(), Zotlabs\Module\Page\init(), Zotlabs\Module\Feed\init(), Zotlabs\Module\Suggest\init(), Zotlabs\Module\Zotfeed\init(), Zotlabs\Module\Cdav\init(), Zotlabs\Module\Impel\init(), Zotlabs\Module\Ofeed\init(), Zotlabs\Module\Photo\init(), Zotlabs\Module\Directory\init(), Zotlabs\Module\Connect\init(), Zotlabs\Module\Profile\init(), Zotlabs\Module\Thing\init(), Zotlabs\Module\Owa\init(), Zotlabs\Module\Regdir\init(), Zotlabs\Module\Ping\init(), Zotlabs\Module\Acl\init(), Zotlabs\Module\Poke\init(), Zotlabs\Module\Dav\init(), init_groups_visitor(), install_plugin(), is_matrix_url(), item_add_cid(), item_create_edit_activity(), item_message_id(), item_permissions_sql(), item_remove_cid(), item_sign(), item_store(), item_store_update(), items_fetch(), Zotlabs\Lib\Chatroom\leave(), Zotlabs\Module\Dirsearch\list_public_sites(), Zotlabs\Lib\NativeWiki\listwikis(), Zotlabs\Lib\AbConfig\Load(), Zotlabs\Lib\Config\Load(), Zotlabs\Lib\XConfig\Load(), Zotlabs\Lib\NativeWikiPage\load_page(), Zotlabs\Lib\NativeWikiPage\load_page_history(), load_plugin(), local_dir_update(), ZotOAuth1DataStore\lookup_consumer(), ZotOAuth1DataStore\lookup_nonce(), ZotOAuth1DataStore\lookup_token(), mail_store(), mark_orphan_hubsxchans(), Zotlabs\Zot\Verify\match(), match_openid(), member_of(), menu_add_item(), menu_create(), menu_del_item(), menu_delete(), menu_edit(), menu_edit_item(), menu_fetch(), menu_list(), menu_list_count(), Zotlabs\Lib\Chatroom\message(), nav(), ZotOAuth1DataStore\new_access_token(), new_contact(), ZotOAuth1DataStore\new_request_token(), Zotlabs\Module\Api\oauth_get_client(), Zotlabs\Module\Oep\oep_album_reply(), Zotlabs\Module\Oep\oep_articles_reply(), Zotlabs\Module\Oep\oep_cards_reply(), Zotlabs\Module\Oep\oep_display_reply(), Zotlabs\Module\Oep\oep_mid_reply(), Zotlabs\Module\Oep\oep_photo_reply(), Zotlabs\Module\Oep\oep_phototop_reply(), owt_init(), Zotlabs\Lib\NativeWikiPage\page_list(), perm_is_allowed(), permissions_sql(), photo_new_resource(), photo_profile_setperms(), photo_upload(), photos_album_exists(), photos_album_get_db_idstr(), photos_album_rename(), photos_albums_list(), photos_list_photos(), plugin_is_installed(), poco(), poco_load(), Zotlabs\Module\Sources\post(), Zotlabs\Module\Settings\Account\post(), Zotlabs\Module\Locs\post(), Zotlabs\Module\Lostpass\post(), Zotlabs\Module\Admin\Profs\post(), Zotlabs\Module\Settings\Tokens\post(), Zotlabs\Module\Settings\Oauth\post(), Zotlabs\Module\Admin\Account_edit\post(), Zotlabs\Module\Group\post(), Zotlabs\Module\Settings\Channel\post(), Zotlabs\Module\Settings\Display\post(), Zotlabs\Module\Events\post(), Zotlabs\Module\Embedphotos\post(), Zotlabs\Module\Rmagic\post(), Zotlabs\Module\Prate\post(), Zotlabs\Module\Getfile\post(), Zotlabs\Module\Item\post(), Zotlabs\Module\Chatsvc\post(), Zotlabs\Module\Connect\post(), Zotlabs\Module\Register\post(), Zotlabs\Module\Cover_photo\post(), Zotlabs\Module\Chat\post(), Zotlabs\Module\Rate\post(), Zotlabs\Module\Profile_photo\post(), Zotlabs\Module\Photos\post(), Zotlabs\Module\Connedit\post(), Zotlabs\Module\Profiles\post(), Zotlabs\Module\Cdav\post(), Zotlabs\Module\Webpages\post(), private_messages_drop(), private_messages_fetch_conversation(), private_messages_fetch_message(), private_messages_list(), process_channel_sync_delivery(), process_delivery(), process_feed_tombstones(), process_location_delivery(), process_mail_delivery(), process_profile_delivery(), process_rating_delivery(), profile_load(), profile_photo_set_profile_perms(), prune_hub_reinstalls(), public_permissions_sql(), public_recips(), Zotlabs\Zot\Verify\purge(), queue_deliver(), queue_insert(), queue_set_delivered(), rconnect_url(), Zotlabs\Web\SessionHandler\read(), refimport_content(), reflect_comment_store(), reflect_get_channel(), Zotlabs\Extend\Hook\register(), register_hook(), remote_online_status(), remove_all_xchan_resources(), remove_community_tag(), remove_obsolete_hublocs(), remove_queue_by_posturl(), remove_queue_item(), Zotlabs\Lib\NativeWikiPage\rename_page(), Zotlabs\Daemon\Poller\run(), Zotlabs\Daemon\Cron\run(), Zotlabs\Daemon\Thumbnail\run(), Zotlabs\Daemon\Checksites\run(), Zotlabs\Daemon\Gprobe\run(), Zotlabs\Daemon\Queue\run(), Zotlabs\Daemon\Deliver\run(), Zotlabs\Daemon\Onedirsync\run(), Zotlabs\Daemon\Externals\run(), Zotlabs\Daemon\Onepoll\run(), Zotlabs\Daemon\Directory\run(), Zotlabs\Zot\Finger\run(), Zotlabs\Daemon\Notifier\run(), photo_driver\save(), scopes_sql(), search_doc_files(), send_message(), send_reg_approval_email(), send_status_notifications(), Zotlabs\Lib\Cache\set(), Zotlabs\Lib\AbConfig\Set(), Zotlabs\Lib\Config\Set(), Zotlabs\Lib\IConfig\Set(), Zotlabs\Lib\XConfig\Set(), Zotlabs\Lib\PConfig\Set(), start_delivery_chain(), store_doc_file(), store_item_tag(), stream_perms_xchans(), stringify_array_elms(), Zotlabs\Lib\Enotify\submit(), Zotlabs\Lib\NativeWiki\sync_a_wiki_item(), sync_apps(), sync_chatrooms(), sync_directories(), sync_events(), sync_files(), sync_locations(), sync_menus(), sync_objs(), tag_deliver(), tagadelic(), term_item_parent_query(), term_query(), tgroup_check(), uninstall_plugin(), Zotlabs\Extend\Hook\unregister(), Zotlabs\Extend\Hook\unregister_by_file(), unregister_hook(), update_birthdays(), update_directory_entry(), update_hub_connected(), update_modtime(), update_queue_item(), update_r1097(), update_r1122(), update_r1140(), update_r1141(), update_r1151(), update_r1156(), update_r1158(), update_r1159(), update_r1194(), Zotlabs\Lib\NativeWiki\update_wiki(), vcard_from_xchan(), vcard_query(), Zotlabs\Zot\Auth\Verify(), verify_email_address(), Zotlabs\Widget\Savedsearch\widget(), Zotlabs\Widget\Settings_menu\widget(), Zotlabs\Widget\Bookmarkedchats\widget(), Zotlabs\Widget\Forums\widget(), Zotlabs\Widget\Random_block\widget(), Zotlabs\Widget\Album\widget(), Zotlabs\Widget\Portfolio\widget(), Zotlabs\Widget\Item\widget(), Zotlabs\Widget\Cdav\widget(), Zotlabs\Web\SessionHandler\write(), xchan_keychange_acl(), xchan_keychange_table(), xchan_mail_query(), xchan_query(), xchan_store(), z_readdir(), zat_init(), zid_init(), zot_feed(), zot_get_hublocs(), zot_gethub(), zot_process_response(), zot_refresh(), zot_rekey_request(), zot_reply_auth_check(), zot_reply_message_request(), zot_reply_pickup(), zot_reply_purge(), zot_reply_refresh(), and zotinfo().
dbesc_array (& $arr)
Referenced by create_table_from_array(), item_store_update(), and sync_files().
dbesc_array_cb (& $item, $key)
dbesc_identifier ($str)
dbescbin ($str)
Referenced by attach_mkdir(), attach_move(), attach_store(), Zotlabs\Module\Photos\post(), and photo_driver\save().
dbescdate ($date)
Referenced by import_xchan(), process_channel_sync_delivery(), send_message(), and zot_refresh().
dbg ($state)
set database driver debugging state.
Parameters
int $state 0 to disable debugging
dbq ($sql)
Raw DB query, no arguments.
This function executes a raw DB query without any arguments.
Parameters
string $sql The SQL query to execute
Referenced by create_table_from_array(), item_store_update(), Zotlabs\Module\Setup\load_database(), process_channel_sync_delivery(), and sync_files().
dbunescbin ($str)
Referenced by api_file_data(), api_file_detail(), api_photo_detail(), attach_by_hash(), attach_delete(), attach_export_data(), attach_move(), Zotlabs\Module\Cover_photo\get(), Zotlabs\Module\Profile_photo\get(), Zotlabs\Module\Attach\init(), Zotlabs\Module\Photo\init(), Zotlabs\Module\Getfile\post(), Zotlabs\Module\Cover_photo\post(), Zotlabs\Module\Profile_photo\post(), Zotlabs\Module\Photos\post(), Zotlabs\Daemon\Thumbnail\run(), Zotlabs\Thumbs\Video\Thumb(), Zotlabs\Thumbs\Pdf\Thumb(), Zotlabs\Thumbs\Text\Thumb(), Zotlabs\Thumbs\Epubthumb\Thumb(), Zotlabs\Thumbs\Mp3audio\Thumb(), and update_r1159().
printable ($s)
Referenced by dba_mysql\q(), dba_postgres\q(), dba_mysqli\q(), and dba_pdo\q().
q ($sql)
Execute a SQL query with printf style args.
printf style arguments s and d are replaced with variable arguments, which should each be appropriately dbesc() or intval(). SELECT queries return an array of results or false if SQL or DB error. Other queries return true if the command was successful or false if it wasn't.
Example: $r = q("SELECT * FROM %s WHERE `uid` = %d", 'user', 1);
Parameters
string $sql The SQL query to execute
Returns
bool|array
Referenced by Zotlabs\Lib\DB_Upgrade\__construct(), Zotlabs\Lib\Permcat\__construct(), abook_connections(), abook_self(), abook_toggle_flag(), account_allow(), account_approve(), account_deny(), account_remove(), account_service_class_fetch(), account_total(), account_verify_password(), add_source_route(), Zotlabs\Module\Admin\admin_page_summary(), advanced_profile(), allowed_public_recips(), anon_identity_init(), api_client_register(), api_file_data(), api_file_detail(), api_file_meta(), api_group(), api_group_members(), api_login(), api_perm_is_allowed(), api_photo_detail(), api_user(), api_zot_abconfig(), api_zot_abook_xchan(), api_zot_perm_allowed(), Zotlabs\Lib\Apps\app_destroy(), Zotlabs\Lib\Apps\app_feature(), Zotlabs\Lib\Apps\app_install(), Zotlabs\Lib\Apps\app_installed(), Zotlabs\Lib\Apps\app_list(), Zotlabs\Lib\Apps\app_store(), app_tagadelic(), Zotlabs\Lib\Apps\app_undestroy(), Zotlabs\Lib\Apps\app_update(), apply_updates(), article_catblock(), article_tagadelic(), articlecategories_widget(), atoken_abook(), atoken_create_xchan(), atoken_delete(), attach_by_hash(), attach_by_hash_nodata(), attach_can_view_folder(), attach_change_permissions(), attach_count_files(), attach_delete(), attach_drop_photo(), attach_export_data(), attach_folder_select_list(), attach_list_files(), attach_mkdir(), attach_move(), attach_recursive_perms(), attach_store(), attach_syspaths(), attach_upgrade(), authenticate_success(), auto_channel_create(), Zotlabs\Render\Comanche\block(), bookmark_add(), build_sync_packet(), call_hooks(), card_catblock(), card_tagadelic(), cardcategories_widget(), catblock(), categories_widget(), cdav_principal(), change_channel(), change_channel_keys(), channel_apps(), channel_change_address(), channel_export_items(), channel_remove(), channel_remove_final(), channel_total(), channelx_by_hash(), channelx_by_n(), channelx_by_nick(), check_account_email(), check_account_invite(), check_config(), check_for_new_perms(), check_item_source(), check_location_move(), check_webbie(), check_zotinfo(), Zotlabs\Lib\Cache\clear(), collect_recipients(), common_friends(), Zotlabs\Access\Permissions\connect_perms(), Zotlabs\Module\Connedit\connedit_clone(), consume_feed(), contact_block(), contact_profile_assign(), contact_remove(), contact_select(), copy_of_pubitem(), count_common_friends(), Zotlabs\Zot\Verify\create(), Zotlabs\Lib\Chatroom\create(), create_account(), create_conversation(), create_identity(), Zotlabs\Lib\NativeWiki\create_wiki(), Zotlabs\Render\Theme\current(), Zotlabs\Module\Defperms\defperms_clone(), Zotlabs\Lib\AbConfig\Delete(), Zotlabs\Lib\Config\Delete(), Zotlabs\Lib\IConfig\Delete(), Zotlabs\Lib\XConfig\Delete(), Zotlabs\Lib\PConfig\Delete(), delete_imported_item(), delete_item_lowlevel(), Zotlabs\Lib\NativeWikiPage\delete_page(), delete_thing_photo(), deliverable_singleton(), delivery_report_is_storable(), Zotlabs\Lib\Chatroom\destroy(), Zotlabs\Web\SessionHandler\destroy(), Zotlabs\Module\Dirsearch\dir_parse_query(), dir_tagadelic(), discover_by_url(), do_delivery(), downgrade_accounts(), drop_item(), Zotlabs\Module\Embedphotos\embedphotos_widget_album(), encode_item(), Zotlabs\Lib\Chatroom\enter(), event_addtocal(), event_import_ical(), event_import_ical_task(), event_store_event(), event_store_item(), Zotlabs\Lib\NativeWiki\exists_by_name(), expand_groups(), fetch_post_tags(), file_activity(), fileas_widget(), Zotlabs\Access\Permissions\FilledAutoperms(), find_filename_by_hash(), find_folder_hash_by_attach_hash(), find_folder_hash_by_path(), find_upstream_directory(), first_post_date(), fix_attached_photo_permissions(), fix_private_photos(), fix_system_urls(), Zotlabs\Web\SessionHandler\gc(), Zotlabs\Module\Achievements\get(), Zotlabs\Module\Dreport\get(), Zotlabs\Module\Filerm\get(), Zotlabs\Module\Manage\get(), Zotlabs\Module\Chanview\get(), Zotlabs\Module\Lockview\get(), Zotlabs\Module\Notifications\get(), Zotlabs\Module\React\get(), Zotlabs\Module\Viewsrc\get(), Zotlabs\Module\Xchan\get(), Zotlabs\Module\Contactgroup\get(), Zotlabs\Lib\Cache\get(), Zotlabs\Module\Pubstream\get(), Zotlabs\Module\Admin\Queue\get(), Zotlabs\Module\Article_edit\get(), Zotlabs\Module\Card_edit\get(), Zotlabs\Module\Moderate\get(), Zotlabs\Module\Admin\Dbsync\get(), Zotlabs\Module\Editpost\get(), Zotlabs\Module\Fhublocs\get(), Zotlabs\Module\Filer\get(), Zotlabs\Module\Like\get(), Zotlabs\Module\Subthread\get(), Zotlabs\Module\Tagger\get(), Zotlabs\Lib\IConfig\Get(), Zotlabs\Module\Display\get(), Zotlabs\Module\Search\get(), Zotlabs\Module\Sharedwithme\get(), Zotlabs\Module\Dirsearch\get(), Zotlabs\Module\Fbrowser\get(), Zotlabs\Lib\AbConfig\Get(), Zotlabs\Module\Viewconnections\get(), Zotlabs\Module\Block\get(), Zotlabs\Module\Articles\get(), Zotlabs\Module\Cards\get(), Zotlabs\Module\Connections\get(), Zotlabs\Module\Profperm\get(), Zotlabs\Module\Pdledit\get(), Zotlabs\Module\Editblock\get(), Zotlabs\Module\Editlayout\get(), Zotlabs\Module\Layouts\get(), Zotlabs\Module\Editwebpage\get(), Zotlabs\Module\Blocks\get(), Zotlabs\Module\Webpages\get(), Zotlabs\Module\Network\get(), Zotlabs\Module\Hq\get(), Zotlabs\Module\Rpost\get(), Zotlabs\Module\Settings\Featured\get(), Zotlabs\Module\Notify\get(), Zotlabs\Module\Wiki\get(), Zotlabs\Module\Pconfig\get(), Zotlabs\Module\Filestorage\get(), Zotlabs\Module\Cal\get(), Zotlabs\Module\Admin\Account_edit\get(), Zotlabs\Module\Admin\Profs\get(), Zotlabs\Module\Admin\Channels\get(), Zotlabs\Module\Tagrm\get(), Zotlabs\Module\Lostpass\get(), Zotlabs\Module\Directory\get(), Zotlabs\Module\Channel\get(), Zotlabs\Module\Group\get(), Zotlabs\Module\Chatsvc\get(), Zotlabs\Module\Admin\Accounts\get(), Zotlabs\Module\Sources\get(), Zotlabs\Module\Settings\Oauth\get(), Zotlabs\Module\Settings\Tokens\get(), Zotlabs\Module\Appman\get(), Zotlabs\Module\Locs\get(), Zotlabs\Module\Chat\get(), Zotlabs\Module\Invite\get(), Zotlabs\Module\Mitem\get(), Zotlabs\Module\New_channel\get(), Zotlabs\Module\Rate\get(), Zotlabs\Module\Mail\get(), Zotlabs\Module\Poke\get(), Zotlabs\Module\Admin\Site\get(), Zotlabs\Module\Setup\get(), Zotlabs\Module\Register\get(), Zotlabs\Module\Thing\get(), Zotlabs\Module\Events\get(), Zotlabs\Module\Admin\Plugins\get(), Zotlabs\Module\Cover_photo\get(), Zotlabs\Module\Profile_photo\get(), Zotlabs\Module\Settings\Channel\get(), Zotlabs\Module\Connedit\get(), Zotlabs\Module\Photos\get(), Zotlabs\Module\Profiles\get(), Zotlabs\Module\Item\get(), get_account_by_id(), Zotlabs\Web\HTTPSig\get_activitypub_key(), get_all_api_perms(), get_all_perms(), get_channel_default_perms(), get_cloudpath(), get_cover_photo(), get_file_activity_object(), Zotlabs\Lib\Config\get_from_storage(), get_item_elements(), Zotlabs\Zot\Verify\get_meta(), get_online_status(), Zotlabs\Lib\NativeWiki\get_permissions(), get_site_info(), get_sys_channel(), get_things(), get_webpage_elements(), Zotlabs\Lib\NativeWiki\get_wiki(), get_zcard(), get_zcard_embed(), Zotlabs\Zot\Auth\GetHublocs(), group_add(), group_add_member(), group_byname(), group_get_members(), group_get_members_xchan(), group_get_profile_members_xchan(), group_rec_byhash(), group_rmv(), group_rmv_member(), group_select(), group_side(), groups_containing(), handle_feed(), handle_tag(), hubloc_change_primary(), hubloc_mark_as_down(), identity_basic_export(), identity_check_service_class(), identity_export_year(), identity_selector(), Zotlabs\Module\Import\import_account(), import_apps(), import_author_rss(), import_author_unknown(), import_author_zot(), import_channel(), import_conv(), import_directory_keywords(), import_directory_profile(), import_hublocs(), import_item_ids(), import_items(), import_likes(), import_mail(), import_site(), Zotlabs\Lib\Apps\import_system_apps(), import_webpage_element(), import_xchan(), import_xchan_photo(), Zotlabs\Module\Rmagic\init(), Zotlabs\Module\Branchtopic\init(), Zotlabs\Module\Bookmarks\init(), Zotlabs\Module\Hcard\init(), Zotlabs\Module\Prate\init(), Zotlabs\Module\Sitelist\init(), Zotlabs\Module\Notify\init(), Zotlabs\Module\Rate\init(), Zotlabs\Module\Ratingsearch\init(), Zotlabs\Module\Search_ac\init(), Zotlabs\Module\Starred\init(), Zotlabs\Module\Magic\init(), Zotlabs\Module\Common\init(), Zotlabs\Module\Xrd\init(), Zotlabs\Module\Wfinger\init(), Zotlabs\Module\Suggest\init(), Zotlabs\Module\Attach\init(), Zotlabs\Module\Page\init(), Zotlabs\Module\Profiles\init(), Zotlabs\Module\Share\init(), Zotlabs\Module\Zotfeed\init(), Zotlabs\Module\Cdav\init(), Zotlabs\Module\Chatsvc\init(), Zotlabs\Module\Home\init(), Zotlabs\Module\Impel\init(), Zotlabs\Module\Photo\init(), Zotlabs\Module\Directory\init(), Zotlabs\Module\Mood\init(), Zotlabs\Module\Connect\init(), Zotlabs\Module\Profile\init(), Zotlabs\Module\Thing\init(), Zotlabs\Module\Owa\init(), Zotlabs\Module\Defperms\init(), Zotlabs\Module\Regdir\init(), Zotlabs\Module\Ping\init(), Zotlabs\Module\Acl\init(), Zotlabs\Module\Poke\init(), Zotlabs\Module\Connedit\init(), Zotlabs\Module\Dav\init(), init_groups_visitor(), install_plugin(), is_matrix_url(), is_sys_channel(), item_add_cid(), Zotlabs\Module\Item\item_check_service_class(), item_create_edit_activity(), item_expire(), item_message_id(), item_remove_cid(), item_sign(), item_store(), item_store_update(), items_fetch(), layout_select(), Zotlabs\Lib\Chatroom\leave(), Zotlabs\Lib\Chatroom\list_count(), Zotlabs\Module\Dirsearch\list_public_sites(), Zotlabs\Lib\NativeWiki\listwikis(), Zotlabs\Lib\AbConfig\Load(), Zotlabs\Lib\Config\Load(), Zotlabs\Lib\PConfig\Load(), Zotlabs\Lib\XConfig\Load(), load_contact_links(), load_hooks(), Zotlabs\Lib\NativeWikiPage\load_page(), Zotlabs\Lib\NativeWikiPage\load_page_history(), Zotlabs\Lib\Permcat\load_permcats(), load_plugin(), load_translation_table(), local_dir_update(), ZotOAuth1\loginUser(), ZotOAuth1DataStore\lookup_consumer(), ZotOAuth1DataStore\lookup_nonce(), ZotOAuth1DataStore\lookup_token(), mail_store(), mark_orphan_hubsxchans(), Zotlabs\Zot\Verify\match(), match_openid(), member_of(), menu_add_item(), menu_create(), menu_del_item(), menu_delete(), menu_delete_id(), menu_edit(), menu_edit_item(), menu_fetch(), menu_fetch_id(), menu_list(), menu_list_count(), Zotlabs\Lib\Chatroom\message(), mini_group_select(), nav(), ZotOAuth1DataStore\new_access_token(), new_contact(), ZotOAuth1DataStore\new_request_token(), notifications_off(), notifications_on(), Zotlabs\Module\Api\oauth_get_client(), Zotlabs\Module\Oep\oep_album_reply(), Zotlabs\Module\Oep\oep_articles_reply(), Zotlabs\Module\Oep\oep_cards_reply(), Zotlabs\Module\Oep\oep_display_reply(), Zotlabs\Module\Oep\oep_mid_reply(), Zotlabs\Module\Oep\oep_photo_reply(), Zotlabs\Module\Oep\oep_phototop_reply(), owt_init(), Zotlabs\Lib\NativeWikiPage\page_list(), pdl_selector(), perm_is_allowed(), photo_new_resource(), photo_profile_setperms(), photo_upload(), photos_album_exists(), photos_album_get_db_idstr(), photos_album_rename(), photos_albums_list(), photos_list_photos(), plugin_is_installed(), poco(), poco_load(), populate_acl(), Zotlabs\Module\Sources\post(), Zotlabs\Module\Settings\Account\post(), Zotlabs\Module\Admin\Profs\post(), Zotlabs\Module\Locs\post(), Zotlabs\Module\Lostpass\post(), Zotlabs\Module\Tagrm\post(), Zotlabs\Module\Admin\Account_edit\post(), Zotlabs\Module\Settings\Tokens\post(), Zotlabs\Module\Settings\Oauth\post(), Zotlabs\Module\Group\post(), Zotlabs\Module\Settings\Channel\post(), Zotlabs\Module\Settings\Display\post(), Zotlabs\Module\Events\post(), Zotlabs\Module\Admin\Channels\post(), Zotlabs\Module\Admin\Accounts\post(), Zotlabs\Module\Hq\post(), Zotlabs\Module\Embedphotos\post(), Zotlabs\Module\Rmagic\post(), Zotlabs\Module\Getfile\post(), Zotlabs\Module\Prate\post(), Zotlabs\Module\Item\post(), Zotlabs\Module\Connect\post(), Zotlabs\Module\Chatsvc\post(), Zotlabs\Module\Tasks\post(), Zotlabs\Module\Cover_photo\post(), Zotlabs\Module\Register\post(), Zotlabs\Module\Defperms\post(), Zotlabs\Module\Chat\post(), Zotlabs\Module\Rate\post(), Zotlabs\Module\Profile_photo\post(), Zotlabs\Module\Photos\post(), Zotlabs\Module\Connedit\post(), Zotlabs\Module\Profiles\post(), Zotlabs\Module\Cdav\post(), Zotlabs\Module\Webpages\post(), private_messages_drop(), private_messages_fetch_conversation(), private_messages_fetch_message(), private_messages_list(), process_channel_sync_delivery(), process_delivery(), process_feed_tombstones(), process_location_delivery(), process_mail_delivery(), process_profile_delivery(), process_rating_delivery(), profile_edit_menu(), profile_load(), profile_photo_set_profile_perms(), profiles_build_sync(), prune_hub_reinstalls(), public_recips(), Zotlabs\Zot\Verify\purge(), queue_deliver(), queue_insert(), queue_set_delivered(), random_profile(), rconnect_url(), Zotlabs\Web\SessionHandler\read(), refimport_content(), reflect_comment_store(), reflect_get_channel(), Zotlabs\Extend\Hook\register(), register_hook(), reload_plugins(), remote_online_status(), remove_all_xchan_resources(), remove_community_tag(), remove_obsolete_hublocs(), remove_queue_by_posturl(), remove_queue_item(), Zotlabs\Lib\NativeWikiPage\rename_page(), retain_item(), Zotlabs\Lib\Chatroom\roomlist(), Zotlabs\Daemon\Cron\run(), Zotlabs\Daemon\Cron_daily\run(), Zotlabs\Daemon\Cron_weekly\run(), Zotlabs\Daemon\Poller\run(), Zotlabs\Daemon\Expire\run(), Zotlabs\Daemon\Thumbnail\run(), Zotlabs\Daemon\Deliver_hooks\run(), Zotlabs\Daemon\Checksites\run(), Zotlabs\Daemon\Gprobe\run(), Zotlabs\Daemon\Queue\run(), Zotlabs\Daemon\Externals\run(), Zotlabs\Daemon\Onepoll\run(), Zotlabs\Daemon\Onedirsync\run(), Zotlabs\Daemon\Ratenotif\run(), Zotlabs\Daemon\Deliver\run(), Zotlabs\Daemon\Directory\run(), Zotlabs\Zot\Finger\run(), Zotlabs\Daemon\Notifier\run(), photo_driver\save(), scopes_sql(), search_doc_files(), send_message(), send_reg_approval_email(), send_status_notifications(), service_class_fetch(), Zotlabs\Lib\Cache\set(), Zotlabs\Lib\AbConfig\Set(), Zotlabs\Lib\Config\Set(), Zotlabs\Lib\IConfig\Set(), Zotlabs\Lib\XConfig\Set(), Zotlabs\Lib\PConfig\Set(), set_default_login_identity(), start_delivery_chain(), store_doc_file(), store_item_tag(), stream_perms_api_uids(), stream_perms_xchans(), Zotlabs\Lib\Enotify\submit(), suggestion_query(), Zotlabs\Lib\NativeWiki\sync_a_wiki_item(), sync_an_item(), sync_apps(), sync_chatrooms(), sync_directories(), sync_events(), sync_files(), sync_locations(), sync_menus(), sync_objs(), tag_deliver(), tagadelic(), tasks_fetch(), term_item_parent_query(), tgroup_check(), translate_channel_perms_outbound(), uninstall_plugin(), Zotlabs\Extend\Hook\unregister(), Zotlabs\Extend\Hook\unregister_by_file(), unregister_hook(), update_birthdays(), update_channels_active_halfyear_stat(), update_channels_active_monthly_stat(), update_channels_total_stat(), update_directory_entry(), update_hub_connected(), update_local_comments_stat(), update_local_posts_stat(), update_modtime(), update_queue_item(), update_r1000(), update_r1001(), update_r1002(), update_r1003(), update_r1004(), update_r1005(), update_r1006(), update_r1007(), update_r1008(), update_r1009(), update_r1010(), update_r1011(), update_r1012(), update_r1013(), update_r1014(), update_r1015(), update_r1016(), update_r1017(), update_r1018(), update_r1019(), update_r1020(), update_r1021(), update_r1022(), update_r1023(), update_r1024(), update_r1025(), update_r1026(), update_r1027(), update_r1028(), update_r1029(), update_r1030(), update_r1031(), update_r1032(), update_r1033(), update_r1034(), update_r1035(), update_r1036(), update_r1037(), update_r1038(), update_r1039(), update_r1040(), update_r1041(), update_r1042(), update_r1043(), update_r1044(), update_r1045(), update_r1046(), update_r1047(), update_r1048(), update_r1049(), update_r1050(), update_r1051(), update_r1052(), update_r1053(), update_r1054(), update_r1055(), update_r1056(), update_r1057(), update_r1058(), update_r1059(), update_r1060(), update_r1061(), update_r1062(), update_r1063(), update_r1064(), update_r1065(), update_r1066(), update_r1067(), update_r1068(), update_r1069(), update_r1070(), update_r1071(), update_r1072(), update_r1073(), update_r1074(), update_r1075(), update_r1076(), update_r1077(), update_r1078(), update_r1079(), update_r1080(), update_r1081(), update_r1082(), update_r1083(), update_r1084(), update_r1085(), update_r1086(), update_r1087(), update_r1088(), update_r1089(), update_r1090(), update_r1092(), update_r1093(), update_r1094(), update_r1095(), update_r1096(), update_r1097(), update_r1098(), update_r1099(), update_r1100(), update_r1101(), update_r1102(), update_r1104(), update_r1105(), update_r1106(), update_r1107(), update_r1108(), update_r1109(), update_r1110(), update_r1111(), update_r1112(), update_r1113(), update_r1114(), update_r1115(), update_r1117(), update_r1118(), update_r1119(), update_r1120(), update_r1121(), update_r1122(), update_r1123(), update_r1124(), update_r1125(), update_r1126(), update_r1127(), update_r1128(), update_r1129(), update_r1130(), update_r1131(), update_r1132(), update_r1133(), update_r1134(), update_r1135(), update_r1136(), update_r1137(), update_r1138(), update_r1139(), update_r1140(), update_r1141(), update_r1142(), update_r1143(), update_r1144(), update_r1145(), update_r1146(), update_r1147(), update_r1148(), update_r1149(), update_r1150(), update_r1151(), update_r1152(), update_r1153(), update_r1154(), update_r1155(), update_r1156(), update_r1157(), update_r1158(), update_r1159(), update_r1160(), update_r1161(), update_r1162(), update_r1163(), update_r1164(), update_r1165(), update_r1166(), update_r1167(), update_r1168(), update_r1169(), update_r1170(), update_r1171(), update_r1172(), update_r1173(), update_r1174(), update_r1175(), update_r1176(), update_r1177(), update_r1178(), update_r1179(), update_r1180(), update_r1181(), update_r1182(), update_r1183(), update_r1184(), update_r1185(), update_r1186(), update_r1187(), update_r1188(), update_r1189(), update_r1190(), update_r1191(), update_r1192(), update_r1193(), update_r1194(), update_r1195(), update_r1196(), update_r1197(), update_suggestions(), Zotlabs\Lib\NativeWiki\update_wiki(), vcard_from_xchan(), vcard_query(), Zotlabs\Zot\Auth\Verify(), verify_email_address(), visible_plugin_list(), Zotlabs\Widget\Admin\widget(), Zotlabs\Widget\Appcategories\widget(), Zotlabs\Widget\Activity\widget(), Zotlabs\Widget\Forums\widget(), Zotlabs\Widget\Savedsearch\widget(), Zotlabs\Widget\Random_block\widget(), Zotlabs\Widget\Bookmarkedchats\widget(), Zotlabs\Widget\Settings_menu\widget(), Zotlabs\Widget\Suggestedchats\widget(), Zotlabs\Widget\Follow\widget(), Zotlabs\Widget\Album\widget(), Zotlabs\Widget\Portfolio\widget(), Zotlabs\Widget\Cdav\widget(), Zotlabs\Widget\Filer\widget(), Zotlabs\Widget\Item\widget(), Zotlabs\Web\SessionHandler\write(), wtagblock(), xchan_fetch(), xchan_keychange_acl(), xchan_keychange_table(), xchan_mail_query(), xchan_query(), xchan_store(), z_readdir(), zat_init(), zid_init(), zot_feed(), zot_get_hublocs(), zot_gethub(), zot_import(), zot_process_response(), zot_refresh(), zot_rekey_request(), zot_reply_auth_check(), zot_reply_message_request(), zot_reply_pickup(), zot_reply_purge(), zot_reply_refresh(), zot_site_info(), and zotinfo().