The Hubzilla: util/Doxygen_phpvarfilter.php File Reference
Doxygen_phpvarfilter.php File Reference
A Doxygen INPUT_FILTER to parse @var member variable documentation.
Variables
$source = file_get_contents($argv[1])
$regexp = '#\@var\s+([^\s]+)([^/]+)/\s+(var|public|protected|private)\s+(\$[^\s;=]+)#'
$replac = '${2} */ ${3} ${1} ${4}'
Detailed Description
A Doxygen INPUT_FILTER to parse @var member variable documentation.
An input filter for Doxygen to parse @var class member variable documentation, so it is a bit more compatible how anybody else interpretes it.
See Also
http://stackoverflow.com/questions/4325224/doxygen-how-to-describe-class-member-variables-in-php/8472180#8472180
Variable Documentation
$regexp = '#\@var\s+([^\s]+)([^/]+)/\s+(var|public|protected|private)\s+(\$[^\s;=]+)#'
$replac = '${2} */ ${3} ${1} ${4}'
$source = file_get_contents($argv[1])
Referenced by attach_store(), format_css_if_exists(), format_js_if_exists(), head_get_css(), head_get_js(), head_get_links(), head_get_main_js(), Zotlabs\Module\Sources\post(), Zotlabs\Module\Admin\Plugins\post(), Zotlabs\Module\Webpages\post(), and Zotlabs\Lib\NativeWikiPage\toc().