The Hubzilla: include/event.php File Reference
event.php File Reference
Event related functions.
Functions
format_event_html ($ev)
Returns an event as HTML.
format_event_obj ($jobject)
ical_wrapper ($ev)
format_event_ical ($ev)
format_todo_ical ($ev)
format_ical_text ($s)
format_ical_sourcetext ($s)
format_event_bbcode ($ev)
bbtovcal ($s)
bbtoevent ($s)
sort_by_date ($arr)
Sorts the given array of events by date.
ev_compare ($a, $b)
Compare function for events.
event_store_event ($arr)
event_addtocal ($item_id, $uid)
ical_to_ev ($s)
parse_vobject ($ical, $type)
parse_ical_file ($f, $uid)
event_import_ical ($ical, $uid)
event_ical_get_sourcetext ($s)
event_import_ical_task ($ical, $uid)
event_store_item ($arr, $event)
todo_stat ()
tasks_fetch ($arr)
cdav_principal ($uri)
cdav_perms ($needle, $haystack, $check_rw=false)
translate_type ($type)
Detailed Description
Event related functions.
Function Documentation
bbtoevent ($s)
Referenced by bbcode(), bbtovcal(), and event_addtocal().
bbtovcal ($s)
cdav_perms ($needle, $haystack, $check_rw = false)
Referenced by Zotlabs\Module\Cdav\post().
cdav_principal ($uri)
Referenced by Zotlabs\Module\Cdav\get(), Zotlabs\Module\Cdav\init(), Zotlabs\Module\Cdav\post(), and Zotlabs\Widget\Cdav\widget().
ev_compare ($a, $b)
Compare function for events.
This function can be used in usort() to sort events by date.
See Also
sort_by_date()
Parameters
array $a
array $b
Returns
number return values like strcmp()
event_addtocal ($item_id, $uid)
Referenced by Zotlabs\Module\Events\get(), and update_imported_item().
event_ical_get_sourcetext ($s)
event_import_ical ($ical, $uid)
Referenced by parse_ical_file().
event_import_ical_task ($ical, $uid)
Referenced by parse_ical_file().
event_store_event ($arr)
Hooks:
event_store_event Called when an event record is created or updated.
array event
array existing_event
boolean cancel - default false
Referenced by event_addtocal(), Zotlabs\Module\Events\post(), Zotlabs\Module\Tasks\post(), and update_birthdays().
event_store_item ($arr, $event)
Fixme:
can only update sig if we have the author's channel on this site Until fixed, set it to nothing so it won't give us signature errors.
Hooks:
event_updated Called when an event record is modified.
Hooks:
event_created Called when an event record is created.
Referenced by Zotlabs\Module\Events\post(), and update_birthdays().
format_event_bbcode ($ev)
Referenced by event_store_item().
format_event_html ($ev)
Returns an event as HTML.
Parameters
array $ev
Returns
string HTML formatted event
Todo:
move this to template
Referenced by bbtovcal(), Zotlabs\Module\Cal\get(), Zotlabs\Module\Events\get(), and Zotlabs\Module\Events\post().
format_event_ical ($ev)
Referenced by ical_wrapper().
format_event_obj ($jobject)
Referenced by prepare_body().
format_ical_sourcetext ($s)
Referenced by format_event_ical(), and format_todo_ical().
format_ical_text ($s)
Referenced by format_event_ical(), and format_todo_ical().
format_todo_ical ($ev)
Referenced by format_event_ical().
ical_to_ev ($s)
Referenced by bbtoevent().
ical_wrapper ($ev)
Referenced by Zotlabs\Module\Events\get().
parse_ical_file ($f, $uid)
Referenced by Zotlabs\Module\Events\post().
parse_vobject ($ical, $type)
Referenced by ical_to_ev().
sort_by_date ($arr)
Sorts the given array of events by date.
See Also
ev_compare()
Parameters
array $arr
Returns
array Date sorted array of events
Referenced by Zotlabs\Module\Cal\get(), and Zotlabs\Module\Events\get().
tasks_fetch ($arr)
Referenced by Zotlabs\Module\Tasks\init().
todo_stat ()
translate_type ($type)