The Hubzilla: util/extract.php File Reference
extract.php File Reference
Variables
$arr = array()
$files = array('index.php','boot.php')
foreach($files as $file) $s = '<?php' . "\n"
foreach($arr as $a) $zones = timezone_identifiers_list()
Variable Documentation
$arr = array()
Referenced by abook_store_lowlevel(), account_service_class_fetch(), account_store_lowlevel(), activity_sanitise(), api_network_stream(), api_perm_is_allowed(), Zotlabs\Lib\Apps\app_store(), Zotlabs\Lib\Apps\app_update(), array_sanitise(), arrtoxml(), attach_mkdir(), attach_mkdirp(), attach_store(), auto_channel_create(), bb_translate_video(), bookmark_add(), Zotlabs\Text\Tagadelic\calc(), change_channel(), channel_apps(), channel_store_lowlevel(), check_account_admin(), check_account_email(), check_account_invite(), check_account_password(), check_channelallowed(), check_list_permissions(), check_location_move(), check_plugin_versions(), check_siteallowed(), check_webbie(), Zotlabs\Lib\NativeWikiPage\commit(), Zotlabs\Lib\NativeWikiPage\compare_page(), construct_page(), contact_block(), contact_select(), conversation(), convert_oldfields(), Zotlabs\Lib\Chatroom\create(), create_account(), create_identity(), Zotlabs\Widget\Wiki_pages\create_missing_page(), Zotlabs\Lib\NativeWikiPage\create_page(), create_table_from_array(), Zotlabs\Lib\NativeWiki\create_wiki(), Zotlabs\Lib\NativeWikiPage\delete_page(), Zotlabs\Lib\Chatroom\destroy(), discover_by_url(), discover_by_webbie(), Zotlabs\Web\Router\Dispatch(), drop_item(), event_store_event(), event_store_item(), Zotlabs\Lib\ActivityStreams\expand(), Zotlabs\Web\Session\extend_cookie(), feature_enabled(), fetch_xrd_links(), file_activity(), Zotlabs\Access\Permissions\FilledAutoperms(), Zotlabs\Access\Permissions\FilledPerms(), Zotlabs\Lib\Apps\find_app_in_array(), Zotlabs\Lib\Permcat\find_permcat(), find_xchan_in_array(), flatten_array_recursive(), Zotlabs\Theme\RedbasicConfig\form(), format_like(), generate_map(), generate_named_map(), Zotlabs\Module\Linkinfo\get(), Zotlabs\Module\Like\get(), Zotlabs\Module\Subthread\get(), Zotlabs\Module\Tagger\get(), Zotlabs\Module\Suggest\get(), Zotlabs\Module\Settings\Features\get(), Zotlabs\Module\Network\get(), Zotlabs\Theme\RedbasicConfig\get(), Zotlabs\Module\Admin\Features\get(), Zotlabs\Module\Directory\get(), Zotlabs\Module\Connect\get(), Zotlabs\Module\Defperms\get(), Zotlabs\Module\Connedit\get(), Zotlabs\Module\Profiles\get(), get_all_api_perms(), get_all_perms(), get_atom_elements(), get_best_language(), get_cloudpath(), Zotlabs\Lib\ThreadItem\get_comment_box(), get_features(), Zotlabs\Web\HttpMeta\get_field(), Zotlabs\Lib\NativeWikiPage\get_file_ext(), get_item_elements(), get_mail_elements(), get_mood_verbs(), Zotlabs\Lib\NativeWikiPage\get_page_content(), get_poke_verbs(), get_profile_elements(), Zotlabs\Lib\ThreadItem\get_template_data(), get_terms_oftype(), group_select(), head_add_link(), html2bb_video(), hubloc_store_lowlevel(), ids_to_array(), ids_to_querystr(), import_author_unknown(), import_author_xchan(), import_directory_profile(), import_hublocs(), import_site(), import_webpage_element(), import_xchan(), Zotlabs\Module\Hostxrd\init(), Zotlabs\Module\Well_known\init(), Zotlabs\Module\Magic\init(), Zotlabs\Module\Wfinger\init(), Zotlabs\Module\Xrd\init(), Zotlabs\Module\Tasks\init(), Zotlabs\Module\Impel\init(), Zotlabs\Module\Mood\init(), Zotlabs\Module\Oep\init(), Zotlabs\Module\Thing\init(), Zotlabs\Web\Session\init(), Zotlabs\Module\Ping\init(), Zotlabs\Module\Poke\init(), item_getfeedattach(), item_store(), item_store_update(), items_fetch(), Zotlabs\Module\Setup\load_database(), Zotlabs\Lib\NativeWikiPage\load_page(), Zotlabs\Lib\NativeWikiPage\load_page_history(), load_pdl(), local_dir_update(), mail_store(), menu_add_item(), menu_create(), menu_edit(), menu_edit_item(), menu_element(), Zotlabs\Lib\Chatroom\message(), new_contact(), Zotlabs\Web\Session\new_cookie(), obj_verbs(), oembed_action(), Zotlabs\Access\Permissions\OPerms(), owt_init(), Zotlabs\Lib\NativeWikiPage\page_history(), pdl_selector(), perm_is_allowed(), photo_calculate_scale(), photo_upload(), photos_album_get_db_idstr(), photos_create_item(), po2php_run(), Zotlabs\Module\Admin\Profs\post(), Zotlabs\Module\Admin\Features\post(), Zotlabs\Module\Appman\post(), Zotlabs\Module\Rmagic\post(), Zotlabs\Module\Chatsvc\post(), Zotlabs\Module\Register\post(), Zotlabs\Module\Chat\post(), Zotlabs\Module\Connedit\post(), Zotlabs\Module\New_channel\post(), Zotlabs\Module\Wiki\post(), post_activity_item(), proc_run(), process_channel_sync_delivery(), process_delivery(), process_location_delivery(), process_mail_delivery(), process_profile_delivery(), process_rating_delivery(), profile_activity(), profile_sidebar(), profile_store_lowlevel(), queue_deliver(), queue_insert(), red_item(), refimport_content(), reflect_comment_store(), Zotlabs\Extend\Hook\register_array(), Zotlabs\Render\Comanche\register_page_template(), remove_community_tag(), Zotlabs\Lib\NativeWikiPage\rename_page(), Zotlabs\Lib\NativeWikiPage\render_page_history(), replace_macros(), Zotlabs\Lib\NativeWikiPage\revert_page(), Zotlabs\Daemon\Importfile\run(), Zotlabs\Daemon\Externals\run(), Zotlabs\Lib\LDSignatures\salmon_sign(), photo_driver\save(), Zotlabs\Lib\NativeWikiPage\save_page(), Zotlabs\Module\Cover_photo\send_cover_photo_activity(), send_profile_photo_activity(), send_reg_approval_email(), service_class_fetch(), Zotlabs\Zot\DReport\set(), App\set_apps(), Zotlabs\Lib\ActivityStreams\set_recips(), Zotlabs\Lib\JSalmon\sign(), site_store_lowlevel(), sort_by_date(), stringify_array_elms(), Zotlabs\Daemon\Master\Summon(), sync_locations(), tag_deliver(), tasks_fetch(), text_highlight(), theme_attachments(), Zotlabs\Lib\Apps\translate_system_apps(), Zotlabs\Module\Admin\Security\trim_array_elems(), update_vcard(), Zotlabs\Lib\NativeWiki\update_wiki(), validate_channelname(), validate_item_elements(), vcard_query(), Zotlabs\Zot\Auth\Verify(), verify_email_address(), Zotlabs\Widget\Catcloud_wall\widget(), Zotlabs\Widget\Clock\widget(), Zotlabs\Widget\Activity\widget(), Zotlabs\Widget\Rating\widget(), Zotlabs\Widget\Wiki_page_history\widget(), Zotlabs\Widget\Tagcloud_wall\widget(), Zotlabs\Widget\Forums\widget(), Zotlabs\Widget\Random_block\widget(), Zotlabs\Widget\Admin\widget(), Zotlabs\Widget\Cover_photo\widget(), Zotlabs\Widget\Affinity\widget(), Zotlabs\Widget\Archive\widget(), Zotlabs\Widget\Item\widget(), Zotlabs\Widget\Photo_rand\widget(), Zotlabs\Widget\Photo_albums\widget(), Zotlabs\Widget\Categories\widget(), Zotlabs\Widget\Suggestions\widget(), Zotlabs\Widget\Photo\widget(), Zotlabs\Widget\Wiki_pages\widget(), xchan_fetch(), xchan_mail_query(), xchan_query(), xchan_store(), xchan_store_lowlevel(), xml2array(), zid(), zid_init(), zot_feed(), zot_fetch(), zot_gethub(), zot_import(), zot_process_response(), zot_register_hub(), zot_reply_auth_check(), zot_reply_message_request(), zot_reply_purge(), and zotinfo().
$files = array('index.php','boot.php')
Referenced by create_zip_file(), Zotlabs\Module\Fbrowser\get(), Zotlabs\Module\Pdledit\get(), Zotlabs\Module\Admin\Themes\get(), Zotlabs\Module\Settings\Display\get(), Zotlabs\Module\Admin\Site\get(), Zotlabs\Module\Admin\Plugins\get(), Zotlabs\Theme\RedbasicConfig\get_schemas(), Zotlabs\Lib\Apps\get_system_apps(), Zotlabs\Module\Ping\init(), Zotlabs\Module\Admin\Plugins\post(), refimport_content(), rrmdir(), Zotlabs\Daemon\Thumbnail\run(), sync_files(), and Zotlabs\Daemon\Importdoc\update_docs_dir().
$s = '<?php' . "\n"
Referenced by Zotlabs\Lib\MarkdownSoap\__construct(), Zotlabs\Render\SimpleTemplate\_build_nodes(), Zotlabs\Render\SimpleTemplate\_replcb_node(), acl2json(), Zotlabs\Lib\Apps\app_decode(), Zotlabs\Lib\Apps\app_encode(), Zotlabs\Lib\Apps\app_list(), attach_move(), attribute_contains(), base64special_decode(), base64special_encode(), base64url_decode(), base64url_encode(), bb_tag_preg_replace(), bb_translate_video(), Zotlabs\Lib\NativeWikiPage\bbcode(), bbtoevent(), bbtovcal(), Zotlabs\Render\Comanche\block(), btlogger(), chanlink_hash(), chanlink_url(), clean_query_string(), compat_photos_list(), Zotlabs\Lib\NativeWikiPage\convert_links(), Zotlabs\Render\Comanche\css(), Zotlabs\Lib\SuperCurl\curl_read(), Zotlabs\Storage\CalDAVClient\curl_read(), datetime_convert(), day_translate(), detect_language(), Zotlabs\Module\Dirsearch\dir_flag_build(), Zotlabs\Module\Dirsearch\dir_parse_query(), Zotlabs\Module\Dirsearch\dir_query_build(), ellipsify(), Zotlabs\Lib\MarkdownSoap\escape(), event_ical_get_sourcetext(), expand_acl(), extra_query_args(), Zotlabs\Lib\MarkdownSoap\extract_code(), file_tag_decode(), file_tag_encode(), file_tag_file_query(), filepath_macro(), find_doc_file(), fix_mce_lf(), fix_private_photos(), format_categories(), format_filer(), format_hashtags(), format_ical_sourcetext(), format_ical_text(), format_mentions(), format_term_for_display(), Zotlabs\Lib\NativeWikiPage\generate_toc(), Zotlabs\Module\Xchan\get(), Zotlabs\Module\Oexchange\get(), Zotlabs\Module\Pdledit\get(), Zotlabs\Module\Admin\Themes\get(), Zotlabs\Module\Mail\get(), get_attach_binname(), get_bb_tag_pos(), App\get_channel_links(), get_intltext_template(), get_language_name(), get_markup_template(), get_tags(), html2bb_video(), ical_to_ev(), Zotlabs\Lib\Apps\import_system_apps(), import_xchan(), info(), Zotlabs\Module\Bookmarks\init(), is_a_date_arg(), is_foreigner(), is_member(), is_null_date(), item_permissions_sql(), Zotlabs\Render\Comanche\js(), json_url_replace(), legal_webbie(), legal_webbie_text(), linkify(), load_doc_file(), load_pdl(), logger(), magic_link(), markdown_to_bb(), Zotlabs\Render\Comanche\menu(), network_to_name(), normalise_openid(), notice(), oembed_iframe(), oembed_replacecb(), Zotlabs\Render\Comanche\parse(), parse_ical_file(), Zotlabs\Render\Comanche\parse_pass0(), Zotlabs\Render\Comanche\parse_pass1(), parse_xml_string(), poco_load(), Zotlabs\Module\Wall_attach\post(), Zotlabs\Module\Photos\post(), prepare_body(), prepare_text(), print_template(), private_messages_fetch_conversation(), private_messages_fetch_message(), private_messages_list(), Zotlabs\Lib\MarkdownSoap\protect_autolinks(), protect_sprintf(), Zotlabs\Lib\MarkdownSoap\purify(), purify_filename(), purify_html(), Zotlabs\Lib\MarkdownSoap\putback_code(), qp(), random_string(), refimport_content(), Zotlabs\Render\Comanche\region(), Zotlabs\Render\SimpleTemplate\replace(), replace_macros(), Zotlabs\Render\SmartyTemplate\replace_macros(), Zotlabs\Render\SimpleTemplate\replace_macros(), Zotlabs\Daemon\Notifier\run(), scale_external_images(), scrape_feed(), scrape_vcard(), search(), search_doc_files(), searchbox(), Zotlabs\Lib\SuperCurl\set_data(), Zotlabs\Storage\CalDAVClient\set_data(), smilies(), sslify(), store_doc_file(), string_replace(), strip_owt(), strip_query_param(), strip_zats(), strip_zids(), t(), Zotlabs\Render\template_escape(), Zotlabs\Render\template_unescape(), term_item_parent_query(), term_query(), Zotlabs\Render\Comanche\test_condition(), text_highlight(), theme_attachments(), translate_projectname(), unamp(), undo_post_tagging(), Zotlabs\Lib\MarkdownSoap\unescape(), Zotlabs\Lib\MarkdownSoap\unprotect_autolinks(), unxmlify(), update_channels_active_halfyear_stat(), update_channels_active_monthly_stat(), Zotlabs\Daemon\Importdoc\update_docs_dir(), Zotlabs\Render\Theme\url(), Zotlabs\Render\SimpleTemplate\var_replace(), webfinger_rfc7033(), Zotlabs\Render\Comanche\webpage(), x(), z_fetch_url(), z_input_filter(), z_obscure(), z_post_url(), z_unobscure(), zid(), zidify_links(), zidify_text(), and zot_refresh().
foreach ($arr as $a) $zones = timezone_identifiers_list()