The Hubzilla: include/features.php File Reference
features.php File Reference
Functions
feature_enabled ($uid, $feature)
get_feature_default ($feature)
feature_level ($feature, $def)
get_features ($filtered=true)
Function Documentation
feature_enabled ($uid, $feature)
Referenced by advanced_profile(), Zotlabs\Lib\Apps\app_render(), articlecategories_widget(), cardcategories_widget(), categories_widget(), channel_apps(), Zotlabs\Access\Permissions\connect_perms(), conversation(), findpeople_widget(), Zotlabs\Theme\RedbasicConfig\form(), Zotlabs\Module\Article_edit\get(), Zotlabs\Module\Card_edit\get(), Zotlabs\Module\Editpost\get(), Zotlabs\Module\Articles\get(), Zotlabs\Module\Cards\get(), Zotlabs\Module\Pdledit\get(), Zotlabs\Module\Settings\Features\get(), Zotlabs\Module\Settings\Featured\get(), Zotlabs\Module\Wiki\get(), Zotlabs\Module\Cal\get(), Zotlabs\Module\Directory\get(), Zotlabs\Module\Sources\get(), Zotlabs\Module\Chat\get(), Zotlabs\Module\Settings\Display\get(), Zotlabs\Module\Mail\get(), Zotlabs\Module\Defperms\get(), Zotlabs\Module\Thing\get(), Zotlabs\Module\Events\get(), Zotlabs\Module\Settings\Channel\get(), Zotlabs\Module\Connedit\get(), Zotlabs\Module\Profiles\get(), Zotlabs\Lib\ThreadItem\get_comment_box(), Zotlabs\Lib\ThreadItem\get_template_data(), group_side(), Zotlabs\Module\Profiles\init(), nav(), Zotlabs\Lib\Apps\parse_app_description(), photo_upload(), Zotlabs\Module\Sources\post(), Zotlabs\Module\Pdledit\post(), Zotlabs\Module\Item\post(), Zotlabs\Module\Profiles\post(), post_is_importable(), profile_edit_menu(), profile_load(), search(), searchbox(), update_birthdays(), Zotlabs\Widget\Savedsearch\widget(), Zotlabs\Widget\Notes\widget(), Zotlabs\Widget\Settings_menu\widget(), Zotlabs\Widget\Tagcloud_wall\widget(), Zotlabs\Widget\Suggestedchats\widget(), Zotlabs\Widget\Bookmarkedchats\widget(), Zotlabs\Widget\Affinity\widget(), Zotlabs\Widget\Archive\widget(), Zotlabs\Widget\Categories\widget(), Zotlabs\Widget\Suggestions\widget(), zidify_callback(), and zidify_img_callback().
feature_level ($feature, $def)
Referenced by get_features().
get_feature_default ($feature)
Referenced by feature_enabled().
get_features ($filtered = true)
Referenced by Zotlabs\Module\Settings\Features\get(), Zotlabs\Module\Admin\Features\get(), get_feature_default(), Zotlabs\Module\Settings\Features\post(), Zotlabs\Module\Admin\Features\post(), and Zotlabs\Widget\Settings_menu\widget().