The Hubzilla: include/group.php File Reference
group.php File Reference
Functions
group_add ($uid, $name, $public=0)
group_rmv ($uid, $name)
group_byname ($uid, $name)
group_rec_byhash ($uid, $hash)
group_rmv_member ($uid, $name, $member)
group_add_member ($uid, $name, $member, $gid=0)
group_get_members ($gid)
group_get_members_xchan ($gid)
group_get_profile_members_xchan ($uid, $gid)
mini_group_select ($uid, $group= '')
group_side ($every="connections", $each="group", $edit=false, $group_id=0, $cid= '', $mode=1)
expand_groups ($g)
member_of ($c)
groups_containing ($uid, $c)
Function Documentation
expand_groups ($g)
Referenced by attach_recursive_perms(), collect_recipients(), and enumerate_permissions().
group_add ($uid, $name, $public = 0)
Referenced by create_identity(), Zotlabs\Module\Group\post(), and Zotlabs\Module\Settings\Channel\post().
group_add_member ($uid, $name, $member, $gid = 0)
Referenced by create_identity(), Zotlabs\Module\Contactgroup\get(), Zotlabs\Module\Group\get(), new_contact(), Zotlabs\Module\Settings\Channel\post(), Zotlabs\Module\Connedit\post(), and zot_refresh().
group_byname ($uid, $name)
Referenced by group_add(), group_add_member(), group_rmv_member(), handle_tag(), and Zotlabs\Module\Group\post().
group_get_members ($gid)
Referenced by Zotlabs\Module\Contactgroup\get(), Zotlabs\Module\Network\get(), Zotlabs\Module\Group\get(), and items_fetch().
group_get_members_xchan ($gid)
Referenced by Zotlabs\Module\Acl\init().
group_get_profile_members_xchan ($uid, $gid)
Referenced by Zotlabs\Module\Acl\init().
group_rec_byhash ($uid, $hash)
Referenced by Zotlabs\Module\Network\get(), items_fetch(), new_contact(), Zotlabs\Module\Connedit\post(), and zot_refresh().
group_rmv ($uid, $name)
Referenced by Zotlabs\Module\Group\get().
group_rmv_member ($uid, $name, $member)
Referenced by Zotlabs\Module\Contactgroup\get(), and Zotlabs\Module\Group\get().
group_side ($every = "connections", $each = "group", $edit = false, $group_id = 0, $cid = '', $mode = 1)
Referenced by Zotlabs\Widget\Collections\widget().
groups_containing ($uid, $c)
Referenced by group_side().
member_of ($c)
mini_group_select ($uid, $group = '')
Referenced by Zotlabs\Module\Settings\Channel\get().