The Hubzilla: include/help.php File Reference
help.php File Reference
Functions
get_help_content ($tocpath=false)
preg_callback_help_include ($matches)
determine_help_language ()
load_doc_file ($s)
find_doc_file ($s)
search_doc_files ($s)
doc_rank_sort ($s1, $s2)
load_context_help ()
store_doc_file ($s)
Function Documentation
determine_help_language ()
Returns
boolean|array
Referenced by Zotlabs\Module\Help\get(), load_doc_file(), and Zotlabs\Widget\Helpindex\widget().
doc_rank_sort ($s1, $s2)
find_doc_file ($s)
Referenced by load_doc_file().
get_help_content ($tocpath = false)
Parameters
string $tocpath
Returns
string|unknown
Referenced by Zotlabs\Module\Help\get(), and Zotlabs\Widget\Helpindex\widget().
load_context_help ()
Returns
string
Referenced by nav().
load_doc_file ($s)
Referenced by get_help_content(), load_context_help(), and preg_callback_help_include().
preg_callback_help_include ($matches)
search_doc_files ($s)
Parameters
string $s
Returns
number|mixed|unknown|boolean
Referenced by Zotlabs\Module\Help\get().
store_doc_file ($s)
Parameters
string $s
Returns
void|boolean[]|number[]|string[]|unknown[]
Referenced by Zotlabs\Daemon\Importdoc\update_docs_dir().