The Hubzilla: include/import.php File Reference
import.php File Reference
Functions
import_channel ($channel, $account_id, $seize)
Import a channel.
import_config ($channel, $configs)
Import pconfig for channel.
import_profiles ($channel, $profiles)
Import profiles.
import_hublocs ($channel, $hublocs, $seize, $moving=false)
Import hublocs.
import_objs ($channel, $objs)
Import things.
sync_objs ($channel, $objs)
Import things.
import_apps ($channel, $apps)
Import apps.
sync_apps ($channel, $apps)
Sync apps.
import_chatrooms ($channel, $chatrooms)
Import chatrooms.
sync_chatrooms ($channel, $chatrooms)
Sync chatrooms.
import_items ($channel, $items, $sync=false, $relocate=null)
Import items to channel.
sync_items ($channel, $items, $relocate=null)
Sync items to channel.
import_item_ids ($channel, $itemids)
import_events ($channel, $events)
Import events.
sync_events ($channel, $events)
Sync events.
import_menus ($channel, $menus)
Import menus.
sync_menus ($channel, $menus)
Sync menus.
import_likes ($channel, $likes)
Import likes.
import_conv ($channel, $convs)
import_mail ($channel, $mails, $sync=false)
Import mails.
sync_mail ($channel, $mails)
Synchronise mails.
sync_files ($channel, $files)
Synchronise files.
convert_oldfields (&$arr, $old, $new)
Rename a key in an array.
scan_webpage_elements ($path, $type, $cloud=false)
import_webpage_element ($element, $channel, $type)
get_webpage_elements ($channel, $type= 'all')
create_zip_file ($files=array(), $destination= '', $overwrite=false)
Create a compressed zip file.
Function Documentation
convert_oldfields (& $arr, $old, $new)
Rename a key in an array.
Replaces $old key with $new key in $arr.
Parameters
[in,out] array &$arr The array where to work on
string $old The old key in the array
string $new The new key in the array
Referenced by import_events(), import_profiles(), sync_events(), and sync_files().
create_zip_file ($files = array(), $destination = '', $overwrite = false)
Create a compressed zip file.
Parameters
array $files List of files to put in zip file
string $destination
boolean $overwrite
Returns
boolean Success status
get_webpage_elements ($channel, $type = 'all')
Referenced by Zotlabs\Module\Webpages\get().
import_apps ($channel, $apps)
Import apps.
Parameters
array $channel
array $apps
Referenced by Zotlabs\Module\Import\import_account().
import_channel ($channel, $account_id, $seize)
Import a channel.
Parameters
array $channel
int $account_id
int $seize
Returns
boolean|array
Referenced by Zotlabs\Module\Import\import_account().
import_chatrooms ($channel, $chatrooms)
Import chatrooms.
Parameters
array $channel
array $chatrooms
Referenced by Zotlabs\Module\Import\import_account().
import_config ($channel, $configs)
Import pconfig for channel.
Parameters
array $channel
array $configs
Referenced by Zotlabs\Module\Import\import_account().
import_conv ($channel, $convs)
Referenced by Zotlabs\Module\Import\import_account(), and process_channel_sync_delivery().
import_events ($channel, $events)
Import events.
Parameters
array $channel
array $events
Referenced by Zotlabs\Module\Import\import_account().
import_hublocs ($channel, $hublocs, $seize, $moving = false)
Import hublocs.
Parameters
array $channel
array $hublocs
unknown $seize
boolean $moving (optional) default false
Referenced by Zotlabs\Module\Import\import_account().
import_item_ids ($channel, $itemids)
Parameters
array $channel A channel array.
array $itemids
Referenced by Zotlabs\Module\Import\import_account(), and Zotlabs\Module\Import_items\post().
import_items ($channel, $items, $sync = false, $relocate = null)
Import items to channel.
Parameters
array $channel where to import to
array $items
boolean $sync default false
array $relocate default null
Referenced by Zotlabs\Module\Import\import_account(), Zotlabs\Module\Import_items\post(), and sync_items().
import_likes ($channel, $likes)
Import likes.
Parameters
array $channel
array $likes
Referenced by Zotlabs\Module\Import\import_account(), and process_channel_sync_delivery().
import_mail ($channel, $mails, $sync = false)
Import mails.
Parameters
array $channel
array $mails
boolean $sync (optional) default false
Referenced by Zotlabs\Module\Import\import_account(), and sync_mail().
import_menus ($channel, $menus)
Import menus.
Parameters
array $channel
array $menus
Referenced by Zotlabs\Module\Import\import_account().
import_objs ($channel, $objs)
Import things.
Parameters
array $channel
array $objs
Referenced by Zotlabs\Module\Import\import_account().
import_profiles ($channel, $profiles)
Import profiles.
Parameters
array $channel
array $profiles
Todo:
put all the applicable photos into the export.
Referenced by Zotlabs\Module\Import\import_account().
import_webpage_element ($element, $channel, $type)
Referenced by Zotlabs\Module\Webpages\post().
scan_webpage_elements ($path, $type, $cloud = false)
Referenced by Zotlabs\Module\Webpages\post().
sync_apps ($channel, $apps)
Sync apps.
Parameters
array $channel
array $apps
Referenced by process_channel_sync_delivery().
sync_chatrooms ($channel, $chatrooms)
Sync chatrooms.
Parameters
array $channel
array $chatrooms
Referenced by process_channel_sync_delivery().
sync_events ($channel, $events)
Sync events.
Parameters
array $channel
array $events
Referenced by process_channel_sync_delivery().
sync_files ($channel, $files)
Synchronise files.
Parameters
array $channel
array $files
Fixme:
update attachment structures if they are modified rather than created
Todo:
should we queue this and retry or delete everything or what?
Referenced by process_channel_sync_delivery().
sync_items ($channel, $items, $relocate = null)
Sync items to channel.
See Also
import_items
Parameters
array $channel where to import to
array $items
array $relocate default null
Referenced by process_channel_sync_delivery(), and sync_files().
sync_mail ($channel, $mails)
Synchronise mails.
See Also
import_mail
Parameters
array $channel
array $mails
Referenced by process_channel_sync_delivery().
sync_menus ($channel, $menus)
Sync menus.
Parameters
array $channel
array $menus
Referenced by process_channel_sync_delivery().
sync_objs ($channel, $objs)
Import things.
Parameters
array $channel
array $objs
Referenced by process_channel_sync_delivery().