The Hubzilla: include/menu.php File Reference
menu.php File Reference
Functions
menu_fetch ($name, $uid, $observer_xchan)
menu_element ($channel, $menu)
menu_render ($menu, $class='', $edit=false, $var=array())
menu_fetch_id ($menu_id, $channel_id)
menu_create ($arr)
menu_list ($channel_id, $name= '', $flags=0)
menu_list_count ($channel_id, $name= '', $flags=0)
menu_edit ($arr)
menu_delete ($menu_name, $uid)
menu_delete_id ($menu_id, $uid)
menu_add_item ($menu_id, $uid, $arr)
menu_edit_item ($menu_id, $uid, $arr)
menu_del_item ($menu_id, $uid, $item_id)
menu_sync_packet ($uid, $observer_hash, $menu_id, $delete=false)
Function Documentation
menu_add_item ($menu_id, $uid, $arr)
Referenced by bookmark_add(), import_menus(), Zotlabs\Module\Impel\init(), Zotlabs\Module\Mitem\post(), and sync_menus().
menu_create ($arr)
Referenced by bookmark_add(), import_menus(), Zotlabs\Module\Impel\init(), Zotlabs\Module\Menu\post(), and sync_menus().
menu_del_item ($menu_id, $uid, $item_id)
Referenced by Zotlabs\Module\Mitem\get().
menu_delete ($menu_name, $uid)
menu_delete_id ($menu_id, $uid)
Referenced by Zotlabs\Module\Menu\get(), menu_delete(), and sync_menus().
menu_edit ($arr)
Referenced by Zotlabs\Module\Menu\post(), and sync_menus().
menu_edit_item ($menu_id, $uid, $arr)
Referenced by Zotlabs\Module\Mitem\post().
menu_element ($channel, $menu)
Referenced by Zotlabs\Module\Menu\get(), identity_basic_export(), and menu_sync_packet().
menu_fetch ($name, $uid, $observer_xchan)
Referenced by Zotlabs\Module\Bookmarks\get(), Zotlabs\Module\Menu\get(), Zotlabs\Module\Mitem\get(), identity_basic_export(), Zotlabs\Render\Comanche\menu(), menu_render(), menu_sync_packet(), and profile_sidebar().
menu_fetch_id ($menu_id, $channel_id)
Referenced by Zotlabs\Module\Menu\get(), Zotlabs\Module\Mitem\init(), and menu_sync_packet().
menu_list ($channel_id, $name = '', $flags = 0)
If $flags is present, check that all the bits in $flags are set so that MENU_SYSTEM|MENU_BOOKMARK will return entries with both bits set. We will use this to find system generated bookmarks.
Referenced by bookmark_add(), Zotlabs\Module\Rbmark\get(), Zotlabs\Module\Bookmarks\get(), Zotlabs\Module\Menu\get(), Zotlabs\Module\Mitem\get(), Zotlabs\Module\Settings\Channel\get(), identity_basic_export(), and menu_render().
menu_list_count ($channel_id, $name = '', $flags = 0)
Referenced by channel_apps().
menu_render ($menu, $class = '', $edit = false, $var = array())
Referenced by Zotlabs\Module\Bookmarks\get(), Zotlabs\Render\Comanche\menu(), profile_sidebar(), and Zotlabs\Widget\Menu_preview\widget().
menu_sync_packet ($uid, $observer_hash, $menu_id, $delete = false)
Referenced by Zotlabs\Module\Menu\get(), Zotlabs\Module\Mitem\get(), Zotlabs\Module\Menu\post(), and Zotlabs\Module\Mitem\post().