The Hubzilla: include/message.php File Reference
message.php File Reference
Functions
mail_prepare_binary ($item)
send_message ($uid=0, $recipient= '', $body= '', $subject= '', $replyto= '', $expires=NULL_DATE, $mimetype= 'text/bbcode', $raw=false)
create_conversation ($channel, $recipient, $subject)
private_messages_list ($uid, $mailbox= '', $start=0, $numitems=0)
private_messages_fetch_message ($channel_id, $messageitem_id, $updateseen=false)
private_messages_drop ($channel_id, $messageitem_id, $drop_conversation=false)
private_messages_fetch_conversation ($channel_id, $messageitem_id, $updateseen=false)
Function Documentation
create_conversation ($channel, $recipient, $subject)
Referenced by mail_store(), and send_message().
mail_prepare_binary ($item)
Referenced by Zotlabs\Module\Mail\get(), Zotlabs\Module\Mail\post(), and private_messages_fetch_conversation().
private_messages_drop ($channel_id, $messageitem_id, $drop_conversation = false)
Referenced by Zotlabs\Module\Mail\get().
private_messages_fetch_conversation ($channel_id, $messageitem_id, $updateseen = false)
Referenced by Zotlabs\Module\Mail\get().
private_messages_fetch_message ($channel_id, $messageitem_id, $updateseen = false)
Referenced by Zotlabs\Module\Mail\get().
private_messages_list ($uid, $mailbox = '', $start = 0, $numitems = 0)
Referenced by Zotlabs\Module\Mail\get(), and Zotlabs\Widget\Conversations\widget().
send_message ($uid = 0, $recipient = '', $body = '', $subject = '', $replyto = '', $expires = NULL_DATE, $mimetype = 'text/bbcode', $raw = false)
When a photo was uploaded into the message using the (profile wall) ajax uploader, The permissions are initially set to disallow anybody but the owner from seeing it. This is because the permissions may not yet have been set for the post. If it's private, the photo permissions should be set appropriately. But we didn't know the final permissions on the post until now. So now we'll look for links of uploaded messages that are in the post and set them to the same permissions as the post itself.
Referenced by Zotlabs\Module\Mail\post().