The Hubzilla: install/migrate-mypg.php File Reference
migrate-mypg.php File Reference
Functions
ask_question ($menu, $options, $default)
get_data ($prompt, $regex)
parse_htconfig ($file)
get_configtype (array $data)
phpquote ($str)
run_sql ($file, $db, &$err, &$n)
Variables
$drivers =true
if($drivers) if(!$drivers)
foreach(array('install','include','mod','view')
as $dir) $cfgfile = '.htconfig.php'
if($argc >=2 &&$argv[1]==
'--resume') $cfg = parse_htconfig($cfgfile)
$type = get_configtype($cfg)
try
if(!file_exists('.htconfig.php-pgsql')) $pcfg = parse_htconfig('.htconfig.php-pgsql')
$ptype = get_configtype($pcfg)
catch(PDOException $e) $B = "\033[0;34m"
$H = "\033[0;35m"
$W = "\033[1;37m"
$M = "\033[1;31m"
$N = "\033[0m"
if(isset($starttable)) else
if ($err)
$res = $pgdb->query("select relname, attname, pg_type.typname from ((pg_attribute inner join pg_class on attrelid=pg_class.oid) inner join pg_type on atttypid=pg_type.oid) inner join pg_namespace on relnamespace=pg_namespace.oid where nspname='public' and atttypid not in (26,27,28,29) and relkind='r' and attname <> 'item_search_vector';")
if($res===false) $schema = array()
if($res===false) $pkeys = array()
$err = 0
$n = 0
$reserved = array('ignore','key','with')
foreach ($schema as $table=> $fields) = glob('mod/*.php')
$r = ask_question("Everything successful. Once you connect up the pg database there is no going back. Do you want to make it live (N,y)?", array('y', 'n'), 'n')
Function Documentation
ask_question ($menu, $options, $default)
get_configtype (array $data)
get_data ($prompt, $regex)
parse_htconfig ($file)
phpquote ($str)
run_sql ($file, $db, & $err, & $n)
Variable Documentation
catch (PDOException $e) $B = "\033[0;34m"
Referenced by localize_item().
if ($argc >=2 &&$argv[1]== '--resume') $cfg = parse_htconfig($cfgfile)
if ($drivers) if (!$drivers) foreach (array('install','include','mod','view') as $dir) $cfgfile = '.htconfig.php'
$drivers =true
$err = 0
Referenced by Zotlabs\Module\Cloud\DAVException(), parse_xml_string(), Zotlabs\Module\Settings\Account\post(), Zotlabs\Module\Settings\Channel\post(), run_sql(), and xml2array().
$H = "\033[0;35m"
$M = "\033[1;31m"
$N = "\033[0m"
$n = 0
Referenced by activity_match(), attach_move(), build_sync_packet(), Zotlabs\Module\React\get(), Zotlabs\Module\Rbmark\get(), Zotlabs\Module\Nojs\init(), Zotlabs\Module\Ratings\init(), Zotlabs\Module\New_channel\init(), load_pdl(), plural_dates(), Zotlabs\Module\Profiles\post(), Zotlabs\Daemon\Ratenotif\run(), run_sql(), App\set_pager_itemspage(), App\set_pager_total(), string_plural_select_default(), sync_locations(), zot_import(), and zot_reply_message_request().
if (!file_exists('.htconfig.php-pgsql')) $pcfg = parse_htconfig('.htconfig.php-pgsql')
if ($res===false) $pkeys = array()
$ptype = get_configtype($pcfg)
$r = ask_question("Everything successful. Once you connect up the pg database there is no going back. Do you want to make it live (N,y)?", array('y', 'n'), 'n')
Referenced by Zotlabs\Lib\DB_Upgrade\__construct(), Zotlabs\Lib\Permcat\__construct(), abook_connections(), abook_self(), abook_toggle_flag(), account_allow(), account_approve(), account_deny(), account_remove(), account_service_class_fetch(), account_total(), add_source_route(), Zotlabs\Module\Admin\admin_page_summary(), allowed_public_recips(), anon_identity_init(), api_call(), api_client_register(), api_file_data(), api_file_detail(), api_file_meta(), api_group(), api_group_members(), api_login(), api_oauth_access_token(), api_oauth_request_token(), api_perm_is_allowed(), api_photo_detail(), api_red_xchan(), api_zot_abconfig(), api_zot_abook_xchan(), api_zot_perm_allowed(), Zotlabs\Lib\Apps\app_destroy(), Zotlabs\Lib\Apps\app_feature(), Zotlabs\Lib\Apps\app_install(), Zotlabs\Lib\Apps\app_installed(), Zotlabs\Lib\Apps\app_list(), Zotlabs\Lib\Apps\app_store(), app_tagadelic(), app_tagblock(), Zotlabs\Lib\Apps\app_undestroy(), Zotlabs\Lib\Apps\app_update(), article_catblock(), article_tagadelic(), articlecategories_widget(), ask_question(), atoken_abook(), atoken_create_xchan(), atoken_delete(), attach_by_hash(), attach_by_hash_nodata(), attach_can_view_folder(), attach_change_permissions(), attach_count_files(), attach_delete(), attach_export_data(), attach_folder_select_list(), attach_list_files(), attach_mkdir(), attach_move(), attach_store(), attach_syspaths(), attach_upgrade(), authenticate_success(), autoname(), Zotlabs\Render\Comanche\block(), bookmark_add(), build_sync_packet(), card_catblock(), card_tagadelic(), cardcategories_widget(), catblock(), categories_widget(), cdav_principal(), change_channel(), change_channel_keys(), channel_apps(), channel_change_address(), channel_export_items(), channel_remove(), channel_total(), channelx_by_hash(), channelx_by_n(), channelx_by_nick(), check_account_email(), check_account_invite(), check_config(), check_for_new_perms(), check_item_source(), check_location_move(), check_webbie(), check_zotinfo(), collect_recipients(), common_friends(), common_friends_visitor_widget(), Zotlabs\Access\Permissions\connect_perms(), Zotlabs\Module\Connedit\connedit_clone(), construct_activity_object(), construct_activity_target(), consume_feed(), contact_block(), contact_profile_assign(), contact_remove(), contact_select(), copy_of_pubitem(), count_common_friends(), Zotlabs\Lib\Chatroom\create(), create_account(), create_conversation(), create_identity(), create_table_from_array(), Zotlabs\Lib\NativeWiki\create_wiki(), crypto_methods(), Zotlabs\Render\Theme\current(), Zotlabs\Module\Defperms\defperms_clone(), Zotlabs\Lib\AbConfig\Delete(), delete_imported_item(), delete_item_lowlevel(), delete_thing_photo(), deliverable_singleton(), delivery_report_is_storable(), Zotlabs\Lib\Chatroom\destroy(), dir_tagadelic(), dir_tagblock(), discover_by_url(), downgrade_accounts(), drop_item(), Zotlabs\Module\Embedphotos\embedphotos_widget_album(), encode_item(), Zotlabs\Lib\Chatroom\enter(), event_addtocal(), event_store_event(), event_store_item(), expand_groups(), fileas_widget(), Zotlabs\Access\Permissions\FilledAutoperms(), find_filename_by_hash(), find_folder_hash_by_attach_hash(), find_folder_hash_by_path(), find_upstream_directory(), first_post_date(), fix_attached_photo_permissions(), fix_private_photos(), fix_system_urls(), Zotlabs\Module\Achievements\get(), Zotlabs\Module\Dreport\get(), Zotlabs\Module\Filerm\get(), Zotlabs\Module\Manage\get(), Zotlabs\Module\Chanview\get(), Zotlabs\Module\Lockview\get(), Zotlabs\Module\Notifications\get(), Zotlabs\Module\Viewsrc\get(), Zotlabs\Module\Xchan\get(), Zotlabs\Module\Contactgroup\get(), Zotlabs\Module\Webfinger\get(), Zotlabs\Module\Zping\get(), Zotlabs\Module\Pubstream\get(), Zotlabs\Lib\Cache\get(), Zotlabs\Module\Moderate\get(), Zotlabs\Module\Admin\Queue\get(), Zotlabs\Module\Admin\Dbsync\get(), Zotlabs\Module\Fhublocs\get(), Zotlabs\Module\Filer\get(), Zotlabs\Module\Like\get(), Zotlabs\Module\Subthread\get(), Zotlabs\Module\Tagger\get(), Zotlabs\Lib\IConfig\Get(), Zotlabs\Module\Display\get(), Zotlabs\Module\Search\get(), Zotlabs\Module\Sharedwithme\get(), Zotlabs\Module\Dirsearch\get(), Zotlabs\Module\Fbrowser\get(), Zotlabs\Module\Help\get(), Zotlabs\Lib\AbConfig\Get(), Zotlabs\Module\Viewconnections\get(), Zotlabs\Module\Block\get(), Zotlabs\Module\Articles\get(), Zotlabs\Module\Cards\get(), Zotlabs\Module\Connections\get(), Zotlabs\Module\Suggest\get(), Zotlabs\Module\Profperm\get(), Zotlabs\Module\Pdledit\get(), Zotlabs\Module\Common\get(), Zotlabs\Module\Editblock\get(), Zotlabs\Module\Editlayout\get(), Zotlabs\Module\Layouts\get(), Zotlabs\Module\Editwebpage\get(), Zotlabs\Module\Blocks\get(), Zotlabs\Module\Webpages\get(), Zotlabs\Module\Network\get(), Zotlabs\Module\Hq\get(), Zotlabs\Module\Rpost\get(), Zotlabs\Module\Settings\Featured\get(), Zotlabs\Module\Notify\get(), Zotlabs\Module\Wiki\get(), Zotlabs\Module\Pconfig\get(), Zotlabs\Module\Filestorage\get(), Zotlabs\Module\Cal\get(), Zotlabs\Module\Admin\Profs\get(), Zotlabs\Module\Tagrm\get(), Zotlabs\Module\Lostpass\get(), Zotlabs\Module\Directory\get(), Zotlabs\Module\Channel\get(), Zotlabs\Module\Group\get(), Zotlabs\Module\Menu\get(), Zotlabs\Module\Chatsvc\get(), Zotlabs\Module\Sources\get(), Zotlabs\Module\Settings\Oauth\get(), Zotlabs\Module\Appman\get(), Zotlabs\Module\Locs\get(), Zotlabs\Module\Chat\get(), Zotlabs\Module\Invite\get(), Zotlabs\Module\Mitem\get(), Zotlabs\Module\New_channel\get(), Zotlabs\Module\Rate\get(), Zotlabs\Module\Mail\get(), Zotlabs\Module\Poke\get(), Zotlabs\Module\Page\get(), Zotlabs\Module\Setup\get(), Zotlabs\Module\Register\get(), Zotlabs\Module\Thing\get(), Zotlabs\Module\Events\get(), Zotlabs\Module\Admin\Plugins\get(), Zotlabs\Module\Cover_photo\get(), Zotlabs\Module\Profile_photo\get(), Zotlabs\Module\Photos\get(), Zotlabs\Module\Profiles\get(), Zotlabs\Module\Item\get(), get_account_by_id(), Zotlabs\Web\HTTPSig\get_activitypub_key(), get_all_api_perms(), get_all_perms(), get_channel_default_perms(), get_cloudpath(), get_cover_photo(), get_data(), get_item_elements(), Zotlabs\Zot\Verify\get_meta(), get_online_status(), Zotlabs\Lib\NativeWiki\get_permissions(), get_plugin_info(), get_site_info(), get_sys_channel(), get_theme_info(), get_things(), get_webpage_elements(), get_zcard(), get_zcard_embed(), group_add(), group_add_member(), group_byname(), group_get_members(), group_get_members_xchan(), group_get_profile_members_xchan(), group_rec_byhash(), group_rmv(), group_rmv_member(), group_select(), group_side(), groups_containing(), handle_tag(), hubloc_change_primary(), hubloc_mark_as_down(), identity_basic_export(), identity_check_service_class(), identity_export_year(), identity_selector(), Zotlabs\Module\Import\import_account(), import_author_rss(), import_author_unknown(), import_author_zot(), import_channel(), import_channel_photo(), import_conv(), import_directory_keywords(), import_directory_profile(), import_item_ids(), import_items(), import_likes(), import_site(), Zotlabs\Lib\Apps\import_system_apps(), import_xchan(), import_xchan_photo(), Zotlabs\Module\Branchtopic\init(), Zotlabs\Module\Hcard\init(), Zotlabs\Module\Prate\init(), Zotlabs\Module\Sitelist\init(), Zotlabs\Module\Rmagic\init(), Zotlabs\Module\Rate\init(), Zotlabs\Module\Starred\init(), Zotlabs\Module\Ratingsearch\init(), Zotlabs\Module\Search_ac\init(), Zotlabs\Module\Notify\init(), Zotlabs\Module\Wfinger\init(), Zotlabs\Module\Xrd\init(), Zotlabs\Module\Magic\init(), Zotlabs\Module\Attach\init(), Zotlabs\Module\Share\init(), Zotlabs\Module\Page\init(), Zotlabs\Module\Zotfeed\init(), Zotlabs\Module\Profiles\init(), Zotlabs\Module\Cdav\init(), Zotlabs\Module\Home\init(), Zotlabs\Module\Photo\init(), Zotlabs\Module\Mood\init(), Zotlabs\Module\Connect\init(), Zotlabs\Module\Profile\init(), Zotlabs\Module\Thing\init(), Zotlabs\Module\Owa\init(), Zotlabs\Module\Defperms\init(), Zotlabs\Module\Regdir\init(), Zotlabs\Module\Ping\init(), Zotlabs\Module\Acl\init(), Zotlabs\Module\Poke\init(), Zotlabs\Module\Connedit\init(), Zotlabs\Module\Dav\init(), init_groups_visitor(), is_matrix_url(), is_sys_channel(), item_add_cid(), Zotlabs\Module\Item\item_check_service_class(), item_create_edit_activity(), item_expire(), item_getfeedattach(), item_message_id(), item_remove_cid(), item_sign(), item_store(), item_store_update(), items_fetch(), jsonld_document_loader(), layout_select(), Zotlabs\Lib\Chatroom\leave(), legal_webbie(), Zotlabs\Lib\Chatroom\list_count(), Zotlabs\Module\Dirsearch\list_public_sites(), Zotlabs\Lib\AbConfig\Load(), Zotlabs\Lib\Config\Load(), Zotlabs\Lib\PConfig\Load(), Zotlabs\Lib\XConfig\Load(), load_contact_links(), Zotlabs\Module\Setup\load_database(), load_hooks(), Zotlabs\Lib\NativeWikiPage\load_page(), Zotlabs\Lib\NativeWikiPage\load_page_history(), local_dir_update(), ZotOAuth1\loginUser(), ZotOAuth1DataStore\lookup_consumer(), ZotOAuth1DataStore\lookup_nonce(), ZotOAuth1DataStore\lookup_token(), mail_store(), mark_orphan_hubsxchans(), Zotlabs\Zot\Verify\match(), match_openid(), member_of(), menu_add_item(), menu_create(), menu_del_item(), menu_delete(), menu_delete_id(), menu_edit(), menu_edit_item(), menu_fetch(), menu_fetch_id(), menu_list(), menu_list_count(), menu_sync_packet(), Zotlabs\Lib\Chatroom\message(), mini_group_select(), ZotOAuth1DataStore\new_access_token(), new_contact(), ZotOAuth1DataStore\new_request_token(), notifications_off(), Zotlabs\Module\Api\oauth_get_client(), Zotlabs\Module\Oep\oep_album_reply(), Zotlabs\Module\Oep\oep_articles_reply(), Zotlabs\Module\Oep\oep_cards_reply(), Zotlabs\Module\Oep\oep_photo_reply(), Zotlabs\Module\Oep\oep_phototop_reply(), owt_init(), Zotlabs\Lib\NativeWikiPage\page_list(), pdl_selector(), pemtome(), perm_is_allowed(), photo_new_resource(), photo_profile_setperms(), photo_upload(), photos_album_exists(), photos_album_get_db_idstr(), photos_albums_list(), photos_list_photos(), phpquote(), ping_site(), plugin_is_installed(), poco(), poco_load(), populate_acl(), Zotlabs\Module\Settings\Account\post(), Zotlabs\Module\Sources\post(), Zotlabs\Module\Admin\Profs\post(), Zotlabs\Module\Lostpass\post(), Zotlabs\Module\Locs\post(), Zotlabs\Module\Admin\Account_edit\post(), Zotlabs\Module\Settings\Oauth\post(), Zotlabs\Module\Tagrm\post(), Zotlabs\Module\Settings\Tokens\post(), Zotlabs\Module\Group\post(), Zotlabs\Module\Settings\Channel\post(), Zotlabs\Module\File_upload\post(), Zotlabs\Module\Settings\Display\post(), Zotlabs\Module\Events\post(), Zotlabs\Module\Mail\post(), Zotlabs\Module\Wall_attach\post(), Zotlabs\Module\Menu\post(), Zotlabs\Module\Embedphotos\post(), Zotlabs\Module\Rmagic\post(), Zotlabs\Module\Getfile\post(), Zotlabs\Module\Item\post(), Zotlabs\Module\Connect\post(), Zotlabs\Module\Chatsvc\post(), Zotlabs\Module\Tasks\post(), Zotlabs\Module\Mitem\post(), Zotlabs\Module\Cover_photo\post(), Zotlabs\Module\Register\post(), Zotlabs\Module\Defperms\post(), Zotlabs\Module\Profile_photo\post(), Zotlabs\Module\Photos\post(), Zotlabs\Module\Connedit\post(), Zotlabs\Module\Profiles\post(), Zotlabs\Module\Cdav\post(), Zotlabs\Module\Wiki\post(), preg_heart(), private_messages_drop(), private_messages_fetch_conversation(), private_messages_fetch_message(), private_messages_list(), process_channel_sync_delivery(), process_delivery(), process_feed_tombstones(), process_location_delivery(), process_mail_delivery(), process_profile_delivery(), process_rating_delivery(), profile_edit_menu(), profile_load(), profile_photo_set_profile_perms(), profiles_build_sync(), prune_hub_reinstalls(), public_recips(), pubrsatome(), dba_mysql\q(), dba_postgres\q(), dba_mysqli\q(), dba_pdo\q(), random_profile(), rconnect_url(), Zotlabs\Web\SessionHandler\read(), refimport_content(), reflect_comment_store(), Zotlabs\Extend\Hook\register(), register_hook(), relative_date(), reload_plugins(), remote_online_status(), remove_all_xchan_resources(), remove_community_tag(), remove_obsolete_hublocs(), replace_macros(), Zotlabs\Render\SmartyTemplate\replace_macros(), retain_item(), Zotlabs\Lib\Chatroom\roomlist(), Zotlabs\Daemon\Cron\run(), Zotlabs\Daemon\Poller\run(), Zotlabs\Daemon\Cron_weekly\run(), Zotlabs\Daemon\Expire\run(), Zotlabs\Daemon\Deliver_hooks\run(), Zotlabs\Daemon\Gprobe\run(), Zotlabs\Daemon\Queue\run(), Zotlabs\Daemon\Checksites\run(), Zotlabs\Daemon\Onepoll\run(), Zotlabs\Daemon\Externals\run(), Zotlabs\Daemon\Ratenotif\run(), Zotlabs\Daemon\Deliver\run(), Zotlabs\Daemon\Onedirsync\run(), Zotlabs\Zot\Finger\run(), Zotlabs\Daemon\Notifier\run(), run_sql(), photo_driver\save(), search_doc_files(), send_message(), send_reg_approval_email(), send_status_notifications(), service_class_fetch(), Zotlabs\Lib\Cache\set(), Zotlabs\Lib\AbConfig\Set(), Zotlabs\Lib\IConfig\Set(), set_default_login_identity(), Zotlabs\Storage\BasicAuth\setAuthenticated(), signing_methods(), start_delivery_chain(), store_doc_file(), store_item_tag(), stream_perms_api_uids(), stream_perms_xchans(), Zotlabs\Lib\Enotify\submit(), suggestion_query(), Zotlabs\Lib\NativeWiki\sync_a_wiki_item(), sync_an_item(), sync_apps(), sync_chatrooms(), sync_directories(), sync_events(), sync_files(), sync_locations(), sync_menus(), sync_objs(), tag_deliver(), tagadelic(), tagblock(), tasks_fetch(), term_item_parent_query(), tgroup_check(), theme_attachments(), translate_channel_perms_outbound(), Zotlabs\Extend\Hook\unregister(), Zotlabs\Extend\Hook\unregister_by_file(), unregister_hook(), update_birthdays(), update_channels_active_halfyear_stat(), update_channels_active_monthly_stat(), update_channels_total_stat(), update_hub_connected(), update_queue_item(), update_r1000(), update_r1001(), update_r1002(), update_r1003(), update_r1004(), update_r1006(), update_r1007(), update_r1008(), update_r1009(), update_r1010(), update_r1011(), update_r1012(), update_r1013(), update_r1014(), update_r1015(), update_r1016(), update_r1017(), update_r1018(), update_r1019(), update_r1020(), update_r1021(), update_r1022(), update_r1023(), update_r1024(), update_r1025(), update_r1026(), update_r1027(), update_r1028(), update_r1029(), update_r1030(), update_r1031(), update_r1032(), update_r1033(), update_r1034(), update_r1035(), update_r1036(), update_r1038(), update_r1039(), update_r1041(), update_r1042(), update_r1043(), update_r1044(), update_r1045(), update_r1046(), update_r1047(), update_r1048(), update_r1049(), update_r1050(), update_r1051(), update_r1052(), update_r1053(), update_r1054(), update_r1055(), update_r1056(), update_r1057(), update_r1059(), update_r1060(), update_r1061(), update_r1063(), update_r1064(), update_r1065(), update_r1066(), update_r1067(), update_r1068(), update_r1069(), update_r1070(), update_r1071(), update_r1072(), update_r1075(), update_r1076(), update_r1077(), update_r1078(), update_r1079(), update_r1080(), update_r1081(), update_r1082(), update_r1083(), update_r1084(), update_r1086(), update_r1087(), update_r1088(), update_r1089(), update_r1090(), update_r1093(), update_r1094(), update_r1095(), update_r1096(), update_r1097(), update_r1098(), update_r1099(), update_r1100(), update_r1101(), update_r1102(), update_r1104(), update_r1105(), update_r1106(), update_r1107(), update_r1108(), update_r1109(), update_r1110(), update_r1111(), update_r1112(), update_r1113(), update_r1114(), update_r1115(), update_r1117(), update_r1118(), update_r1120(), update_r1121(), update_r1122(), update_r1125(), update_r1126(), update_r1127(), update_r1128(), update_r1129(), update_r1130(), update_r1133(), update_r1134(), update_r1135(), update_r1139(), update_r1140(), update_r1141(), update_r1144(), update_r1145(), update_r1149(), update_r1150(), update_r1152(), update_r1154(), update_r1158(), update_r1159(), update_r1160(), update_r1161(), update_r1164(), update_r1166(), update_r1176(), update_r1177(), update_r1179(), update_r1180(), update_r1191(), update_r1194(), update_r1197(), update_suggestions(), vcard_from_xchan(), vcard_query(), Zotlabs\Zot\Auth\Verify(), verify_email_address(), visible_plugin_list(), Zotlabs\Widget\Activity\widget(), Zotlabs\Widget\Savedsearch\widget(), Zotlabs\Widget\Bookmarkedchats\widget(), Zotlabs\Widget\Appcategories\widget(), Zotlabs\Widget\Conversations\widget(), Zotlabs\Widget\Admin\widget(), Zotlabs\Widget\Random_block\widget(), Zotlabs\Widget\Forums\widget(), Zotlabs\Widget\Chatroom_list\widget(), Zotlabs\Widget\Suggestedchats\widget(), Zotlabs\Widget\Follow\widget(), Zotlabs\Widget\Filer\widget(), Zotlabs\Widget\Album\widget(), Zotlabs\Widget\Portfolio\widget(), Zotlabs\Widget\Item\widget(), Zotlabs\Widget\Suggestions\widget(), Zotlabs\Widget\Tagcloud\widget(), wtagblock(), xchan_fetch(), xchan_keychange_acl(), xchan_keychange_table(), xchan_store(), z_readdir(), zat_init(), zid_init(), zot_feed(), zot_gethub(), zot_import(), zot_refresh(), zot_rekey_request(), zot_reply_message_request(), zot_reply_pickup(), zot_reply_purge(), zot_reply_refresh(), zot_site_info(), and zotinfo().
$res = $pgdb->query("select relname, attname, pg_type.typname from ((pg_attribute inner join pg_class on attrelid=pg_class.oid) inner join pg_type on atttypid=pg_type.oid) inner join pg_namespace on relnamespace=pg_namespace.oid where nspname='public' and atttypid not in (26,27,28,29) and relkind='r' and attname <> 'item_search_vector';")
Referenced by account_allow(), Zotlabs\Access\Permissions\BlockedAnonPerms(), Zotlabs\Module\Setup\check_keys(), event_store_item(), feed_get_reshare(), fix_private_photos(), Zotlabs\Module\Webfinger\get(), Zotlabs\Module\Probe\get(), Zotlabs\Module\Lostpass\get(), get_atom_elements(), get_bb_tag_pos(), get_cover_photo(), Zotlabs\Module\Photo\init(), Zotlabs\Module\Oep\oep_album_reply(), Zotlabs\Module\Oep\oep_articles_reply(), Zotlabs\Module\Oep\oep_cards_reply(), Zotlabs\Module\Oep\oep_display_reply(), Zotlabs\Module\Oep\oep_mid_reply(), Zotlabs\Module\Oep\oep_photo_reply(), Zotlabs\Module\Oep\oep_phototop_reply(), Zotlabs\Module\Lostpass\post(), Zotlabs\Module\Invite\post(), Zotlabs\Module\Cover_photo\post(), Zotlabs\Module\Register\post(), Zotlabs\Module\Profile_photo\post(), Zotlabs\Module\Photos\post(), profile_activity(), Zotlabs\Lib\Enotify\send(), send_reg_approval_email(), send_register_success_email(), update_imported_item(), verify_email_address(), and z_mail().
$reserved = array('ignore','key','with')
if ($res===false) $schema = array()
$type = get_configtype($cfg)
Referenced by api_apply_template(), api_call(), api_zot_version(), article_catblock(), article_tagadelic(), atom_author(), atom_entry(), atom_render_author(), attach_store(), card_catblock(), card_tagadelic(), catblock(), Zotlabs\Zot\Verify\create(), feed_get_reshare(), file_tag_file_query(), fix_private_photos(), format_like(), Zotlabs\Module\Lockview\get(), Zotlabs\Module\Linkinfo\get(), Zotlabs\Module\Display\get(), Zotlabs\Module\Cal\get(), Zotlabs\Module\Events\get(), Zotlabs\Module\Connedit\get(), get_atom_elements(), get_feed_for(), Zotlabs\Zot\Verify\get_meta(), get_terms_oftype(), get_vcard_array(), get_webpage_elements(), getIconFromType(), guess_image_type(), import_channel_photo(), import_channel_photo_from_url(), import_webpage_element(), import_xchan_photo(), Zotlabs\Module\Sslify\init(), Zotlabs\Module\Photo\init(), Zotlabs\Module\Acl\init(), Zotlabs\Thumbs\Pdf\Match(), Zotlabs\Thumbs\Mp3audio\Match(), Zotlabs\Thumbs\Epubthumb\Match(), Zotlabs\Zot\Verify\match(), Zotlabs\Thumbs\Text\MatchDefault(), Zotlabs\Thumbs\Video\MatchDefault(), parse_vobject(), photo_factory(), photo_upload(), Zotlabs\Module\Events\post(), Zotlabs\Module\Webpages\post(), Zotlabs\Zot\Verify\purge(), random_string(), scale_external_images(), scan_webpage_elements(), store_item_tag(), tagadelic(), tagblock(), term_item_parent_query(), term_query(), translate_type(), vcard_translate_type(), Zotlabs\Zot\Auth\Verify(), Zotlabs\Widget\Tagcloud\widget(), wtagblock(), xml2array(), z_input_filter(), and zot_build_packet().
$W = "\033[1;37m"
if (isset($starttable)) else
Initial value:
{
    $r = ask_question("Ready to migrate {$W}Red{$M}(#){$W}Matrix$N from mysql db @$B{$cfg['host']}$N/$B{$cfg['data']}$N to postgres db @$B{$pcfg['host']}$N/$B{$pcfg['data']}$N.
The site will be disabled during the migration by moving the $H.htconfig.php$N file to $H.htconfig.php-mysql$N.
If for any reason the migration fails, you will need to move the config file back into place manually before trying again.
Are you ready to begin (N/y)? ", array('y','n'), 'n'
    )
foreach = glob('mod/*.php')
if
Initial value:
{
    showForm(null, $content)
try
Initial value:
{
    $mydb = new PDO("mysql:host={$cfg['host']};dbname={$cfg['data']};port={$cfg['port']}", $cfg['user'], $cfg['pass'])