The Hubzilla: include/nav.php File Reference
nav.php File Reference
Functions
nav ($template= 'default')
nav_set_selected ($item)
channel_apps ($is_owner=false, $nickname=null)
Function Documentation
channel_apps ($is_owner = false, $nickname = null)
Referenced by nav().
nav ($template = 'default')
Build page header and site navigation bars
Provide a banner/logo/whatever
Display login or logout
The following nav links are only show to logged in users
Admin page
Referenced by construct_page().
nav_set_selected ($item)
Referenced by Zotlabs\Module\Lang\get(), Zotlabs\Module\Manage\get(), Zotlabs\Module\Notifications\get(), Zotlabs\Module\Apps\get(), Zotlabs\Module\Probe\get(), Zotlabs\Module\Pubstream\get(), Zotlabs\Module\Message\get(), Zotlabs\Module\Apporder\get(), Zotlabs\Module\Search\get(), Zotlabs\Module\Help\get(), Zotlabs\Module\Cards\get(), Zotlabs\Module\Articles\get(), Zotlabs\Module\Connections\get(), Zotlabs\Module\Suggest\get(), Zotlabs\Module\Webpages\get(), Zotlabs\Module\Network\get(), Zotlabs\Module\Hq\get(), Zotlabs\Module\Rpost\get(), Zotlabs\Module\Wiki\get(), Zotlabs\Module\Admin\get(), Zotlabs\Module\Cal\get(), Zotlabs\Module\Settings\get(), Zotlabs\Module\Directory\get(), Zotlabs\Module\Channel\get(), Zotlabs\Module\Chat\get(), Zotlabs\Module\Invite\get(), Zotlabs\Module\Mood\get(), Zotlabs\Module\Mail\get(), Zotlabs\Module\Poke\get(), Zotlabs\Module\Events\get(), Zotlabs\Module\Photos\get(), Zotlabs\Module\Cdav\get(), Zotlabs\Module\Bookmarks\init(), Zotlabs\Module\Profiles\init(), and Zotlabs\Module\Profile\init().