The Hubzilla: include/perm_upgrade.php File Reference
perm_upgrade.php File Reference
Functions
perm_limits_upgrade ($channel)
perms_int_to_array ($p)
autoperms_upgrade ($channel)
perm_abook_upgrade ($abook)
translate_channel_perms_outbound (&$channel)
translate_channel_perms_inbound ($channel)
translate_abook_perms_outbound (&$abook)
translate_abook_perms_inbound ($channel, $abook)
Function Documentation
autoperms_upgrade ($channel)
Referenced by update_r1180().
perm_abook_upgrade ($abook)
Referenced by translate_abook_perms_inbound(), and update_r1180().
perm_limits_upgrade ($channel)
Referenced by translate_channel_perms_inbound(), and update_r1180().
perms_int_to_array ($p)
Referenced by autoperms_upgrade(), and perm_abook_upgrade().
translate_abook_perms_inbound ($channel, $abook)
Referenced by Zotlabs\Module\Import\import_account(), and process_channel_sync_delivery().
translate_abook_perms_outbound (& $abook)
Referenced by build_sync_packet(), and identity_basic_export().
translate_channel_perms_inbound ($channel)
Referenced by import_channel(), and process_channel_sync_delivery().
translate_channel_perms_outbound (& $channel)
Referenced by build_sync_packet(), and identity_basic_export().