The Hubzilla: view/php/theme_init.php File Reference
theme_init.php File Reference
Variables
$channel = App::get_channel()
Variable Documentation
$channel = App::get_channel()
Those who require this feature will know what to do with it. Those who don't, won't. Eventually this functionality needs to be provided by a module such that permissions can be enforced. At the moment it's more of a proof of concept; but sufficient for our immediate needs.
Referenced by account_verify_password(), api_call(), api_channel_stream(), api_file_export(), api_network_stream(), api_user(), attach_change_permissions(), attach_export_data(), attach_mkdir(), attach_mkdirp(), attach_store(), authenticate_success(), autoperms_upgrade(), bb_observer(), bbcode(), bookmark_add(), build_sync_packet(), change_channel_keys(), channel_apps(), channel_change_address(), channel_reddress(), channel_remove(), check_zotinfo(), Zotlabs\Module\Connedit\connedit_clone(), conversation(), copy_folder_to_cloudfiles(), copy_of_pubitem(), Zotlabs\Lib\Chatroom\create(), create_conversation(), Zotlabs\Lib\NativeWiki\create_wiki(), Zotlabs\Module\Defperms\defperms_clone(), design_tools(), Zotlabs\Lib\Chatroom\destroy(), Zotlabs\Lib\LDSignatures\dopplesign(), Zotlabs\Module\Embedphotos\embedphotos_widget_album(), event_addtocal(), event_import_ical(), event_import_ical_task(), fix_attached_file_permissions(), Zotlabs\Module\Dreport\get(), Zotlabs\Module\React\get(), Zotlabs\Module\Probe\get(), Zotlabs\Module\Pubstream\get(), Zotlabs\Module\Article_edit\get(), Zotlabs\Module\Card_edit\get(), Zotlabs\Module\Editpost\get(), Zotlabs\Module\Message\get(), Zotlabs\Module\Subthread\get(), Zotlabs\Module\Tagger\get(), Zotlabs\Module\Display\get(), Zotlabs\Module\Sharedwithme\get(), Zotlabs\Module\Articles\get(), Zotlabs\Module\Cards\get(), Zotlabs\Module\Editblock\get(), Zotlabs\Module\Editlayout\get(), Zotlabs\Module\Layouts\get(), Zotlabs\Module\Editwebpage\get(), Zotlabs\Module\Webpages\get(), Zotlabs\Module\Blocks\get(), Zotlabs\Module\Network\get(), Zotlabs\Module\Hq\get(), Zotlabs\Module\Rpost\get(), Zotlabs\Module\Settings\Permcats\get(), Zotlabs\Module\Filestorage\get(), Zotlabs\Module\Cal\get(), Zotlabs\Module\Rbmark\get(), Zotlabs\Module\Settings\get(), Zotlabs\Module\Admin\Channels\get(), Zotlabs\Module\Changeaddr\get(), Zotlabs\Module\Bookmarks\get(), Zotlabs\Module\Channel\get(), Zotlabs\Module\Menu\get(), Zotlabs\Module\Settings\Tokens\get(), Zotlabs\Module\Locs\get(), Zotlabs\Module\Appman\get(), Zotlabs\Module\Chat\get(), Zotlabs\Module\Invite\get(), Zotlabs\Module\Mitem\get(), Zotlabs\Module\Rate\get(), Zotlabs\Module\Mail\get(), Zotlabs\Module\Defperms\get(), Zotlabs\Module\Thing\get(), Zotlabs\Module\Events\get(), Zotlabs\Module\Cover_photo\get(), Zotlabs\Module\Profile_photo\get(), Zotlabs\Module\Settings\Channel\get(), Zotlabs\Module\Connedit\get(), Zotlabs\Module\Photos\get(), Zotlabs\Module\Profiles\get(), Zotlabs\Module\Cdav\get(), App\get_channel(), get_dirpath_by_cloudpath(), get_feed_for(), get_filename_by_cloudname(), get_public_feed(), get_webpage_elements(), get_zcard(), get_zcard_embed(), handle_feed(), handle_tag(), Zotlabs\Module\Import\import_account(), import_apps(), import_channel(), import_chatrooms(), import_config(), import_conv(), import_events(), import_hublocs(), import_item_ids(), import_items(), import_likes(), import_mail(), import_menus(), import_objs(), import_profiles(), import_webpage_element(), Zotlabs\Module\Hcard\init(), Zotlabs\Module\Uexport\init(), Zotlabs\Module\Prate\init(), Zotlabs\Module\Branchtopic\init(), Zotlabs\Module\Rate\init(), Zotlabs\Module\Magic\init(), Zotlabs\Module\Wfinger\init(), Zotlabs\Module\Feed\init(), Zotlabs\Module\Follow\init(), Zotlabs\Module\Profperm\init(), Zotlabs\Module\Connections\init(), Zotlabs\Module\Impel\init(), Zotlabs\Module\Ofeed\init(), Zotlabs\Module\Photo\init(), Zotlabs\Module\Home\init(), Zotlabs\Module\Cdav\init(), Zotlabs\Module\Mood\init(), Zotlabs\Module\Chat\init(), Zotlabs\Module\Network\init(), Zotlabs\Module\Profile\init(), Zotlabs\Module\Thing\init(), Zotlabs\Module\Wiki\init(), Zotlabs\Module\Defperms\init(), Zotlabs\Module\Channel\init(), Zotlabs\Module\Ping\init(), Zotlabs\Module\Acl\init(), Zotlabs\Module\Poke\init(), Zotlabs\Module\Connedit\init(), Zotlabs\Module\Cover_photo\init(), Zotlabs\Module\Cloud\init(), Zotlabs\Module\Profile_photo\init(), is_public_profile(), item_url_replace(), items_fetch(), Zotlabs\Lib\NativeWiki\listwikis(), mail_store(), menu_add_item(), menu_edit_item(), menu_element(), nav(), new_contact(), Zotlabs\Module\Oep\oep_articles_reply(), Zotlabs\Module\Oep\oep_cards_reply(), Zotlabs\Lib\Apps\parse_app_description(), perm_limits_upgrade(), photo_upload(), photos_albums_list(), photos_create_item(), photos_list_photos(), populate_acl(), Zotlabs\Module\Changeaddr\post(), Zotlabs\Module\Sources\post(), Zotlabs\Module\Locs\post(), Zotlabs\Module\Settings\Permcats\post(), Zotlabs\Module\Settings\Tokens\post(), Zotlabs\Module\Filestorage\post(), Zotlabs\Module\Settings\Channel\post(), Zotlabs\Module\File_upload\post(), Zotlabs\Module\Events\post(), Zotlabs\Module\Wall_upload\post(), Zotlabs\Module\Import_items\post(), Zotlabs\Module\Mail\post(), Zotlabs\Module\Wall_attach\post(), Zotlabs\Module\Prate\post(), Zotlabs\Module\Getfile\post(), Zotlabs\Module\Item\post(), Zotlabs\Module\Rbmark\post(), Zotlabs\Module\Tasks\post(), Zotlabs\Module\Cover_photo\post(), Zotlabs\Module\Defperms\post(), Zotlabs\Module\Chat\post(), Zotlabs\Module\Rate\post(), Zotlabs\Module\Profile_photo\post(), Zotlabs\Module\Photos\post(), Zotlabs\Module\Connedit\post(), Zotlabs\Module\Profiles\post(), Zotlabs\Module\Cdav\post(), Zotlabs\Module\Webpages\post(), post_activity_item(), process_channel_sync_delivery(), process_delivery(), process_mail_delivery(), refimport_content(), reflect_comment_store(), reflect_photo_callback(), Zotlabs\Daemon\Importfile\run(), Zotlabs\Daemon\Ratenotif\run(), Zotlabs\Daemon\Directory\run(), Zotlabs\Zot\Finger\run(), Zotlabs\Daemon\Notifier\run(), Zotlabs\Lib\LDSignatures\salmon_sign(), save_chunk(), scan_webpage_elements(), Zotlabs\Module\Cover_photo\send_cover_photo_activity(), send_message(), send_profile_photo_activity(), App\set_channel(), Zotlabs\Lib\LDSignatures\sign(), start_delivery_chain(), sync_apps(), sync_chatrooms(), sync_events(), sync_files(), sync_items(), sync_mail(), sync_menus(), sync_objs(), thread_author_menu(), translate_abook_perms_inbound(), translate_channel_perms_inbound(), translate_channel_perms_outbound(), Zotlabs\Zot\Auth\Verify(), website_portation_tools(), Zotlabs\Widget\Wiki_list\widget(), Zotlabs\Widget\Notifications\widget(), Zotlabs\Widget\Cover_photo\widget(), Zotlabs\Widget\Settings_menu\widget(), Zotlabs\Widget\Rating\widget(), Zotlabs\Widget\Zcard\widget(), Zotlabs\Widget\Cdav\widget(), zot_build_packet(), zot_encode_locations(), and zot_refresh().