The Hubzilla: include/queue_fn.php File Reference
queue_fn.php File Reference
Functions
update_queue_item ($id, $add_priority=0)
remove_queue_item ($id, $channel_id=0)
remove_queue_by_posturl ($posturl)
queue_set_delivered ($id, $channel=0)
queue_insert ($arr)
queue_deliver ($outq, $immediate=false)
Function Documentation
queue_deliver ($outq, $immediate = false)
Referenced by Zotlabs\Daemon\Queue\run(), and Zotlabs\Daemon\Deliver\run().
queue_insert ($arr)
Referenced by build_sync_packet(), Zotlabs\Daemon\Ratenotif\run(), Zotlabs\Daemon\Directory\run(), Zotlabs\Daemon\Notifier\run(), and zot_reply_message_request().
queue_set_delivered ($id, $channel = 0)
remove_queue_by_posturl ($posturl)
Referenced by Zotlabs\Module\Admin\Queue\get(), and queue_deliver().
remove_queue_item ($id, $channel_id = 0)
Referenced by queue_deliver(), Zotlabs\Daemon\Deliver\run(), zot_process_response(), and zot_reply_pickup().
update_queue_item ($id, $add_priority = 0)
Referenced by build_sync_packet(), do_delivery(), queue_deliver(), Zotlabs\Daemon\Ratenotif\run(), and zot_reply_message_request().