The Hubzilla: include/taxonomy.php File Reference
taxonomy.php File Reference
Functions
file_tag_encode ($s)
file_tag_decode ($s)
file_tag_file_query ($table, $s, $type= 'file')
term_query ($table, $s, $type=TERM_UNKNOWN, $type2= '')
term_item_parent_query ($uid, $table, $s, $type=TERM_UNKNOWN, $type2= '')
store_item_tag ($uid, $iid, $otype, $type, $term, $url= '')
get_terms_oftype ($arr, $type)
format_term_for_display ($term)
tagadelic ($uid, $count=0, $authors= '', $owner= '', $flags=0, $restrict=0, $type=TERM_HASHTAG)
card_tagadelic ($uid, $count=0, $authors= '', $owner= '', $flags=0, $restrict=0, $type=TERM_CATEGORY)
article_tagadelic ($uid, $count=0, $authors= '', $owner= '', $flags=0, $restrict=0, $type=TERM_CATEGORY)
dir_tagadelic ($count=0)
app_tagblock ($link, $count=0)
app_tagadelic ($count=0)
tagblock ($link, $uid, $count=0, $authors= '', $owner= '', $flags=0, $restrict=0, $type=TERM_HASHTAG)
wtagblock ($uid, $count=0, $authors= '', $owner= '', $flags=0, $restrict=0, $type=TERM_HASHTAG)
catblock ($uid, $count=0, $authors= '', $owner= '', $flags=0, $restrict=0, $type=TERM_CATEGORY)
card_catblock ($uid, $count=0, $authors= '', $owner= '', $flags=0, $restrict=0, $type=TERM_CATEGORY)
article_catblock ($uid, $count=0, $authors= '', $owner= '', $flags=0, $restrict=0, $type=TERM_CATEGORY)
dir_tagblock ($link, $r)
obj_verbs ()
obj_verb_selector ($current= '')
get_things ($profile_hash, $uid)
Function Documentation
app_tagadelic ($count = 0)
Referenced by app_tagblock().
app_tagblock ($link, $count = 0)
Referenced by Zotlabs\Widget\Appcloud\widget().
article_catblock ($uid, $count = 0, $authors = '', $owner = '', $flags = 0, $restrict = 0, $type = TERM_CATEGORY)
article_tagadelic ($uid, $count = 0, $authors = '', $owner = '', $flags = 0, $restrict = 0, $type = TERM_CATEGORY)
Referenced by article_catblock().
card_catblock ($uid, $count = 0, $authors = '', $owner = '', $flags = 0, $restrict = 0, $type = TERM_CATEGORY)
card_tagadelic ($uid, $count = 0, $authors = '', $owner = '', $flags = 0, $restrict = 0, $type = TERM_CATEGORY)
Referenced by card_catblock().
catblock ($uid, $count = 0, $authors = '', $owner = '', $flags = 0, $restrict = 0, $type = TERM_CATEGORY)
Referenced by Zotlabs\Widget\Catcloud_wall\widget().
dir_tagadelic ($count = 0)
Referenced by Zotlabs\Module\Dirsearch\get().
dir_tagblock ($link, $r)
Referenced by Zotlabs\Widget\Dirtags\widget().
file_tag_decode ($s)
file_tag_encode ($s)
file_tag_file_query ($table, $s, $type = 'file')
format_term_for_display ($term)
get_terms_oftype ($arr, $type)
Referenced by format_categories(), format_filer(), format_hashtags(), format_mentions(), Zotlabs\Module\Article_edit\get(), Zotlabs\Module\Card_edit\get(), Zotlabs\Module\Editpost\get(), Zotlabs\Module\Events\get(), Zotlabs\Module\Bookmarks\init(), item_expire(), item_getfeedtags(), tag_deliver(), and tgroup_check().
get_things ($profile_hash, $uid)
Referenced by advanced_profile().
obj_verb_selector ($current = '')
Referenced by Zotlabs\Module\Thing\get().
obj_verbs ()
verbs: [0] = first person singular, e.g. "I want", [1] = 3rd person singular, e.g. "Bill wants" We use the first person form when creating an activity, but the third person for use in activities FIXME: There is no accounting for verb gender for languages where this is significant. We may eventually require obj_verbs() to provide full conjugations and specify which form to use in the $_REQUEST params to this module.
Referenced by get_things(), Zotlabs\Module\Thing\init(), and obj_verb_selector().
store_item_tag ($uid, $iid, $otype, $type, $term, $url = '')
Referenced by Zotlabs\Lib\Apps\app_feature(), Zotlabs\Lib\Apps\app_store(), Zotlabs\Lib\Apps\app_update(), Zotlabs\Module\Tagger\get(), Zotlabs\Module\Filer\get(), import_apps(), sync_apps(), and tag_deliver().
tagadelic ($uid, $count = 0, $authors = '', $owner = '', $flags = 0, $restrict = 0, $type = TERM_HASHTAG)
Referenced by catblock(), tagblock(), Zotlabs\Widget\Tagcloud\widget(), and wtagblock().
tagblock ($link, $uid, $count = 0, $authors = '', $owner = '', $flags = 0, $restrict = 0, $type = TERM_HASHTAG)
term_item_parent_query ($uid, $table, $s, $type = TERM_UNKNOWN, $type2 = '')
Referenced by Zotlabs\Module\Articles\get(), Zotlabs\Module\Cards\get(), and Zotlabs\Module\Channel\get().
term_query ($table, $s, $type = TERM_UNKNOWN, $type2 = '')
Referenced by Zotlabs\Module\Network\get(), and items_fetch().
wtagblock ($uid, $count = 0, $authors = '', $owner = '', $flags = 0, $restrict = 0, $type = TERM_HASHTAG)
Referenced by Zotlabs\Widget\Tagcloud_wall\widget().