The Hubzilla: include/xchan.php File Reference
xchan.php File Reference
Functions
xchan_store_lowlevel ($arr)
xchan_store ($arr)
xchan_fetch ($arr)
xchan_keychange_table ($table, $column, $oldxchan, $newxchan)
xchan_keychange_acl ($table, $column, $oldxchan, $newxchan)
xchan_change_key ($oldx, $newx, $data)
Function Documentation
xchan_change_key ($oldx, $newx, $data)
Referenced by change_channel_keys(), process_channel_sync_delivery(), and zot_rekey_request().
xchan_fetch ($arr)
Referenced by api_red_xchan(), and api_zot_perm_allowed().
xchan_keychange_acl ($table, $column, $oldxchan, $newxchan)
Referenced by xchan_change_key().
xchan_keychange_table ($table, $column, $oldxchan, $newxchan)
Referenced by xchan_change_key().
xchan_store ($arr)
Referenced by api_red_xchan(), and reflect_comment_store().
xchan_store_lowlevel ($arr)
Referenced by anon_identity_init(), atoken_create_xchan(), change_channel_keys(), create_identity(), discover_by_url(), Zotlabs\Module\Import\import_account(), import_author_rss(), import_author_unknown(), import_xchan(), process_channel_sync_delivery(), and xchan_store().